### ISSUE TITLE
New java support fails to set up workspace directory.

### ISSUE THREAD

**Issue by ShimmerFairy** [joaotavora/eglot#1007]
I've noticed that in #868 the support for JDTLS was completely changed. Unfortunately, I found that in my case this renders the server unusable. The `jdtls` script requires a `-data` argument so that it can store data relevant to its operation.

Looking at the old code in #868 I can see that this used to be handled by eglot:

```elisp
        (cons 'eglot-eclipse-jdt
              (list (executable-find "java")
                    "-Declipse.application=org.eclipse.jdt.ls.core.id1"
                    "-Dosgi.bundles.defaultStartLevel=4"
                    "-Declipse.product=org.eclipse.jdt.ls.core.product"
                    "-jar" jar
                    "-configuration" config
                    "-data" workspace)))))
```

Where `workspace` was defined by this bit of code:

```elisp
(workspace
              (expand-file-name (md5 (project-root (eglot--current-project)))
                                (locate-user-emacs-file
                                 "eglot-eclipse-jdt-cache")))
```

Running `jdtls` in a terminal myself, I found that omitting the `-data` argument results in an error log that, save for timestamps, is identical to the error log that comes up when trying to start it up through eglot. Providing a `-data` argument on the terminal allows it to run (or at least, not immediately terminate).

While I can supply my own `-data` as specified in #868 , I don't know how to give it the same value it used to have (if it's even possible from within init.el). And in any case, it's still a regression in eglot that needs to be fixed.

**Comment by joaotavora** [comment]
Read the instructions that you deleted and try again, please.
