### ISSUE TITLE
JDTLS not working right

### ISSUE THREAD

**Issue by sabinpocris** [joaotavora/eglot#1043]
Hi,
If I am into a Maven project, I get "_file_ is a non-project file, only syntax errors are reported" .

However, if I change the `-data` parameter I get "`class` cannot be resolved to a type", even though the class's implementation is in the same folder.

Googling I saw [another issue like this](https://github.com/mfussenegger/nvim-jdtls/discussions/151#discussioncomment-1395676), maybe using `(java-mode . ("jdtls" "-data" ".jdtls-cache"))` is not the right choice?

What can I do?

I'm using the last `jdtls` snapshot, last `eglot` version and `openjdk 18.`</div>

**Comment by joaotavora** [comment]
> What can I do?

Ask the jdtls folks, maybe
