### ISSUE TITLE
Feature Request: show code actions in modeline

### ISSUE THREAD

**Issue by chmouel** [joaotavora/eglot#1073]
More of a Feature Request than a bug report. It would be nice if we were able to show the "code actions" available at point in the modeline.

Currently we need to "request" for it via elgot-code-actions to figure out if one is available at point.

**Comment by joaotavora** [comment]
Did you read the instructions at all before deleting them?

**Comment by joaotavora** [comment]
Duplicate of #1070 .

**Comment by chmouel** [comment]
oops very sorry i was looking for modeline string and could not find the string anywhere, i did search on reddit/stackoverflow and github issues

**Comment by chmouel** [comment]
sorry about that should have read this better,
