### ISSUE TITLE
Split the JSON-RPC API into a separate library

### ISSUE THREAD

**Issue by amol-mandhane** [joaotavora/eglot#11]
It would make the codebase simpler if JSON-RPC part is split into a separate library.  I have an implementation of JSON-RPC for elisp which can be used.  It uses native JSON functionality of Emacs 27 which can be backported with json.el for Emacs 26.  If you are looking for contributions, I can modify the library and add it here.

**Comment by netjune** [comment]
As for as I known, there is a json-rpc lib by the author. 

https://github.com/joaotavora/eglot/tree/jsonrpc-refactor

**Comment by joaotavora** [comment]
I'm rewriting a bit of the "native" emacs code to improve it to work with
plists. So yes, the idea is to use said functions. Where is your library?

**Comment by amol-mandhane** [comment]
I have a local implementation of JSON-RPC protocol which is very similar to yours.  The only difference is that I am using the native JSON functions[1].  This gives 5x improvement in JSON encoding time and 30% improvement in decoding time.

[1]: https://github.com/emacs-mirror/emacs/blob/master/src/json.c

**Comment by joaotavora** [comment]
@amol-mandhane, I understood that from your first message. Is the source for your implementation available somewhere?

I have also stated that Ii plan to use json.c, but first I'm changing it slightly, in Emacs itself, to support plists. Do you understand this?

**Comment by amol-mandhane** [comment]
IIUC, you are changing json.c to return plists.  Correct me if I'm wrong.

My current implementation is pretty much same as yours, except it returns alist instead of plists.  I also have some backports of json.c function using json.el to have some backward compatibility for Emacs 26 as follows.

```emacs-lisp
(require 'json)

(defalias backport-json-serialize
  (if (fboundp 'json-serialize)
      #'json-serialize
    (lambda (object)
      (let ((json-array-type 'vector)
            (json-key-type nil)
            (json-false :false)
            (json-null :null)
            (json-encoding-separator ",")
            (json-encoding-default-indentation "")
            (json-encoding-pretty-print nil))
       (json-encode object)))
```

And I use `backport-json-*` functions everywhere in my library.

However, my final library is using some proprietary code (helper functions that we have internally).  If you are looking for an existing implementation, I can clean it up to make includable in eglot.

But if you already have plans to use native json.c in your library with plists, I guess my implementation adds little value and we can close this issue.

**Comment by joaotavora** [comment]
OK, stay tuned and feel free to ask questions or submit changes (though you should have assigned copyright to the FSF for that, ask in emacs-devel).
