### ISSUE TITLE
eglot+gopls 0.10.1 positioning is incorrect

### ISSUE THREAD

**Issue by Cerebus** [joaotavora/eglot#1102]
Absolutely minimal example:
```
~/Documents/projects/newgo main
> ls -la
total 16
drwxr-xr-x   5 tmiller  staff   160 Nov  9 09:05 .
drwxr-xr-x@ 92 tmiller  staff  2944 Nov  9 09:05 ..
drwxr-xr-x  10 tmiller  staff   320 Nov  9 09:05 .git
-rw-r--r--   1 tmiller  staff    33 Nov  9 09:06 foo.go
-rw-r--r--   1 tmiller  staff    28 Nov  9 09:04 go.mod
```

`foo.go` contains:
```
package main

import (
	"fmt"
)
```

Still get the same weird errors:

![Screen Shot 2022-11-09 at 9 15 50 AM](https://user-images.githubusercontent.com/49740/200868452-9cf4b2b8-c504-4b40-90f4-d0052641160e.png)

~~In addition, when completions are selected, they're inserted at the wrong point:~~  (My bad, was mucking with positioning and forgot to undo it)

_Originally posted by @Cerebus in https://github.com/joaotavora/eglot/discussions/1100#discussioncomment-4098147_

**Comment by Cerebus** [comment]
It behaves like gopls is reading the file, not the buffer.

**Comment by Cerebus** [comment]
I should add:

emacs 28.2/Darwin (d12frosted/emacs-plus) with native-compilation.

**Comment by joaotavora** [comment]
You should also add an Emacs -Q recipe as described in the bug reporting
instructions. We need to rule out any interference from unknown pieces of
elisp. Thanks.

**Comment by Cerebus** [comment]
Dammit, yeah, it's something in corfu/cape/embark/marginalia/orderless/vertico.  Now I have to go splitting to figure out which.

**Comment by joaotavora** [comment]
@Cerebus, please next time do not create an additional issue if I have converted your incompletely described issue to a discussion.  It doesn't help, or bring any more attention to your problem.
