### ISSUE TITLE
Is it possible to use childframe for eglot?

### ISSUE THREAD

**Issue by FirstLoveLife** [joaotavora/eglot#112]
Just come from `lsp-mode` then found this great package, thanks for you great work!

I noticed unlike `lsp-uii`'s childframe, eglot usually uses `side-window`(just like helm instead of minibuffer from ivy). I wonder is it possible to use `childframe` in eglot? Because I have to move my eyes frequently when using `side-window`.

**Comment by joaotavora** [comment]
I don't know what you mean by `lsp-uii`'s childframe.  What is `side-window` that eglot uses? I think you are talking about an Emacs feature, but it would be great if you post a screenshot so we can understand what you are talking about.

**Comment by FirstLoveLife** [comment]
Sure. 

### lsp-ui:
![image](https://user-images.githubusercontent.com/37442588/45959455-866ae500-c04c-11e8-8cc6-77d49860a49f.png)

![image](https://user-images.githubusercontent.com/37442588/45959484-9682c480-c04c-11e8-93e5-8a80590ba51d.png)

### eglot:
![image](https://user-images.githubusercontent.com/37442588/45959610-e3669b00-c04c-11e8-8181-19897dcc33c5.png)

![image](https://user-images.githubusercontent.com/37442588/45959642-f7120180-c04c-11e8-8ede-41e10ab19eed.png)


As the pictures show, lsp-ui can use child-frame, so it has window which is close to my code. Eglot's doc window is always at bottom, just like helm's default layout. IMO, eglot will be nicer if it can use child-frame.

**Comment by FirstLoveLife** [comment]
BTW, I know it is just personal taste for the choice of childframe or side-window. But if eglot can provide the option of childframe, I will very appreciate

**Comment by whatacold** [comment]
Hi @FirstLoveLife ,

I wonder is it `eglot-help-at-point` to get this help doc? It's handy.

I try this command in a c++ project, eglot prompts me a `*eglot help*` buffer,
so I'm not sure if it is the command.

**Comment by FirstLoveLife** [comment]
@whatacold Good to know this function. But i think it is not as flexible as child-frame from lsp-ui

**Comment by whatacold** [comment]
@FirstLoveLife ,

Maybe I haven't make me clear :(

Actually I want to know how do you show up the `side window` as shown in the picture, in the `elgot` manner?
It doesn't look like a `*eglot-help*` buffer as I mentioned.

**Comment by FirstLoveLife** [comment]
> It doesn't look like a *eglot-help* buffer as I mentioned.

Yes. With `eglot-help-at-point`, the `eglot-help` buffer is positioned side by side(just like what `C-x 3` does. 

> Actually I want to know how do you show up the side window as shown in the picture, in the elgot manner?

I didn't do anything. eglot's default config use `side-window` above when any lsp is hooked by eglot, including ccls

**Comment by whatacold** [comment]
I see now, it's a `textDocument/hover` response shown by `eldoc-message` function.
I haven't noticed it as I truncated the message, and now I can see the whole multi-line message
after setting `(setq message-truncate-lines nil)`.

Thanks.

**Comment by joaotavora** [comment]
There seems to be a workaround, and also this kind of UI functionality isn't anything that Eglot should be supporting anyway (emacs's own `display-buffer-alist` or modes like `company-quickhelp-mode` seem more appropriate).

**Comment by casouri** [comment]
I cooked up some code to use childframe: https://github.com/casouri/eglot-doc

**Comment by joaotavora** [comment]
@casouri, could you maybe do this in `eldoc-message-function` exclusively (and thus provide this service to non-Eglot users) like I suggest in #111?  It would also probably need less Eglot-specific code and custom requests.

**Comment by casouri** [comment]
Done. I removed eglot-dependency and renamed it to eldoc-box.

**Comment by joaotavora** [comment]
Oh very nice, going to try it out with my minor modes
