### ISSUE TITLE
What is the expected format of hover text?

### ISSUE THREAD

**Issue by juliandolby** [joaotavora/eglot#113]
I have been using eglot with my LSP server, and I am trying to figure out the intended formatting of text for hovers.  When I use plain text, a string like 'pixel[n]' seems to get formatted with the 'n' having an underscore, at least in my Emacs.  Is that intended?

 My server can also generate Markdown formatted hovers, if that is what eglot wants.  However, I notice that the eglot client capabilities object does not specify a hover format.

**Comment by joaotavora** [comment]
Hi @juliandolby , sorry to have left this issue pass unanswered. If you're still interested and the problem persists (please test with the newest version), I will reopen and re-analyse.
