### ISSUE TITLE
gopls Organize Imports not working as intended

### ISSUE THREAD

**Issue by samimb** [joaotavora/eglot#1132]
Discussed in https://github.com/joaotavora/eglot/discussions/1117 - No replies

I’m trying to get the code action of organize imports to work with `before-save-hook`. Specifically for `go-mode`.
I’ve been searching around and found a couple of issues later [linking](https://github.com/joaotavora/eglot/issues/574) to a solution similar to this:

```elisp
(defun sami/eglot-organize-imports ()
  (call-interactively 'eglot-code-action-organize-imports))
(defun sami/before-saving-go ()
  (add-hook 'before-save-hook #'eglot-format-buffer -10 t)
  (add-hook 'before-save-hook #'sami/eglot-organize-imports nil t))
(add-hook 'go-mode-hook #'sami/before-saving-go)
```
Problem seems to be, running `M-x` + `eglot-code-actions` and selecting `Organize imports` works fine, but running the stand-alone function of `eglot-code-action-organize-imports` does not yield anything.

Test case:
In any go file, add something like `fmt.Println(“hello”)` imports the package `fmt` automatically, deleting or commenting the line does not delete the imported package `fmt`. `eglot-code-action-organize-imports` does not delete the imported package `fmt`. Running the function `eglot-code-actions` and selecting `Organize imports` DOES delete the package `fmt` from imports.

Here is the `client-request` and `server-response`.

```elisp
[client-request] (id:613) Mon Dec  5 23:43:48 2022:
(:jsonrpc "2.0" :id 613 :method "textDocument/codeAction" :params
	  (:textDocument
	   (:uri "file:///Users/sami/Code/Go/src/sami/something/temp.go")
	   :range
	   (:start
	    (:line 5 :character 6)
	    :end
	    (:line 5 :character 10))
	   :context
	   (:diagnostics
	    []
	    :only
	    ["source.organizeImports"])))
[server-reply] (id:613) Mon Dec  5 23:43:48 2022:
(:jsonrpc "2.0" :result
	  [(:title "Organize Imports" :kind "source.organizeImports" :edit
		   (:documentChanges
		    [(:textDocument
		      (:version 172 :uri "file:///Users/sami/Code/Go/src/sami/something/temp.go")
		      :edits
		      [(:range
			(:start
			 (:line 3 :character 2)
			 :end
			 (:line 3 :character 2))
			:newText "bytes\"\n	\"crypto/tls\"\n	\"encoding/json\"\n	\"")
		       (:range
			(:start
			 (:line 4 :character 2)
			 :end
			 (:line 4 :character 2))
			:newText "go/token\"\n	\"")
		       (:range
			(:start
			 (:line 5 :character 10)
			 :end
			 (:line 5 :character 10))
			:newText "\"\n	\"sami/something/models\"\n	\"sami/something/tool")])]))]
	  :id 613)
```

Single difference between the usage of `eglot-code-action-organize-imports` and not is 
```elisp
...
            :only
            ["source.organizeImports"])))
...
```
added to the `client-request` to the running of `eglot-code-actions` and selection.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by joaotavora** [comment]
Creating an issue doesn't serve to call more attention to your problem, only more unnecessary nose. If I  or others haven't replied, it's because I or others don't have time or availability. I'm very sorry, but this is 100% unpaid volunteer work.

**Comment by joaotavora** [comment]
Please add the above information to the discussion.

**Comment by samimb** [comment]
> Creating an issue doesn't serve to call more attention to your problem, only more unnecessary nose. If I or others haven't replied, it's because I or others don't have time or availability. I'm very sorry, but this is 100% unpaid volunteer work.

Apologies, not the intention, I figured this to be an issue so registered it as such and moving it from discussion instead. But fair point, I'll keep it in discussions instead.

**Comment by mpolden** [comment]
I'm experiencing this bug too. Please consider reopening the issue.

Code example:

```go
package main

func main() {
	fmt.Println("hello")
}
```

As the author noted, calling `M-x eglot-code-action-organize-imports` does nothing, but `M-x eglot-code-actions` and choosing `Organize Imports` works fine and adds the `fmt` import.

I took a look at the code, and it seems `eglot-code-action-organize-imports` is never considered interactive, so `eglot--read-execute-code-action` is not invoked here: https://github.com/joaotavora/eglot/blob/64bbbeb6b6ffd2dd0df2c1f52bb06a022eb63ad6/eglot.el#L3334-L3336

Maybe the fix is as simple as making the `eglot--code-action` macro call `eglot-code-actions` interactively?

**Comment by joaotavora** [comment]
If you want me to reopen the bug, please follow the  instructions. https://joaotavora.github.io/eglot/#Troubleshooting-Eglot

Read the steps 1-6.  I have already gopls installed in my machine, so no need to teach me that (step 3).  But please do follow the other steps carefully, especially the final step 6. 

There has to be some way to show me the presumed bug happening, else I don't want to waste my time guessing what it might be or reading people's opinions (happy to read opinions and suggestions _after_ I have witnessed the problem, of course).

**Comment by samimb** [comment]
I filled out this and the discussion as you asked, which no one has actually looked at it. But I did not reopen this nor continued on the discussion base on you frankly rude handling of it earlier. 

Meanwhile it forced me to move to lsp-mode which I am not a fan of for other reasons. 

I do believe you have what is needed to re-produce this based on all information I had given before.

**Comment by joaotavora** [comment]
You believe that, but I don't. This is volunteer unpaid work, and i don't have hours to put in if you don't want to follow the simple rules i set forth. Good luck and goodnight.

**Comment by mpolden** [comment]
> 1. The transcript of events obtained from the buffer popped up by M-x eglot-events-buffer.

```
[client-request] (id:8) Thu Mar 16 10:52:28 2023:
(:jsonrpc "2.0" :id 8 :method "textDocument/codeAction" :params
	  (:textDocument
	   (:uri "file:///private/tmp/main.go")
	   :range
	   (:start
	    (:line 0 :character 0)
	    :end
	    (:line 0 :character 7))
	   :context
	   (:diagnostics
	    []
	    :only
	    ["source.organizeImports"])))
[server-reply] (id:8) Thu Mar 16 10:52:28 2023:
(:jsonrpc "2.0" :result
	  [(:title "Organize Imports" :kind "source.organizeImports" :edit
		   (:documentChanges
		    [(:textDocument
		      (:version 0 :uri "file:///private/tmp/main.go")
		      :edits
		      [(:range
			(:start
			 (:line 1 :character 0)
			 :end
			 (:line 1 :character 0))
			:newText "\nimport \"fmt\"\n")])]))]
	  :id 8)
```
> 2. If Emacs signaled an error (an error message was seen or heard), make sure to repeat the process after toggling debug-on-error on (via M-x toggle-debug-on-error). 

No errors occur.

> 3. An explanation of how to obtain, install, and configure the language server you used.

You stated that you didn't need this.

> 4. A description of how to setup the minimal project (one or two files and their contents) where the problem happens. 

Create a file named `main.go` with the following contents:

```go
package main

func main() {
	fmt.Println("hello")
}
```

> 5. A recipe to replicate the problem with a clean Emacs run. 

`emacs -Q` and this config to load `go-mode` and `eglot`:

```elisp
(require 'package)
(package-initialize)
(require 'eglot) ;; version 1.13
```

1. Open the `main.go` file
1. Run `M-x eglot`
1. Run `M-x eglot-code-action-organize-imports`

Expectation: The `fmt` import is added.
Actual result: Import is not added.

> 6. Make sure to double check all the above elements and re-run the recipe to see that the problem is reproducible.

I have done this multiple times now, both with my daily config and a minimal config.

**Comment by joaotavora** [comment]
Thanks.  Reproduced and fixed [here](https://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-29&id=9d3fdf7e0d4c9355b2466aca51938291ea4e26c7).  Look for it in Emacs 29's bundled Eglot and upcoming Eglot 1.14.

> emacs -Q and this config to load eglot:

Yes, a better way to say this is just `emacs -Q -f package-initialize`, since `package.el` and `eglot.el` have autoloads.

It would have been even better if you had stated how you had `package-install`ed `go-mode`, `eglot`, ... and at what version xx, yy. A maintainer following this recipe who even less familiar with Go than I am wouldn't know where to get `go-mode`, what version etc.

**Comment by mpolden** [comment]
> It would have been even better if you had stated how you had package-installed go-mode, eglot, ... and at what version xx, yy. A maintainer following this recipe who even less familiar with Go than I am wouldn't know where to get go-mode, what version etc.

I did mention my Eglot version though. Perhaps there should be a step 7 in the troubleshooting section? "Include your Emacs variant and version, Eglot version, and how you installed Eglot".

**Comment by mpolden** [comment]
I see the fix was exactly what I suggested in my first comment, so I wasn't that far off. 🙂

**Comment by joaotavora** [comment]
> I did mention my Eglot version though. Perhaps there should be a step 7 in the troubleshooting section? "Include your Emacs variant and version, Eglot version, and how you installed Eglot".

Yes, I will do this.

> I see the fix was exactly what I suggested in my first comment, so I wasn't that far off. slightly_smiling_face

Pretty much on the money: a two character fix
