### ISSUE TITLE
Hangs with message "[jsonrpc] (warning) Sentinel for EGLOT (~/c-mode) still hasn't run,  deleting it!"

### ISSUE THREAD

**Issue by twlz0ne** [joaotavora/eglot#114]
![emacs--test-eglot](https://user-images.githubusercontent.com/2653486/45529772-83d0ea00-b819-11e8-8d21-6df4e643de4a.png)

### Steps to reproduce the behavior

1. Download [test-eglot.el](https://gist.github.com/twlz0ne/bfdf29909db5baec24fd4e9ad622adc2#file-test-eglog-el)
2. `/path/to/emacs -nw -Q -l /path/to/test-eglot.el`

### Environment

- macOS: 10.11.6
- Emacs: 27.0.50
- Cquery: stable 20180718, HEAD
- Packages: eglot-20180908.2219, jsonrpc-1.0.6

**Comment by joaotavora** [comment]
> Packages: eglot-20180908.2219, jsonrpc-1.0.6

Are you sure these are the versions you are using and that everything is OK with your recipe? Because that eglot version uses `ccls` by default, not `cquery`. So:

1. you must be doing something else that is not in `test-eglot.el`, to get cquery working in the version you report OR

2. You are not using the version you report

Also, Emacs 27.0.50 is just a shorthand for the "master" branch of Emacs right now.  If the problem only reproduced with that verion (and not with 26.1), please indicate the commit hash you are using or at least the date of the git checkout.

**Comment by joaotavora** [comment]
My best guess right now is that you *think* you are running these versions of eglot and jsonrpc.el but are actualy running other versions.  Your  `require-package` function doesn't update packages that are already installed. 

Can you `M-x find-library RET jsonrpc RET` and read the version number at the top of the file?

**Comment by twlz0ne** [comment]
@joaotavora My `require-package` function downloads packages to `~/.emacs.d/test-eglot/<emacs-version>/`, and I delete this folder everty time before test:

```shell
$ tree -L 3 ~/.emacs.d/test-eglot/
├── 26.1
│   └── elpa
│       ├── archives
│       ├── eglot-20180908.2219
│       └── jsonrpc-1.0.6
└── 27.0.50
    └── elpa
        ├── archives
        ├── eglot-20180908.2219
        └── jsonrpc-1.0.6
```

I also have ccls(stable 0.20180521) and Emacs 26.1 installed in the system, and also tried `(setq eglot-server-programs '(((c++-mode c-mode) . ("cquery"))))`. Still no luck.

And hers is ert tests result:

<details>
<summary>eglot-tests.log</summary>

⋊> emacs --batch -l ert -l eglot.el -l eglot-tests.el -f ert-run-tests-batch-and-exit
Running 16 tests (2018-09-14 20:41:29+0800, selector ‘t’)
  skipped   1/16  auto-detect-running-server (0.000882 sec)
  skipped   2/16  auto-reconnect (0.000697 sec)
Can’t guess python-indent-offset, using defaults: 4
[eglot] Connected! Server `EGLOT (project/python-mode)' now managing `python-mode' buffers in project `project'.
[eglot] Asking EGLOT (project/python-mode) politely to terminate
exit([status])

Exit the interpreter by raising SystemExit(status).
If the status is omitted or None, it defaults to zero (i.e., success).
If the status is an integer, it will be used as the system exit status.
If it is another kind of object, it will be printed and the system
exit status will be one (i.e., failure).
[jsonrpc] Server exited with status 0
[eglot] Killing project buffers something.py, deleting /var/folders/3c/800j6mnd1b7d3fk7vhh8rmw00000gn/T/eglot--fixture9QHwvg, killing server (EGLOT (project/python-mode))
   passed   3/16  basic-completions (3.759688 sec)
   passed   4/16  eglot-capabilities (0.000449 sec)
Can’t guess python-indent-offset, using defaults: 4
[eglot] Connected! Server `EGLOT (project/python-mode)' now managing `python-mode' buffers in project `project'.
[eglot] applying 1 edits to `something.py'...
[eglot] applying 1 edits to `something.py'...done
[eglot] applying 1 edits to `something.py'...
[eglot] applying 1 edits to `something.py'...done
[eglot] Asking EGLOT (project/python-mode) politely to terminate
[jsonrpc] Server exited with status 0
[eglot] Killing project buffers something.py, deleting /var/folders/3c/800j6mnd1b7d3fk7vhh8rmw00000gn/T/eglot--fixturerehKXg, killing server (EGLOT (project/python-mode))
   passed   5/16  formatting (2.391380 sec)
Can’t guess python-indent-offset, using defaults: 4
[eglot] Killing project buffers something.py, deleting /var/folders/3c/800j6mnd1b7d3fk7vhh8rmw00000gn/T/eglot--fixturek77sbv, killing server nil
Test hover-after-completions backtrace:
  signal(error ("Timed out waiting for test to finish"))
  error("%s" "Timed out waiting for test to finish")
  (progn (error "%s" (concat "Timed out " message)))
  (if (eq retval timed-out) (progn (error "%s" (concat "Timed out " me
  (unwind-protect (setq retval (catch tag (setq timer (run-with-timer
  (let* ((tag (gensym "eglot-test-timeout")) (timed-out (make-symbol "
  eglot--call-with-timeout(2 (closure ((timeout) rust-mode-abbrev-tabl
  eglot--tests-connect()
  apply(eglot--tests-connect nil)
  (setq value-193 (apply fn-191 args-192))
  (unwind-protect (setq value-193 (apply fn-191 args-192)) (setq form-
  (if (unwind-protect (setq value-193 (apply fn-191 args-192)) (setq f
  (let (form-description-195) (if (unwind-protect (setq value-193 (app
  (let ((value-193 'ert-form-evaluation-aborted-194)) (let (form-descr
  (let* ((fn-191 #'eglot--tests-connect) (args-192 (condition-case err
  (save-current-buffer (set-buffer (eglot--find-file-noselect "project
  (closure (rust-mode-abbrev-table rust-mode-syntax-table t) nil (save
  funcall((closure (rust-mode-abbrev-table rust-mode-syntax-table t) n
  (let ((find-file-hook (cons #'(lambda nil (setq new-buffers (cons ..
  (unwind-protect (let ((find-file-hook (cons #'(lambda nil (setq new-
  (let* ((fixture-directory (make-temp-file "eglot--fixture" t)) (defa
  eglot--call-with-dirs-and-files((("project" ("something.py" . "impor
  (closure (rust-mode-abbrev-table rust-mode-syntax-table t) nil (let*
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name hover-after-completions :documentatio
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests [#s(ert-test
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  command-line-1(("-l" "ert" "-l" "eglot.el" "-l" "eglot-tests.el" "-f
  command-line()
  normal-top-level()
Test hover-after-completions condition:
    (error "Timed out waiting for test to finish")
   FAILED   6/16  hover-after-completions (2.050927 sec)
  skipped   7/16  javascript-basic (0.001039 sec)
  skipped   8/16  rls-basic-diagnostics (0.000761 sec)
  skipped   9/16  rls-hover-after-edit (0.000718 sec)
  skipped  10/16  rls-rename (0.000897 sec)
  skipped  11/16  rls-watches-files (0.000952 sec)
Can’t guess python-indent-offset, using defaults: 4
[eglot] Connected! Server `EGLOT (project/python-mode)' now managing `python-mode' buffers in project `project'.
[eglot] Asking EGLOT (project/python-mode) politely to terminate
[jsonrpc] Server exited with status 0
[eglot] Killing project buffers something.py, deleting /var/folders/3c/800j6mnd1b7d3fk7vhh8rmw00000gn/T/eglot--fixturecckAMF, killing server (EGLOT (project/python-mode))
Test slow-async-connection backtrace:
  signal(ert-test-failed (((should-not (apply #'eglot--connect (eglot-
  ert-fail(((should-not (apply #'eglot--connect (eglot--guess-contact)
  (if (not (unwind-protect (setq value-276 (apply fn-274 args-275)) (s
  (let (form-description-278) (if (not (unwind-protect (setq value-276
  (let ((value-276 'ert-form-evaluation-aborted-277)) (let (form-descr
  (let* ((fn-274 #'apply) (args-275 (condition-case err (let ((signal-
  (let ((eglot-sync-connect 1) (eglot-server-programs '((python-mode "
  (save-current-buffer (set-buffer (eglot--find-file-noselect "project
  (closure (rust-mode-abbrev-table rust-mode-syntax-table t) nil (save
  funcall((closure (rust-mode-abbrev-table rust-mode-syntax-table t) n
  (let ((find-file-hook (cons #'(lambda nil (setq new-buffers (cons ..
  (unwind-protect (let ((find-file-hook (cons #'(lambda nil (setq new-
  (let* ((fixture-directory (make-temp-file "eglot--fixture" t)) (defa
  eglot--call-with-dirs-and-files((("project" ("something.py" . "impor
  (closure (rust-mode-abbrev-table rust-mode-syntax-table t) nil (let*
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name slow-async-connection :documentation
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests [... ... ...
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  command-line-1(("-l" "ert" "-l" "eglot.el" "-l" "eglot-tests.el" "-f
  command-line()
  normal-top-level()
Test slow-async-connection condition:
    (ert-test-failed
     ((should-not
       (apply #'eglot--connect
                (eglot--guess-contact)))
      :form
      (apply eglot--connect
             (python-mode
              (transient . "/var/folders/3c/800j6mnd1b7d3fk7vhh8rmw00000gn/T/eglot--fixturecckAMF/project/")
              eglot-lsp-server
              ("sh" "-c" "sleep 2 && pyls")))
      :value #s(#s(eieio--class eglot-lsp-server "Represents a server. Wraps a process for LSP communication."
                                (#s(eieio--class jsonrpc-process-connection "A JSONRPC connection over an Emacs process.
The following initargs are accepted:

:PROCESS (mandatory), a live running Emacs process object or a
function of no arguments producing one such object.  The process
represents either a pipe connection to locally running process or
a stream connection to a network host.  The remote endpoint is
expected to understand JSONRPC messages with basic HTTP-style
enveloping headers such as \"Content-Length:\".

:ON-SHUTDOWN (optional), a function of one argument, the
connection object, called when the process dies ." ...
                                                 [#s(cl-slot-descriptor name unbound t ...)
                                                    #s(cl-slot-descriptor -request-dispatcher ... t ...)
                                                    #s(cl-slot-descriptor -notification-dispatcher ... t ...)
                                                    #s(cl-slot-descriptor last-error unbound t ...)
                                                    #s(cl-slot-descriptor -request-continuations ... t ...)
                                                    #s(cl-slot-descriptor -events-buffer unbound t ...)
                                                    #s(cl-slot-descriptor -events-buffer-scrollback-size unbound t ...)
                                                    #s(cl-slot-descriptor -deferred-actions ... t ...)
                                                    #s(cl-slot-descriptor -next-request-id 0 t ...)
                                                    #s(cl-slot-descriptor -process unbound t ...)
                                                    ...]
                                                 #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8125 data
                                                               (name 0 -request-dispatcher 1 -notification-dispatcher 2 last-error 3 -request-continuations 4 -events-buffer 5 -events-buffer-scrollback-size 6 -deferred-actions 7 -next-request-id 8 -process 9 ...))
                                                 ... ...
                                                 []
                                                 []
                                                 ...))
                                [#s(cl-slot-descriptor name unbound t ...)
                                   #s(cl-slot-descriptor -request-dispatcher ... t ...)
                                   #s(cl-slot-descriptor -notification-dispatcher ... t ...)
                                   #s(cl-slot-descriptor last-error unbound t ...)
                                   #s(cl-slot-descriptor -request-continuations ... t ...)
                                   #s(cl-slot-descriptor -events-buffer unbound t ...)
                                   #s(cl-slot-descriptor -events-buffer-scrollback-size unbound t ...)
                                   #s(cl-slot-descriptor -deferred-actions ... t ...)
                                   #s(cl-slot-descriptor -next-request-id 0 t ...)
                                   #s(cl-slot-descriptor -process unbound t ...)
                                   ...]
                                #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8125 data
                                              (name 0 -request-dispatcher 1 -notification-dispatcher 2 last-error 3 -request-continuations 4 -events-buffer 5 -events-buffer-scrollback-size 6 -deferred-actions 7 -next-request-id 8 -process 9 ...))
                                (eglot-cquery eglot-rls)
                                (... ... ... ... ... ...)
                                []
                                []
                                ...)
                  "EGLOT (project/python-mode)"
                  (closure
                   (... ... ... ... ... ... ... ... ... ... ...)
                   (&rest args)
                   (apply fn ...))
                  (closure
                   (... ... ... ... ... ... ... ... ... ... ...)
                   (&rest args)
                   (apply fn ...))
                  unbound #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                        (1
                                         (... ...
                                          [nil 23451 44192 179717 nil
                                               #[0 "\307\306\310\300!\"\210\307\304\305D\311\300!\"\210\303\203\303 \207\312\300\313\301\314\306\315\302\257\"\207"
                                                   [#2 :initialize ... ... nil #<killed buffer> 1 remhash jsonrpc--request-continuations jsonrpc--deferred-actions ...]
                                                   8]
                                               nil nil 0])
                                         ...))
                  #<buffer *EGLOT
                  (project/python-mode)
                  events*> 2000000 #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
                                                 ( ...))
                  1 ...)))
   FAILED  12/16  slow-async-connection (0.159705 sec)
Can’t guess python-indent-offset, using defaults: 4
[jsonrpc] Server exited with status 1
[eglot] Killing project buffers something.py, deleting /var/folders/3c/800j6mnd1b7d3fk7vhh8rmw00000gn/T/eglot--fixtureaooiXz, killing server nil
Test slow-sync-connection-intime backtrace:
  signal(error ("[eglot] -1: Server died"))
  error("[eglot] %s" "-1: Server died")
  eglot--error("-1: Server died")
  (if tag (throw tag (cons 'error msg)) (eglot--error msg))
  (let ((msg (format "%s: %s" code message))) (if tag (throw tag (cons
  (if cancelled nil (jsonrpc-shutdown server) (let ((msg (format "%s:
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((m
  (let* ((code (car (cdr (plist-member --cl-rest-- ':code)))) (message
  (closure ((jsonrpc-lambda-elem4 :code -1 :message "Server died") (ta
  apply((closure ((jsonrpc-lambda-elem4 :code -1 :message "Server died
  (closure ((tag) (cancelled) (server . #<eglot-lsp-server eglot-lsp-s
  #f(compiled-function (id triplet) #<bytecode 0x40e2e31d>)(1 ((closur
  maphash(#f(compiled-function (id triplet) #<bytecode 0x40e2e31d>) #<
  jsonrpc--process-sentinel(#<process EGLOT (project/python-mode)<1>>
  accept-process-output(nil 2)
  (cond ((numberp eglot-sync-connect) (accept-process-output nil eglot
  (catch tag (jsonrpc-async-request server :initialize (list :processI
  (let ((retval (catch tag (jsonrpc-async-request server :initialize (
  (condition-case _quit (let ((retval (catch tag (jsonrpc-async-reques
  (unwind-protect (condition-case _quit (let ((retval (catch tag (json
  (let* ((default-directory (car (project-roots project))) (nickname (
  eglot--connect(python-mode (transient . "/var/folders/3c/800j6mnd1b7
  apply(eglot--connect (python-mode (transient . "/var/folders/3c/800j
  (closure ((timeout . 3) rust-mode-abbrev-table rust-mode-syntax-tabl
  funcall((closure ((timeout . 3) rust-mode-abbrev-table rust-mode-syn
  (catch tag (setq timer (run-with-timer timeout nil #'(lambda nil (if
  (setq retval (catch tag (setq timer (run-with-timer timeout nil #'(l
  (unwind-protect (setq retval (catch tag (setq timer (run-with-timer
  (let* ((tag (gensym "eglot-test-timeout")) (timed-out (make-symbol "
  eglot--call-with-timeout(3 (closure ((timeout . 3) rust-mode-abbrev-
  eglot--tests-connect(3)
  apply(eglot--tests-connect 3)
  (setq value-266 (apply fn-264 args-265))
  (unwind-protect (setq value-266 (apply fn-264 args-265)) (setq form-
  (if (unwind-protect (setq value-266 (apply fn-264 args-265)) (setq f
  (let (form-description-268) (if (unwind-protect (setq value-266 (app
  (let ((value-266 'ert-form-evaluation-aborted-267)) (let (form-descr
  (let* ((fn-264 #'eglot--tests-connect) (args-265 (condition-case err
  (let ((eglot-sync-connect 2) (eglot-server-programs '((python-mode "
  (save-current-buffer (set-buffer (eglot--find-file-noselect "project
  (closure (rust-mode-abbrev-table rust-mode-syntax-table t) nil (save
  funcall((closure (rust-mode-abbrev-table rust-mode-syntax-table t) n
  (let ((find-file-hook (cons #'(lambda nil (setq new-buffers (cons ..
  (unwind-protect (let ((find-file-hook (cons #'(lambda nil (setq new-
  (let* ((fixture-directory (make-temp-file "eglot--fixture" t)) (defa
  eglot--call-with-dirs-and-files((("project" ("something.py" . "impor
  (closure (rust-mode-abbrev-table rust-mode-syntax-table t) nil (let*
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name slow-sync-connection-intime :document
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests [... ... ...
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  command-line-1(("-l" "ert" "-l" "eglot.el" "-l" "eglot-tests.el" "-f
  command-line()
  normal-top-level()
Test slow-sync-connection-intime condition:
    (error "[eglot] -1: Server died")
   FAILED  13/16  slow-sync-connection-intime (1.446336 sec)
Can’t guess python-indent-offset, using defaults: 4
[eglot] Connected! Server `EGLOT (project/python-mode)' now managing `python-mode' buffers in project `project'.
[eglot] Connected! Server `EGLOT (project/python-mode)' now managing `python-mode' buffers in project `project'.
[eglot] Asking EGLOT (project/python-mode) politely to terminate
[jsonrpc] Server exited with status 0
[eglot] Asking EGLOT (project/python-mode) politely to terminate
[jsonrpc] Server exited with status 0
[eglot] Killing project buffers something.py, deleting /var/folders/3c/800j6mnd1b7d3fk7vhh8rmw00000gn/T/eglot--fixtureVBRjEK, killing server (EGLOT (project/python-mode) EGLOT (project/python-mode))
   passed  14/16  slow-sync-connection-wait (3.400433 sec)
Can’t guess python-indent-offset, using defaults: 4
[jsonrpc] Server exited with status 9
[eglot] Killing project buffers something.py, deleting /var/folders/3c/800j6mnd1b7d3fk7vhh8rmw00000gn/T/eglot--fixtureFHhMXn, killing server nil
   passed  15/16  slow-sync-timeout (1.186424 sec)
Can’t guess python-indent-offset, using defaults: 4
[eglot] Connected! Server `EGLOT (project/python-mode)' now managing `python-mode' buffers in project `project'.
Can’t guess python-indent-offset, using defaults: 4
Warning [flymake bar.py]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
[eglot] Asking EGLOT (project/python-mode) politely to terminate
[jsonrpc] Server exited with status 0
[eglot] Killing project buffers bar.py, foo.py, deleting /var/folders/3c/800j6mnd1b7d3fk7vhh8rmw00000gn/T/eglot--fixtureCxSLSe, killing server (EGLOT (project/python-mode))
Warning [flymake foo.py]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
   passed  16/16  zzz-eglot-ensure (2.623300 sec)

Ran 16 tests, 6 results as expected, 3 unexpected, 7 skipped (2018-09-14 20:41:48+0800, 19.284853 sec)

3 unexpected results:
   FAILED  hover-after-completions
   FAILED  slow-async-connection
   FAILED  slow-sync-connection-intime

7 skipped results:
  SKIPPED  auto-detect-running-server
  SKIPPED  auto-reconnect
  SKIPPED  javascript-basic
  SKIPPED  rls-basic-diagnostics
  SKIPPED  rls-hover-after-edit
  SKIPPED  rls-rename
</details>

**Comment by joaotavora** [comment]
> @joaotavora My require-package function downloads packages to ~/.emacs.d/test-eglot/<emacs-version>/, and I delete this folder everty time before test:

Then how do you explain that, without setting up eglot for cquery in the `test-eglot.el` file that you attached, your MELPA version `20180908.2219` misteriously managed to pick it up?

**Comment by joaotavora** [comment]
> (setq eglot-server-programs '(((c++-mode c-mode) . ("cquery"))))

Cquery needs a special one-liner in eglot. https://github.com/joaotavora/eglot#installation-and-usage
```
(add-to-list 'eglot-server-programs '((c++ mode c-mode) . (eglot-cquery "cquery")))
```

**Comment by joaotavora** [comment]
> Still no luck.

When you say "still no luck" do you mean you *always* get the jsonrpc/sentinel error in the title of this issue?

**Comment by twlz0ne** [comment]
> ```
> (add-to-list 'eglot-server-programs '((c++ mode c-mode) . (eglot-cquery "cquery")))
> ```

 Thanks for point that out. It's my fault, I just copied the configuration of ccls, without reading the README.
 
 Now cquery is working, but ccls does not, maybe I should ask the author of ccls.
 
 ![emacs--test-eglot-with-cquery](https://user-images.githubusercontent.com/2653486/45553705-2c596b00-b867-11e8-9b36-2b9a7b04519e.png)
 
 I'm going to close this Issue.

**Comment by joaotavora** [comment]
> ccls does not

But with the jsonrpc sentinel message???

**Comment by twlz0ne** [comment]
> with the jsonrpc sentinel message?

Yes
