### ISSUE TITLE
eglot keeps sending `didSave` notifications despite the active server not supporting `textDocumentSync`

### ISSUE THREAD

**Issue by 6b6279** [joaotavora/eglot#1140]
**Steps to reproduce issue:**
1. Create example Dart project using Flutter: `flutter create hello_world`
2. Open `hello_world/lib/main.dart` in Emacs
3. Start eglot with `M-x eglot RET`
4. Make a rudimentary change in the file; ex. add a line break
5. Save with `C-x C-s`
Following text appears in the minibuffer area: `[eglot] Server reports (type=1): Unknown method textDocument/didSave`

See https://github.com/dart-lang/sdk/issues/36464 and https://github.com/microsoft/language-server-protocol/issues/288

Thanks in advance.

**Comment by joaotavora** [comment]
👍 make sure to cc me in a message to that bug, so i can join the discussion (and potentially do the patch)
