### ISSUE TITLE
Inconsistent state after some misterious crash. Had to use eglot--managed-mode

### ISSUE THREAD

**Issue by tromey** [joaotavora/eglot#115]
I was using eglot with Rust and "something" happened -- I don't know exactly what but I assume that RLS crashed.

After this, eglot ended up in a state where I could do very little.  For example, I could not `M-x revert-buffer`, because some eglot hook function errored (due IIRC the process being dead).  I couldn't kill eglot-managed buffers, either.  `M-x eglot-shutdown` did not help.

In the end I skimmed through the eglot source and did `M-x eglot--managed-mode`.

I think eglot should be more careful about process failures and avoid allowing exceptions to unwind past the boundaries of hook functions.

**Comment by joaotavora** [comment]
> I think eglot should be more careful about process failures and avoid allowing exceptions to unwind past the boundaries of hook functions.

I agree to the first part, though I don't fully understand the second.  Let's keep this open and mark the `eglot--managed-mode` a workaround for such situations for now.

**Comment by joaotavora** [comment]
By the way, you can try killing RLS or otherwise making it crash on purpose.  Eglot should recover automatically, if it doesn't please report here.

**Comment by tromey** [comment]
> I don't fully understand the second

For example, in my case I think I found that the eglot function that is attached to `kill-buffer-hook` was throwing an exception.  This was propagating out of the function and so it was terminating the `kill-buffer`.  But I think it would be better not to stop `kill-buffer` from completing -- so the hook function would have to use `condition-case` (or `ignore-errors`, which is simpler) to avoid this.

If I reproduce this again I will be sure to attach more information to this bug.

**Comment by joaotavora** [comment]
>  (or ignore-errors, which is simpler) to avoid this.

Or `with-demoted-errors` so, you can debug the thing when it happens (if you happen to have `debug-on-error` turned on).
