### ISSUE TITLE
M-x eglot-format-buffer > [eglot]  Server can't format!

### ISSUE THREAD

**Issue by pablos-here** [joaotavora/eglot#1150]
Hi,

I'm learning about LSPs and eglot.  Very wet behind the ears.   :)

In the two languages I've tested (`python` and `bash`), I'm getting the titled error when trying to format the buffer.  

The details below are for `bash` as I figured it has the least requirements.  

Man, I hope I haven't made some boneheaded mistake ... hold my beer, I'm pressing _Submit new issue_

**High-level**

- Server used: **bash-language-server**
- ... installed:  `# npm -i -g bash-language-server`
- Emacs version: **GNU Emacs 28.2**
- Operating system: **Linux 6.1.3-1**
- Eglot version: **pulled from MELPA:  eglot-20221020.1010**
- Eglot installation method: **package.el**
- Using Doom: **No**

**Recipe**

1. Prepare `~/.emacs.d`,  `init.el` and create the **test script** per below.
2. Install the `bash-language-server`
3. In a shell, run `\emacs -Q -l init.el`
4. `M-x eglot-format-buffer` generates `[eglot]  Server can't format!`

**Details**

<details>
<summary>~/.emacs.d and init.el</summary>

Start with an empty` ~/.emacs.d` and create the following `init.el` file:

```lisp
;;; minimal-ess-eglot.el -*- lexical-binding: t; -*-

(require 'package)

(setq package-list '(eglot))
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(unless package-archive-contents
  (package-refresh-contents))

(dolist (package package-list)
  (unless (package-installed-p package)
    (package-install package)))

(add-hook 'sh-mode-hook #'eglot-ensure)
```
</details>

<details>
<summary>Test script</summary>

Create ` /var/tmp/who_me` with:
```bash
#!/bin/bash

echo "hi mom"

exit 0
```
</details>

<details>
<summary>M-x eglot-events-buffer (trimmed)</summary>

```
.... trimmed ....
[client-request] (id:6) Mon Jan  9 09:38:00 2023:
(:jsonrpc "2.0" :id 6 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///var/tmp/who_me")
	   :position
	   (:line 5 :character 0)))
[client-request] (id:7) Mon Jan  9 09:38:00 2023:
(:jsonrpc "2.0" :id 7 :method "textDocument/documentHighlight" :params
	  (:textDocument
	   (:uri "file:///var/tmp/who_me")
	   :position
	   (:line 5 :character 0)))
[server-notification] Mon Jan  9 09:38:00 2023:
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 4 :message "onHover 5:0 word=null"))
[server-reply] (id:6) Mon Jan  9 09:38:00 2023:
(:jsonrpc "2.0" :id 6 :result nil)
[server-notification] Mon Jan  9 09:38:00 2023:
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 4 :message "onDocumentHighlight 5:0 word=null"))
[server-reply] (id:7) Mon Jan  9 09:38:00 2023:
(:jsonrpc "2.0" :id 7 :result
	  [])
[client-request] (id:8) Mon Jan  9 09:38:38 2023:
(:jsonrpc "2.0" :id 8 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///var/tmp/who_me")
	   :position
	   (:line 5 :character 0)))
[client-request] (id:9) Mon Jan  9 09:38:38 2023:
(:jsonrpc "2.0" :id 9 :method "textDocument/documentHighlight" :params
	  (:textDocument
	   (:uri "file:///var/tmp/who_me")
	   :position
	   (:line 5 :character 0)))
[server-notification] Mon Jan  9 09:38:38 2023:
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 4 :message "onHover 5:0 word=null"))
[server-reply] (id:8) Mon Jan  9 09:38:38 2023:
(:jsonrpc "2.0" :id 8 :result nil)
[server-notification] Mon Jan  9 09:38:38 2023:
(:jsonrpc "2.0" :method "window/logMessage" :params
	  (:type 4 :message "onDocumentHighlight 5:0 word=null"))
[server-reply] (id:9) Mon Jan  9 09:38:38 2023:
(:jsonrpc "2.0" :id 9 :result
	  [])
```
</details>

<details>
<summary>M-x toggle-debug-on-error</summary>

```
Debugger entered--Lisp error: (error "[eglot] Server can't format!")
  signal(error ("[eglot] Server can't format!"))
  error("[eglot] %s" "Server can't format!")
  eglot--error("Server can't format!")
  eglot-format(nil nil)
  eglot-format-buffer()
  funcall-interactively(eglot-format-buffer)
  call-interactively(eglot-format-buffer record nil)
  command-execute(eglot-format-buffer record)
  execute-extended-command(nil "eglot-format-buffer" "eglot-format-b")
  funcall-interactively(execute-extended-command nil "eglot-format-buffer" "eglot-format-b")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
</details>

<details>
<summary>M-x eglot-stderr-buffer</summary>

No buffer was displayed but the following message was produced in the mini-buffer:

```
eglot--current-server-or-lose: jsonrpc-error: "No current JSON-RPC connection", (jsonrpc-error-code . 32603), (jsonrpc-error-message . "No current JSON-RPC connection")
```
</details>

**Comment by 6b6279** [comment]
I took a look at the features of bash-lsp/bash-language-server and it seems like it does not offer any facilities for auto-formatting source files. `eglot` should return that error if `(eglot--server-capable cap)` returns false — so I am assuming that the language server simply doesn’t support auto-formatting.

**Comment by pablos-here** [comment]
Hi @6b6279 ,

Thank you for taking the time to do the analysis and provide an explanation.  

Please let me know if you'd like me to close this issue or keep it open for the error-checking implementation.

**Comment by 6b6279** [comment]
`eglot` seems to work as intended: It recognizes that the current language server does not support auto-formatting of source files and informs the user that the called function has failed. I would say this is a wontfix. If you think `eglot` should handle this differently, I suggest creating a bug report on the official Emacs bug tracker.

There is already an interface over at the language server repository regarding the missing auto-format feature: bash-lsp/bash-language-server#320

**Comment by pablos-here** [comment]
Sounds good!
