### ISSUE TITLE
Loading eglot breaks visting buffers in non-existent directories

### ISSUE THREAD

**Issue by rvandegrift** [joaotavora/eglot#1177]
I often open buffers in a non-existent directory.  Then, `M-x make-directory` will create the parent directories.  If  `eglot` is loaded, this no longer works:  when the dir doesn't exist, emacs doesn't create a buffer.

Maybe I'm doing something dumb.  But I have a precise way to reproduce it.

# Recipe
1. Using emacs 28.2 from debian buster, install eglot with `M-x package-install` (I've tried 1.10 and 1.11)
2. Quit emacs and restart with no init files: `emacs -Q`
3. `M-x package-initialize`
4. `M-x load-library`
5. At the `Library name:` prompt, enter `eglot`
6. `C-x C-f`
7. At the `Find file:` prompt, enter a path to a file in a nonexistent dir: `~/wooo/yeah`
8. No buffer is opened.  The minibuffer will flash the messages:
    1. `Use M-x make-directory RET RET to create the directory and its parents`.
    2. `Opening directory: No such file or directory, /home/ross/wooo`.  But no buffer is opened.
10. If you immediately repeat 6-7, the minibuffer instead says `File /home/ross/wooo/yeah is read-only on disk.  Make buffer read-only, too? (y or n)`.  Either way I answer, emacs /does/ create the buffer on the second try.

To help further confirm eglot triggers this, you can continue:
1. `M-x unload-feature`
3. At the `Unload feature:` prompt, enter `eglot`.
4. `C-x C-f`
5. At the `Find file:` prompt, enter a path to a file in a nonexistent dir: `~/wooo/yeah`
6. emacs opens the buffer normally with the minibuffer prompt about creating the parent dirs.

# event/stderr buffers

`M-x eglot-events-buffer` returns:
> eglot--error: [eglot] Can't find an Eglot events buffer!

`M-x eglot-stderr-buffer` returns:
> eglot--current-server-or-lose: jsonrpc-error: "No current JSON-RPC connection", (jsonrpc-error-code . 32603), (jsonrpc-error-message . "No current JSON-RPC connection")

**Comment by joaotavora** [comment]
Irreproducible in Emacs 29, following your recipe (except `package-initialize`, which is uneeded since Eglot is in core).

**Comment by joaotavora** [comment]
Also can't reproduce with Emacs 28, now following exactly your recipe with Eglot from ELPA

**Comment by joaotavora** [comment]
Please try again with `M-x toggle-debug-on-error` set to true.

**Comment by rvandegrift** [comment]
On debian w/emacs 28 and `M-x toggle-debug-on-error` set to true: no traceback is generated.

So I tried on a Mac w/emacs 28.2 from homebrew cask (which is from emacsformacosx.com).  The behavior is the same, but on Mac I get this:
```
Debugger entered--Lisp error: (file-missing "Opening directory" "No such file or directory" "/Users/Ross/asdf")
  directory-files("~/asdf/" nil "\\(\\`\\.svn\\'\\)\\|\\(\\`\\.bzr\\'\\)\\|\\(\\`\\.git\\'\\)\\|\\(\\`\\..." t)
  #f(compiled-function (d) #<bytecode 0x1a23da1124ef8568>)("~/asdf/")
  locate-dominating-file("/Users/Ross/asdf/" #f(compiled-function (d) #<bytecode 0x1a23da1124ef8568>))
  project-try-vc("/Users/Ross/asdf/")
  run-hook-with-args-until-success(project-try-vc "/Users/Ross/asdf/")
  project--find-in-directory("/Users/Ross/asdf/")
  project-current()
  eglot--current-project()
  eglot-current-server()
  eglot--maybe-activate-editing-mode()
  run-hooks(change-major-mode-after-body-hook after-change-major-mode-hook)
  normal-mode(t)
  after-find-file(t t)
  find-file-noselect-1(#<buffer asdf> "~/asdf/asdf" nil nil "~/asdf/asdf" nil)
  find-file-noselect("~/asdf/asdf" nil nil t)
  find-file("~/asdf/asdf" t)
  funcall-interactively(find-file "~/asdf/asdf" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)

```

**Comment by joaotavora** [comment]
Thanks, this is indeed the backtrace I remember seeing.  Something else must be going on. This gives me a clue

**Comment by joaotavora** [comment]
Alright, I think I know why I can't reproduced it.  It's been fixed in `project.el`

```
commit 128a999bfe7ebafd78e2b463586156fc6972181d
Author: Dmitry Gutov <dgutov@yandex.ru>
Date:   Sat Jan 28 03:17:39 2023 +0200

    Make project-current not error out inside non-existent dirs
    
    * lisp/progmodes/project.el (project-try-vc):
    Use condition-case to catch 'file-missing' (bug#61107).
    
    * test/lisp/progmodes/project-tests.el
    (project-vc-nonexistent-directory-no-error): New test.
```

I think this is the correct fix, by the way.

Related: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=61107

Now the question becomes: when do you get this new `project.el` version.  It should be tagged so that GNU ELPA can update it.

**Comment by joaotavora** [comment]
Actually, it's already bumped.  `project.el` 0.9.8 should already contain the fix.  You can install it manually with `M-x package-install` probably.  Else I will tag Eglot soon and change it to depend on that `project.el`.

**Comment by rvandegrift** [comment]
Oh that's awesome!  Confirmed, upgrading `project` to 0.9.8 fixed the issue.

On Mac: the upgrade was straightforward, nothing unusual.

On Debian: just upgrading the package didn't help.  I think native compilation is making things worse - after upgrading and removing `~/.emacs.d/eln-cache`, it seems better.

Thanks for your help.
