### ISSUE TITLE
python: ref-find-definitions should go directly to the definition

### ISSUE THREAD

**Issue by runekaagaard** [joaotavora/eglot#132]
First, thanks for at great piece of software!

Is there a way to make "ref-find-definitions" skip the import statement in top of current buffer and go directly to the definition of what I'm looking for? As it is now, you have to press "M-." twice.

**Comment by mkcms** [comment]
This is feature of the server. Eglot only displays the location that the server provides.

**Comment by runekaagaard** [comment]
Of course. Thanks for your quick reply!

**Comment by edkolev** [comment]
@runekaagaard did you manage to tweak the python language server to go directly to the definition?

**Comment by runekaagaard** [comment]
No I did not.

**Comment by fbergroth** [comment]
@edkolev you can by setting `pyls.plugins.jedi_definition.follow_imports` to `true`.
```
(setq eglot-workspace-configuration '((pyls . ((plugins . ((jedi_definition . ((follow_imports . t)))))))))
```
The feature is currently not released, so you have to install from the git repo.
There is also a setting called `pyls.plugins.jedi_definition.follow_builtin_imports` (boolean).
