### ISSUE TITLE
Flymake mode-line lighter not showing warnings count if there are only warnings

### ISSUE THREAD

**Issue by muffinmad** [joaotavora/eglot#133]
Hi!

This is little snippet of code from [flymake--mode-line-format](https://github.com/emacs-mirror/emacs/blob/08192e40093bdbc8e6be6b283935b51c12d66eca/lisp/progmodes/flymake.el#L1189):

```elisp
(let ((diags-by-type (make-hash-table)))
  (maphash (lambda (_b state)
             (mapc (lambda (diag)
                     (push diag
                           (gethash (flymake--diag-type diag)
                                    diags-by-type)))
                   (flymake--backend-state-diags state)))
           flymake--backend-state)
  (format "keys: %s union keys: %s"
          (hash-table-keys diags-by-type)
          (cl-union (hash-table-keys diags-by-type)
                    '(:error :warning)
                    :key #'flymake--severity)))
```

If there are errors and warnings:
```
keys: (eglot-error eglot-warning) union keys: (eglot-error eglot-warning)
```

But if there are only warnings:
```
keys: (eglot-warning) union keys: (:error :warning)
```

And then [(`gethash :warning diags-by-type`)](https://github.com/emacs-mirror/emacs/blob/08192e40093bdbc8e6be6b283935b51c12d66eca/lisp/progmodes/flymake.el#L1194) returns `nil`.

**Comment by mkcms** [comment]
Looks like a bug in flymake, I sent [a report](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=33187) to the bug-gnu-emacs mailing list.

**Comment by mkcms** [comment]
Fixed in https://github.com/emacs-mirror/emacs/commit/0e6635fdb9ad34dea0540c121c8b981a4fc14832.
