### ISSUE TITLE
`M-x package-install RET eglot RET` results in `https://elpa.gnu.org/packages/seq-2.23.tar: Not found`

### ISSUE THREAD

**Issue by rybak** [joaotavora/eglot#1333]
### Steps to reproduce

1. Follow instructions for installation from [the README](https://github.com/joaotavora/eglot/blob/28c1c3a52e1cb7fa7260815eb53700f348d48dd5/README.md)
2. "Just type `M-x package-install RET eglot RET` into Emacs 26.3+."

### Actual result
Installation fails with:

```
Contacting host: elpa.gnu.org:443
package--with-response-buffer-1: https://elpa.gnu.org/packages/seq-2.23.tar: Not found
```

### Expected result
Eglot is installed.

### Notes
My Emacs version is:

> GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2023-08-16, modified by Debian

**Comment by joaotavora** [comment]
I can't help.  This is GNU Elpa's problem.  report this to bug-gnu-emacs@debbugs.org

If you want to help, I'll also accept a PR removing the dependency on `seq.el`
