### ISSUE TITLE
eglot--mode-line-format when jsonrpc.el v1.0.22 is installed

### ISSUE THREAD

**Issue by XO39** [joaotavora/eglot#1341]
Using both Eglot v1.15 and jsonrpc.el v1.0.22 will throw the following error (gopls v0.14.2):

> Error during redisplay: (eval (eglot--mode-line-format)) signaled (wrong-type-argument hash-table-p nil)

And the mode-line shows empty square brackets `[]` instead of `[eglot:project]`.

I'm not aware of any other issues, but just to be save I deleted the latest version of jsonrpc.el and it seems that eglot 1.15 works fine with the built-in version of jsonprc v.1.0.16.

It may not be a big issue but I thought latest versions of both packages will work together.

Is it possible that this issue is related to gopls and not to eglot? Didn't have the time yet to try eglot with other language than go.

**Comment by joaotavora** [comment]
You need to get latest Eglot from GNU devel ELPA (https://elpa.gnu.org/devel/) and I need to make a new Eglot release.

**Comment by XO39** [comment]
After install latest Eglot from GNU devel ELPA, I'm now getting this error:

**Comment by XO39** [comment]
Yes, it's working now with Eglot 1.16 and Jsonrpc 1.23.

Thanks

**Comment by jbowman-selectech** [comment]
I'm having this problem with the current versions from elpa stable (eglot 1.17 and jsonrpc 1.25).  

`Error during redisplay: (eval (eglot--mode-line-format)) signaled (void-function jsonrpc--request-continuations) [59 times]`
