### ISSUE TITLE
How to work with projects using non-UTF-8 coding systems?

### ISSUE THREAD

**Issue by whatacold** [joaotavora/eglot#135]
Hi,

At work I have some cpp projects using `chinese-gkb` to encode source files,
`eglot` together with `ccls` errors to work when doing completion:

``` text
[jsonrpc] (warning) Invalid JSON: (: 0) {"jsonrpc":"2.0","id":7,"result":{"isIncomplete":false,"items":[{"label":"hello(const char *name) -> void","kind":3,"detail":"","documentation":"Say hello to someone ��ĳ���ʺ�","sortText":"...........","insertText":"hello(${1:const char *name})$0","filterText":"hello","insertTextFormat"
```

And if I change the coding to `utf-8` temporally, it works fine.

Is it a bug for `eglot` or `ccls`? [The spec](https://microsoft.github.io/language-server-protocol/specification#content-part)
says:
> It defaults to utf-8, which is the only encoding supported right now.

Software info:
- eglot 20181024.1053
- `ccls` as LS

**Comment by MaskRay** [comment]
I would not call this as anyone (eglot or ccls)'s fault. GBK encoded file would not work. You can suggest your employer use Unicode.

Fortunately I think the encoding issue only applies to comments, and in rare occasions string literals.

**Comment by mkcms** [comment]
It might be either eglot's or jsonrpc's library fault, I quickly looked at the sources and I couldn't find anything related to encoding conversion there.

**Comment by whatacold** [comment]
> I would not call this as anyone (eglot or ccls)'s fault. GBK encoded file would not work. You can suggest your employer use Unicode.
Does it stem from the spec that only supporting UTF-8?

> Fortunately I think the encoding issue only applies to comments, and in rare occasions string literals. Just ignore them.
I noticed that if the comment for functions ("docstring") contains gbk, eglot won't be able to prompt the completion candidates, so it hurts usability.

**Comment by whatacold** [comment]
With current implementations of both sides, the problem comes by:
1. eglot sends everything out in UTF-8(as in `make-process`), even if file using GBK. (Emacs helps do the job.)
2. ccls sends say hover info back as in the file, GBK in this case, and does not specify `Content-Type` header(UTF-8 as default).
3. The filter function in jsonrpc will decode the response with UTF-8, then feeds the response to `json-read`
4. `json-read` complains about the definitively invalid json object.

I can think of two workarounds to this:
1. eglot have a customizable way to allow user to set the coding system
2. ccls allows user to set the coding system via arguments

I tend to prefer the second considering the spec.

**Comment by MaskRay** [comment]
For option 2, ccls uses a naive UTF-8 transcoding stuff to convert between clang byte-based SourceLocation/SourceRange and UTF-8 measured line/character. In practice, these clang based language servers (ccls, clangd, cquery) may read files from the file system (i.e. do not take file contents send by the language client as the single source) for indexing (and completion/diagnostics).

```cpp
// ccls/src/working_files.cc
int GetOffsetForPosition(lsPosition position, std::string_view content) {
  size_t i = 0;
  for (; position.line > 0 && i < content.size(); i++)
    if (content[i] == '\n')
      position.line--;
  for (; position.character > 0 && i < content.size(); position.character--)
    if (uint8_t(content[i++]) >= 128) {
      // Skip 0b10xxxxxx
      while (i < content.size() && uint8_t(content[i]) >= 128 &&
             uint8_t(content[i]) < 192)
        i++;
    }
  return int(i);
}

// and also in src/message_handler.cc src/messages/textDocument_formatting.cc
```

The line number will be correct, but the character can be inaccurate for other encodings retaining the feature of low bytes being 1-byte characters. If you don't put indexable identities on a line after GBK, this should work fine:

```cpp
long RIP; // 金庸
```

**Comment by whatacold** [comment]
Thanks for pointing out `GetOffsetForPosition`, actually I haven't understood the source code too much,
but I did wonder how it does the conversion between character-based and byte-based positon/range.

I may need some time to see whether my workaround fork works well or not.

> ```
> 
> The line number will be correct, but the character can be inaccurate for other encodings retaining the feature of low bytes being 1-byte characters. If you don't put indexable identities on a line after GBK, this should work fine:
> 
> ```c++
> long RIP; // 金庸
> ```
> 
> This will break character measurement:
> 
> ```c++
> int 紅顏彈指老, 剎那芳華;
> ```
> 
There is no code like the second case above in our projects, so it should work fine I guess.

**Comment by joaotavora** [comment]
@whatacold can you check if using `clangd` with the fixes from #124 and #125 fix your problem?  You might have to 
```
(setf eglot-current-column-function #'eglot-lsp-abiding-column
      eglot-move-to-column-function #'eglot-move-to-lsp-abiding-column)
```

**Comment by whatacold** [comment]
Unfortunately, it doesn't help with the HEAD commit of eglot.el https://github.com/joaotavora/eglot/commit/38da3d3b31ee19a5cea03951f5c535750858aaac ,
, clangd and below settings as you suggest:

```lisp
(setf eglot-current-column-function #'eglot-lsp-abiding-column
      eglot-move-to-column-function #'eglot-move-to-lsp-abiding-column)
```

I make a [demo repo](https://github.com/whatacold/eglot-gbk-demo) if you're insterested.

**Comment by joaotavora** [comment]
Thanks @whatacold, what LSP server are you using (name and version).

**Comment by whatacold** [comment]
I use clangd with version:

    clangd --version
    LLVM (http://llvm.org/):
      LLVM version 6.0.1
      Optimized build.
      Default target: x86_64-unknown-linux-gnu
      Host CPU: broadwell

**Comment by joaotavora** [comment]
looks like clangd version 6.  If you switch to version 7 or 8 you should be OK, I think. @mkcms?

**Comment by whatacold** [comment]
It seems that if we want to support non utf-8 coding systems, we need to
allow user to specify the coding system:

1. for `make-process` in `eglot--connect` in eglot.el
2. for `jsonrpc--json-read` in `jsonrpc.el`

I tried to work around it there, but it seems not that elegant, so I quit.

And I also have managed to convert the json string to UTF-8 in ccls side,
but I can't make ccls itself work at work, so I quit it too.

At last, I came up with a workaround with a thin translator written in python,
which translates the LSP server output to UTF-8 as I specified.
It works fine for my projects for now, and it has an extra benefit, that is
I can use it to fit cquery, ccls and clangd, depends on which works best.
(It should work with any LS though.)

**Comment by whatacold** [comment]
> looks like clangd version 6. If you switch to version 7 or 8 you should be OK

Is it related to clangd version? I'll try to see if I could get clangd 7/8 to verify this.

**Comment by joaotavora** [comment]
> It seems that if we want to support non utf-8 coding systems, we need to
allow user to specify the coding system:

I'm sorry perhaps I misread the whole discussion, but at some point it was related to misreported character/column positions.  Text communication between client and LSP server as specified by [the standard (Base Protocol, Content Part)](https://microsoft.github.io/language-server-protocol/specification) is `utf-8` and there are **no plans** to change it to anything else.

> Yeah, auto-completion does work with clangd 7:

completion?  I gave you a solution for incorrect column reporting. Everything else would be a problem with the server.

**Comment by whatacold** [comment]
I'm sorry that I haven't make the issue clear.

> is utf-8 and there are no plans to change it to anything else.

Totally understand that, so I gonna close this.

> I gave you a solution for incorrect column reporting.

I'll verify this if I have some time, and report back here.
