### ISSUE TITLE
Is eglot compatible with ccls on Windows?

### ISSUE THREAD

**Issue by rdeterre** [joaotavora/eglot#136]
Hello,

I am wondering if eglot supports ccls on Windows. I built the application and compiled a test project with a JSON compilation database, but when I start eglot on my machine, emacs freezes with the "[jsonrpc] (warning) Sentinel for EGLOT (include/c++-mode) still hasn't run, deleting it!" message at the command line.

This error message was reported before as #114, but I'm not sure if this is the same issue.

I am using Emacs 26.1 with Eglot 20181024.1053 and emacs-ccls 20181023.339

**Comment by whatacold** [comment]
Hi, I do have this error too on linux.

Just a hour ago I think this is related to my project using `chinese-gbk` coding system,
and haven't figured out why yet.

Now I tend to believe this is some kind of regression maybe, after reading your issue.
As I just update eglot to `20181024.1053` this morning, I haven't seen this error before.

**Comment by whatacold** [comment]
It looks like that `ccls` could work on Windows from its [wiki](https://github.com/MaskRay/ccls/wiki/Build),
but build on it seems to be a bit tricky.

I think you should run `ccls -h` inside cmd.exe to verify if the exe is ok.
If it is, then try to use it with eglot.

**Comment by MaskRay** [comment]
ccls can be compiled in two ways on Windows now:

* msys2
* MSVC 2017 . After https://github.com/MaskRay/ccls/pull/118
