### ISSUE TITLE
Windows Python (pyls): Emacs crashes on eglot activate

### ISSUE THREAD

**Issue by JHonaker** [joaotavora/eglot#143]
I'm trying to get eglot set up on my work laptop. It's on Windows 8, and I have basically a clean Emacs 26.1 config (just a theme and Ivy). I can't for the life of me get eglot to activate through TCP or the stdin.

If I connect through the standard stdin method, just leaving it as (python-mode . "pyls), then Emacs crashes when I use `M-x eglot`. If I setup TCP using the example in the README, it opens the server, then closes within a few seconds.

I'm at my wit's end. It works perfectly on my Mac and Linux machines.

I have the MELPA version of eglot installed, not ELPA. Any advice? Any more information needed?

**Comment by joaotavora** [comment]
I use Windows at work, too. I'll try myself tomorrow if I find the time.
The TCP thing is probably the way to go. Watch out for debug messages where
you start the server.

**Comment by joaotavora** [comment]
Who knows? does the connection last long enough to see something in the eglot events buffer?

**Comment by sebasmonia** [comment]
Apparently there's a bug with pyls, you have to downgrade to version 0.20.0

**Comment by nemethf** [comment]
@JHonaker, is this issue still relevant?  Or installing a different version of pyls is indeed a solution?

**Comment by sebasmonia** [comment]
@JHonaker if you don't have this problem anymore maybe we can close the issue?

**Comment by nemethf** [comment]
I close this issue.  If you still see the problem, comment here and I'll reopen.
