### ISSUE TITLE
Microsoft's python language server sending non-standard keys

### ISSUE THREAD

**Issue by galeo** [joaotavora/eglot#144]
I've tried to use eglot with microsoft's [python language server](https://github.com/Microsoft/python-language-server) and the following error was raised:

```
Debugger entered--Lisp error: (error "Keyword argument :_version not one of (:contents :range)")
  signal(error ("Keyword argument :_version not one of (:contents :range)"))
  error("Keyword argument %s not one of (:contents :range)" :_version)
  #f(compiled-function (&rest rest) #<bytecode 0x430a9b0d>)(:contents (:kind "plaintext" :value "") :range nil :_version nil :_typeNames nil)
  apply(#f(compiled-function (&rest rest) #<bytecode 0x430a9b0d>) (:contents (:kind "plaintext" :value "") :range nil :_version nil :_typeNames nil))
  #f(compiled-function (jsonrpc-lambda-elem13) #<bytecode 0x407f268d>)((:contents (:kind "plaintext" :value "") :range nil :_version nil :_typeNames nil))
  jsonrpc-connection-receive(#<eglot-pyls eglot-pyls> (:jsonrpc "2.0" :id 25 :result (:contents (:kind "plaintext" :value "") :range nil :_version nil :_typeNames nil)))
  jsonrpc--process-filter(#<process EGLOT (Desktop/python-mode)> "Content-Length: 128\015\n\015\n{\n  \"jsonrpc\": \"2.0\",\n  \"id\": 24,\n  \"result\": {\n    \"signatures\": null,\n    \"activeSignature\": 0,\n    \"activeParameter\": 0\n  }\n}Content-Length: 187\015\n\015\n{\n  \"jsonrpc\": \"2.0\",\n  \"id\": 25,\n  \"result\": {\n    \"contents\": {\n      \"kind\": \"plaintext\",\n      \"value\": \"\"\n    },\n    \"range\": null,\n    \"_version\": null,\n    \"_typeNames\": null\n  }\n}")
```

I build the python language server following the [guide](https://github.com/Microsoft/python-language-server/blob/master/CONTRIBUTING.md#setup) and copy the `languageServer` directory to my emacs directory.

The server program I defined:

```emacs-lisp
(setq pyls-command
      (expand-file-name
       "languageServer/Microsoft.Python.LanguageServer"
       user-emacs-directory))
(defclass eglot-pyls (eglot-lsp-server) ()
  :documentation
  "Microsoft's Python Language Server.")

(cl-defmethod eglot-initialization-options ((server eglot-pyls))
  "Passes through required pyls initialization options."
  `((:interpreter
     (:properties
      (:UseDefaultDatabase t :Version "3.7")))))

(add-to-list
 'eglot-server-programs
 `(python-mode eglot-pyls ,pyls-command))
```

The python code I used for testing:
```python
# ~/Desktop/test.py
import os

os.
```

<details>
<summary>Eglot events logs</summary>
<pre><code>
client-request (id:1) Fri Nov  2 15:50:29 2018:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 33063 :rootPath "/Users/galeo/Desktop/" :rootUri "file:///Users/galeo/Desktop/" :initializationOptions
                      ((:interpreter
                        (:properties
                         (:UseDefaultDatabase t :Version 3.6))))
                      :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges :json-false)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false))
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport t))
                        :hover
                        (:dynamicRegistration :json-false)
                        :signatureHelp
                        (:dynamicRegistration :json-false)
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false)
                        :documentSymbol
                        (:dynamicRegistration :json-false)
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false)
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false))
                       :experimental nil)))

server-notification Fri Nov  2 15:50:30 2018:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 0 :message "Microsoft Python Language Server version 0.1.50.0"))

server-notification Fri Nov  2 15:50:30 2018:
(:jsonrpc "2.0" :method "window/logMessage" :params
          (:type 0 :message "Initializing for generic interpreter"))

server-reply (id:1) Fri Nov  2 15:50:30 2018:
(:jsonrpc "2.0" :id 1 :result
          (:capabilities
           (:textDocumentSync
            (:openClose t :change 2 :willSave :json-false :willSaveWaitUntil :json-false :save nil)
            :hoverProvider t :completionProvider
            (:resolveProvider :json-false :triggerCharacters
                              ["."])
            :signatureHelpProvider
            (:triggerCharacters
             ["(,)"])
            :definitionProvider t :referencesProvider t :documentHighlightProvider :json-false :documentSymbolProvider t :workspaceSymbolProvider t :codeActionProvider :json-false :codeLensProvider nil :documentFormattingProvider :json-false :documentRangeFormattingProvider :json-false :documentOnTypeFormattingProvider
            (:firstTriggerCharacter "\n" :moreTriggerCharacter
                                    [";" ":"])
            :renameProvider t :documentLinkProvider nil :executeCommandProvider nil :experimental nil)))

client-notification Fri Nov  2 15:50:30 2018:
(:jsonrpc "2.0" :method "initialized" :params
          (:__dummy__ t))

client-notification Fri Nov  2 15:50:30 2018:
(:jsonrpc "2.0" :method "textDocument/didOpen" :params
          (:textDocument
           (:uri "file:///Users/galeo/Desktop/test.py" :version 0 :languageId "python" :text "import os\n\nos.path.join\n")))

client-notification Fri Nov  2 15:50:30 2018:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
          (:settings nil))

server-notification Fri Nov  2 15:50:30 2018:
(:jsonrpc "2.0" :method "python/languageServerStarted" :params
          [])

server-notification Fri Nov  2 15:50:30 2018:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///Users/galeo/Desktop/test.py" :diagnostics
                []))

client-request (id:2) Fri Nov  2 15:50:35 2018:
(:jsonrpc "2.0" :id 2 :method "textDocument/signatureHelp" :params
          (:textDocument
           (:uri "file:///Users/galeo/Desktop/test.py")
           :position
           (:line 2 :character 12)))

client-request (id:3) Fri Nov  2 15:50:35 2018:
(:jsonrpc "2.0" :id 3 :method "textDocument/hover" :params
          (:textDocument
           (:uri "file:///Users/galeo/Desktop/test.py")
           :position
           (:line 2 :character 12)))

server-reply (id:2) Fri Nov  2 15:50:35 2018:
(:jsonrpc "2.0" :id 2 :result
          (:signatures nil :activeSignature 0 :activeParameter 0))

server-reply (id:3) Fri Nov  2 15:50:35 2018:
(:jsonrpc "2.0" :id 3 :result
          (:contents
           (:kind "plaintext" :value "")
           :range nil :_version nil :_typeNames nil))
</code></pre>
</details>

**Comment by joaotavora** [comment]
For some reason this server is sending non-standard fields `_version`  and `_typenames` as a reply to a `textDocument/hover` request. You should ask the server's developers to follow the standard, which is what eglot is doing.  Eglot will in the near future attempt to behave with leniency towards these cases (see #138), but the short-term fix lies in the server.

**Comment by galeo** [comment]
I opened an [issue](https://github.com/Microsoft/python-language-server/issues/400) in the repo of this language server. From the replies of the its developers, I think eglot maybe better ignores the fields that not supported.

> Adherence to the LSP means sending data required by the LSP but does not mean limiting fields to the current LSP spec. Moreover, LSP itself is not fixed and new fields were added over the last few months to the existing structures such as CompletionItem. Addition of new fields did not break existing clients when servers started sending new structures. Per JSON communication client takes those fields it supports and ignores the rest. This way older clients work with newer servers just fine.

From @MikhailArkhipov

They have make a change to the server to ignore any outgoing properties that start with `_` that I haven't tested. I'd also really expect eglot could work with additional fields just as other lsp clients(vs code, sublime or vim) behave.

Thanks.

**Comment by mkcms** [comment]
>     1. `Debugger entered--Lisp error: (wrong-type-argument char-or-string-p (:kind "plaintext" :value ""))`

I pushed a commit which fixes this issue.

> > Adherence to the LSP means sending data required by the LSP but does not mean limiting fields to the current LSP spec. Moreover, LSP itself is not fixed and new fields were added over the last few months to the existing structures such as CompletionItem. Addition of new fields did not break existing clients when servers started sending new structures. Per JSON communication client takes those fields it supports and ignores the rest. This way older clients work with newer servers just fine.
> 
> From @MikhailArkhipov
> 
> They have make a change to the server to ignore any outgoing properties that start with `_` that I haven't tested. I'd also really expect eglot could work with additional fields just as other lsp clients(vs code, sublime or vim) behave.

IMO this makes sense, we should only use keys that we care about and ignore the rest.

**Comment by galeo** [comment]
1. [MikhailArkhipov](https://github.com/MikhailArkhipov), the developer of the Microsoft python language server has closed the [issue](https://github.com/Microsoft/python-language-server/issues/400) since sending non-standard keys is a behavior by design.

   Just as another developer [jakebailey](https://github.com/jakebailey) pointed out that:
   > This language server is also integrated with PTVS, Python Tools for Visual Studio, which requires these values in many places. It might not be possible to remove them without breaking things, or some other consumer which depends on our existing public API surface.

   So I don't think the [`ignore-non-lsp-keys` branch](https://github.com/jakebailey/python-language-server/tree/ignore-non-lsp-keys) **jakebailey** forked will be merged into the mainline. At least not for the present.

2. I don't really know what the `UseDefaultDatabase` option does, the server may use it for
   [AST module caching](https://github.com/Microsoft/python-language-server/blob/master/src/Analysis/Engine/Impl/Interpreter/Ast/AstModuleCache.cs#L39). The `Version` option ("3.7" in the example above) is set to the version of the python interpreter that in your path.
   I borrow this configuration from the [instructions for using SublimeText](https://github.com/Microsoft/python-language-server/blob/master/Using_in_sublime_text.md) with this server.

I really hope @mkcms would finish pull [#156](https://github.com/joaotavora/eglot/pull/156) and get it merged in the near term.

Thanks.

**Comment by joaotavora** [comment]
> non-standard keys is a behavior by design.

beautiful...

> I really hope @mkcms would finish pull #156 and get it merged in the near term.

Let's not rush it.  The reckless way the spec is moving threatens to spaghettize Eglot and that would be bad:tm:

**Comment by MaskRay** [comment]
> non-standard keys is a behavior by design.

I also think using non-standard keys is natural and should be the default.

**Comment by muffinmad** [comment]
[SourceKit-LSP](https://github.com/apple/sourcekit-lsp) also sending non-standard keys:

Error message: `error in process filter: Keyword argument :sk_usr not one of (:contents :range)`

    server-reply (id:14) Fri Nov 23 10:43:23 2018:
    (:jsonrpc "2.0" :id 14 :result
          (:sk_usr "s:s16TextOutputStreamP" :contents
                   (:kind "markdown" :value "# TextOutputStream\n```\nprotocol TextOutputStream\n```\n\nA type...")))

**Comment by joaotavora** [comment]
> I also think using non-standard keys is natural and should be the default.

FWIW, I couldn't disagree more. Why have a _specification_ in the first place then. Allowing non-standard behaviour to serve particular Client-Server friendships only disencourages developers from finding solutions within the existing specification, and contribute to a better-designed specification.  The way this goes is that non-standard behaviour becomes stadard _de facto_ by popularity, not by _thoughful design_.  I've seen this destroy API's so many times that makes me sick

**Comment by mkcms** [comment]
> FWIW, I couldn't disagree more. Why have a _specification_ in the first place then?

You're right. LSP is growing at the moment and there are a lot of changes happening all the time, so I just think we should accept them for convenience of users who use the newest servers with experimental features. LSP should be strict though, or at least guarantee backwards comptability.

**Comment by joaotavora** [comment]
> just think we should accept them for convenience of users who use the newest servers with experimental features.

I don't know exactly what you mean? I think this

1. We should follow LSP only. Once it's in the spec, we must abide by it.
2. We must do our part in preventing that porrly thought out things go into the spec just because they're popular ways to solve problems in some subregion of the server/client map.

Offering _some_ resistance to experimental features is one of the ways to do 2.

**Comment by MaskRay** [comment]
Allowing other keys is a good way to provide forward compatibility, accommodate future versions of LSP and a wide range of language servers. Let's see a file system analogy:

```c
struct xfs_sb {
...
	/* feature masks */
	uint32_t	sb_features_compat;
	uint32_t	sb_features_ro_compat;
	uint32_t	sb_features_incompat;
	uint32_t	sb_features_log_incompat;
```

XFS defines several compatibility categories to make old disk recognized by newer kernel and new disk recognized by old kernel.

*sb_features_compat*::
Read-write compatible feature flags.  The kernel can still read and write this
FS even if it doesn't understand the flag.  Currently, there are no valid
flags.

*sb_features_ro_compat*::
Read-only compatible feature flags.  The kernel can still read this FS even if
it doesn't understand the flag.

*sb_features_incompat*::
Read-write incompatible feature flags.  The kernel cannot read or write this
FS if it doesn't understand the flag.

*sb_features_log_incompat*::
Read-write incompatible feature flags for the log.  The kernel cannot read or
write this FS log if it doesn't understand the flag.  Currently, no flags are
defined.

IMHO most evolution of LSP methods are similar to `sb_features_ro_compat` and `sb_features_compat`. The clients are still able to handle parameters in a fallback manner.

**Comment by joaotavora** [comment]
Thanks for the example. I'm not sure I understand it fully but at any rate
it seems to show that in XFS this is a controlled process, not a
free-for-all. That's what I am proposing, too: a lax mode for experiments,
and a strict mode for controlled reproduction of bugs, for example.

I'm not saying liberally allowing other keys isn't practical in the short
term:  but it makes finding bugs a lot harder.

**Comment by joaotavora** [comment]
@galeo, can you try MS's python server with the newest commit f63bedb?

**Comment by joaotavora** [comment]
@galeo, I did some further tweaks to eglot and now can get a minimal working server with
```lisp
(defclass eglot-pyls (eglot-lsp-server) ()
  :documentation
  "Microsoft's Python Language Server.")

(cl-defmethod eglot-initialization-options ((server eglot-pyls))
  "Passes through required pyls initialization options."
  `(:interpreter (:properties (:UseDefaultDatabase t))))

(add-to-list 'eglot-server-programs
             `(python-mode eglot-pyls
                           "dotnet"
                           "path/to/Microsoft.Python.LanguageServer.dll"))
``` 

I've also opened https://github.com/Microsoft/python-language-server/issues/469 to simplify this setup (and eventually add it to the built-in`eglot-server-programs`)

**Comment by galeo** [comment]
Sorry, not now. I’m on a vacation, and didn't bring a computer. But the last time when I tested it, it also triggered some other errors. One of the most impressive is that when executing `eglot-shutdown` command, the server seems couldn’t handle the shutdown request correctly. Alnother problem is probably a `<t> is undefined` error that maybe caused by company-mode which I posted a few days ago and I don’t know how to debug it.

**Comment by joaotavora** [comment]
Yes I've noticed those too... Look like server bugs...  but absolutely no rush :) enjoy your vacation

**Comment by yorodm** [comment]
Hello, any advance on this issue?

**Comment by joaotavora** [comment]
@yorodm This issue is closed, not only formally, but substantively. Eglot does now allow non-standard keys by default.

Microsoft's python language server apparently needs some hand-holding.  https://github.com/microsoft/python-language-server/issues/469 is an attempt to reduce the amount of needed hand-holding.  Maybe you can ask there.

And I can ask you, have you tried Eglot with MS's pyls recently?

**Comment by yorodm** [comment]
@joaotavora I'm trying to set them up as we speak, the language servers throws some exception messages, I think is something on their side.

**Comment by muffinmad** [comment]
By analysing NPE and AttributeError errors thrown by ms pyls and inspecting their source code I managed to run ms pyls with eglot. Too bad they expecting some configuration params and don't mention it somewhere. Anyway, here is the code snippet bases on @joaotavora's one:

```elisp
(require 'eglot)

(defvar lsp-python "/path/to/python/python")
(defvar lsp-search-paths [])

(defclass eglot-mspyls (eglot-lsp-server) ()
  :documentation
  "MS Python Language Server.")

(setq-default eglot-workspace-configuration
              '((:python :autoComplete (:extraPaths nil)
                         :analysis (:autoSearchPaths :json-false :usePYTHONPATH :json-false))))

(cl-defmethod eglot-initialization-options ((_server eglot-mspyls))
  `(:interpreter
    (:properties
     (:InterpreterPath ,lsp-python))
     :searchPaths ,lsp-search-paths))

(add-to-list 'eglot-server-programs
             `(python-mode eglot-mspyls
                           "/path/to/dotnet/dotnet"
                           "/path/to/mspyls/dll/Microsoft.Python.LanguageServer.dll"))
```

**Comment by yorodm** [comment]
Yep, it was a case of the old "Microsoft Strikes Back". Thanks for the snippet!!!
