### ISSUE TITLE
Completion snippets don't work without company

### ISSUE THREAD

**Issue by mkcms** [joaotavora/eglot#148]
This is because the string passed to completion `:exit-function` is stripped of it's properties.
A solution might be to store the completion data in an alist.

**Comment by mkcms** [comment]
To clarify, this only happens when you select the completion from `*completions*` buffer.

**Comment by joaotavora** [comment]
Yes, it is indeed a bug. Perhaps we could ask why emacs' core completion engine strips the properties and company's doesn't...

**Comment by mkcms** [comment]
I suggested an alist and had something very similar in mind.
The only problem with this approach is it won't allow us to differentiate duplicates (which are possible in LSP).
However this might not be a problem at all, because from what I can see, `*completions*` buffer doesn't even display duplicates.

**Comment by joaotavora** [comment]
> I suggested an alist and had something very similar in mind.

There's no need to use an associative container if it doesn't bring any benefit.  A hash table could improve performance, but I don't think it's worth it.

> However this might not be a problem at all, because from what I can see, *completions* buffer doesn't even display duplicates.

Yes, it's not a problem.
