### ISSUE TITLE
Use together with Company

### ISSUE THREAD

**Issue by sondr3** [joaotavora/eglot#15]
This is probably a dumb question, but how do you get completions from Eglot to Company? I tried looking at your .emacs.d settings but couldn't find anything that'd help me get any kind of completion in my Emacs. Thanks for the great package though!

**Comment by joaotavora** [comment]
> This is probably a dumb question, but how do you get completions from Eglot to Company?

There's nothing to configure. Just enable `company-mode` in the buffer where eglot is also enabled, and it should pick up automatically. If you also have `company-quickhelp` installed it should also pick up automatically (not for rust, tho, but that's RLS's fault, I think).

> I tried looking at your .emacs.d settings

Really? They are online, but where did you find them?

**Comment by sondr3** [comment]
Hmm, I'll have to try some again because it seemingly didn't pick up on it when I tried. And I found your settings here on Github: https://github.com/joaotavora/holy/tree/master/etc/emacs/ :smile:

**Comment by sondr3** [comment]
Nevermind, I figured it out. `TAB` wasn't set as the default completion in Company, I forgot I switched configs so it wasn't actually completing. My mistake.

**Comment by joaotavora** [comment]
Nice!
