### ISSUE TITLE
flymake bug?

### ISSUE THREAD

**Issue by zbelial** [joaotavora/eglot#162]
Sorry to report a flymake bug here as I don't know where to report it and this problem occurs when starting eglot.
I think the following function in flymake has a bug on the fourth line, where the use of  1+  function is needless. 
I'm using emacs 26.1. Please check this problem, thanks. 

```elisp
(defun flymake-proc--delete-temp-directory (dir-name)
  "Attempt to delete temp dir created by `flymake-proc-create-temp-with-folder-structure', do not fail on error."
  (let* ((temp-dir    temporary-file-directory)
	 (suffix      (substring dir-name (1+ (length temp-dir)))))

    (while (> (length suffix) 0)
      (setq suffix (directory-file-name suffix))
      ;;+(flymake-log 0 "suffix=%s" suffix)
      (flymake-proc--safe-delete-directory
       (file-truename (expand-file-name suffix temp-dir)))
      (setq suffix (file-name-directory suffix)))))

```

**Comment by joaotavora** [comment]
Hello 太阳,

To report this bug use M-x report-emacs-bug or send email to
bug-gnu-emacs@gnu.org. Also send a copy of that mail to me.

You can explain there exactly what happens, and suggest your fix.

By the way. This part of flymake is not related to eglot at all... So I'm
suspicious that it has something to do with your configuration.

Thanks
João
