### ISSUE TITLE
Command in CodeAction can be a string or a Command object

### ISSUE THREAD

**Issue by mkcms** [joaotavora/eglot#164]
According to the spec, return value of `textDocument/codeAction` request can be `(Command | CodeAction)[] | null`. These two objects share a `:command` field. In `Command`, it is a string, in `CodeAction` it's a `Command`. Right now we're assuming it's always a string.
This leads to the following error when using the eclipse.jdt.ls server:

```
Debugger entered--Lisp error: (wrong-type-argument stringp (:title "Add throws declaration" :command "java.apply.workspaceEdit" :arguments [(:changes (:file:///tmp/guava/guava-tests/test/com/google/common/net/HostAndPortTest\.java [(:range (:start ... :end ...) :newText " throws ") (:range (:start ... :end ...) :newText "IOException")]))]))
  intern((:title "Add throws declaration" :command "java.apply.workspaceEdit" :arguments [(:changes (:file:///tmp/guava/guava-tests/test/com/google/common/net/HostAndPortTest\.java [(:range (:start ... :end ...) :newText " throws ") (:range (:start ... :end ...) :newText "IOException")]))]))
  (eglot-execute-command server (intern command) arguments)
  (progn (eglot-execute-command server (intern command) arguments))
  (if command (progn (eglot-execute-command server (intern command) arguments)))
  (when command (eglot-execute-command server (intern command) arguments))
  (progn (when edit (eglot--apply-workspace-edit edit)) (when command (eglot-execute-command server (intern command) arguments)))
  (let* ((#:--cl-rest-- action) (command (car (cdr (plist-member #:--cl-rest-- ':command)))) (arguments (car (cdr (plist-member #:--cl-rest-- ':arguments)))) (edit (car (cdr (plist-member #:--cl-rest-- ':edit))))) (progn (when edit (eglot--apply-workspace-edit edit)) (when command (eglot-execute-command server (intern command) arguments))))
  (cl-destructuring-bind (&key command arguments edit &allow-other-keys) action (when edit (eglot--apply-workspace-edit edit)) (when command (eglot-execute-command server (intern command) arguments)))
  (eglot--destructuring-bind (&key command arguments edit) action (when edit (eglot--apply-workspace-edit edit)) (when command (eglot-execute-command server (intern command) arguments)))
  (let* ((server (eglot--current-server-or-lose)) (actions (jsonrpc-request server :textDocument/codeAction (list :textDocument (eglot--TextDocumentIdentifier) :range (list :start (eglot--pos-to-lsp-position beg) :end (eglot--pos-to-lsp-position end)) :context `(:diagnostics [...])))) (menu-items (or (mapcar (jsonrpc-lambda (&key title command arguments edit _kind _diagnostics) `(... :command ... :arguments ... :edit ...)) actions) (eglot--error "No code actions here"))) (menu `("Eglot code actions:" ("dummy" ,@menu-items))) (action (if (listp last-nonmenu-event) (x-popup-menu last-nonmenu-event menu) (let ((never-mind (gensym)) retval) (setcdr (cadr menu) (cons `... (cdadr menu))) (if (eq (setq retval ...) never-mind) (keyboard-quit) retval))))) (eglot--destructuring-bind (&key command arguments edit) action (when edit (eglot--apply-workspace-edit edit)) (when command (eglot-execute-command server (intern command) arguments))))
  eglot-code-actions(4177 4201)
  funcall-interactively(eglot-code-actions 4177 4201)
  call-interactively(eglot-code-actions)
  #f(compiled-function (event) (interactive "e") #<bytecode 0x18bae45>)((mouse-1 (#<window 141 on *Backtrace*> 4188 (153 . 568) 20446247 nil 4188 (17 . 31) nil (0 . 10) (9 . 18))))
  funcall-interactively(#f(compiled-function (event) (interactive "e") #<bytecode 0x18bae45>) (mouse-1 (#<window 141 on *Backtrace*> 4188 (153 . 568) 20446247 nil 4188 (17 . 31) nil (0 . 10) (9 . 18))))
  call-interactively(#f(compiled-function (event) (interactive "e") #<bytecode 0x18bae45>) nil nil)
  command-execute(#f(compiled-function (event) (interactive "e") #<bytecode 0x18bae45>))
```

**Comment by joaotavora** [comment]
Isn't there a way to know beforehand which of the million little variations the server is going to use? LSP version? Server capabilities, anything?

**Comment by joaotavora** [comment]
@mkcms I've reverted the commit that I had prematurely merged. There's something I don't understand...

**Comment by joaotavora** [comment]
Isn't the correct fix to check to check if `actions` is a `Command` object instead of a vector of `CodeAction` objects?  In that case we should display a one-line menu.

**Comment by joaotavora** [comment]
> Am I misunderstanding this?

No. I was, sorry. 

> we needed eglot--dbind macro for it, so I wanted to wait. I should've written that.

A good `eglot--dcase` macro, you mean.  Or, alternatively, your pcase patterns.  `eglot--dbind` should behave mostly like `cl-destructuring-bind`, meaning it does destructuring but doesn't do matching (i.e. it always runs the same body).

**Comment by mkcms** [comment]
> A good `eglot--dcase` macro, you mean.

Right.

> Or, alternatively, your pcase patterns. `eglot--dbind` should behave mostly like `cl-destructuring-bind`, meaning it does destructuring but doesn't do matching (i.e. it always runs the same body).

OK, I will probably push some improved pcase concept later today.
I have one issue though. With what I have now, `pcase` will look in `eglot--lsp-interface-alist` to find required keys for a given type, at runtime. Can we get rid of that variable, move the type specifications from it to  `pcase-defmacro`s for each type, and then build `eglot--dbind` on top of `pcase`? Or do you want to keep that alist so it can be modified at runtime?

**Comment by mkcms** [comment]
> > Can we get rid of that variable, move the type specifications from it to pcase-defmacros for each type
> 
> Yes, you could. Though you could also generate the `pcase-defmacro`s _from that variable_ at compile time. That would be perhaps nicer.

That's a cool idea, I will try that.

> > and then build eglot--dbind on top of pcase
> 
> Yes, exactly. Keeping the current protocol, yes?

Sure, it will just be `pcase` + a catch-all case which will signal an error. I don't know if without hacking, we can get an error message saying exactly what was missing/excessive though.

**Comment by joaotavora** [comment]
> Sure, it will just be pcase + a catch-all case which will signal an error. I don't know if without hacking, we can get an error message saying exactly what was missing/excessive though.

We probably can, but don't make it a priority. We can always ask Stefan later.

**Comment by joaotavora** [comment]
I just remembered that this isn't really fixed yet, since I reverted the commit.  Wonder what can be done now that we have `eglot--dcase`

**Comment by joaotavora** [comment]
@mkcms Can you try and possibly tweak 8032c20?

**Comment by mkcms** [comment]
> @mkcms Can you try and possibly tweak [8032c20](https://github.com/joaotavora/eglot/commit/8032c2039b88fd2512837223849c4a7fe2736bad)?

I fixed one error (`intern` not called on command title). Seems to work fine, I'll test it more later.

**Comment by joaotavora** [comment]
Damn, I pushed the wrong commit.
