### ISSUE TITLE
Eglot Configuration Issues

### ISSUE THREAD

**Issue by nickenchev** [joaotavora/eglot#166]
Hi, I'm trying to setup Eglot with cquery but running into some problems.
Emacs 26.1
eglot-20181121.1924

If I just open a CPP buffer and run: ```eglot```
It assumes i want to use ccls, so I type "cquery" and it hangs with a message like ```(warning) Sentinel for EGLOT still hasn't run, deleting it!```

I found an issue report regarding this and realized I didn't have Eglot fully configured, so I add the following to my .emacs:
```(add-to-list 'eglot-server-programs '((c++ mode c-mode) . (eglot-cquery "cquery")))```

This causes my emacs to fail initializing, complaining that eglot-server-programs is Void. So then I add the following right before the above line:
```(require 'eglot)```

This removes the Void error and Emacs starts up fine, but when I run M-x: eglot in my buffer, it does the same thing described at the start of this issue report.

Any ideas?

**Comment by nickenchev** [comment]
Btw, installed ccls and it works great, liking it more than cquery with emacs-cquery (so buggy).

**Comment by mkcms** [comment]
@nickenchev After the error is signalled, do `M-x eglot-events-buffer` and post the contents of that buffer here. Also do the same for `M-x eglot-stderr-buffer`.

**Comment by nickenchev** [comment]
I can't actually switch to the buffer as emacs completely hangs. As per my original post, should I be doing ```(require 'eglot)``` during the emacs init? I don't see it in the getting started guide so I'm not sure if its assumed that everyone does that.

**Comment by mkcms** [comment]
When Emacs hangs, just do C-g a couple of times quickly until it unblocks. Does this work?

**Comment by nickenchev** [comment]
Weirdly enough, I can't get this to happen anymore, I have no idea if my test was wrong, or there's some black magic happening. Seems to be working with cquery now as its not hanging and I'm seeing the .cquery index directory.

**Comment by mkcms** [comment]
> Weirdly enough, I can't get this to happen anymore,

Great, reopen if you have this issue again.
