### ISSUE TITLE
xref-find-references bug in clangd (C++)?

### ISSUE THREAD

**Issue by amosnier** [joaotavora/eglot#168]
Hi,
I have just started to use eglot, and I find it great so far. Thanks a lot.
With the latest clangd 8.0.0, `xref-find-references`, in one of my projects, just returns the references in the same file which makes it not very useful. Please note that I was able to get confirmation of the issue with by manually searching for the server's answer in eglot's event buffer in Emacs: clangd only returns references in the same file.
I have tested the same project with ccls, and the same search works perfectly (all the correct hits in multiple files are found).
On the other hand, code completion seems far from great with ccls (it wanted to complete `std::en` to `std::endl(`!).
A little frustrating.
My current intention is to keep clangd, because I value an accurate code completion, and I am hoping that clangd will be improved soon.
Are these known issues? Is there any way to report issues to the clangd project?
Also, I'm a little surprised not to find a function in LSP that would go from declaration to definition. I do not think that finding references really replaces that. Any thoughts on that? Am I missing something?
Thanks again.

**Comment by MaskRay** [comment]
What else do you think clangd's code completion is superior to ccls's?
`std::endl` is a rare case where you want to complete the function name without `(` to get its address, as `std::cout<<` accepts a function pointer: `__ostream_type&      operator<<(__ostream_type& (*__pf)(__ostream_type&))` In most cases you would need the paren.

For the general `snippetSupport` in completion, if you don't like it, you can turn off `yas-minor-mode`.

**Comment by amosnier** [comment]
@mkcms, thanks a lot for your answer. I had seen the page you refer to (I guess you mean the table that says "Find references - No"). My experience of clangd is that clangd-7 does not have support for `find-references` at all (absent capability in the first server answer), while clangd-8 obviously has, but obviously too, very limited. Do I understand you correctly: if I build on my own with `clangd-indexer` I will get an experimental, but in intent fully functional, project-wide `find-references`? In that case, I will definitely try that.

**Comment by MaskRay** [comment]
@amosnier I'll just use an improper analogy, ccls is to clangd what eglot is to vscode-languageserver-node. Lacking of manpower is not necessarily bad as there are so many trade-offs. I'm fine if it remains as a minority tool but I'll need it for learning purpose. It helps me to learn clang internals in the past few months and I definitely need a tool at my own proposal as some crazy ideas might never be adopted by tools controlled by others :(

To your other question about clangd-indexer:

"Creating release_70 branch off revision 338536" The release_70 branch was cut off in August. References feature in clangd needs some commits in October, so no luck with clangd-indexer using 7.0

**Comment by mkcms** [comment]
> Do I understand you correctly: if I build on my own with `clangd-indexer` I will get an experimental, but in intent fully functional, project-wide `find-references`?

This tool is available if you build clangd from source. You run it over files in your project and it generates a file which you provide to clangd via `-index-file` argument. This feature is undocumented, but you can see more info if you run `clangd -help-list-hidden`.

**Comment by MaskRay** [comment]
For the declaration debate, I recall this is some issue in the LSP repo to clarify `textDocument/implementation` and `textDocument/definition`. I guess they were JavaScript/TypeScript oriented when the methods were designed.

ccls uses this approach: `textDocument/definition` jumps to the definitions (there can be many across many TUs, thinking of odr violation) if available. If the cursor is on a definition, jump to declarations instead. Jumping from templates are difficult as for dependent names the targets are indefinite. ccls tries to get every target. These stuff are in the category of project management. These tools may get idea from established tools but the established tools unfortunately have too complex design and too much code :(

**Comment by amosnier** [comment]
@MaskRay. I like your attitude. I will definitely give ccls another try.
@mkcms . Thanks. I understand better.
