### ISSUE TITLE
Feature Request: Add support for angular-language-service

### ISSUE THREAD

**Issue by yorodm** [joaotavora/eglot#172]
Add support for [Angular Language Service](https://angular.io/guide/language-service).

**Comment by joaotavora** [comment]
Eglot already supports all compliant language servers.  If you have confirmed Eglot works with this LS and it is important enough to be in `eglot-server-programs` and listed in the front page, open a PR.

**Comment by sofeepokhrel** [comment]
@yorodm  Have you setup ? Please provide me code.
Thank you

**Comment by yorodm** [comment]
Hi!! Sorry but I'm not using Angular for development anymore. If I recall correctly I was able to partially solve the issue using `tsserver`

**Comment by pietroiusti** [comment]
This worked for me:

``` elisp
(add-to-list 'eglot-server-programs
             '(html-mode "node"
                         "/usr/lib/node_modules/@angular/language-server"
                         "--ngProbeLocations"
                         "/usr/lib/node_modules"
                         "--tsProbeLocations"
                         "/usr/lib/node_modules"
                         "--stdio"))
```

(Cf. [https://github.com/emacs-lsp/lsp-mode/wiki/Install-Angular-Language-server](https://github.com/emacs-lsp/lsp-mode/wiki/Install-Angular-Language-server))

**Comment by JordanAnthonyKing** [comment]
@pietroiusti  Bump an old thread but did you ever encounter this:
![image](https://github.com/user-attachments/assets/6320018b-f9dc-4291-b628-c28f0f2def11)

**Comment by hectorhon** [comment]
> This worked for me:
> 
> (add-to-list 'eglot-server-programs
>              '(html-mode "node"
>                          "/usr/lib/node_modules/@angular/language-server"
>                          "--ngProbeLocations"
>                          "/usr/lib/node_modules"
>                          "--tsProbeLocations"
>                          "/usr/lib/node_modules"
>                          "--stdio"))
> (Cf. https://github.com/emacs-lsp/lsp-mode/wiki/Install-Angular-Language-server)

For anyone having trouble with this, check that the mode is exactly `html-mode` instead of something like `mhtml-mode`, because this affects the language id that is sent to the angular language server.

# Incorrect

If using, say, mhtml-mode:

> [jsonrpc] e[00:22:58.329] --> textDocument/didOpen {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///c%3A/Users/.../test.html","version":0,"languageId":"**mhtml**","text":

Which results in an error such as:

> [jsonrpc] e[00:27:07.372]   <-- window/logMessage {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"**No config file for** c:/Users/.../test.html"}}

# Correct

If using html-mode:

> [jsonrpc] e[00:25:02.203] --> textDocument/didOpen {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///c%3A/Users/.../test.html","version":0,"languageId":"**html**","text":

Test: xref-find-definitions works on a component method in the html file
