### ISSUE TITLE
kotlin language server

### ISSUE THREAD

**Issue by jave** [joaotavora/eglot#18]
I wanted to try a Kotlin language server with eglot, but it didnt go too well.

https://github.com/fwcd/KotlinLanguageServer

I get this error:

[eglot] Ooops: -32603: Internal error.

Caveat: I'm not too familiar with either kotlin or eglot

**Comment by joaotavora** [comment]
Never mind, I see you posted a link.  If you can, please post the contents
of the events buffer associated with the failed attempt, it normally holds
clues as to what went wrong. You'll find it in the buffer list under an
appropriate name.

**Comment by joaotavora** [comment]
I just tried to install the KotlinLanguageServer but couldn't. It fails many self-tests and I don't know how to start it. It seems to be a reasonably experimental thing, with many problems, according to the README. Also I don't know what major mode is being used.

Do try and post the associated events buffer here, and, if you started it as a subprocess, the stderr buffer, too.

**Comment by jave** [comment]
Ok I will try this out. As you say, it is all very experimental, so I wouldnt want you to waste too much time on this. I will also ask the kotlin lsp server people what they think about this.

**Comment by joaotavora** [comment]
I can confirm the "Internal Error" is being sent by the kotlin server.

**Comment by fwcd** [comment]
@joaotavora @jave Hi, I am the current maintainer of KotlinLanguageServer.

First of all, I am not very familiar with Emacs, but I will try to address the problems mentioned. The language server should be (whilst still having a couple of bugs) decently complete. With a correct Java installation, things like code completion or diagnostics should more or less work out of the box.

[As mentioned in this issue](https://github.com/fwcd/KotlinLanguageServer/issues/15), the implementation uses stdio to communicate with the client. The CI integration is currently highly experimental and falsely shows a failing build (whilst all tests pass fine on a local machine).

If there is any concrete error information or stack trace to analyze the problem, I will gladly try to help you.

**Comment by joaotavora** [comment]
Hi @fwcd 
@jave is the one who tried this.  I could't test myself.  I installed:

* kotlin per https://idroot.net/linux/install-kotlin-compiler-debian-9/
* kotlinLanguageServer per https://github.com/fwcd/KotlinLanguageServer/blob/master/BUILDING.md

The first seems to have succeeded, but the second didnd't.  Or at least I think it didn't.  All but 2 of the self tests fail.  I also don't know how to start the server (in case the tests reporting false negatives).

**Comment by fwcd** [comment]
@joaotavora The BUILDING.md was outdated.

In the past the server used a "fat JAR" that bundled all of the dependencies in a single archive. Currently, dependencies are included externally and the server is launched through a start script. To address this issue I have pushed a new version of the repo. Let me know if it works.

The failing tests are probably related to Maven and are going to be addressed soon. They should (hopefully) not impact the language server itself when used with a Maven/Gradle project that at least requires the Kotlin standard library as a dependency.

**Comment by joaotavora** [comment]
@fwcd: I see your new BUILDING.MD, thanks.

Do you confirm that I will be able to run the Kotlin LSP server after just the two steps I gave above?i.e. Kotlin works, KLS tests fail, but scripts should start ls with no problem.

I ask this because I deleted all this kotlin stuff and will only install it agian if I expect a good outcome.  I.e. I would be disappointed if I were to need yet another javaland dependency.

**Comment by fwcd** [comment]
@joaotavora I can understand your frustration, but it's really hard for me to figure issues that do not persist on my own machine. Once I have successfully tested the LS on a separate machine I will post to this thread.

**Comment by joaotavora** [comment]
It's not a matter of frustration, I'm just asking if your LSP server needs another dependency apart from kotln (with which I successfully compiled and ran only a hello world)  I'm not using oracle's jdk for example, is that needed?

**Comment by fwcd** [comment]
@joaotavora There are no new dependencies, so if you have already completed the previous build procedure, there should not be any new downloads needed :)

**Comment by joaotavora** [comment]
again, compiling the hello world kotlin example succeeds (in the same sdk environment)
```
~/S/J/KotlinLanguageServer ❯❯❯ nano hello.kt                                                             
~/S/J/KotlinLanguageServer ❯❯❯ kotlinc hello.kt -include-runtime -d hello.jar                    
~/S/J/KotlinLanguageServer ❯❯❯ java -jar hello.jar  
Hello, World!
```

**Comment by jave** [comment]
I now tried to git pull the kotlin lsp, then:

 ./gradlew build                                                                                                                                                                                          
  /home/joakim/KotlinLanguageServer/build/distributions/kotlin-language-server-0.1.1/bin/kotlin-language-server                                                                                            
 
I used the long path above with eglot, and now I get completions for kotlin in emacs! Nice!

**Comment by jave** [comment]
also, my env is Fedora 27, no oracle jvm, just openjdk. Also, I have gradle installed via fedora repos.

**Comment by joaotavora** [comment]
@jave  that's great.

@fwcd , I was running the wrong script, i think. But now I get 
```
/home/capitaomorte/Source/Java/KotlinLanguageServer/build/install/kotlin-language-server/bin/kotlin-language-server
Exception in thread "main" java.lang.IllegalStateException: LOGGING: Loading modules: [java.se, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynalink, jdk.httpserver, jdk.incubator.httpclient, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jshell, jdk.jsobject, jdk.management, jdk.net, jdk.scripting.nashorn, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsupported, jdk.xml.dom, java.base, java.rmi, java.sql, java.logging, java.xml, java.scripting, java.management.rmi, java.management, java.xml.crypto, java.prefs, java.datatransfer, java.sql.rowset, java.naming, java.instrument, java.compiler, java.security.jgss, java.desktop, java.security.sasl, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.ed, jdk.internal.opt, jdk.internal.le] (no MessageCollector configured)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report(ClasspathRootsResolver.kt:314)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report$default(ClasspathRootsResolver.kt:312)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.addModularRoots(ClasspathRootsResolver.kt:254)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.computeRoots(ClasspathRootsResolver.kt:124)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:79)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:233)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:117)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:413)
	at org.javacs.kt.Compiler.<init>(Compiler.kt:52)
	at org.javacs.kt.CompilerClassPath.<init>(CompilerClassPath.kt:9)
	at org.javacs.kt.KotlinLanguageServer.<init>(KotlinLanguageServer.kt:14)
	at org.javacs.kt.MainKt.main(Main.kt:8)
```

**Comment by fwcd** [comment]
@joaotavora You probably have only a JRE (Java Runtime Environment) installed, but need a JDK (Java Development Kit)

**Comment by joaotavora** [comment]
Nahhh, I give up. I installed the jre and the jdk to the latest version and still get the same error. I'll come back when I need to use this language. In the meantime, let's hope bug reports are scant or contain sufficient information for me to process them without testing locally.

@fwcd, you could make a kotlin/lsp/debian from-scratch guide when you find the time. It's a very common distribution. Many thanks for your prompt support anyway.

**Comment by fwcd** [comment]
@joaotavora No problem, I will create one in the future once I have some more time to spare

**Comment by jojojames** [comment]
@joaotavora Would you be open to adding this to eglot? I think

```
(kotlin-mode . "kotlin-language-server")
```

works OK for me (given I build the server). Not sure if there are other arguments to pass to the language server @fwcd @jave.
