### ISSUE TITLE
wrong number of arguments

### ISSUE THREAD

**Issue by humanitiesNerd** [joaotavora/eglot#191]
I installed eglot with straight

I open a javascript file (with js2 mode)

I do 

`M-x eglot`

and in the minibuffer an error message pops up:

`Wrong number of arguments: assoc, 3`

![eglot](https://user-images.githubusercontent.com/283791/50404988-965ea600-07ae-11e9-83b4-50d3e1de9f94.png)

**Comment by eubarbosa** [comment]
Please give us more info: 

M-x toggle-debug-on-error
Emacs, eglot, server, version
Which package are enable while that error occurs
Did you confirm with just those package enabled that the issues still happens? (emacs -Q)...

**Comment by humanitiesNerd** [comment]
of course, sorry

this is what i get with M-x toggle-debug-on-error

```
Debugger entered--Lisp error: (wrong-number-of-arguments assoc 3)
  assoc(js2-mode ((rust-mode eglot-rls "rls") (python-mode "pyls") ((js-mode js2-mode rjsx-mode typescript-mode) "javascript-typescript-stdio") (sh-mode "bash-language-server" "start") ((c++-mode c-mode) "ccls") ((caml-mode tuareg-mode reason-mode) "ocaml-language-server" "--stdio") (ruby-mode "solargraph" "socket" "--port" :autoport) (php-mode "php" "vendor/felixfbecker/language-server/bin/php-language-server.php") (haskell-mode "hie-wrapper") (kotlin-mode "kotlin-language-server") (go-mode "go-langserver" "-mode=stdio" "-gocodecompletion") ((R-mode ess-r-mode) "R" "--slave" "-e" "languageserver::run()") (java-mode . eglot--eclipse-jdt-contact)) #[514 "=\206
```
Emacs 5.2.1

About eglot, I installed it with [straight](https://github.com/raxod502/straight.el) so I don't know exactly which version I got
I opened the eglot.el file in the package and it seems to be version 1.3

The server is `javascript-typescript-stdio`, I installed it with npm 6.4.1 (I got it with nodejs 10.14.0), globally, I don't know which version it is

In my `.emacs` file I have these lines
```
(straight-use-package 'js2-mode)
(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
(straight-use-package 'eglot)
(straight-use-package 'markdown-mode)
(set-frame-font "DejaVu Sans Mono-21" nil t)
```

with `emacs -Q` straight doesn't get loaded, so eglot doesn't get loaded either

I hope this helps !

If I can report any more information, please let me know !

**Comment by humanitiesNerd** [comment]
I'm reading now that eglot requires Emacs 26.1 :-/

Sorry for the fuss

**Comment by eubarbosa** [comment]
@joaotavora Should not be be a warning that Eglot require 26.1 at top of README? I have seen a lot of confusing on that!

**Comment by humanitiesNerd** [comment]
Ok, I tried with Emacs 26.1 and it works like a charm

Sorry again

**Comment by joaotavora** [comment]
@eubarbosa thanks for debugging this. But no, no org please. Maybe a slightly larger warning,  there is already a notice about emacs 26, and I think it only installs via package.el on 26.1, how else would it satisfy dependencies?

**Comment by eubarbosa** [comment]
@joaotavora Straight literaly ignore and even suggest it users turning off package.el, it is pretty smart about dependencies..

Oh, ok!

**Comment by tomjaguarpaw** [comment]
I've just run across this.  Is it at all possible to display a warning message when eglot is run under Emacs < 26 saying that it is not compatible?  I'm sure that will save a lot of people time.

**Comment by joaotavora** [comment]
> I've just run across this. Is it at all possible to display a warning message when eglot is run under Emacs < 26 saying that it is not compatible?

I _could_ do that, but not many Emacs packages I know do that.  It's very clear on the homepage, and in the package managers MELPA and GNU ELPA it shouldn't be possible to install into Emacs 25.1.  So I prefer to keep it simple.

**Comment by tomjaguarpaw** [comment]
Those, like me, who are not particularly familiar with Emacs may not even know which version they are running.  It seems like it would improve user experience if those with knowledge automated the provision of diagnostics.  New users may not even know where to look for information.  I was very lucky that Google directed me to this ticket.

**Comment by tomjaguarpaw** [comment]
If you're wondering why I didn't just use MELPA or ELPA, well, I can't work out how to pin specific package versions using those repositories, and I prefer that my software configuration is deterministic. (In fact it looks like it's [not possible at all to pin versions in MELPA](https://emacs.stackexchange.com/questions/14263/how-to-install-a-specific-version-of-package)).

**Comment by lxbarbosa** [comment]
@tomjaguarpaw To achieve that sue Quelpa, Straight and I think borg too.

**Comment by tomjaguarpaw** [comment]
> To achieve that, use Quelpa, Straight, and I think borg too.

Thank you for the suggestion.  However the eglot README does say "Install from ELPA or MELPA".

**Comment by xuchunyang** [comment]
Your package manager should refuse to install the package if the dependencies aren't satisfied and warns you, since that is totally the job of a package manager. If it doesn't, we should fix the package manager instead.

And even if eglot does ensure 26.1 is satisfied, it might not be enough, since its dependencies can require higher version such as 26.3, in the end, we will need all packages to check Emacs version, which is not a good idea.

And in this case,

> Wrong number of arguments: assoc, 3

`assoc` accepts 3 arguments until Emacs 26.1, if you use an old version of Emacs to compile the package, you should already been warned by something like the following

    foo.el:2:4:Warning: assoc called with 3 arguments, but accepts only 2

although it's a warning, but 2 arguments function definitely can't deal with 3 arguments, when this line of code runs, it will 100% fail.

**Comment by tomjaguarpaw** [comment]
OK, thank you for the thorough explanation.

**Comment by joaotavora** [comment]
You needn't pin anything to anything. Just understand that eglot needs
Emacs 26 and use it's package installer. Git is for users who want to
develop Eglot. I assume those users read the README.

**Comment by joaotavora** [comment]
> To achieve that, use Quelpa, Straight, and I think borg too.

> MELPA and ELPA even thought their popularity, are not required or the only supported way to fetch packages in Emacs land.

@lxbarbosa , as far as Eglot is concerned, this is _bad advice_.  GNU ELPA and MELPA _are_ the only supported way to install Eglot (you can install via Git _if_ you know what you are doing.

**Comment by lxbarbosa** [comment]
@joaotavora 
I agree on: 'if you know what you are doing'
