### ISSUE TITLE
Removing hard flymake dependancy for textDocument/publishDiagnostics

### ISSUE THREAD

**Issue by akash-akya** [joaotavora/eglot#195]
I have created a flycheck checker for eglot by wrapping `eglot-flymake-backend`. currently, I had to modify https://github.com/joaotavora/eglot/blob/master/eglot.el#L1408 to remove flymake dependency. It would be useful if we separate the logic of consuming diagnostics notifications and flymake dependency, so anyone can plug their own highlighter.

**Comment by joaotavora** [comment]
@akash-akya removing that check makes perfect sense. I just have to double-check the implications, but it should be ok.

@eubarbosa using flycheck isn't a crime! :)

**Comment by joaotavora** [comment]
@akash-akya can you show the code of your flycheck checker?

**Comment by akash-akya** [comment]
Hi @joaotavora!  thanks for the quick reply
This is the very basic flycheck checker I'm using. 

```lisp
;;;; -*- lexical-binding: t -*-
(require 'eglot)
(require 'flycheck)
(require 'cl)

(defvar-local eglot-flycheck--fc-callback nil)

(cl-defun eglot-flycheck--point->line-col (buffer beg)
  (with-current-buffer buffer
    (save-excursion
      (goto-char beg)
      (cons (line-number-at-pos)
            (- (point)
               (line-beginning-position))))))

(cl-defun eglot-flycheck--fm-error->fc-error (err)
  (pcase-let* ((msg (flymake--diag-text err))
               (beg (flymake--diag-beg err))
               (buffer (flymake--diag-buffer err))
               (`(,line . ,col) (eglot-flycheck--point->line-col buffer beg)))
    (flycheck-error-new-at
     line nil ;; TODO: use column and region
     (pcase (flymake--diag-type err)
       (':error 'error)
       (':warning 'warning)
       (':note 'info))
     msg
     :id "eglot-flycheck"
     ;; :checker
     :buffer buffer
     :filename (buffer-file-name buffer))))

(cl-defun eglot-flycheck--flymake-handle-result (flymake-errors &key region)
  (funcall eglot-flycheck--fc-callback
           'finished
           (mapcar #'eglot-flycheck--fm-error->fc-error flymake-errors)))

(cl-defun eglot-flycheck-checker (checker callback)
  (setq eglot-flycheck--fc-callback callback)
  (eglot-flymake-backend #'eglot-flycheck--flymake-handle-result))

(flycheck-define-generic-checker
    'eglot-checker
  "eglot flycheck checker"
  :start #'eglot-flycheck-checker
  :modes (eglot--all-major-modes))
```

Hi @eubarbosa, I didnt say that flymake should't be default. I meant that replacing the flymake should be straight forward. I like flymake but I find flycheck UI is better.

**Comment by joaotavora** [comment]
@akash-akya good one

> I like flymake but I find flycheck UI better.

If you can, spare a minute or two and write to `bug-gnu-emacs@gnu.org` with a wishlist on Flymake's UI. Make sure to include me in the CC.
