### ISSUE TITLE
Flicker doc on minibuffer when cursor changes but doc doesn't

### ISSUE THREAD

**Issue by rodrigues** [joaotavora/eglot#198]
Hi, I'm trying to setup eglot with elixir-ls, it's working pretty good so far 👍🏼

One bad thing that happens though is this flickering the doc when cursor moves forward or backward.

(I recorded the behaviour in the gif below, might take a bit to show properly)

Not sure it's something in my setup (I'm also a bit recent to emacs), or if the same behaviour happens with other languages.

![flicker-doc](https://user-images.githubusercontent.com/128147/50665071-9da46180-0faf-11e9-9f77-b78d92b66966.gif)

Also, another weird thing at the same feature is that the documentation always shown a bit off… the first `n` lines are just skipped in the minibuffer, I don't know why.

**Comment by joaotavora** [comment]
> One bad thing that happens though is this flickering the doc when cursor moves forward or backward.

So you're OK with the long doc in the minibuffer.  Because if you weren't I would suggest https://github.com/casouri/eldoc-box

Flickering the doc is indeed a bug.  I'll see what I can do.

> Also, another weird thing at the same feature is that the documentation always shown a bit off… the first n lines are just skipped in the minibuffer, I don't know why.

This might or not be another bug.  Can you reproduce this with an `Emacs -Q` run where you setup nothing but eglot, elixir-mode and your language server?

**Comment by rodrigues** [comment]
@joaotavora Actually, I wasn't OK with the hover/minibuffer behaviour, heheh… Obrigado 👍🏼

The box is definitely better than the minibuffer, thanks for the suggestion, hover is also bad, at least for Elixir I think, because it gets too verbose, so I'm going with a solution based on the [Help at point hack](https://github.com/casouri/eldoc-box#help-at-point-hack) suggestion in eldoc-box's README.

I've had issues with disabling the minibuffer on hover (I guess it's because of [this line](https://github.com/joaotavora/eglot/blob/master/eglot.el#L1153)?), then I've made that function a bit uglier with my little elisp, and it's working! Pasted the code [here](https://gist.github.com/rodrigues/0866b71ba98a600169cc04ab1473beb6).

With the box, it doesn't jump lines anymore, that's great!

This solution still has a small issue, I don't know if it's specific to my code, or it's related to eglot or eldoc-box: it misbehaves when it runs first time on full screen for mac OS. [Error recording video here](https://drive.google.com/open?id=1EUNXaFWfu8tUhRaflRTcv7ykDLCVuQif)

**Comment by joaotavora** [comment]
The problems with `eldoc-box` are something you should report to its maintainer.  Open an issue there and mention me, maybe I can suggest something. In the meantime I will fix the issues pertaining only to Eglot's use of the minibuffer.

**Comment by rodrigues** [comment]
Thanks, will do!

**Comment by joaotavora** [comment]
Hi @rodrigues , I pushed two commits that improve Eglot's documentation facilities even without `eldoc-box` which may be a bit unstable (it is sometimes so in my experience).  By default, too large docstrings are displayed in their own `*eglot-help*` buffer, though the buffer may not be displayed automatically.  Two new `defcustom`s control this: `eglot-eldoc-extra-buffer` and `eglot-auto-display-eldoc-extra-buffer`.

**Comment by joaotavora** [comment]
@casouri I don't have the specifics here.  I'll try again later.  I whink it was very slugglish on linux.

**Comment by Inkbottle007** [comment]
The snippet above works really well to have the type of the function at point in a very well behaved side-window. It makes use of `eldoc-doc-buffer`. The action of `eldoc-doc-buffer` is exactly as described here: [There should be a cmd called eldoc-doc-buffer that pops up a new buffer showing the contents that would normally be in eldoc. You can scroll in this buffer as well.](https://www.reddit.com/r/emacs/comments/pipu20/comment/hbru60k/?utm_source=share&utm_medium=web2x&context=3)

There is another sort of help at point, which is about the errors at point, when there is wavy underline. I can get the related help two different ways: mouse-hovering or `M-x display-local-help`. Both are in the echo area. The first way is single line, which is not enough, and requires the mouse which I don't usually use. The second is also showing a flickering message saying that I could use `C-h .`, sharing the same echo area, which is very inconvenient.

Anyway, I haven't even started to describe the point that is troubling me.
I'm making use of both `eldoc-doc-buffer` and `display-local-help`. I need the action of `eldoc-doc-buffer` to keep behaving as described in the reddit post above. Both commands have totally different actions. They are linked to the same shortcut:
```emacs-lisp
(defvar eglot-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map [remap display-local-help] #'eldoc-doc-buffer)
    map))
```
btw. `C-h .` is not working on my emacs (29.0.50), I have to either `M-x display-local-help` or `M-x eldoc-doc-buffer` which anyway have totally different actions.

Long flickering messages in echo area are a distraction. Overlay windows like with `echo-box` are small, a distraction too, require a mouse, can't scroll them without a mouse wheel, which I do not have, heavy when compared to plain text buffer...

I have managed to very neatly tame the eldoc doc concerning types and function signatures. I was about to try to do the same with help messages concerning errors, when I stumbled on the snippet above which I do not understand at all. It identifies two actions seemingly totally different. (Also I don't understand, in eglot.el, how those two actions are implemented, where they take their content from, but that's a completely different story.)

Note: the code I actually use to tame "flicker doc on minibuffer when cursor changes..." is just the one in the previous post but wrapped into some `(advice-add 'select-window :after #'my/select-window-action)`, so the eldoc buffer in only showing when the main buffer is eglot managed. It's working really well, and I'd be happy if I can keep using it.
