### ISSUE TITLE
"Terrible hack" in Emacs 27.0.50

### ISSUE THREAD

**Issue by frondeus** [joaotavora/eglot#21]
Hi I'm using Emacs:
> GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin17.5.0, NS appkit-1561.40 Version 10.13.4 (Build 17E202)) of 2018-06-01

I noticed bug in eglot using `flymake-make-diagnostics`. It seems that eglot provides wrong number of arguments.

I also noticed your "horrible hack" for Emacs 26. After I changed condition to `(when (version< emacs-version "27.1")` (from "27.0") - it works fine.

Was this hack merged into Emacs master? Maybe I just need pull it and recompile?

**Comment by joaotavora** [comment]
27.0.50 is indeed a pseudo-version. If you pull and recompile you should
fix your problem. Don't touch the code, then.

**Comment by joaotavora** [comment]
@frondeus, I take it that the 👍 means you're all set. Closing
