### ISSUE TITLE
company completion not popup when it should

### ISSUE THREAD

**Issue by xuchunyang** [joaotavora/eglot#210]
I'm using Eglot with Elixir-Ls, and set `company-minimum-prefix-length` to 2. In the following picture,

- `String.` completion popups
- `String.t` completion doesn't popup (**_unexpected_**)
- `String.tr` completion popups

![2019-01-14 17 46 44](https://user-images.githubusercontent.com/4550353/51108442-38613380-182d-11e9-9abe-7791d44e4b1f.gif)

and if I type `M-x company-complete` after `String.t`, the completion does popup successfully.

**Comment by joaotavora** [comment]
You mean it doesn't popup when you type a `t` after the `.` *and* the popup wasn't open yet,right? 

You could report this to company-mode and request this kind of thing to be programmable.

BTW, the reason it popped up up on `.` is eglot-specific (`.` is a LSP trigger char that the elixir server requested).

**Comment by xuchunyang** [comment]
> You mean it doesn't popup when you type a `t` after the `.` _and_ the popup wasn't open yet,right?

Yes

> You could report this to company-mode and request this kind of thing to be programmable.

I'll consider that.

> BTW, the reason it popped up up on `.` is eglot-specific (`.` is a LSP trigger char that the elixir server requested).

Thanks for the explanation. I didn't know that.

**Comment by joaotavora** [comment]
Closing this.
