### ISSUE TITLE
Eglot ignores eldoc-echo-area-use-multiline-p

### ISSUE THREAD

**Issue by phst** [joaotavora/eglot#214]
If `eldoc-echo-area-use-multiline-p` is nil, then `eldoc-documentation-function` should only return a single line to not overflow the echo area, but Eglot seems to ignore this.

**Comment by joaotavora** [comment]
Thanks. I'll have a look.

**Comment by muffinmad** [comment]
See #443 #453 and maybe #459

**Comment by joaotavora** [comment]
Yes, let's close this.  @muffinmad I made you a collaborator, you should have permissions to close issues, among other things, when you see an obvious thing like this.
