### ISSUE TITLE
eglot using bash-language-server and company-mode doesn't do symbol completion

### ISSUE THREAD

**Issue by vkazanov** [joaotavora/eglot#215]
Thanks for a wonderful package! 

I have a question though. While definition jumping and reference finding works as intended, I don't seem to be able symbol completion using company or plain C-M-i. Instead I just get a list of *all* known symbols.

Is there something I misconfigured something or this kind of completion is just not supported yet? bash-language-server mentions that is has support for it.

**Comment by vkazanov** [comment]
I've did some further investigation and found out that I had some custom code that overrided some of the functions used by eglot. Now that I got rid of it it works as charm.

Thanks!

**Comment by joaotavora** [comment]
Cool. I love when bugs sort themselves out :-D
