### ISSUE TITLE
Eglot still runs after there's no opened buffer for a project

### ISSUE THREAD

**Issue by rodrigues** [joaotavora/eglot#217]
I know we have `eglot-shutdown`, but it would be really nice if eglot auto shuts down after there are no open buffers anymore for a project.

Maybe that's already possible and I'm not aware?

Thanks!

**Comment by nemethf** [comment]
059ea59d5f4453090629e1382762d264e7d8831c implemented auto-shutdown, so I'm closing this issue.  Reopen if that's not what you want.

**Comment by rodrigues** [comment]
just tested and it works like a charm 👍

thanks for the amazing work!
