### ISSUE TITLE
truncated type in flymake diagnostics buffer

### ISSUE THREAD

**Issue by Sarcasm** [joaotavora/eglot#225]
I'm not sure if eglot is the right target or if it should be reported to flymake, but the diagnostic `type` is kinda useless as currently displayed in the flymake diagnostics buffer.

![image](https://user-images.githubusercontent.com/424046/52540777-b01f7100-2d8d-11e9-9ad0-43dc0f9ff91f.png)

As you can see, the type is truncated  to 8 characters, which means we just get `eglot...`, not knowing, apart from the color, that this is an error, a warning, or a note.

Is it possible for eglot to specify a shorter name to flymake?

**Comment by muffinmad** [comment]
I believe it is fixed by [this commit](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=adb5f45d7bc4612916a5b8e4bd2b92d49119b57a).

**Comment by Sarcasm** [comment]
Indeed!
