### ISSUE TITLE
[JS/TS]Typescript server can't find project absolute paths or use jsconfig.json

### ISSUE THREAD

**Issue by rafauke** [joaotavora/eglot#232]
Hey guys,

I would really like to use eglot instead of tide, it feels a lot better to me :) However, I am having some problems, maybe you could guide me what is the possible issue.

I am attaching prntsc for reference:
<img width="522" alt="screenshot 2019-02-22 at 19 23 23" src="https://user-images.githubusercontent.com/9576167/53262743-c73c5800-36d7-11e9-8a30-f3ac38f6b4ef.png">

So, as You can see on the pic, React is properly identified because there is `@types/react` installed. I am also using simple helper library, `prop-styles`, which doesn't have any types included. There are also couple of my own components that are imported with absolute paths: `components/**` and a helper from `helpers`.

```json
{
  "compilerOptions": {
    "target": "es2017",
    "allowSyntheticDefaultImports": true,
    "noEmit": true,
    "checkJs": true,
    "jsx": "react",
    "lib": [ "dom", "es2017" ],
    "baseUrl": "./src"
  },
  "paths": {
    "config": ["config"],
    "helpers": ["helpers"],
    "components": ["components"],
    "hocs": ["./hocs"]
  },
  "exclude": [
    "./ios",
    "./android",
    "./fastlane",
    "./config",
    "./docs"
  ]
}
```

This is the `jsconfig.json` that I have in the root folder of my project. It seems like `javascript-typescript-stdio` which I am using for `web-mode` major mode doesn't read that file or rescpect it anyway. Can you point out what I'm doing wrong?

BTW I am not using typescript in my project _per se_, I just need typings and `node_modules` to jump between files and have these fancy company completions! I would be thankful for any help. Cheers :)

**Comment by nemethf** [comment]
Hi,

What's tide?  Does that also exhibit the same error?  Do you think this is an eglot issue and not an issue with javascript-typescript-stdio?

**Comment by eabarbosa** [comment]
@nemethf 

An Emacs TypeScript "IDE"  package: https://github.com/ananthakumaran/tide

**Comment by rafauke** [comment]
@nemethf  just as @alexanderbarbosa mentioned :)

> 
> What's tide? Does that also exhibit the same error? Do you think this is an eglot issue and not an issue with javascript-typescript-stdio?

Tide actually uses the `jsconfig.json` correctly. Maybe `javascript-typescript-stdio` does not recognize the config file in project root, I don't know...

**Comment by nemethf** [comment]
So, it seems tide relies on [tsserver](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29), which does not speak the language server protocol.  However,  there's an lsp version of tsserver named  [typescript-language-server](https://github.com/theia-ide/typescript-language-server).  You might like to tried that out with eglot.  Having installed the new server, you can configure eglot similarly to [this comment](https://github.com/joaotavora/eglot/issues/243#issuecomment-476508482).

If this indeed a shortcoming of the javascript-typescript-stdio, then I encourage you to report the problem upstream.

**Comment by rafauke** [comment]
@nemethf That's great, thanks for explanation and all the help - This solved the issue 🎉 

For reference: 

```
;; tell eglot to use typescript-language-server instead of avascript-typescript-stdio.
;; ...and don't forget the --stdio flag.
;; https://github.com/joaotavora/eglot/issues/243#issuecomment-476654444
 (add-to-list 'eglot-server-programs '(web-mode . ("typescript-language-server" "--stdio")))
```
