### ISSUE TITLE
Code action fails for javascript-typescript-stdio

### ISSUE THREAD

**Issue by terlar** [joaotavora/eglot#234]
When running the code action "Add 'Type' to existing import declaration from '...'" I receive the following error:
```
error in process filter: jsonrpc-connection-receive: Keyword argument :meta not one of (:method :id :error :params :result :jsonrpc)
error in process filter: Keyword argument :meta not one of (:method :id :error :params :result :jsonrpc)
```

I don't seem to be running with `eglot-strict-mode` set which was the first thing that came to mind. I also don't remember how to get the more verbose error logging. I checked all the eglot buffers (stderr, output and events), but I don't see any information regarding this, only the request/response for the code actions and the request to execute the code fix, but not the response from that last action.

To reproduce you need to have a file with two type definitions, then another ts file using one of those type definitions and then try to use the second type and try to include it via the code actions.

types.ts
```
export interface TypeA {
  propA: string
}

export interface TypeB {
  propB: string
}
```

sample.ts
```
import { TypeA } from './types'

const dataA: TypeA = { propA: 'valueA' }
const dataB: TypeB = { propB: 'valueB' }
```

Execute code action on TypeB

I run the `javascript-typescript-stdio` v2.11.2 and eglot revision: 7d6e3cf5d7ae098aa6c8572343c8bc9b8453aace

**Comment by nemethf** [comment]
I believe this error comes from jsonrpc.el because the server sends an additional meta field in its json rpc objects as its [README describes](https://github.com/sourcegraph/javascript-typescript-langserver/blob/d107424f1f964c4cb3b6061570890639fd69b9e6/README.md#debugging-performance-with-opentracing). 

I could eliminate similar errors with the following patch:
```patch
--- /usr/share/emacs/27.0.50/lisp/jsonrpc.el.gz
+++ #<buffer jsonrpc.el.gz>
@@ -162,7 +162,7 @@
   "Process MESSAGE just received from CONNECTION.
 This function will destructure MESSAGE and call the appropriate
 dispatcher in CONNECTION."
-  (cl-destructuring-bind (&key method id error params result _jsonrpc)
+  (cl-destructuring-bind (&key method id error params result _jsonrpc _meta)
       message
     (let (continuations)
       (jsonrpc--log-event connection message 'server)
```
This is probably not the right way to fix the issue and might not work for you, but it's worth giving it a try.

**Comment by terlar** [comment]
A bit slow turn-around, but I didn't know how to patch such files on my system, so had a bit har time to try it out. I have not figured out how to apply patches to elpa packages and have tried with this patch and I can verify that this resolved the issue for me and the code actions seem to work. But share your concerns, for now I will use this patch.

Thank you for finding this workaround.

**Comment by skangas** [comment]
It seems like this particular language server from sourcegraph has [stopped development in October 2020](https://github.com/sourcegraph/javascript-typescript-langserver/tree/master). They point existing users to [this other language server](https://github.com/typescript-language-server/typescript-language-server) instead. I don't think we should spend time on supporting a now defunct language server.

However, there is a question if `jsonrpc.el` in Emacs should error out when extra fields are added or not. I have not been able to find a definitive answer to that, as [the specification stays quiet on it](https://www.jsonrpc.org/specification). This [particular answer on StackOverflow](https://stackoverflow.com/questions/55080278/json-rpc-2-0-do-extra-fields-on-request-objects-violate-specification) suggests that one reference implementation written by one of the specification authors does _not_ allow it. However, before looking into that further, I think we would want a concrete use case, and it seems like we no longer have one here.

I'm therefore closing this bug report. Feel free to add any thoughts and comments: if there are good arguments against this conclusion, we can always reconsider. Thanks.
