### ISSUE TITLE
hover-after-completions

### ISSUE THREAD

**Issue by nemethf** [joaotavora/eglot#239]
I've tried into why the hover-after-completions test fails in the recent travis builds (e.g, #235, #233).  If I understand correctly, eglot-completion-at-point calls eglot-eldoc-function in its exit-function with the intention of displaying the eldoc documentation.  However, depending on the the eldoc-timer, soon eldoc will check whether there's a documentation for the current point.  Since completion-at-point (C-M-i) is not in the eldoc-message-commands, eldoc will clear the echo area, and set eldoc-last-message to nil. 

So instead of calling eglot-eldoc-function at the end of elgot-completion-at-point.  Eglot cloud  (eldoc-add-command 'completion-at-point) in eglot--managed-mode.  

However, following João's philosophy, I think eglot should not implement this feature.  If users want to see documentation after completions, then they should add (eldoc-add-command 'completion-at-point) to their init files, or try to ask the eldoc maintainers to modify eldoc-edit-message-commands to return completion-at-point as well.  In the mean time, it might be a good idea to draw attention to the eldoc-add-command in the readme.

**Comment by joaotavora** [comment]
@nemeth `hover-after-completions` is passing again.  Are you sure this is still needed?  Let me know and I will re-open.
