### ISSUE TITLE
Q: lsp-ui

### ISSUE THREAD

**Issue by rileyrg** [joaotavora/eglot#240]
is lsp-ui supposed to work with this? If not how do I enable lsp type features like peek and sideline?

**Comment by joaotavora** [comment]
No, `lsp-ui` is a completely different and foreign component to eglot.  What particular feature are you looking for?

**Comment by rileyrg** [comment]
Stuff like LSP UI provides:signatures, docs, #define values, definition
code  and flymake error integration.   LSP works well for me I was just
wondering if eglot bought anything to the table . I'm using ccls.

**Comment by joaotavora** [comment]
> Stuff like LSP UI provides:signatures, docs, #define values, definition code and flymake error integration. 

All of those are supported by eglot as far as I know, perhaps under slightly different names or interfaces.  

Peek and sideline are notably not supported yet.
