### ISSUE TITLE
xref-find-definitions fails to locate component in a React project

### ISSUE THREAD

**Issue by carlbolduc** [joaotavora/eglot#243]
With the following code:
```
import React from "react";
import OtherComponent from "./OtherComponent";

const MainComponent = props => {
  return (
    <tr>
      <td>{props.item.date}</td>
      <td>{props.item.description}</td>
      <td style={{ textAlign: "center" }}>
        <OtherComponent onClick={() => props.doStuff()} />
      </td>
    </tr>
  );
};

export default MainComponent;
```

Calling `xref-find-definitions` using `M-.` will go to the second line of the file (`import OtherComponent from "./OtherComponent";`) instead of actually going to the file where `OtherComponent` is defined.

Trying the same thing in VS Code will go to the file where `OtherComponent` is defined. Although VS Code might be using a different LSP than Eglot. The behaviour of VS Code is much more useful.

Is there something that can be configured to support find definition in a React jsx file?

**Comment by nemethf** [comment]
I haven't used React before, but it might help to understand the issue if you could switch to the *EGLOT (...) events* buffer and search for the "textDocument/definition" client-request and post that here with the corresponding server-reply.

**Comment by carlbolduc** [comment]
Here is what I see in the event buffer:
```
client-request (id:15) Sat Mar 23 21:05:08 2019:
(:jsonrpc "2.0" :id 15 :method "textDocument/definition" :params
	  (:textDocument
	   (:uri "file:///Users/carl/src/cfdg-portal/src/scenes/MealPlans/MealPlans.jsx")
	   :position
	   (:line 102 :character 14)))

server-reply (id:15) Sat Mar 23 21:05:08 2019:
(:jsonrpc "2.0" :id 15 :result
	  [(:uri "file:///Users/carl/src/cfdg-portal/src/scenes/MealPlans/MealPlans.jsx" :range
		 (:start
		  (:line 4 :character 7)
		  :end
		  (:line 4 :character 15)))])
```

My sample above was a simplification of my real code that is being used here for this test. The behaviour is the same:
- I ask for the definition
- It goes to the beginning of the same file where the import is (line 4) instead of going in the actuel file where the import is defined.

**Comment by nemethf** [comment]
According to the log, everything is fine on the elgot's side.  The server's reply states the definition is at line 4.

It is possible that VS Code sends a different request or it does some post processing cleverness once it has received the reply from the server.  However, before we go down on that path, can you make sure that you run the same version of the server with both clients (VS Code, eglot)?  Alternatively, you might like to ask the server developers what they think about this textDocument/definition reply.

**Comment by carlbolduc** [comment]
After doing some research, it looks like VS Code does not use LSP for code navigation in JavaScript files, it uses a built-in `tsserver`. It's been wrapped in a LSP server apparently though:
https://github.com/theia-ide/typescript-language-server

**Comment by nemethf** [comment]
I assume you used something else than the typescript-language-server in your original report.  So, does the problem still exist if you switch to the typescript-language-server?

**Comment by carlbolduc** [comment]
Yes, I was using the one recommended in the Eglot documentation (`javascript-typescript-stdio`). If I try to use `typescript-language-server`, I get nothing.

I configured it this way:
```
(add-to-list 'eglot-server-programs '(web-mode . ("typescript-language-server")))
```

It's not working however, when I check the Eglot buffer:
```
jsonrpc-error: jsonrpc-error: "No current JSON-RPC connection", (jsonrpc-error-code . 32603), (jsonrpc-error-message . "No current JSON-RPC connection")
```

**Comment by eabarbosa** [comment]
@carlbolduc Should you call it with js-mode instead of web-mode? Anyway, you can call a specific server with m-x eglot
Can you confirm if it works?

**Comment by nemethf** [comment]
I don't know what web-mode is, but that part is probably OK, since you managed to get an effect using it.  However, according to the web page of typescript-language-server, you should start it by passing a command line argument to it (--stdio).  You can verify this by starting the program from the command line without the argument and with it.  If the argument is in deed necessary, then the above configuration line should be changed to something like this:

      (add-to-list 'eglot-server-programs '(web-mode . ("typescript-language-server" "--stdio")))

In the mean time, however, I'd encourage you to report your findings about javascript-typescript-stdio to its developers.

**Comment by carlbolduc** [comment]
Adding `"--stdio"` did the trick, thank you very much.

About `web-mode`, it handles the React syntax (JSX) really well. Since I am running an LSP integration, I don't need all the features of `js2-mode`, I just need a good syntax highlighter.

**Comment by eabarbosa** [comment]
> Adding `"--stdio"` did the trick, thank you very much.
> 
> About `web-mode`, it handles the React syntax (JSX) really well. Since I am running an LSP integration, I don't need all the features of `js2-mode`, I just need a good syntax highlighter.

I do just the same. Tho, I dont use jsx too, just plain js-mode + eglot

**Comment by joaotavora** [comment]
It looks like this is fixed.
