### ISSUE TITLE
What unicode unit does eglot use in lsp ranges?

### ISSUE THREAD

**Issue by Avi-D-coder** [joaotavora/eglot#244]
Does this project use UTF-8, UTF-16, codepoint, or grapheme cluster indexes for lsp ranges?

If this project uses a unit other than UTF-16 could/would you ever conform to the protocol 3.0 and use UTF-16?

I am conducting a [survey](https://github.com/Avi-D-coder/lsp-range-unit-survey) to inform the debate over what unit ranges should use in the [Language Server Protocol](https://github.com/Microsoft/language-server-protocol).
The debate is occuring in [issue #376](https://github.com/Microsoft/language-server-protocol/issues/376).

**Comment by joaotavora** [comment]
> If this project uses a unit other than UTF-16 could/would you ever conform to the protocol 3.0 and use UTF-16?

If I understand the issue correctly, there is code in this project to use UTF-16 but it is disabled by default, since most servers don't need it and it is slightly less performant. See #124, #125 and #135.

**Comment by Avi-D-coder** [comment]
@jabranham thanks
