### ISSUE TITLE
eglot with Julia LanguageServer.jl

### ISSUE THREAD

**Issue by non-Jedi** [joaotavora/eglot#250]
I just wanted to leave an issue here to ping the eglot maintainer and let you know [I successfully got eglot with Julia's LanguageServer.jl and documented the process in its github wiki here](https://github.com/JuliaEditorSupport/LanguageServer.jl/wiki/Emacs). I haven't had enough time messing with it to see what's working and not working, but I've noticed no problems in the 10 minutes I've spent playing with it so far. I will make sure to file issues here for any problems I run into. Thanks for the great project!

**Comment by joaotavora** [comment]
Great! But let's close this one and you can open specific issues for the eglot-related issues you run into. Don't worry able opening multiple issues, and be as specific as possible.

**Comment by non-Jedi** [comment]
eglot is the first emacs package I've run into in the wild that hooks into project.el. Do you know if the vision for integration with specific language's project structure is for that code to live in the language major mode package (should I try to push project.el integration into julia-mode)? or maybe that kind of question is still to be defined.

**Comment by alexanderbarbosa** [comment]
@non-Jedi You are free to integrated it to whatever helps and easy developer's workspace.

If you are up to that, expand julia-mode, pull request at its repo: https://github.com/JuliaEditorSupport/julia-emacs

**Comment by joaotavora** [comment]
> Do you know if the vision for integration with specific language's project structure is for that code to live in the language major mode package

Yes, precisely.  At least as far as eglot is concerned, that is exactly the vision. Well at least _my_ vision.

> If you are up to that, expand julia-mode, pull request at its repo: https://github.com/JuliaEditorSupport/julia-emacs

If licensing terms allow it, sooner or later julia-mode should make it into GNU Elpa or GNU Emacs' core. That needs the copyright assignment of julia-mode's authors, so I would consider taking that step regardless (ask in the emacs-devel@gnu.org mailing list).

> PS: project.el is an emacs bultin package, there is projectile as another alternative, stabler and bigger.

If you want the dependencies of the programs you write for Emacs to be reduced to Emacs, I would avoid `projectile.el`.  The project-discovering in `projectile.el` logic is only a small part of it, according to the author. The other parts that I presume are there, such as grepping a project, or finding a file in a project... are _also_ being added to Emacs core, where they coexist and integrate, not only with `project.el` but with other built-in components, such as `xref.el`, etc...
