### ISSUE TITLE
Completion has extra "stuff"

### ISSUE THREAD

**Issue by jabranham** [joaotavora/eglot#252]
In a python buffer like:

```python
import os
os.gete
```

M-x completion-at-point after os.gete, then select getenv, results in:

```python
import os

os.getenv(${1:key}, ${2:default})$0
```

**Comment by alexanderbarbosa** [comment]
I've tried to reproduce with no success.

Anyway, that a  yasnippet expansion not correctly finished, found here: https://github.com/joaotavora/eglot/blob/7d6e3cf5d7ae098aa6c8572343c8bc9b8453aace/eglot.el#L1038

@joaotavora is kinda busy, if you discover how to fix it, please pull it up, as you too have gnu signed! :D 

Emacs 26.2 (emacs -Q) / eglot Version: 1.4 / pyls (stdio)

**Comment by nemethf** [comment]
For a short period of time, there was a bug in python-language-server (I assume that's what you use), which made pyls send snippets even if the client said it wasn't capable of processing them.  So, you can try to upgrade/downgrade your server.  Alternatively, you can enable snippet support in eglot by installing yasnippet from GNU ELPA and M-x yas-global-mode before starting eglot.  The snippet support is rarely annoying and often useful.

**Comment by jabranham** [comment]
@nemethf Thanks, upgrading to python-language-server to 0.26.1 seems to solve the issue.
