### ISSUE TITLE
Julia language server: handle server crashes during textDocument/definition more gracefully

### ISSUE THREAD

**Issue by non-Jedi** [joaotavora/eglot#253]
This is mostly [an upstream bug with the language server](https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/339), but the user experience on the emacs side isn't the nicest. When using `xref-find-definitions`, the language server crashes (but only when eglot has just been started recently and only sometimes); this causes the entire emacs UI to hang and eventually an error shows up in messages: `jsonrpc-error: "request id=2 failed:", (jsonrpc-error-code . -1), (jsonrpc-error-message . "Server died"), (jsonrpc-error-data)`. Is there any way to make this asynchronous so that everything isn't frozen for 5+ seconds if the server crashes in the background?

**Comment by non-Jedi** [comment]
I'm having trouble reproducing the server crash for the upstream bug report. Are there conditions where the contents of the `textDocument/definition` request may be different than normal? Some sort of race condition?

**Comment by nemethf** [comment]
I don't see how xref-find-definitions (`M-.`) could be asynchronous.  You press M-., continue editing, then five seconds later, when you are in middle of something, the definitions arrive and the point changes out of the blue.  That would be annoying.

Currently, you should be able to abort the blocking command with `C-g`.   Isn't that enough?

**Comment by non-Jedi** [comment]
You're right. I don't think, there's anything else that could be done here.
