### ISSUE TITLE
Julia language server: consistent timeout error on `eglot-shutdown`

### ISSUE THREAD

**Issue by non-Jedi** [joaotavora/eglot#254]
Every time I invoke `eglot-shutdown` against the Julia language server it results in a "Timed out" error. My guess is that this is just the server shutting down slowly, but maybe this particular server hasn't implemented polite shutdown. Not sure how to tell. In general, since functions in Julia are compiled "just ahead of time" on first invocation, the first time any capability of the language server is used, it tends to hang a bit, so this could be that. 

In any case, should there be an `eglot-shutdown-timeout` variable?

**Comment by nemethf** [comment]
(If the server doesn't reply to the Shutdown Request, then it violates the protocol.)

**Comment by nemethf** [comment]
The shutdown logic in Eglot was changed since your report.  @non-Jedi, do you still get timeouts?

**Comment by non-Jedi** [comment]
Not an issue any more afaict. Thanks for the ping.
