### ISSUE TITLE
clangd performance

### ISSUE THREAD

**Issue by fcangss** [joaotavora/eglot#256]
sorry to ask this question, but i have no idea to solve this problem. my environment is win10+emacs26.1,use eglot+clangd to write c++ files, it was very slowly to show the candidate list, i guess it had too much time to search,for example, vector<int>iv, iv.  when i press dot, after 10 seconds it popup the list,how to improve the performance?

**Comment by mkcms** [comment]
I remember I once improved clangd performence by disabling outputting debug info from clangd to standard error. In my case, I modified the clangd entry in `eglot-server-programs` to something like `bash -c 'clangd 2>/dev/null'`.

You can also set `eglot-events-buffer-size` to zero, that may also improve performance a bit.

**Comment by joaotavora** [comment]
Closing to to inactivity (and a workaround was provided).
