### ISSUE TITLE
Be able to customize change idle timer

### ISSUE THREAD

**Issue by ambihelical** [joaotavora/eglot#258]
Currently eglot "notices" changes after 0.5s of idle time (in eglot--after-change).  If find this is too quick for my tastes, and would like to be able to set it to a larger value via a custom setting.  

Experimentally, I find that setting it to 2s helps with the mode-line issue described in #236.  But I realize this is a personal taste thing, so it should be customizable.

**Comment by joaotavora** [comment]
Customizing this makes sense, and is a something to include in  `eglot.el` directly.  Should be simple, so pull requests welcome.  Try to follow the existing coding style and commit format as closely as possible. Thanks.
