### ISSUE TITLE
Other enabled flymake diagnostics functions gets dropped

### ISSUE THREAD

**Issue by terlar** [joaotavora/eglot#268]
When trying to use eglot together with other flymake diagnostics functions it overwrites the `flymake-diagnostic-functions` with:
```
(eglot-flymake-backend
 t)
```

Only way to use eglot is to ensure the other backends are enabled after the fact that eglot has loaded. I think it would make sense if eglot didn't overwrite the functions specified in `flymake-diagnostic-functions` but instead append it's own.

I've tried to add another backend by hooking into `eglot-mode-hook`, but only way I have gotten it to work is to manually enable the other backend after eglot to have both.

**Comment by joaotavora** [comment]
ack. I remember this was intentional, to fix some problem that maybe isn't so important anymore.  I'll check soon.

**Comment by joaotavora** [comment]
@terlar sorry for the long delay.  The problem still exists.  Flymake will check all the backends and gather all the diagnostics.  Sometimes, in `python-mode`, this leads to duplicated diagnostics. So, by default, Eglot uses only the `eglot-flymake-backend` and supresses the others.

If you'd like to take control of this in your configuration, you can use the new variable `eglot-stay-out-of` to control this.

```lisp
(setq eglot-stay-out-of '(flymake))
(add-hook 'eglot--managed-mode-hook (lambda () (add-hook 'flymake-diagnostic-functions 'eglot-flymake-backend nil t)))
```

This is untested, but should work.

**Comment by joaotavora** [comment]
Let me know if I should reopen this.

**Comment by JiaHong-Lee** [comment]
> ```lisp
> (add-hook 'eglot--managed-mode-hook (lambda () (add-hook 'flymake-diagnostic-functions 'eglot-flymake-backend nil t)))
> ```

Thanks! This code is working for me.

**Comment by joaotavora** [comment]
Please note that this is unofficial for now.  However there will be an `eglot-managed-mode-hook` soon (and the `eglot--managed-mode-hook` will be kept, but deprecated).

**Comment by hacktivista** [comment]
Wow, this actually breaks Flymake functionality. You should warn about on the README.

**Comment by joaotavora** [comment]
> Please consider not forcing the current unexpected behavior.

I have considered it, and created `eglot-stay-out-of` for this and other questions.  You can make a pull request referencing it in the README, in the proper section and following the README's existing style.

**Comment by hacktivista** [comment]
Yup, I'm using it. But still think is a suboptimal design choice, though probably you made it thinking on something I'm not able to understand. You know your project.

I'm sending the patch to the README here https://github.com/joaotavora/eglot/pull/403

**Comment by joaotavora** [comment]
> But still think is a suboptimal design choice, though probably you made it thinking on something I'm not able to understand.

Alright I'll explain it.  Elglot and LSP are supposed to "take over" the managing of the buffer, so having other overlapping functionality is more confusing than helpful.  Not saying _some_ people won't find it helpful, as you certainly did (and _that's_ why I created the override), but I decided that _most_  people would be confused by it.  

Exactly the same with the `company-backends`.  See this recipe in `clangd`'s repo:  https://clang.llvm.org/extra/clangd/Installation.html

At some point is says: 

"company-clang is enabled by default, and will interfere with clangd. Disable it in M-x customize-variable RET company-backends RET."

Now, ever since `eglot-stay-out-of`, that doesn't need to be done.

**Comment by hacktivista** [comment]
I thought that you thought that.

Still, I think there are a lot of cases where simply makes more sense to have emacs natively handing the checkers than with external servers (as on VSCode). Flymake indeed is for syntax checking, and nothing else, while LSP for a lot more things, it just makes more sense to append linters directly to it.

I really consider that LSP is a great addition to Emacs, and simplifies a lot of things that on other times were just a mess. Though I still see the value of Emacs being a modular editor and not an opinionated IDE.

I have nothing to argue with you regarding how you prefer your project to work, if you like it opinionated that's your choice. Though IMO interfering with the behavior of other packages is not sane, and if you do it, you should state it clearly. I've lost a few hours trying to check why Flymake didn't do what I was telling it to do.

**Comment by joaotavora** [comment]
> I have nothing to argue with you regarding how you prefer your project to work, if you like it opinionated that's your choice.

I don't like it opinionated for "opinionations" sake. It wasn't "an opinion": I took this decision to fix a real problem: interference of non-LSP functionality with LSP, the main goal of Eglot.

I'm very sorry you lost a lot of time.  Make a contribution to the documentation to help other, I say, a sober and concise one that doesn't needlessly express this aggravation. And do consider I put in quite a bit more than a few hours creating Eglot (and Flymake) and answering user's questions.
