### ISSUE TITLE
Eglot creates too many language server processes?

### ISSUE THREAD

**Issue by pclalv** [joaotavora/eglot#270]
in short, i was wondering whether or not there's some way to configure eglot to start a single language server per project, and to then have all buffers for that language within that project communicate with that server. 

for context, my experience with eglot is that it starts a process per buffer - in the case of a ruby project, it'll start a solargraph process for each ruby file that i have open. i tend to leave a bunch of buffers open, so the processes really pile up. it also seems like killing a buffer doens't kill that buffer's solargraph process. this has been taxing my computer recently, and it's gotten to the point where i'm actively looking for an easier way of doing thing.

**Comment by alexanderbarbosa** [comment]
related: https://github.com/joaotavora/eglot/issues/249

**Comment by joaotavora** [comment]
> start a single language server per project,

I can assure you that this is what Eglot does, from the very beginning.  Maybe you don't have a project relating all those ruby buffers.  If they are all int he same .git directory there should be some project relating them.

**Comment by joaotavora** [comment]
>  it also seems like killing a buffer doens't kill that buffer's solargraph process.

This is true: a project with no open buffers will not automatically kill the server (though you need at least a one-buffer-long project to start a server).  This part could be changed, i.e. one could automatically kill a server if the project is emptied of buffers, subject to a customization.

**Comment by pclalv** [comment]
okay, i understand now. i'm a projectile user; i applied [this elisp](https://github.com/joaotavora/eglot/issues/129#issuecomment-444130367) and now i've got one server for all the files in my project. 

i encountered that same issue before creating this one but i didn't understand what it was about. i see too that there's a point in the [readme's Historical differences to lsp-mode.el section](https://github.com/joaotavora/eglot) that speaks to this issue. 

feel free to close this issue. thanks for your time.

**Comment by skangas** [comment]
It seems like everything is done here, so I'm closing this issue. If this conclusion is incorrect, please write below and we can re-open. Thanks in advance.
