### ISSUE TITLE
Handle signature label offsets error in eglot--sig-info

### ISSUE THREAD

**Issue by galeo** [joaotavora/eglot#272]
Eglot added support for signature label offsets in 3ecdef1ea. However, when `documentation` in ParameterInformation is none nil, the wrong type argument error will be issued:

```
Debugger entered--Lisp error: (wrong-type-argument stringp [25 29])
  propertize([25 29] face eldoc-highlight-function-argument)
  #f(compiled-function () #<bytecode 0x44103e71>)()
  eglot--call-with-interface((ParameterInformation (:label) (:documentation)) (:label [25 29] :documentation (:kind "plaintext" :value "host: str")) #f(compiled-function () #<bytecode 0x44103e71>))
  ...
```

**Comment by galeo** [comment]
Here is an example of signature information from the MS python language server:
```emacs-lisp
(:label "ForeignKey(to, on_delete=None, related_name=None, related_query_name=None, limit_choices_to=None, parent_link=False, to_field=None, db_constraint=True, kwargs)"
 :documentation (:kind "plaintext"
                 :value "\n    Provide a many-to-one relation by adding a column to the local model\n    to hold the remote value.\n\n    By default ForeignKey will target the pk of the remote model but this\n    behavior can be changed by using the ``to_field`` argument.\n    ")
 :parameters
        [(:label [11 13] :documentation (:kind "plaintext" :value "to"))
         (:label [15 24] :documentation (:kind "plaintext" :value "on_delete"))
         (:label [31 43] :documentation (:kind "plaintext" :value "related_name"))
         (:label [50 68] :documentation (:kind "plaintext" :value "related_query_name"))
         (:label [75 91] :documentation (:kind "plaintext" :value "limit_choices_to"))
         (:label [98 109] :documentation (:kind "plaintext" :value "parent_link: bool"))
         (:label [117 125] :documentation (:kind "plaintext" :value "to_field"))
         (:label [132 145] :documentation (:kind "plaintext" :value "db_constraint: bool"))
         (:label [152 158] :documentation (:kind "plaintext" :value "kwargs"))])
```

**Comment by galeo** [comment]
The `label` in ParameterInformation can be type `string | [number, number]`.
> a label of type string should be a substring of its containing signature label.

From the above example of signature information, the `value` property of `documenation` (type `string | MarkupContent`) in ParameterInformation is equal to the substring of signature label (calculated by `label` property in a parameter).

**Comment by galeo** [comment]
Can get it working with this simple patch:

```diff
@@ -2032,7 +2032,8 @@ is not active."
            ;; Decide what to do with the active parameter...
            (when (and (eql i active-sig) active-param
                       (< -1 active-param (length parameters)))
-             (eglot--dbind ((ParameterInformation) label documentation)
+             (let ((sig-label label))
+               (eglot--dbind ((ParameterInformation) label documentation)
                  (aref parameters active-param)
                ;; ...perhaps highlight it in the formals list
                (when params-start
@@ -2055,8 +2056,11 @@ is not active."
                  (goto-char (point-max))
                  (insert "\n"
                          (propertize
-                          label 'face 'eldoc-highlight-function-argument)
-                         ": " (eglot--format-markup documentation))))))
+                          (if (stringp label)
+                              label
+                            (substring sig-label (aref label 0) (aref label 1)))
+                          'face 'eldoc-highlight-function-argument)
+                         ": " (eglot--format-markup documentation)))))))
```

**Comment by joaotavora** [comment]
@galeo OK thanks. I think I understand what's going on.  You can further simplify the patch if you notice that the text you're looking for (when `label` isn't a string) is in the buffer itself at exactly the positions you expect.  So ditch the `sig-label` variable and use `buffer-substring` instead of `substring`.  Then make a pull request with a properly formatted commit message (see the others for examples).

**Comment by galeo** [comment]
I’d like to do it, but I have not signed the fsf paper yet. Do I need to sign the paper?

**Comment by joaotavora** [comment]
> Do I need to sign the paper?

No. It's small enough that it doesn't need an assignment.

Just make sure you add the string `Copyright-paperwork-exempt: yes` to an isolated line in your commit message.

**Comment by galeo** [comment]
@joaotavora I have created a pull request that contains a simplified piece of code. Please review it. Thanks.

**Comment by joaotavora** [comment]
> Please review it. Thanks.

Had a look, looks pretty good.  A bit worried by the test failure, though it's probably not your fault. Have you tested it?

**Comment by joaotavora** [comment]
> Have you tested it?

Kind of a dumb question, you probably have. I meant to ask, what servers did you test it with?

**Comment by galeo** [comment]
Yes，the [MS python language server](https://github.com/Microsoft/python-language-server).

**Comment by galeo** [comment]
@joaotavora  I just took a look at the CI log and it reports that the `jsonrpc` package is unavailable. The `make check` command exits abnormally, which should be the reason for the test failure. 

I tested the modified code with MS python language server without problems. There is no problem either with Apple's swift language server [sourcekit-lsp](https://github.com/apple/sourcekit-lsp).

**Comment by joaotavora** [comment]
> I just took a look at the CI log and it reports that the  jsonrpc package is unavailable

I think I know what's boing on, it's a false positive...
