### ISSUE TITLE
Handle invalid position in textDocument/publishDiagnostics

### ISSUE THREAD

**Issue by haqle314** [joaotavora/eglot#273]
I'm not sure what triggers this exactly but sometimes `pyflakes` returns `-1`
for character. The relevant part of the data sent from the server looks like this

```
(:source "pyflakes"
 :range (:start (:line 69 :character -1)
         :end (:line 69 :character 1))
 :message "f-string: empty expression not allowed" :severity 1)
```

The main problem is every time this happens, I get errors and Emacs hangs for a couple of seconds. The error message in Emacs is

```
error in process filter: eglot--lsp-position-to-point: Wrong type argument: wholenump, -1
error in process filter: Wrong type argument: wholenump, -1
error in process filter: eglot--lsp-position-to-point: Wrong type argument: wholenump, -1
error in process filter: Wrong type argument: wholenump, -1
```

I think `eglot-handle-notification` should check for invalid position like this and just ignore it, or maybe emit a warning.

**Comment by nemethf** [comment]
I personally against ignoring errors like this, because if users expects a specific behavior, they won't know why that behavior does not happen (Is there a bug in the server, in the client, or in emacs?)

However, I agree eglot should handle the error more gracefully.  Emiting a warning might be OK.
I might try to implement this but I need a minimal step-by-step report to reproduce the issue. 

(It is clearly a server-side bug as the specification says "Special values like for example -1 to denote the end of a line are not supported."  Have you reported the bug there as well?)

**Comment by joaotavora** [comment]
> However, I agree eglot should handle the error more gracefully. 

Yes

> Emiting a warning might be OK. I might try to implement this but I need a minimal step-by-step report to reproduce the issue.

Yes, maybe even skipping the step-by-step, it should be reasonably safe in this case.  What's your opinion on this (untested) patch?
```lisp
diff --git a/eglot.el b/eglot.el
index 4fa58a7..944cc39 100644
--- a/eglot.el
+++ b/eglot.el
@@ -1020,8 +1020,13 @@ If optional MARKER, return a marker instead"
     (forward-line (min most-positive-fixnum
                        (plist-get pos-plist :line)))
     (unless (eobp) ;; if line was excessive leave point at eob
-      (let ((tab-width 1))
-        (funcall eglot-move-to-column-function (plist-get pos-plist :character))))
+      (let ((tab-width 1)
+            (col (plist-get pos-plist :character)))
+        (unless (wholenump col)
+          (eglot--warn
+           :eglot "Caution: LSP server sent invalid ~a character position. Using 0 instead.")
+          (setq col 0))
+        (funcall eglot-move-to-column-function col)))
     (if marker (copy-marker (point-marker)) (point))))
 
 (defun eglot--path-to-uri (path)
```

**Comment by nemethf** [comment]
The patch looks good to me for this particular bug report.  Although I don't understand the "~a" part in the warning message.

However, if the start is vaild and the end is invaild, then the beginning of the region can be larger than the end.  Eglot has `length (- end beg)` somewhere, so I guess even if eglot--lsp-position-to-point is bulletproof, eglot might fail ungracefully somewhere else for servers that are buggy in a different way.  Or it might not, I'm not completely sure.

**Comment by joaotavora** [comment]
> Although I don't understand the "~a" part in the warning message.

Because it's wrong :-)

> However, if the start is vaild and the end is invaild, then the beginning of the region can be larger than the end. Eglot has length (- end beg) somewhere, so I guess even if eglot--lsp-position-to-point is bulletproof, eglot might fail ungracefully somewhere else for servers that are buggy in a different way. Or it might not, I'm not completely sure.

It could, yes.  We're just covering a (presumably) common case here.  Let's cross that other bridge when we get to it.

**Comment by haqle314** [comment]
For anyone curious, I opened an issue upstream (PyCQA/pyflakes#450). Turned out, it's a bug with CPython itself and it's supposed to be fixed in 3.8.

**Comment by haqle314** [comment]
@joaotavora I found a minor mistake in the warning message. The `:eglot` shouldn't be there.

    (eglot--warn
     :eglot "Caution: LSP server sent invalid character position %s. Using 0 instead."
     col)

**Comment by joaotavora** [comment]
You're right, can you submit a fix? The GitHub web UI should be enough
