### ISSUE TITLE
eglot-completion-at-point function: insertText can be an empty string

### ISSUE THREAD

**Issue by vkazanov** [joaotavora/eglot#280]
I had this crash when using the Java server: 

```emacs-lisp
Debugger entered--Lisp error: (args-out-of-range 0 1)
  put-text-property(0 1 eglot--lsp-completion (:label " - completion)))) jsonrpc-lambda-elem359))) 

;;; a huge list of completion candidates here

items)))))) string pred action))) nil)
  completion-at-point()
  complete-symbol(nil)
  funcall-interactively(complete-symbol nil)
  call-interactively(complete-symbol nil nil)
  command-execute(complete-symbol)
```

I investigated it this morning and it seems that it boils down to :insertText being empty (a zero-length string" for one of the completion candidates, i.e. the following line cannot assign a property to a substring (0 1) as length of the string is 0.

https://github.com/joaotavora/eglot/blob/d6508e06b3569f2c2fa6d09326eadad47f41345a/eglot.el#L1900

Now I am not really sure if it's a server's fault, or Eglot's but it makes it really hard to use completion for Java.

Thanks for an amazing mode, btw!

**Comment by vkazanov** [comment]
Just inserting a trimmed label on (string-empty-p insertText) does the job for me.

**Comment by joaotavora** [comment]
Pretty sure I fixed this in a recent commit (I redesigned `eglot-completion-at-point`).  Please test and we can reopen if necessary.

**Comment by vkazanov** [comment]
I think it's fine now, thanks
