### ISSUE TITLE
How to add eclipse.jdt.ls to CLASSPATH?

### ISSUE THREAD

**Issue by ianpan870102** [joaotavora/eglot#282]

**Comment by ianpan870102** [comment]
I'm closing this issue as I've moved to using `lsp-java`, which automatically installs eclipse.jdt.ls and puts it under `.emacs.d`.

I understand the minimal approach of eglot, but sometimes user convenience is also important. I hope that eglot would consider automating some trivial processes.

**Comment by mkcms** [comment]
> I understand the minimal approach of eglot, but sometimes user convenience is also important. I hope that eglot would consider automating some trivial processes.

You should blame the eclipse.jdt.ls developers in this case, they made their installation procedure needlessly complicated and non-standard. Other language servers don't have this problem. Eglot is a generic client, why should we make exceptions for a small number of users?

Besides, it's not that inconvenient. Eglot will ask you for a path where your language server is, and all you have to do is enter a top level directory where you extracted it.
