### ISSUE TITLE
JSONRPC error with evil-mode

### ISSUE THREAD

**Issue by lockie** [joaotavora/eglot#283]
Hi.
I'm using latest ELPA eglot with the latest pyls. I'm also using evil-mode, in which keys `gd` conveniently bound to some function called [`evil-goto-definition`](https://github.com/emacs-evil/evil/blob/3766a521a60e6fb0073220199425de478de759ad/evil-commands.el#L2652), but when this function is called, I get some JSONRPC error from pyls:
```
client-request (id:7) Sun Jul  7 01:05:11 2019:
(:jsonrpc "2.0" :id 7 :method "textDocument/definition" :params nil)

server-reply (id:7) ERROR Sun Jul  7 01:05:11 2019:
(:jsonrpc "2.0" :id 7 :error
          (:code -32602 :message "TypeError: 'NoneType' object is not subscriptable" :data
                 (:traceback
                  ["  File \"/home/lock/.local/lib64/python3.6/site-packages/pyls_jsonrpc/endpoint.py\", line 113, in consume\n    self._handle_request(message['id'], message['method'], message.get('params'))\n" "  File \"/home/lock/.local/lib64/python3.6/site-packages/pyls_jsonrpc/endpoint.py\", line 182, in _handle_request\n    handler_result = handler(params)\n" "  File \"/home/lock/.local/lib64/python3.6/site-packages/pyls_jsonrpc/dispatchers.py\", line 23, in handler\n    return method(**(params or {}))\n" "  File \"/home/lock/.local/lib64/python3.6/site-packages/pyls/python_ls.py\", line 269, in m_text_document__definition\n    return self.definitions(textDocument['uri'], position)\n"])))
```

However, using basic `M-x xref-find-definitions` works just fine, and I can see in event log:
```
client-request (id:9) Sun Jul  7 01:05:58 2019:
(:jsonrpc "2.0" :id 9 :method "textDocument/definition" :params
          (:textDocument
           (:uri "file:///path/redacted/out.py")
           :position
           (:line 9 :character 21)))
```
followed by proper pyls response.
Comparing those two requests from eglot it looks like the first one (leading to the error) is quite weird, because it sends `nil` as `:params`. This as well might be some error in that `evil-goto-definition` function, but my elisp hacker skills are not enough to certainly tell this is the case.
Could you please help me out with this?

**Comment by joaotavora** [comment]
On Sat, Jul 6, 2019, 23:16 Andrew Kravchuk <notifications@github.com> wrote:

> Could you please help me out with this?
>

I will try, but recently there is a growing backlog of bugs in eglot, and
since this seems to be evil-specific, it's not a foremost priority. Can't
you make evil use xref-find-definitions?

>

**Comment by lockie** [comment]
Yeah, I most definitely will remap `gd` to `xref-find-definitions` for the time being. The `nil` argument just seemed odd to me.
Thanks!

**Comment by joaotavora** [comment]
@lockie some recent improvements in Eglot changed the way it uses `xref`.  No idea if it fixes your evil problem, but it'd be nice if you could test.

**Comment by lockie** [comment]
I've tested the recent version of eglot, and `evil-goto-definition` works flawlessly. Thanks a lot!
