### ISSUE TITLE
Implement workspace/didChangeConfiguration

### ISSUE THREAD

**Issue by tromey** [joaotavora/eglot#29]
At least RLS uses `workspace/didChangeConfiguration`; see https://github.com/rust-lang-nursery/rls#configuration.

Maybe configuration could be handled similarly to `.dir-locals.el` somehow - just a file with a sexp in it that is passed to the LSP server when it changes?

**Comment by joaotavora** [comment]
> What do you think, wanna give it a shot? :-)

Actually, I had a look and this looked trivial so I tried it myself. 100% untested (and still missing the `safe-local-variable` bit`. But tell me if it works.

**Comment by joaotavora** [comment]
ping? @tromey do you have any comments on the fix I proposed for this issue?
