### ISSUE TITLE
Can't install eglot. Missing jsonrpc-1.0.7

### ISSUE THREAD

**Issue by andreyorst** [joaotavora/eglot#290]
Running `M-x package-install RET eglot RET` result in this error message:

     package-compute-transaction: Package ‘jsonrpc-1.0.7’ is unavailable

Searching through packages shows that there's `json-rpc` package, but I'm not sure if it is the same package, just renamed.

GNU Emacs 26.2 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.8) of 2019-04-30

**Comment by nemethf** [comment]
Try with `emacs -Q`, you will find the package.

Also: http://elpa.gnu.org/packages/jsonrpc.html
