### ISSUE TITLE
Hover information confused by tabs

### ISSUE THREAD

**Issue by ambihelical** [joaotavora/eglot#296]
Server: ccls

For a file without leading tabs for indentation, the hover information seems correct, however if the file has tabs for indentation, eglot pulls the wrong columns out of the buffer.  

For a line like this:

`\t\t\tLOG_ERR(`

The hover information looks like this

`    LOG_:  correct description of LOG_ERR here`

The offset error appears to be equal to the number of leading tab characters.   
tab-width is 4 in this file if it matters.

**Comment by nemethf** [comment]
Can you post the full content of the events buffer for a minimal example that demonstrates the bug? (I might look into this, but I don't want to install the server.)

**Comment by ambihelical** [comment]
I'm attaching the events buffer for an open source file which has the issue after I introduced leading tabs in the source.  I hovered over a symbol "Clang" on a line with the newly added leading tabs to reproduce the issue (file attached).   The result was "::Clan". I note also that this happens for e.g. rust rls as well, so it seems likely the issue is in eglot or something in my config, but not the server.  

I found out an important clue in the process of generating those files when I turned off whitespace mode in the buffer, eglot displays the right thing.  My whitespace configuration represents tabs with a triangle character, and I'm guessing eglot is confused by that.  Here is my whitespace config:

```
(use-package whitespace
  :config
  (setq whitespace-line-column nil                      ; highlight past fill-column
        whitespace-style '(face trailing tabs tab-mark lines-tail space-before-tab)
        whitespace-display-mappings '((tab-mark 9 [9657 9] [92 9])))
  :init
  (add-hook 'whitespace-mode-hook 'me:set-extra-font-attributes)
  (add-hook 'prog-mode-hook #'whitespace-mode)
  (add-hook 'text-mode-hook #'whitespace-mode)
  :diminish whitespace-mode)
```



[eglot-events.log](https://github.com/joaotavora/eglot/files/3561202/eglot-events.log)
[compiler.cc.gz](https://github.com/joaotavora/eglot/files/3561211/compiler.cc.gz)

**Comment by ambihelical** [comment]
Possibly this is another example of the same issue as seen in #297

**Comment by nemethf** [comment]
I  think  I can reproduce this bug and I found a workaround as well.  eglot--lsp-position-to-point fails to move the point to the correct location when whitespace-mode is enabled and the current line starts with some tabs.  Luckily, setting eglot-move-to-column-function to eglot-move-to-lsp-abiding-column solved the issue for me.

Can you, please, check if this works in your case as well?

(There are no utf-16 encoded characters in my test file.  But with whitespace-mode on, move-to-column doesn't move the point to the correct location and forward-char does.)

**Comment by ambihelical** [comment]
Yes, that seems to fix it for rls at least.  I haven't tried ccls yet.  I will try that soon.

**Comment by nemethf** [comment]
Great. Do you experience noticeable slowdown compared to the default eglot-move-to-column-function?

**Comment by joaotavora** [comment]
Thanks @nemethf for handling this. I can't do anything about these issues lately.

**Comment by joaotavora** [comment]
(oops closed by mistake).  @nemethf, if @ambihelical reports no noticeable slowdown, maybe it's a good idea to change the default of `eglot-move-to-column-function`. I will give you commit rights asap.

**Comment by ambihelical** [comment]
I didn't notice any slowdown but I wasn't paying attention to performance. I will take another look today and see if I notice anything. 

Is it safe to enable this for all servers?  From the doc strings it sounds like some servers aren't 100% compliant, so maybe it should be a server-specific setting?

**Comment by nemethf** [comment]
You're right, eglot-move-to-lsp-abiding-column works with servers expecting utf-16 encoding.    You haven't experienced significant slowdown, so I can change the default to a new eglot-move-to-column, which would use forward-char similarly to eglot-move-to-lsp-abiding-column.  Just give me a day or two.

**Comment by nemethf** [comment]
@ambihelical, I think I finally found a faster and simpler solution.  I've changed the default to this.  Can you, please, test my fix? It is in a new branch:  https://github.com/joaotavora/eglot/tree/scratch/fix-296-move-to-column

Thanks.

**Comment by ambihelical** [comment]
It looks good for ccls.  I won't have a chance to test rls until later.

**Comment by joaotavora** [comment]
This looks good Felicián, you can push to master.

João

**Comment by nemethf** [comment]
I pushed it to the master (28ecd5df456fec), but somehow managed to reference the wrong issue number :(  I'm sorry, next time I'll pay more attention to it.
