### ISSUE TITLE
Symbol highlighting and renaming conflicts with prettify-symbols-mode

### ISSUE THREAD

**Issue by charJe** [joaotavora/eglot#297]
If I have this code:
`bool DynamicArray<E>::inSide(int index) {
	return firstIndex <= index && index > length;
}`
With prettify symbols mode:
![image](https://user-images.githubusercontent.com/45857837/63813037-ec618b80-c8f1-11e9-9271-2c9e9f14ed57.png)

and  when i eglot-rename the index variable I get this:
`bool DynamicArray<E>::inSide(int foo) {
	return firstIndex <= ifoo&& infoo length;
}`

**Comment by nemethf** [comment]
Can you try to set eglot-move-to-column-function to eglot-move-to-lsp-abiding-column and see if that solves the issue?
