### ISSUE TITLE
Run environment aware language server instances

### ISSUE THREAD

**Issue by shahinism** [joaotavora/eglot#3]
Right now it looks like running servers are not aware of environment variables of the emacs instance. This causes some problems, for example Python modules installed in project's virtual environment will not be available for auto-completion or documentation. Virtualenv switchers like `pyvenv` [will set `VIRTUAL_ENV` variable](https://github.com/jorgenschaefer/pyvenv/blob/85f762a1bce2a2336b84a8c84223a98abc261cfc/pyvenv.el#L230) and `pyls` [reflects to its value](https://github.com/palantir/python-language-server/issues/126). But when `eglot` loads `pyls` directly, modules installed in `virtualenv` are not available.

**Comment by joaotavora** [comment]
> Right now it looks like running servers are not aware of environment variables of the emacs instance. 

I don't think this particular sentence is true. All processes should inherit Emacs' environment.

I'm not very python-savvy I'm afraid. Are you saying that loading `pyls` directly is not a good way? In my machine pyls is `~/.pyenv/shims/pyls` a shell script that eventually does run `pyenv`, which presumavly will read `VIRTUAL_ENV`. In my Emacs I just happen to have, as in my shell, `~/.pyenv/shims/` in my `PATH` and `exec-path`.

Presumably if `VIRTUAL_ENV` is set in Emacs, the launched process, and hence `pyenv` would see it.

Perhaps you have a different setup. What does `M-x eval-expression RET (executable-find "pyls") RET` return for you? What about `M-x getenv RET VIRTUAL_ENV RET`?

Also don't forget that you can tweak `eglot-server-programs` to your hearts desire:
```lisp
(add-to-list 'eglot-server-programs '(python-mode . ("better" "pyls" "startup" "options")))
```

If your solution is

**Comment by joaotavora** [comment]
@shahinism I tried `pyvenv.el` and it seems to do the right thing and set `process-environment` which, for all I know, `pyls` inherits. What situation exactly is failing, can you explain with an example that I can try out?

**Comment by shahinism** [comment]
Hi, 
Thank you for time on this. This is my workflow:

- create a virtualenv and install a package like `requests`
- open a python file
- switch to virtualenv using `pyvenv-mode`
- call `eglot`

Now I suppose that I should be able to complete `requests` methods, but it doesn't work. BTW, if it is fine on your side, it is probably related to my environment. I'll dig it more and update this thread if found anything useful.

**Comment by joaotavora** [comment]
OK, thanks for the pointers. I learned a bit about `virtualenv` and how to use it. I'm a complete newbie for that, I had never used it.

Anyway, I *still* can't reproduce your problem, but at least now I have a clean recipe that you can try. First in whatever shell you use, setup a dummy project.
```shell
/S/Python $ mkdir dummy
~/S/Python $ cd dummy
~/S/P/dummy $ virtualenv .
[... some output elided ...]
Installing setuptools, pip, wheel...done.
~/S/P/dummy $ . ./bin/activate
(dummy) ~/S/P/dummy $ pip install requests
[... some output elided ...]
Successfully installed certifi-2018.4.16 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22
## this opens a new dummy.py file in my Emacs, but you can just C-x C-f it
(dummy) ~/S/P/dummy $ emacsclient dummy.py 
```

Now in Emacs you should have an empty `dummy.py`. Type `M-x pyvenv-activate RET RET`. Now enter this content
```python
import requests
requests.
```
Now type `M-x eglot`. This searches PATH for `pyls`, which is my machine is `"/home/capitaomorte/.pyenv/shims/pyls"`

You should now be connected. Now type `C-M-i` to start completion. I get a (big) list of completions.

**Comment by shahinism** [comment]
I found the problem. I've recently switched from normal `virtualenvwrapper` environments to `pipenv` for my Python projects and thought that it should work the same with `pyvenv-mode`. I was wrong :sweat_smile: . Setting `$WORKON_HOME` to point to `pipenv`'s virtualenv directory resolved my problem. 

Thank you for your time and effort :heart:

**Comment by Horrih** [comment]
In case somebody stumbles upon this issue years later, in the end the least intrusive way I found to solve this issue was to have a simple shell script, wrapper for the language server, that activates the relevant venv before launching the language server of the same name (assuming your .venv is located in your project directory, which is the case with uv package manager and I believe poetry as well).

The basic idea is : locate a .venv directory in the current directory or a parent one. If not found check inside immediate child directories.
source ./venv/bin/activate then call pylsp

I am calling it with the uv package manager to avoid having to install it myself in every .venv, but you can remove the uv part and call pylsp directly if you have installed it.
Place the following content into ~/.local/bin/pylsp then chmod +x

```bash
#!/bin/bash
# If no virtual env enabled, locate a parent virtual env
if [[ -z "$VIRTUAL_ENV" ]]; then
    current_dir="$PWD"
    while [ "$current_dir" != "/" ]; do
        if [ -d "$current_dir/.venv" ]; then
            FOUND_VENV="$current_dir/.venv"
            break
        fi
        current_dir=$(dirname "$current_dir")
    done
    # If not found, find one in the directories below
    # e.g : eglot calls this script from the project root, so if the
    # pyproject.toml is in a subdirectory it won't work without this
    if [[ -z "$FOUND_VENV" ]]; then
        FOUND_VENV=$(find . -maxdepth 2 -type d -name .venv -print -quit)
    fi
    if [[ ! -z "$FOUND_VENV" ]]; then
        source "$FOUND_VENV/bin/activate"
    fi
fi
# If no has been found use project-less pylsp
if [[ -z "$VIRTUAL_ENV" ]]; then
    uvx --from=python-lsp-server pylsp $@
else
    uv run --with=python-lsp-server pylsp $@
fi
```
