### ISSUE TITLE
Support for goto-implementation

### ISSUE THREAD

**Issue by GabCamarda** [joaotavora/eglot#302]
Currently eglot does not provide support for finding the implementation of a method defined in an interface (only noticed this with Java, haven't tried other languages). With lsp-mode this is bound to `lsp-goto-implementation`. I was wondering if there are plans to add support for this.
Thanks

**Comment by nemethf** [comment]
Currently, eglot supports all of the 'goto' functionalities with the help of the xref package. The LSP specification has these: textDocument/{declaration,definition,references,implementation,typeDefinition}, but xref only has xref-find-definitions, xref-find-references, and maybe xref-find-apropos.  

Situations like this, I think, João used to think along the lines of "once xref has been extended with different goto types, then we can start adding support for extra goto types to eglot." 

But maybe all we need to start the ball rolling is to come up with a good UI (key bindings, menu items, ...).

**Comment by joaotavora** [comment]
I'm ok with writing a command like `eglot-find-implementation` which behaves just like `xref-find-definition` but for LSP implementations. Same for declarations, etc...

But indeed there is no current keybinding in the xref library to support them.  Eglot's policy is to not enforce keybindings on the user. Of course, if xref eventually develops an `xref-find-implementation` we can probably take advantage of that.  And I also don't oppose that someone makes some `eglot-popular-bindings` package.

By the way, on a tangent, I think it's a mistake on LSP's part to import C++/Java's ecosystem of possible symbol loci.  In Common Lisp, there are many different types of construct associated with a symbol and they are all "definitions".  A good IDE like SLIME will use something akin to `xref-find-definitions` (indeed xref is modelled after SLIME) and categorize them properly in the result buffer if there is more than one.  So the command should have been `textDocument/definition` with some kind of `subtype` parameter, or at least this is where `xref` should evolve to, i.e. xref should keep the single command `xref-find-definitions` and maybe augment it with some "definition-type" parameter.

**Comment by GabCamarda** [comment]
Thanks.
My Lisp is not that good to try and hack it myself. I'm not too bothered by choosing from a list of references as opposed to go straight to the implementation, however it's definitely more convenient, especially if using it for work. I guess we can close this until a better implementation of `xref` comes along. I've checked other packages like `dumb-jump` and while faster, the results are pretty much the same.

I have other questions, should I open new issues or is there a better communication channel (e.g. IRC) I can use?

p.s.: thanks for the great work!

**Comment by nemethf** [comment]
Does `xref-find-references` (bound to `M-?`) help in this case?

(I have some ideas how M-. cloud include results from textDocument/implementation, but cannot find time in the foreseeable future to actually try to implement them.)

I don't think there's a dedicated eglot IRC channel.  I, for one, wouldn't use it.  But good questions highlight a documentation bugs, so post them here as new issues.

**Comment by MaskRay** [comment]
It will be useful to have a common interface that support methods that return `result: Location | Location[] | LocationLink[] | null`. In lsp-mode and lsp-ui-peek-mode, the methods are called `lsp-find-locations` and `lsp-ui-peek-find-custom`. Ideally the common interface should be easy to support language server specific method names.

**Comment by nemethf** [comment]
@MaskRay, it's good to see you here, I wanted to ask you about ccls :) 
Would it be possible to use the cross reference extensions without explicit editor support?  For example, is it feasible to provide extra cross reference functionality through codeActions?
(Also how $ccls/var is different from textDocument/references?)

Thanks.

**Comment by nemethf** [comment]
Btw, #77 might be relevant here.

**Comment by MaskRay** [comment]
`$ccls/var` can be seen as a specialized `textDocument/references`. It finds all variables that are local variables/parameters/struct members as the user requests.

`Type v;  // Usually point is at Type, but methods can return information if point is at v`

Yes, #77 is relevant.

**Comment by nemethf** [comment]
I've made an attempt to implement the remaining LSP cross reference types in a branch named scratch/issue-302-goto-implementation.  @GabCamarda, can you test it?

**Comment by GabCamarda** [comment]
Thanks @nemethf , just tested it, works great! 

When I tested it with a mono repo containing about 50 services, it hung though. `xref` has the same issue, so it's not isolated to eglot.

**Comment by nemethf** [comment]
@MaskRay, you wrote:
> `textDocument/codeAction` cannot be used for customized cross reference requests, because its `result: (Command | CodeAction)[] | null` is not a list of `Location`.

That's true, but CodeAction can contain a Command and if the client ask the server to execute that command with workspace/executeCommand, then the server returns `any | null`.  And that `any` can be a Location[].

So if the client asks for CodeActions, then the server can return code actions with a special CodeActionKind (e.g., "references"), hence the client would know how to interpret the return value of the corresponding executeCommand.

Sure, the new CodeActionKind  is an extension to the language server protocol, but it's a minimal one.  And with it, clients can support the extra cross-reference methods of ccls without hardcoding ccls methods.

What do you think?

**Comment by MaskRay** [comment]
> So if the client asks for CodeActions, then the server can return code actions with a special CodeActionKind (e.g., "references"), hence the client would know how to interpret the return value of the corresponding executeCommand.

The server can do this, but it'll have to encode some states in the CodeAction result. The client passes the state back to the server via `workspace/executeCommand`. The server then decodes the state. (a) If the state encodes a list of `Location[]`, the CodeAction result will be huge. (b) If the state encodes some token, the server will have to maintain some session data. Then you need to think about garbage collection because the client may not necessarily execute the command. Neither is a good solution.

**Comment by nemethf** [comment]
Maybe I'm wrong, but this is how I image it:  (1) The client sends a code action request only for references.  (2) The server returns a list of code actions, one for each extra reference method, where the tokens are identical.  The token is the arguments part of the command definition and it is a TextDocumentPositionParams constructed from the textDocument and range found in the code action request of step 1.  (3) Then the user selects a reference method.  After that (4) the client asks the server to execute the code action with the given parameters.  (5) The server executes the reference method only in this step and returns a list of locations.   I think the token is relatively small and the server doesn't have to store anything.  

The downside of this approach is that the user might select a method in step 3 that doesn't make sense at a given location.

 We can also complicate the token generation in step 2.  In addition to the text document position, the command arguments could contain additional information, for example, a direction in case of $ccls/navigate.
