### ISSUE TITLE
Does not appear to work

### ISSUE THREAD

**Issue by gdonald** [joaotavora/eglot#306]
I did `gem install solargraph` and then I opened a Ruby file.  I did M-x eglot and I see `[eglot:myapp]` in my modeline.  I see a message saying `[eglot] Done, connected to 49836!`.  But I do not get any sort of code completions like the animated GIFs show.  Is this actually expected to work with Ruby?

**Comment by nemethf** [comment]
I don't write in ruby, and never used the solargraph language server.  However, looking at its [website](https://solargraph.org/), the following should work.  Open an empty file in ruby mode, start eglot, insert:
```ruby
chars = 'a, b, c'
chars.spl
```
and then pressing C-M-i should complete to 'split' or pop up a buffer with possible completions containing 'split' among them.   

If that doesn't work, we can debug the problem by looking at the content of the events buffer (available with M-x eglot-events-buffer)

It might not be clear from skimming through the documentation, but eglot doesn't do code completion by its own.  It provides low level helper functions that other packages/commands (e.g, company or the built-in completion-at-point) can rely on.

**Comment by gdonald** [comment]
That sound worse than just typing 'split'.  Moving on, thanks all the same.

**Comment by joaotavora** [comment]
> That sound worse than just typing 'split'. Moving on, thanks all the same.

Felicián offered help in the form of a debugging recipe.  You're of course free to not try it (even though typing `M-x eglot-events-buffer` and pasting its contents here isn't a lot a of work to ask in return for the time that Felicián and I have put into your report).

Anyway, in case it wasn't clear from his explanation, there is every indication that if the solagraph gem isn't working at 100%, it seems to be a problem on your side, not Eglot's.

**Comment by gdonald** [comment]
Of course it's a problem on my side: I'm probably just not running enough "language" servers.. or maybe my clipboard was fubar as I copied and pasted your instructions, verbatim.  Or maybe my expectations were just too high.  Feel free to blame anyone except you, I don't mind at all.

**Comment by joaotavora** [comment]
> Feel free to blame anyone except you, I don't mind at all.

Greg, don't be an arse. 

I said "it **seems** to be a problem on your side".  Since one of our developers has failed to replicate the problem and you refuse to type a few words into your emacs and use your foobared clipboard to communicate those results here, that suspicion remains.

Have you tried to replicate the problem from a clean `Emacs -Q` run? I.e. one where you load nothing into emacs except Emacs itself and eglot?

**Comment by PuercoPop** [comment]
Fwiw completion with solargraph works as advertised for me. Because the GIF shows completion using company-mode maybe that is the expectation that is not being met?

**Comment by joaotavora** [comment]
> Because the GIF shows completion using company-mode maybe that is the expectation that is not being met?

¯\_(ツ)_/¯
