### ISSUE TITLE
imenu doesn't appear to work properly for cquery

### ISSUE THREAD

**Issue by wyuenho** [joaotavora/eglot#31]
There doesn't seem to be any difference in the imenu index before and after I've enabled eglot in a C buffer. I've pretty sure the cquery server had been successfully started.

**Comment by joaotavora** [comment]
Imenu is one of the less tested features, so it's possible it's broken.  I'll have a look.

**Comment by joaotavora** [comment]
Can you try now?

**Comment by wyuenho** [comment]
Works perfect now, thank you!
