### ISSUE TITLE
Add support for Ada

### ISSUE THREAD

**Issue by tromey** [joaotavora/eglot#316]
Ada has a language server implementation now: https://github.com/AdaCore/ada_language_server

**Comment by joaotavora** [comment]
Hi Tom, I can certainly mention the Ada server in the README.md or add a short entry to `eglot-server-programs`, but first I'd like you to test Eglot with it, just `M-x eglot` in an `ada-mode` buffer and point the prompt to whereever the server executable is located. That's the whole point of LSP, that there is no need for special support from the client (though sometimes it is indeed required).

**Comment by tromey** [comment]
Thanks.  I have a patch but I'm struggling a bit to test it.  I will learn a bit more & get back to you.
