### ISSUE TITLE
xref-find-definitions broken with rls

### ISSUE THREAD

**Issue by ambihelical** [joaotavora/eglot#318]
Using rls, xref-find-definition no longer functions at all.  
I haven't tried any other server.

I get this error for every usage I've tried:
user-error: No definitions found for: LSP identifier at point.

I found this stopped working with commit 4c5d0d491532cd907beae12df5c2f01cd0290a7b.
Workaround is to checkout the previous commit, which still seems ok. 

Events for RLS seem to be the same, as follows...

Events buffer (before commit)

```
client-request (id:40) Sat Oct 12 22:20:53 2019:
(:jsonrpc "2.0" :id 40 :method "textDocument/definition" :params
          (:textDocument
           (:uri "file:///home/work/dev/[removed]/luminance-rs/luminance/src/tess.rs")
           :position
           (:line 244 :character 23)))

server-reply (id:40) Sat Oct 12 22:20:53 2019:
(:jsonrpc "2.0" :id 40 :result
          [(:uri "file:///home/work/dev/[removed]/luminance-rs/luminance/src/tess.rs" :range
                 (:start
                  (:line 301 :character 5)
                  :end
                  (:line 301 :character 26)))])
```

Events Buffer after commit:
```
client-request (id:3) Sat Oct 12 22:24:34 2019:
(:jsonrpc "2.0" :id 3 :method "textDocument/definition" :params
          (:textDocument
           (:uri "file:///home/work/dev/[removed]/luminance-rs/luminance/src/tess.rs")
           :position
           (:line 244 :character 23)))

server-reply (id:3) Sat Oct 12 22:24:34 2019:
(:jsonrpc "2.0" :id 3 :result
          [(:uri "file:///home/work/dev/[removed]/luminance-rs/luminance/src/tess.rs" :range
                 (:start
                  (:line 301 :character 5)
                  :end
                  (:line 301 :character 26)))])

```

Let me know if any other information is required.

**Comment by joaotavora** [comment]
> Let me know if any other information is required.

No this is OK.  I'll try to see what happened.

**Comment by joaotavora** [comment]
> I'll try to see what happened.

What happened it that I broke xref for every LSP with a childish mistake 🤦‍♂ . Have a test in place now, shouldn't happen again so easily...
