### ISSUE TITLE
opt-out to company-backends overwrite

### ISSUE THREAD

**Issue by shackra** [joaotavora/eglot#324]
I [noticed that eglot overwrite the value of `company-backends`](https://github.com/joaotavora/eglot/blob/master/eglot.el#L1202), I don't really like this because in my configuration I already set some sane defaults for `company-backends` which includes `company-capf` and other stuff that modifies all backends to include YaSnippet snippets, so I would like to have the option to tell eglot to not overwrite the value of `company-backends` when turned on.

**Comment by joaotavora** [comment]
OK. You're not the first to complain.  See https://github.com/joaotavora/eglot/commit/a11a41bd67970c62474385da98b9ab7209802126#commitcomment-35576270

I've introduced a new variable `eglot-stay-out-of`.  Use it like this:
```
(setq eglot-stay-out-of '(company))
```
