### ISSUE TITLE
Too much syntax highlight in eldoc with gopls

### ISSUE THREAD

**Issue by xuchunyang** [joaotavora/eglot#328]
```
Glob returns the names of all files matching pattern or nil if there is no matching file.
func Glob(pattern string) (matches []string, err error)
```

![Emacs 2019-10-27 at 20 49 16](https://user-images.githubusercontent.com/4550353/67634807-65359180-f8fb-11e9-97f9-e029f1cabd3b.png)

Both the docstring and the function sig are syntax highlighted as Go code, and the docstring doesn't look very well.

**Comment by joaotavora** [comment]
Hmmm, right.  But isn't this a server-side problem?  Shouldn't it be serving markdown instead, of using the comment syntax on the first line of the documentation?

**Comment by xuchunyang** [comment]
gopls provides a [hoverKind](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#hoverkind-string) setting, and if user sets it to `NoDocumentation`, the server won't send the docstring.

**Comment by xuchunyang** [comment]
> Shouldn't it be serving markdown instead,

I notice the server sends `:kind "plaintext"`

```el
(:jsonrpc "2.0" :result
          (:contents
           (:kind "plaintext" :value "Glob returns the names of all files matching pattern or nil if there is no matching file.\nfunc filepath.Glob(pattern string) (matches []string, err error)")
           :range
           (:start
            (:line 31 :character 10)
            :end
            (:line 31 :character 14)))
          :id 2687)
```

**Comment by joaotavora** [comment]
> I notice the server sends :kind "plaintext"

Yes, and it's perfectly within the spec.

The fontification trick is an Eglot-specific trick, I admit. It relies on the fact that the "plain text" that the server sends is very often syntactically within the language that the server manages.  Therefore it almost always makes sense to fontify according to it.

I remember that it worked reasonably OK in Python or something, at least when I implemented it.

But the first line of the `:value` in the Gopls example is not Go code.  It could be, if it started with `// ` .  Maybe you can convince the Gopls people to change that.  It'd also probably be nicer for copy-paste reasons.

**Comment by xuchunyang** [comment]
Gopls sends plain text by default, and it seems it should be able send markdown too according to
https://github.com/golang/tools/blob/2b544e3f2db1e740d696ff91381987f6357e6bda/internal/lsp/hover.go#L49 , but there's not documentation about this.

---

Gopls does send Markdown to lsp-mode

```json
{
  "contents": {
    "kind": "markdown",
    "value": "Errorf formats according to a format specifier and returns the string as a value that satisfies error\\.\n```go\nfunc fmt.Errorf(format string, a ...interface{}) error\n```"
  },
  "range": {
    "start": {
      "line": 5,
      "character": 10
    },
    "end": {
      "line": 5,
      "character": 16
    }
  }
}

```

the code at https://github.com/emacs-lsp/lsp-mode/blob/1b4e25418c7d321808f33e132a4785c1ee075a7a/lsp-mode.el#L2558 seems related

```el
lsp--client-capabilities
   (hover . ((contentFormat . ["markdown" "plaintext"])))
```

Maybe the client need to tell the server the markdown is supported?

**Comment by joaotavora** [comment]
> Maybe the client need to tell the server the markdown is supported?

Maybe.  I'll have a look in the spec
