### ISSUE TITLE
Start LSP server from project root

### ISSUE THREAD

**Issue by yyadavalli** [joaotavora/eglot#33]
Currently, the language server is started in the working directory of the current file. The `initialize`request sends the correct `rootPath` and `rootUri`. 

Ideally, this should work, but some language servers (eg. metals scala lsp) have issues if not started in the project root. It would be better if we could start the server the project folder as we already know the folder in `eglot--connect` when initiating a connection.

**Comment by joaotavora** [comment]
You mean these server executables expect the current directory (in the [getcwd()](http://man7.org/linux/man-pages/man2/getcwd.2.html) sense) to be the project directory?  If so, I think it can be done yes.  Otherwise, I'm not following..

**Comment by yyadavalli** [comment]
@joaotavora Yes

**Comment by joaotavora** [comment]
I pushed this to a side branch, checkout to that commit and try again.  If it works, I'll push to master.

**Comment by yyadavalli** [comment]
I'm getting an error `No applicable method: project-roots, <fullpath of project base>`

**Comment by wyuenho** [comment]
This seems to be caused by a recent change in [projectile](https://github.com/bbatsov/projectile/commit/09255ddc3369eea918c9b4f318b7db98d4816581).

Just make a projectile-mode-hook to remove those project-find-functions

**Comment by yyadavalli** [comment]
@wyuenho Thanks, I'll give that a try. I was able to get it running just using the `project` variable directly.

**Comment by joaotavora** [comment]
> I'm getting an error No applicable method: project-roots, <fullpath of project base>.

Where exactly do you get this error, can you provide a backtrace. Please `M-x toggle-debug-on-error`.

> This seems to be caused by a recent change in projectile.

The author seems to have just reverted that change. But what are you (@wyuenho  and @yyadavalli ) trying to do exactly?

> I'm having some issues with delayed responses but I have to profile more to get to the bottom of it.

If this is not related to servers starting in wrong directories, please open a new issue for this. OK?

**Comment by yyadavalli** [comment]
> Where exactly do you get this error, can you provide a backtrace. Please M-x toggle-debug-on-error.

The first call to `project-roots` , In the new branch the it is at `(default-directory (car (project-roots project)))` in `eglot--connect`

> If this is not related to servers starting in wrong directories, please open a new issue for this, OK?

Yeah, definitely, did not mean to extend this issue for that. Also I need to verify it with other language servers to pin point the issue.

Do you have a gitter or irc channel for the project? I would like to add some customization settings, it may be easier to discuss those in chat instead of issues.

**Comment by joaotavora** [comment]
I merged the branch to the mainline since the error you are having is probably related to projectile's incorrect hooking into project.el.

> Do you have a gitter or irc channel for the project? I would like to add some customization settings, it may be easier to discuss those in chat instead of issues.

No, sorry, make issues instead.  If you make a gitter, I won't oppose, but I also won't be there more than probably.

You can ask in Reddit and in IRC, who knows, someone might help you there. If you make issues here, I try to respond prompty, when I can.

**Comment by yyadavalli** [comment]
Ok, Thanks...
