### ISSUE TITLE
php-langua-server not working

### ISSUE THREAD

**Issue by gjm** [joaotavora/eglot#330]
I can't get Eglot to connect to `php-language-server`. 

I have the package installed and if I run the startup command (`php vendor/felixfbecker/language-server/bin/php-language-server.php`) manually it starts normally.

If I try to start Eglot I get 

`Could not open input file: vendor/felixfbecker/language-server/bin/php-language-server.php`

It almost seems it isn't being run on the correct path and, as such, the PHP interpreter can't find the source file.

**Comment by gjm** [comment]
OK, so I found out that if I run with `C-u M-x eglot` and replace `vendor/felixfbecker/language-server/bin/php-language-server.php`with the **full path** it starts up the server.

**Comment by joaotavora** [comment]
> OK, so I found out that if I run with C-u M-x eglot and replace vendor/felixfbecker/language-server/bin/php-language-server.phpwith the full path it starts up the server.

Cool. Maybe if you use `./vendor/felixfbecker/language-server/bin/php-language-server.php` it also works.. 

Anyway, I don't think this is a problem with Eglot, so I am going to mark this a work-around (so people can find it) and close the issue.  Let me know if you think I should re-open it.

**Comment by gjm** [comment]
@joaotavora the workaround... doesn't work. Only if I put the full path will the server start...

**Comment by joaotavora** [comment]
> @joaotavora the workaround... doesn't work. Only if I put the full path will the server start...

Hmmm... interesting.  Where exactly do you have the `vendor` directory? Is it a subdirectory of your top-level project dir?

**Comment by gjm** [comment]
Yes.

**Comment by joaotavora** [comment]
Hello @gjm, can you try with this latest commit 2afb426? If it works, I'll push that to master.
