### ISSUE TITLE
Minor: compile warning "Unknown LSP interface ConfigurationItem"

### ISSUE THREAD

**Issue by garyo** [joaotavora/eglot#331]
Saw this while updating to latest eglot:
```
Compiling file c:/Users/garyo/.emacs.d/elpa/eglot-20191028.1529/eglot.el at Tue Oct 29 11:13:41 2019
Entering directory ‘c:/Users/garyo/.emacs.d/elpa/eglot-20191028.1529/’
eglot.el:1686:1:Warning: Unknown LSP interface ConfigurationItem
```
May not be significant so feel free to close if this is expected.

**Comment by joaotavora** [comment]
It's not _unsignificant_, but probably not harmful. I must have forgotten to declare the ConfigurationItem interface.  Thanks for report.

**Comment by joaotavora** [comment]
Closing this.  Not happening anymore.
