### ISSUE TITLE
disable highlight at point

### ISSUE THREAD

**Issue by MoHKale** [joaotavora/eglot#334]
I find eglot highlighting the variable at point distracting. Is there some option to disable this, I couldn't find any mention of it when searching through eglot variables with ivy and the README doesn't include it in the customisations section?

**Comment by MoHKale** [comment]
Turns out extended customisations are under `eglot-ignored-server-capabilites`. In this case: 

```elisp
(setq eglot-ignored-server-capabilites '(:documentHighlightProvider))
```

did the trick for me.

**Comment by theycallmejpo** [comment]
> (setq eglot-ignored-server-capabilites '(:documentHighlightProvider))


Typo
(setq eglot-ignored-server-capabilities '(:documentHighlightProvider))

**Comment by joaotavora** [comment]
Both versions work. Use the correct one.
