### ISSUE TITLE
Commit #6dd5d breaks integration with LSP that does not expose documentSymbolProvider

### ISSUE THREAD

**Issue by CestDiego** [joaotavora/eglot#343]
This displays errors in imenu when using an LSP that doesn't expose documentSymbolProvider. Given that it's not LSP protocol that such a feature is required, shouldn't this method just log a message and gracefully fail?

https://github.com/joaotavora/eglot/commit/6dd5de9b5cb7d51acdc9530b651b9cc1266b7942

**Comment by joaotavora** [comment]
You're right.  Actually what could be happening is Eglot requesting previous imenu functions to try and do the job when Eglot's can't.  I've tried this approach in the above commit. Please test it.

**Comment by CestDiego** [comment]
I meant to get back to you earlier. Yes, this indeed works. Thanks for the quick workaround :)
