### ISSUE TITLE
How to set up per-project servers?

### ISSUE THREAD

**Issue by brainplot** [joaotavora/eglot#347]
Hi, I'm new to Emacs and Elisp. I'm looking for a way to set up per-project servers, invoked with custom arguments. In my current project, there's a `build` folder in the project root with a `compile_commands.json` in it. I'd like to invoke `clangd` with these arguments:
```sh
clangd --compile-commands-dir=build --background-index --header-insertion=iwyu
	-j=6 --pch-storage=memory
```
I know I could use the code below in my init file, as per the `README.md`:
```elisp
(add-to-list 'eglot-server-programs
             `(c++-mode . ("clangd"
                           "--compile-commands-dir=<project-root>/build"
                           "--background-index"
                           "--header-insertion=iwyu"
                           "-j=6"
                           "--pch-storage=memory"
                           :autoport)))
```
but the first argument to `clangd` (i.e. `--compile-commands-dir=<project-root>/build`) is going to of course be different based on the project I'm working on, and I don't want to change it in my global `init.el` every time I switch to another project.
Ideally I would like to set the command flags in `.dir-locals.el` but from the `README.md` it's not very clear how I should go about doing that because, from the example given, `eglot-workspace-configuration` only tunes the behavior of a server that's already in place for that mode.

I searched Google and here in the GitHub issues extensively in order to find a way to achieve this but I couldn't find an answer. If what I'd like to do is the wrong way or if there's another way I'm supposed to do this, do let me know :slightly_smiling_face:

**Comment by joaotavora** [comment]
> but the first argument to clangd (i.e. --compile-commands-dir=<project-root>/build) is going to of course be different.

Yes, you're right.  One way to fix it would be to use `--compile-commands-dir=./build`

BUT there might be a bug, first reported in #330, that I haven't analysed yet.  So I don't know it that will work.

The alternative is to write a contact function, but I will first have a look at the possible bug.

**Comment by joaotavora** [comment]
@brainplot can you try with the commit 2afb426 && `--compile-commands-dir=./build`?

**Comment by brainplot** [comment]
> One way to fix it would be to use `--compile-commands-dir=./build`

Is the server currently started from the project root or from the current directory of the file being edited? In the latter case, that won't work because all source files are under the `src/` folder and its subfolders.

Also, assuming that works, while `./build` is certainly better than hard-coding the full path in my global init file, it still still isn't very robust. Sometimes I generate a `build-debug` and `build-release` in the project root and that would break the set-up :slightly_smiling_face: 

So like I said, being able to put that in `.dir-locals.el` I think would be best; but mine is just a suggestion.

**Comment by joaotavora** [comment]
> Also, assuming that works, while ./build is certainly better than hard-coding the full path in my global init file, it still still isn't very robust. Sometimes I generate a build-debug and build-release folder in the project root and that would break the set-up 🙂

Yes, you are right here too.  In that case, the best solution for now is to read the docstring of `eglot-server-programs` ,the last point regarding `CONTACT`.

Using `.dir-locals` is also a possibility, but it doesn't work very well yet.

**Comment by joaotavora** [comment]
> P.S. I just checked out the commit with the fix. Thank you! I can live without being able to switch output folder per-project :)

But does it work with `./build`?

**Comment by brainplot** [comment]
Yep! It works just fine. I have this in one of my init files:
```lisp
(use-package eglot
  :config
  (add-to-list 'eglot-server-programs
             '(c++-mode . ("clangd"
                           "--background-index"
                           "--compile-commands-dir=./build"
                           "--header-insertion=iwyu"
                           "--pch-storage=memory"
                           "-j=6")))) ; :autoport was removed because it gave an error
```

However, for my specific use case, I noticed this while starting `clangd` from the command line
```
clangd accepts flags on the commandline, and in the CLANGD_FLAGS environment variable
```
so I guess I could set the flags that are global to every project in my init file and define `CLANGD_FLAGS` per-project as needed.

Is there currently a way of setting environment variables via `.dir-locals.el` and `eglot-workspace-configuration` so that eglot can then pass them to the server?
If not, I can always resort to my shell so not the end of the world :slightly_smiling_face:
