### ISSUE TITLE
eglot-imenu used globally

### ISSUE THREAD

**Issue by muffinmad** [joaotavora/eglot#351]
Run `eglot` e.g.
1. `C-x C-f ~/test.py`
2. `M-x eglot`
In other buffer not managed by `eglot` e.g.
3. `C-x C-f ~/test.el`
4. `M-x imenu`
leads to error `jsonrpc-error: jsonrpc-error: "No current JSON-RPC connection", (jsonrpc-error-code . 32603), (jsonrpc-error-message . "No current JSON-RPC connection")`
5. `C-h v imenu-create-index-function`
```
Its value is
#f(advice-wrapper :before-until imenu-default-create-index-function eglot-imenu)
```

IMO after https://github.com/joaotavora/eglot/commit/8c9078e5005ff22a2958af8e768c6c06b8c19bca

**Comment by joaotavora** [comment]
Thanks for the report. Please test the new version.

**Comment by muffinmad** [comment]
Works fine now, thanks!
