### ISSUE TITLE
Add option to choose between rls and rust-analyzer

### ISSUE THREAD

**Issue by brotzeit** [joaotavora/eglot#352]
In rustic I have a snippet to change the lsp server for eglot, but it would be nice if eglot could handle this so rust-mode users also can switch to rust-analyzer easily.

**Comment by joaotavora** [comment]
Just use `C-u M-x eglot` and choose the executable that you believe is the best.

Or have those users tweak `eglot-server-programs`.

Are you aware of those two options? If so, why do you think I should add more infrastructure to support switching between servers?

**Comment by brotzeit** [comment]
> Are you aware of those two options? If so, why do you think I should add more infrastructure to support switching between servers?

I know. But I thought you want to provide at least basic options for customization. If you want to keep eglot slim, no problem. It certainly also has advantages. I will add some instructions to the rust-mode readme.

**Comment by joaotavora** [comment]
But what is the difference between writing:
```
(setq eglot-rust-mode-uses-rustic t)
```
and writing this
```
(add-to-list eglot-server-programs '(rust-mode . "rustic"))
```
Presuming it is this that you are proposing.

> But I thought you want to provide at least basic options for customization. If you want to keep eglot slim, no problem.

I just don't want to add stuff that is already there in some other form.  But maybe I'm misunderstanding your proposal.

**Comment by joaotavora** [comment]
By the way, do you have any indication that "rustic" is somehow superior in features or some other aspect to "rls".  If so, I could change the default that Eglot provides.  I can't decide very well because I don't write much Rust.

**Comment by brotzeit** [comment]
rustic is just a fork of rust-mode that provides out of the box lsp configuration. We decided that rust-mode should only provide basic functionality, but there are also rust-mode users who want to have lsp support.

rust-analyzer is the alternative to rls, however it's not mature enough to make it the default.

It doesn't really make a difference if you have to use

```
(add-to-list 'eglot-server-programs '(rust-mode . "rust-analyzer"))
```
or 
```
(setq eglot-rust-server 'rust-analyzer)
```
but that is what people are used to apply customizations. However adding a ton of customization options would bloat the eglot code base and I can understand if you don't want it.

**Comment by joaotavora** [comment]
> dropping this note here so you can do what you want with it - I've no idea how to use the discussions feature to point 

You just did. Thanks for letting us know. Do you think rls should no longer feature in eglot-server-programs alongside rust-analyzer?

> this out, and I don't have the time or inclination to read all the attendant rules and regulations.)

I see you prefer to save your  time and inclination for the unrelated and the obscure.
