### ISSUE TITLE
rls restart loop takes down emacs

### ISSUE THREAD

**Issue by antifuchs** [joaotavora/eglot#36]
I just tried eglot, and it seems quite reasonable! Unfortunately as soon as RLS crashed the first time (I used `M-.` on an identifier I probably shouldn't have), eglot restarted it, causing RLS to crash again, and so on - now my emacs window is empty and the minibuffer displays `error in process sentinel: Lisp nesting exceeds 'max-lisp-eval-depth'`, which seems to indicate that there's infinite recursion going on.

I guess the retry logic may need an escape hatch & abort if the server crashes when running the command, say, twice?

**Comment by joaotavora** [comment]
There is indeed such an escape hatch. If it isn't working then it's a bug.

Can you try again with debug-on-error set to t, so we can get a backtrace?

As a separate diagnostic, can you try killing the server from the command line? If you do it too fast, eglot should refuse connecting.

**Comment by antifuchs** [comment]
OK, so I have some details:

* I seem to be able to reproduce the reconnect loop whenever I press `M-.` on an identifier that leads to a file I haven't got open. For example, I opened [chars/src/display.rs](https://github.com/antifuchs/chars/blob/master/src/display.rs#L43) from a checkout and pressed `M-.` on `.to_lowercase`. Eglot said that it was reconnecting.

* debug-on-error doesn't help - no elisp error is raised (except for the `max-lisp-eval-depth` one).

* When I kill the process on the command line (with `pkill -l /rls`), the restart loop stops, and eglot jumps to the right definition.

* After a restart, `M-.` leading to that file continues to work, but opening a new file still throws it into the loop.

So a thing just occurred to me: I have `(add-hook 'rust-mode-hook 'eglot-ensure)` in my init file - would opening a new rust file cause eglot to try and spawn a new server?

**Comment by antifuchs** [comment]
Update: I removed `eglot-ensure` from the `rust-mode-hook` and I could jump between rust files without having eglot hang. Unfortunately, the newly opened file doesn't have eglot active, and I have to run `M-x eglot` manually. I think to make this work properly, eglot's `M-.` might have to prime the "next" file's `eglot-ensure` to get the current server connection, does that sound right?

**Comment by joaotavora** [comment]
Hmm nice. `eglot-ensure` is supposed to be protected against this kind of thing as well.

**Comment by joaotavora** [comment]
Is the `chars/src/display.rs` target in the same project as the one you jumped from? If it isn't, it's normal that the jump lands you in an eglot-less file.

**Comment by joaotavora** [comment]
But of course `eglot-ensure` is designed to start another, different server for that new file and all the files in its project.

**Comment by antifuchs** [comment]
Right - the function I jumped to was `.to_lowercase`, from the stdlib. Ahhhhh, and sure enough - the simple repro case is this:

1. Open a file from rust's stdlib
2. `M-x eglot`
=> reconnect loop, emacs hangs.

I am guessing this is because project.el can't find a root.

**Comment by joaotavora** [comment]
@antifuchs, nice! where can I find rust's stdlib :-) I'm a total rust idiot

**Comment by joaotavora** [comment]
> I am guessing this is because project.el can't find a root.

project el has a failsafe (rather dumb) way of making a root when there's no other method. So I don't know exactly what is happening.  Can you point me to a canonical file path from the stdlib (can it be inside `~/.rustup` somewhere?)

**Comment by antifuchs** [comment]
Ah! Great question. I use `rustup` to install the toolchain & source code. Here's some shell code that worked for me (get [rustup](https://rustup.rs/) and then):

``` sh
$ rustup install stable 
$ rustup component add rust-std
```

That'll get you the source code; at that point, you have the source code installed at a platform-dependent place; on macOS, I have it in `~/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src`, you'll have to sub in linux if you try there (:

**Comment by joaotavora** [comment]
> That'll get you the source code; at that point, you have the source code installed at a platform-dependent place; on macOS, I have it in ~/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src, you'll have to sub in linux if you try there (:

OK and what file exactly? because I just tried it on some random file and didn't get the infinite loop.

**Comment by antifuchs** [comment]
Oops, I could repro this on pretty much any one in there - I tried `~/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/num.rs`

**Comment by joaotavora** [comment]
> Oops, I could repro this on pretty much any one in there - I tried ~/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/num.rs

Damm, I can't. Let's sync up our recipes:

```
$ cd dir-to-some-cloned-eglot
$ path/to/emacs -Q -L . -l eglot
M-: (define-derived-mode rust-mode prog-mode "Rust") ;; silly but necessary since rust-mode isn't in Emacs
C-x C-f ~/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/num.rs
M-x eglot
```

**Comment by antifuchs** [comment]
Oh yay, it reproduces for me with your command sequence (I had to do `M-x rust-mode` though)! My emacs is `GNU Emacs 26.1 (build 1, x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2018-04-15` (via the `railwaycats/emacs-mac` port).

I think one thing that might affect things is that I had both `rls-preview` (via rustup) and `rls` (from an older cargo install). I deleted the old `rls` and reinstalled `rls-preview`, and now `M-x eglot RET /Users/asf/.rustup/toolchains/stable-x86_64-apple-darwin/bin/rls` visiting that file does actually work. 

This is pretty weird - wonder if the reconnect logic in addition to running a crashy rls in that directory does something weird.

**Comment by antifuchs** [comment]
> Gonna try a little more. It's fixed for you right?

It is! Thanks for helping me debug my outdated environment!! (One wishlist suggestion, if it's possible, would be to detect outdated RLSes and warn, if they set the right version)

**Comment by joaotavora** [comment]
> It is! Thanks for helping me debug my outdated environment!!

You're welcome.

> One wishlist suggestion, if it's possible, would be to detect outdated RLSes and warn, if they set the right version)

I don't think that's something eglot can/should do. It's pretty agnostic to these things.

But it most definitely shouldn't infloop. So I better keep this issue open.

**Comment by joaotavora** [comment]
hehehehe it's super easy to reproduce:

Just `C-u M-x eglot RET echo RET` i.e. enter something that returns immediately.

Now to fix it... Stay tuned.

**Comment by joaotavora** [comment]
So, indeed a bug, and rather easy to fix once I reproduced it. Thanks!

**Comment by joaotavora** [comment]
Regarding debugging problems with RLS in the future, you can view the `stderr` messages it prints by control-left-clicking in the eglot mode-line indicator.

**Comment by antifuchs** [comment]
Hah, nice and short! Thanks for the super timely fix!

Unfortunately, the stderr buffer was completely empty whenever I checked it (except for the indicators saying the process had terminated, when I managed to kill it on the command line); I'll keep an eye out for those the next time, though!
