### ISSUE TITLE
Is there a way to disable all eglot outputs to the minibuffer?

### ISSUE THREAD

**Issue by r-zip** [joaotavora/eglot#369]
I've been using `eglot` for Python for a while, and it's been great. Favorite Python experience in Emacs by far.

However, I recently started using Haskell IDE Engine with `eglot`, and the `eglot` information clutters the minibuffer. If I set `eglot-put-doc-in-help-buffer` to `t`, `eglot` still prints messages to the minibuffer, such as
```
[eglot] fooBar:
(...truncated. Full help is in `*eglot-help for fooBar*')
```
I'd like instead to prevent `eglot` from writing to the minibuffer, so that I can see type information for the cursor provided by `haskell-mode`. Is there an easy way to disable `eldoc` integration for `eglot`, so that documentation is only provided if requested?

**Comment by xuchunyang** [comment]
#334

**Comment by joaotavora** [comment]
Nice one @xuchunyang .  @r-zip I'm tentatively closing this.  But tell me if that works for you or if you're missing something else.
