### ISSUE TITLE
Completion error when there are multiple candidates

### ISSUE THREAD

**Issue by L42y** [joaotavora/eglot#37]
When there are multiple completion candidates,
with company-mode enabled:
```
Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Company: backend company-capf error "Wrong type argument: stringp, nil" with args (annotation React)" on command post-command
```

without company-mode enabled and M-x completion-at-point:
```
Making completion list...
concat: Wrong type argument: stringp, nil
```

but with single completion candidate, it works fine:
![screen shot 2018-07-06 at 3 42 19 pm](https://user-images.githubusercontent.com/284820/42366233-402bee70-8133-11e8-94b6-d0d2061a55b0.jpg)

**Comment by joaotavora** [comment]
What language is this? JavaScript? And what server?

Perhaps you could try upgrading or downgrading your company-mode.

Otherwise, I'll take a look when I get home.

**Comment by L42y** [comment]
JavaScript with javascript-typescript-stdio, major mode is js2-mode, I'll try downgrading my company-mode, since it's already newest from MELPA

**Comment by L42y** [comment]
tried company-mode's stable version `0.9.6`, no luck

**Comment by joaotavora** [comment]
Alright, thanks. I should have no trouble reproducing in that case.
