### ISSUE TITLE
eglot not respecting ccls-initialization-options

### ISSUE THREAD

**Issue by hisnawi** [joaotavora/eglot#370]
I specify the ccls-initialization-options through dir-locals.el in the base of the project.
But when eglot start indexting the files it is not respecting whitelist/blacklist directories. Instead it indexes the whole project.

When switching to lsp-mode I see that the same setup is being respected.
Is that an expected behavior?

This did not work for me:

```
 (nil . ((eglot-workspace-configuration
      . ((:ccls . (setq ccls-initialization-options `(:index (:blacklist ["test"]) :whitelist ["test2"])))))))

```

**Comment by joaotavora** [comment]
> whitelist/blacklist directories

Where are these directories specified? 

> ccls-initialization-options

What is this, is this an Emacs variable?  If it is, then Eglot is not reading it.  The only variable that Eglot _will_ read that you _can, if you want_ put in `dir-locals.el` is `eglot-workspace-configuration`.  See its docstring and the examples in the README.  Maybe you can get that variable to have a value that you can use to affect CCLS.

**Comment by joaotavora** [comment]
>(nil . ((eglot-workspace-configuration
>     . ((:ccls . (setq ccls-initialization-options `(:index (:blacklist ["test"]) :whitelist 
> ["test2"])))))))

OK, that answers some questions.  But: the middle `setq` is completely useless: eglot is not reading that variable and even if it were the `setq` is not executed when reading `dir-locals.el`.

You should first try to _avoid_ dir-locals and set the value of the variable `eglot-workspace-configuration` _globally_, in your `.emacs` for example.

`(setq eglot-workspace-configuration <something-that-you-think-will-work-for-ccls>)`

Once you have that, you can put that in a `dir-locals.el` file for your project.

**Comment by hisnawi** [comment]
Each project I work on has it's own whitelist/blacklist directories to index. I can't put a global one in my emacs file so I rather keep it in the .dir-locals.el file. But I am honestly confused.

This is what worked for me for lsp-mode/ccls:

```
(
 (nil . ((eval . (progn
                   (require 'projectile)
                   (setq-local ccls-initialization-options
                               `(:index
                                 (
                                  :blacklist
                                  ,(vector
                                    (concat "^" (projectile-project-root) "test1/")
                                    (concat "^" (projectile-project-root) "test2/")
                                    )
                                  :whitelist
                                  ,(vector
                                    (concat "^" (projectile-project-root) "test3/")
                                    (concat "^" (projectile-project-root) "test4/")
                                    )
                                  )))))))
 )

```

Which basically sets this ccls-initialization-options  correctly.
When I open emacs and evaluate the variable it does show the correct setup.

what I don't understand is why when running Eglot CCLS is not using these blacklist/whitelist values when parsing the project. It doesnt seem to me like a Eglot (set variable issue like eglot-workspace-configuration). Why would I need to go through Eglot to set a CCLS variable that is already set correctly anyways through .dir-locals.el?

**Comment by hisnawi** [comment]
This also in the emacs file didn't work:

`      (setq eglot-workspace-configuration '((ccls . ccls-initialization-options)))
`

I basically just want ccls settings (ccls-initialization-options) to be passed to ccls.
In the EGLOT....stderr buffer and after the second line:

`14:16:18                initialize.cc:290 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"".....etc
`
the blacklist and whitelist entries are not populated.

**Comment by joaotavora** [comment]
@hisnawi:`ccls-initialization-options` is **NOT** a variable that Eglot will read.  Eglot is _not_ the same as `lsp-mode`.  You need to ask the Ccls maintainer, which I think is @MaskRay , if there is an L-S-P specific way, one that doesn't depend on `ccls-initilization-options`, to tell the Ccls to whitelist or blacklist directories.

For example, ask him how other clients, such as VS Code or some Vim based client can communicate those things to Ccls.

**Comment by hisnawi** [comment]
Is there a way to ask Eglot not to index the project and just use whatever is indexed in .ccls-cache?

**Comment by joaotavora** [comment]
@hisnawi : Eglot does _not_ index the project.  Eglot is a LSP client, it knows nothing about "indexing".  CCLS is the server you want to use, right?  It does the indexing.  Eglot just provides a way to communicate with your server.  One of those ways is called a initialization message with _server specific_ configurations.  But I don't know what those configurations are, only the CCLS people do.

**Comment by joaotavora** [comment]
@hisnawi do let me know if you find a solution to this, then I can add it to the README.  Thanks

**Comment by zsxh** [comment]
I think ccls-initialization-options is just initializationOptions in InitializeParams only for lsp-mode.

check here:
https://github.com/MaskRay/ccls/wiki/coc.nvim
https://github.com/MaskRay/emacs-ccls/blob/master/ccls.el#L148

**Comment by hisnawi** [comment]
@joaotavora After running with eglot+clangd I have the following observations, I just want to confirm that I am not missing some setup:

1. Even when having a compile_flags.txt file that includes all compile flags/defines (-DDEFINEX) and when visiting a file, there is no dimming of source code that falls within undefined sections. For example, if -DTEXT is included in the compilation:

```
#if !defined(TEXT)
//this code should be dimmed
#endif

```

lsp-mode/ccls does that, so it is an eglot limitation or a clangd one?

2. I noticed that with eldoc I only see the first (not too important) part of the symbole information in the mini buffer.
For example, when I hover over a define, in the mini buffer it shows something like:

`declared in namespace test
`
And I have to actually call eglot-help-at-point to get the actual defined value:
`#define testx 100
`

lsp-mode/ccls only showed the second part which is more relevant in the mini buffer.

Am I missing a setup that changes this behavior and only shows the actual defined value and not where it was declared?

**Comment by joaotavora** [comment]
@zsxh that's a good hint of how to potentially setup `eglot-workspace-configuration`.  Thanks.  Though I don't know if @hisnawi has fully understood it yet.

> lsp-mode/ccls does that, so it is an eglot limitation or a clangd one?

I believe it is an Eglot limitation.  It doesn't support server-dictated syntax-highlighting.  yet.  That's actually a nice feature, I have to try it.

For point 2. can you post a screenshot?  I don't understand your problem very well, it would be better if you could just visually show it.

**Comment by hisnawi** [comment]
This is what shows up when point is on the define in the mini buffer through eldoc:

![1](https://user-images.githubusercontent.com/8878871/70758765-d76e0400-1cf8-11ea-9021-44e5a09dd785.jpg)

This is what shows up when executing eglot-help-at-point:

![2](https://user-images.githubusercontent.com/8878871/70758845-1a2fdc00-1cf9-11ea-968f-1cd5264c8494.jpg)

lsp-mode shows the interesting part in mini buffer:

`constexpr auto NAMES....etc
`

I don't care much about in which namespace the define was declared.
why Eglot doesn't show up that second part (the actual define value)?

**Comment by MaskRay** [comment]
See https://github.com/MaskRay/ccls/wiki/Customization#indexinitialblacklist `index.initialBlacklist` `index.initialWhitelist` `index.blacklist` `index.whitelist`

```elisp
(cl-defmethod eglot-initialization-options ((server eglot-ccls))
  (:index (:initialBlacklist ["/(clang|lld|llvm)/(test|unittests)/" "/StaticAnalyzer/"]))
  )
```

I think this requires

```elisp
(defclass eglot-ccls (eglot-lsp-server) () :documentation "ccls.")
```

**Comment by joaotavora** [comment]
Thanks for your feedback @MaskRay 

> I think this requires

> (defclass eglot-ccls (eglot-lsp-server) () :documentation "ccls.")

Indeed, but it requires a little more than this, in `eglot-server-programs` Oftentimes,  easier solutions are:

1. Pass command-line arguments to the server executable
2. Use `eglot-workspace-configuration` which sends a `workspace/didChangeConfiguration` message. 

Does this last one work with ccls?

**Comment by gagbo** [comment]
Just tested that, it didn't work :
```
eglot-workspace-configuration is a buffer-local variable defined in
eglot.el.

Value in #<buffer scanner.cc>
(((:ccls
   (:index :trackDependency 1 :threads 2))))
```

And my log (EGLOT events) shows :
```
[stderr] 13:33:56 .ccls-wrapped  initialize.cc:285 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cache":{"directory":".ccls-cache","format":"binary","hierarchicalPath":false,"retainInMemory":2},"capabilities":{"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"foldingRangeProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}},"clang":{"excludeArgs":[],"extraArgs":["-isystem","/nix/store/bgvxpx97q789xc8rrginprlvk8p03p93-glibc-2.31-dev/include","-isystem","/nix/store/5qfjxk1aa981nxr9h9srizgk45si12n1-libc++-8.0.1/include/c++/v1","-isystem","/nix/store/mk4b62r7in302isssvl66nqbpdxg8bb9-nodejs-14.9.0/include","-isystem","/nix/store/mk4b62r7in302isssvl66nqbpdxg8bb9-nodejs-14.9.0/include"],"pathMappings":[],"resourceDir":""},"client":{"diagnosticsRelatedInformation":true,"hierarchicalDocumentSymbolSupport":true,"linkSupport":true,"snippetSupport":true},"codeLens":{"localVariables":true},"completion":{"caseSensitivity":2,"detailedLabel":true,"dropOldRequests":true,"duplicateOptional":true,"filterAndSort":true,"include":{"blacklist":[],"maxPathSize":30,"suffixWhitelist":[".h",".hpp",".hh",".inc"],"whitelist":[]},"maxNum":100},"diagnostics":{"blacklist":[],"onChange":1000,"onOpen":0,"onSave":0,"spellChecking":true,"whitelist":[]},"highlight":{"largeFileSize":2097152,"lsRanges":false,"blacklist":[],"whitelist":[]},"index":{"blacklist":[],"comments":2,"initialNoLinkage":false,"initialBlacklist":[],"initialWhitelist":[],"maxInitializerLines":5,"multiVersion":0,"multiVersionBlacklist":[],"multiVersionWhitelist":[],"name":{"suppressUnwrittenScope":false},"onChange":false,"parametersInDeclarations":true,"threads":0,"trackDependency":2,"whitelist":[]},"request":{"timeout":5000},"session":{"maxNum":10},"workspaceSymbol":{"caseSensitivity":1,"maxNum":1000,"sort":true},"xref":{"maxNum":2000}}
```

You can see under the `index` key that it still has the default values `"threads":0,"trackDependency":2,`

**Comment by gagbo** [comment]
I wrote a test so you can see what I mean (sorry if the style is not standard)
```lisp
(ert-deftest ccls-initialization-options ()
  "Test ccls initialization."
  (skip-unless (executable-find "ccls"))
  (eglot--with-fixture
      '(("project/main/" . (("main.cc" . "")))
        ("project/.git/" . nil))
      (let ((root (file-name-as-directory default-directory))
            (eglot-ccls-initialization-options '((:index . (:threads 1)))))
      (with-current-buffer
          (eglot--find-file-noselect "project/main/main.cc")
        (setq-local eglot-workspace-configuration `((:ccls . ,(list eglot-ccls-initialization-options))))
        (eglot--sniffing (:client-requests c-reqs)
          (should (eglot--tests-connect 10))
          (eglot--wait-for (c-reqs 10)
              (&key _id method params &allow-other-keys)
            (when (string= method "initialize")
              (let* ((initialization-options (plist-get params :initializationOptions))
                     (indexing-threads-opts
                      (plist-get
                       (plist-get initialization-options :index) :threads)))
                (and (should (equal initialization-options eglot-ccls-initialization-options)))))))))))

```

**Comment by joaotavora** [comment]
> Just tested that, it didn't work :

Notice that `eglot-workspace-configuration` is a directory-local variable. Either use `.dir-locals.el` or set its global value (in the latter case you'll have to manage the different servers in the same variable value, which seems to be possible).  It is _not_ a per-buffer thing because Eglot manages projects, which can have many buffers.

**Comment by gagbo** [comment]
In the test I should just use `setq` instead of `setq-local` ? I think this fails the test as well

**Comment by joaotavora** [comment]
That's not the same as saying this is the problem here, but `setq-local` for particulars buffers in your project will guaranteedly _not_ work. You can try with `setq` or by using `.dir-locals.el`.  Both _should_ work.  I.e. you should be able to detect those things being handed to the server in the Eglot events buffer.

**Comment by gagbo** [comment]
Looks like no, the didChangeConfiguration is sent but it doesn't reflect as far as I understand :
```
[client-notification] Mon Sep 28 12:31:34 2020:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
          (:settings
           (:ccls
            ((:index :trackDependency 1 :threads 2)))))
[stderr] 12:31:34 .ccls-wrapped  initialize.cc:285 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cache":{"directory":".ccls-cache","format":"binary","hierarchicalPath":false,"retainInMemory":2},"capabilities":{"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"foldingRangeProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}},"clang":{"excludeArgs":[],"extraArgs":["-isystem","/nix/store/bgvxpx97q789xc8rrginprlvk8p03p93-glibc-2.31-dev/include","-isystem","/nix/store/5qfjxk1aa981nxr9h9srizgk45si12n1-libc++-8.0.1/include/c++/v1","-isystem","/nix/store/mk4b62r7in302isssvl66nqbpdxg8bb9-nodejs-14.9.0/include","-isystem","/nix/store/mk4b62r7in302isssvl66nqbpdxg8bb9-nodejs-14.9.0/include"],"pathMappings":[],"resourceDir":""},"client":{"diagnosticsRelatedInformation":true,"hierarchicalDocumentSymbolSupport":true,"linkSupport":true,"snippetSupport":true},"codeLens":{"localVariables":true},"completion":{"caseSensitivity":2,"detailedLabel":true,"dropOldRequests":true,"duplicateOptional":true,"filterAndSort":true,"include":{"blacklist":[],"maxPathSize":30,"suffixWhitelist":[".h",".hpp",".hh",".inc"],"whitelist":[]},"maxNum":100},"diagnostics":{"blacklist":[],"onChange":1000,"onOpen":0,"onSave":0,"spellChecking":true,"whitelist":[]},"highlight":{"largeFileSize":2097152,"lsRanges":false,"blacklist":[],"whitelist":[]},"index":{"blacklist":[],"comments":2,"initialNoLinkage":false,"initialBlacklist":[],"initialWhitelist":[],"maxInitializerLines":5,"multiVersion":0,"multiVersionBlacklist":[],"multiVersionWhitelist":[],"name":{"suppressUnwrittenScope":false},"onChange":false,"parametersInDeclarations":true,"threads":0,"trackDependency":2,"whitelist":[]},"request":{"timeout":5000},"session":{"maxNum":10},"workspaceSymbol":{"caseSensitivity":1,"maxNum":1000,"sort":true},"xref":{"maxNum":2000}}
```

**Comment by joaotavora** [comment]
Well at least know we know that Eglot is sending something that you set in the variable, which is an improvement.  

The next questions to ask are.  1. Are you sending the correct format?  2. Is CCLS respecting "workspace/didChangeConfiguration"?  I cannot answer either.

**Comment by gagbo** [comment]
From my understanding of ccls source :
- there is a handler for didChangeConfiguration ( [here](https://github.com/MaskRay/ccls/blob/468a2fb6ca7a47a12d93b7a841aba8386dfea75b/src/messages/workspace.cc#L25) which is bound to the correct message type elsewhere)
- But this does not alter the `g_config` variable which is what ultimately holds the values for initialConfiguration. This is [https://github.com/MaskRay/ccls/blob/468a2fb6ca7a47a12d93b7a841aba8386dfea75b/src/messages/initialize.cc#L366-L386](the kind of code) that shows that the `g_config` variable is my target for these changes)

I think @MaskRay would agree, since they proposed the same change ([override the initialization options for ccls](https://github.com/joaotavora/eglot/issues/370#issuecomment-565324328) ) but maybe they can confirm

**Comment by joaotavora** [comment]
> But this does not alter the g_config variable 

I'm not familiar with ccls code, but perhaps it could?  From what you linked it seems all that handler done is load the workspace folders, but "workspace configuration" can/should be used for more, no?

Yes, you can override the initialization options for ccls, but server-specific code shouldn't live in Eglot. It can live entirely in your configuration. Alternatively, you can make an eglot-ccls library that irons out those little quirks, if you want.  I know there are exceptions for java-mode and rust-mode, but they are on the way out.

**Comment by gagbo** [comment]
> I know there are exceptions for java-mode and rust-mode, but they are on the way out.

I wasn't sure which way eglot.el was going on that. Ok then :) I'll probably keep that in my private config for now and see if a package is worth it

**Comment by joaotavora** [comment]
> I'll probably keep that in my private config for now and see if a package is worth it

Eventually, when eglot.el is integrated into Emacs proper (an unfortunately delayed, but confirmed, development), you can consider adding that code to Emacs's C-mode, which is where the configuration of other packages should be.

Even so, I would insist a little bit more with CCLS's developer?  Why isn't the workspace configuration message working as expected? Is there a technical reason or is it an oversight?

**Comment by nicolas-graves** [comment]
@MaskRay reviving this thread because I still have the issue. 
https://github.com/joaotavora/eglot/issues/370#issuecomment-699941352 asks about whether it's doable to modify `g_config` in this case in ccls, WDYT ?

**Comment by nicolas-graves** [comment]
In the meantime, I'll use a project specific configuration in `.dir-locals.el`: 
```
((nil
  (eval . (require 'eglot))
  (eval . (defclass eglot-ccls (eglot-lsp-server) ()
            :documentation "CCLS"))
  (eval . (defvar-local eglot-ccls-initialization-options nil
            "Property list of initialization options sent to CCLS on start."))
  (eval . (cl-defmethod eglot-initialization-options ((_server eglot-ccls))
            "Passes through ccls initialization options."
            eglot-ccls-initialization-options))
  (eglot-server-programs . (((c-mode c++-mode) . (eglot-ccls "ccls")))))
 (c-mode
  (c-basic-offset . 4)
  (eglot-ccls-initialization-options
   .  (:clang (:extraArgs ["-Ithird_party/bencode-tools/include"
                           "-Ithird_party/async.h/async"])))
  ;; (eglot-workspace-configuration
  ;; . ((:ccls . (:clang (:extraArgs ["-Ithird_party/bencode-tools/include"
  ;; "-Ithird_party/async.h/async"])))))
  ))
```
