### ISSUE TITLE
eglot--format-markup: (wrong-type-argument char-or-string-p nil)

### ISSUE THREAD

**Issue by lxbarbosa** [joaotavora/eglot#371]
Hi,

Running omnisharp-roslyn and emacs in a fresh install and it issued this error:
```elisp
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  eglot--format-markup(nil)
  mapconcat(eglot--format-markup [nil nil] "\n")
  eglot--hover-info([nil nil] nil)
  #f(compiled-function () #<bytecode 0x15945a6c2b09>)()
  eglot--call-with-interface((Hover (:contents) (:range)) (:contents [nil nil]) #f(compiled-function () #<bytecode 0x15945a6c2b09>))
  #f(compiled-function (jsonrpc-lambda-elem372) #<bytecode 0x15945afc35d9>)((:contents [nil nil]))
  jsonrpc-connection-receive(#<eglot-lsp-server eglot-lsp-server-159456e843f8> (:jsonrpc "2.0" :id 21 :result (:contents [nil nil])))
  jsonrpc--process-filter(#<process EGLOT (all/csharp-mode)> "de\":-32602,\"message\":\"Internal Error - System.Null...")
```

It may be related to https://github.com/emacs-lsp/lsp-ui/issues/350

---------
GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13) of 2019-12-12
Eglot 1.5 - Package-Version: 20191208.2129
OmniSharp-Roslyn 1.34
Arch Linux
Qtile
T430

**Comment by lxbarbosa** [comment]
Follow-up:

Under Debian everything is working correctly.

**Comment by joaotavora** [comment]
> Under Debian everything is working correctly.

Cool, then I can close this.

**Comment by joaotavora** [comment]
By the way, don't edit your original report to change the operating system you originally reported this for.  It's **very** confusing.  Just add more commetns explaining clearly what  you're doing.  If you need to write "Oh, I wrote Debian but I meant Arch", it's OK.

**Comment by lxbarbosa** [comment]
@joaotavora 
I thought the same, I wonder why I wrote Debian at first!

**Comment by lxbarbosa** [comment]
hey @joaotavora  testing omnisharp-roslyn under Ubuntu and the same issue persist. 

Reproducing:

omnisharp-roslyn: v1.34.9 - https://github.com/OmniSharp/omnisharp-roslyn/releases

`emacs -Q`

```elisp
(package-initialize)
(require 'eglot)
(require 'csharp-mode)
(add-to-list 'eglot-server-programs '(csharp-mode . 
                                ("/home/lxbarbosa/.local/omnisharp/run" "-lsp")))
```
m-x csharp-mode
m-x eglot 

scroll down to a class then: 

```elisp
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  eglot--format-markup(nil)
  mapconcat(eglot--format-markup [nil nil] "\n")
  eglot--hover-info([nil nil] nil)
  #f(compiled-function () #<bytecode 0x15918908260d>)()
  eglot--call-with-interface((Hover (:contents) (:range)) (:contents [nil nil]) #f(compiled-function () #<bytecode 0x15918908260d>))
  #f(compiled-function (jsonrpc-lambda-elem571) #<bytecode 0x1591894e89ed>)((:contents [nil nil]))
  jsonrpc-connection-receive(#<eglot-lsp-server eglot-lsp-server-159188eb98f4> (:jsonrpc "2.0" :id 21 :result (:contents [nil nil])))
  jsonrpc--process-filter(#<process EGLOT (omnisharp-roslyn/csharp-mode)> "st (21) textDocument/hover in 0ms\"}}Content-Length...")
```
related: https://github.com/emacs-lsp/lsp-ui/issues/350

\*events\* log: http://ix.io/253F/text

**Comment by lxbarbosa** [comment]
oh, forgot that eglot succefuly connected:

```
[eglot] Connected! Server `EGLOT (omnisharp-roslyn/csharp-mode)' now managing `csharp-mode' buffers in project `omnisharp-roslyn'.
```

**Comment by joaotavora** [comment]
Seems like a server problem.  It's sending `[null null]` as the `:contents` field of a response to `textDocument/hover`, which is not conformant to https://microsoft.github.io//language-server-protocol/specifications/specification-3-14/#textDocument_hover
```
interface Hover {
	/**
	 * The hover's content
	 */
	contents: MarkedString | MarkedString[] | MarkupContent;

	/**
	 * An optional range is a range inside a text document
	 * that is used to visualize a hover, e.g. by changing the background color.
	 */
	range?: Range;
}
```

because

```
type MarkedString = string | { language: string; value: string };
```

**Comment by lxbarbosa** [comment]
@joaotavora 
https://github.com/OmniSharp/omnisharp-roslyn/issues/1087
