### ISSUE TITLE
How to specify init argument "usePlaceholders" for gopls?

### ISSUE THREAD

**Issue by netjune** [joaotavora/eglot#372]
See document: https://github.com/golang/tools/blob/master/gopls/doc/settings.md

**Comment by edkolev** [comment]
See the README, this section https://github.com/joaotavora/eglot#per-project-server-configuration

**Comment by netjune** [comment]
Thanks. 

I see that it needs to set a buffer-local variable eglot-workspace-configuration. I want to enable usePlaceholders globally for gopls. Is it possible to set it in eglot-server-programs?

If not, I will use the buffer-local variable eglot-workspace-configuration.

**Comment by edkolev** [comment]
Yes, just set the variable before loading eglot, i.e. in :init in case you're using use-package

Sorry, can't give you an example right now

**Comment by joaotavora** [comment]
@edkolev @netjune 

There are many ways you can set the variable, and the variable is only _one_ way to tell the server how to behave.  T

1. Set the variable globally
2. Set the variable mode-locally, like for `go-mode` using `go-mode-hook`
3. Set the variable directory-locally, for specific projects
4. Set the variable server-locally, with `eglot-server-initialized-hook`

I think 1,2 and 3 can solve many of your problems.  The README has to be upgraded yet a bit more: 4 is not documented at all.

As for the other ways to configure the server, you can

1. Pass in command-line arguments
2. Make a subclass of `eglot-server` and define `eglot-initialization-options` on it.

This is a quick summary of the ways I know of configuring servers in Eglot.  If someone has _very good_ documentation skills and can upgrade the README to reflect clearly possibilities, I'll welcome that PR.

**Comment by netjune** [comment]
> @edkolev @netjune
> 
> There are many ways you can set the variable, and the variable is only _one_ way to tell the server how to behave. T
> 
> 1. Set the variable globally
> 2. Set the variable mode-locally, like for `go-mode` using `go-mode-hook`
> 3. Set the variable directory-locally, for specific projects
> 4. Set the variable server-locally, with `eglot-server-initialized-hook`
> 

In eglot.el I see eglot-signal-didChangeConfiguration. It sends all information in eglot-workspace-configuration to the lsp server. If it is set globally, the same content in eglot-workspace-configuration will be sent to every lsp server(lsp server for golang or c++). Does this cause problem?

**Comment by joaotavora** [comment]
> It sends all information in eglot-workspace-configuration to the lsp server. If it is set globally, the same content in eglot-workspace-configuration will be sent to every lsp server(lsp server for golang or c++). 

That is correct. 

> Does this cause problem?

I don't know.  Theoretically it could, but I think language servers will only inspect the parts of the resulting json object that they are interested in.  So gopls will probably look up the "Go"-related section and while clang will look up the "C++"-related section.

But ultimately it depends on the server.

**Comment by netjune** [comment]
OK. It is clear for me now. Thanks.
