### ISSUE TITLE
Show only project name in mode-line statically (without changing length)

### ISSUE THREAD

**Issue by hisnawi** [joaotavora/eglot#374]
When running eglot with clagnd I see this in the mode-line:

`eglot[projectname]
`
How ever when moving in the code I see the changes to something like:

`eglot[projectname/2]
`
This flicking in the mode-line is somewhat distracting and I don't see any info added showing this extra pattern of numbers.

Is there a way to disable it? and only show project name?

**Comment by hisnawi** [comment]
I did achieve this by the implementation:

```
    (defun eglot--mode-line-format ()
      "Compose the EGLOT's mode-line."
      (pcase-let* ((server (eglot-current-server))
                   (nick (and server (eglot--project-nickname server)))
                   (pending (and server (hash-table-count
                                         (jsonrpc--request-continuations server))))
                   (`(,_id ,doing ,done-p ,_detail) (and server (eglot--spinner server)))
                   (last-error (and server (jsonrpc-last-error server))))
        (append
         `(,(eglot--mode-line-props "eglot" 'eglot-mode-line nil))
         (when nick
           `(":" ,(eglot--mode-line-props
                   nick 'eglot-mode-line
                   '((C-mouse-1 eglot-stderr-buffer "go to stderr buffer")
                     (mouse-1 eglot-events-buffer "go to events buffer")
                     (mouse-2 eglot-shutdown      "quit server")
                     (mouse-3 eglot-reconnect     "reconnect to server")))
             ,@(when last-error
                 `("/" ,(eglot--mode-line-props
                         "error" 'compilation-mode-line-fail
                         '((mouse-3 eglot-clear-status  "clear this status"))
                         (format "An error occured: %s\n" (plist-get last-error
                                                                     :message)))))
             ,@(when (and doing (not done-p))
                 `("/" ,(eglot--mode-line-props doing
                                                'compilation-mode-line-run '())))
             ,@(when nil
                 `("/" ,(eglot--mode-line-props
                         (format "%d" pending) 'warning
                         '((mouse-3 eglot-forget-pending-continuations
                                    "forget pending continuations"))))))))))

```

I don't think this is the cleanest way of doing it though.

**Comment by nemethf** [comment]
I think those numbers provide some useful information.  While you modified the code, were you able to understand what's the meaning of those numbers?

If the number showing the pending request flickers, it means the server is slow to respond, but not terribly slow.  Maybe it's annoying, but it is a good indication that something is not perfect with the client-server communication. 

On the other hand,  it might make sense not to count those fresh pending requests that are not older than, say, half second.

**Comment by joaotavora** [comment]
> If the number showing the pending request flickers, it means the server is slow to respond, but not terribly slow. Maybe it's annoying, but it is a good indication that something is not perfect with the client-server communication.

:100: but that's not to say it could be configurable, _if_ that configuration is both sufficiently generic to be able to customize the whole of Eglot's mode-line indicator _and_ economic in LOC/complexity.  Until we have such a thing, I'd rather leave it be.
