### ISSUE TITLE
Renaming files doesn't update imports

### ISSUE THREAD

**Issue by theothornhill** [joaotavora/eglot#377]
Hello!

I tried to find an issue like this, but couldn't, so I'll just ask - 
When renaming files inside of a project registered by eglot, imports will not be updated across the project. Is this a feature which should be supported in eglot? The server I am using is `typescript-language-server`, and I am running typescript.

I think the optimal solution would be to get a function like `eglot-rename-symbol`, where we can supply the new name/path, and then all imports affected will be updated. I see this feature is implemented in tide, as well as lsp-mode, and also is supported by the server I am currently using. However, I know these wrap `tsserver`, which I believe doesn't conform completely to the lsp spec.

Is this something that could be hooked into dired, so a batch move/rename will update accordingly. (I realise this possibly would be out of eglots scope)

I may have missed the functionality completely, and if so I am sorry :)
Thanks for a great project!

**Comment by nemethf** [comment]
The language server protocol does not support client-initiated file renaming operations.  However, an LSP server might detect changes in the import statements and could potentially send a RenameFile request to the client. 

However, eglot does not currently support RenameFile requests as it does not have any resourceOperations in its WorkspaceEditClientCapabilities.  

Eglot can be extended with this feature, but it won't give you the workflow you wish to have.   So, can you try to look at the exact LSP communication in the working example you described above?  The detailed logs might provide ideas for an alternative implementation approach.

**Comment by theothornhill** [comment]
Thanks for the thorough answer!

I will look at this when I get some free time - seems like it may be a big task :)
