### ISSUE TITLE
El-doc information stay in the mini-buffer when navigating the code

### ISSUE THREAD

**Issue by hisnawi** [joaotavora/eglot#380]
El-doc information shows up in mini-buffer at the bottom of emacs but when moving around and until the cursor lands on a new symbol the old information stays showing.
Is this intentional? Is there a way to only show el-doc info when the cursor is on the corresponding symbol/function/defines...etc?

I noticed that using the mouse to move around does clear el-doc information. but not with navigation with arrows.

**Comment by muffinmad** [comment]
It is fixed in #439

**Comment by philippludwig** [comment]
Okay, how can I have the old behavior? I want el-doc to keep showing the old documentation when I move the cursor.

**Comment by muffinmad** [comment]
@philippludwig Try this
```elisp
(defun my/keep-eldoc-message (fn &rest args)
  (when (car args)
    (apply fn args)))

(advice-add 'eldoc--message :around #'my/keep-eldoc-message)
```
