### ISSUE TITLE
Make Eglot-format display error messages in echo area when called non-interactively

### ISSUE THREAD

**Issue by thepreacher** [joaotavora/eglot#392]
For elixir, I have `(lambda () (add-hook 'before-save-hook 'eglot-format nil t))` hooked to elixir-mode. When the formatting fails for whatever reason, I'll like to have the message stating the fact in the mini buffer. 

Currently the message is listed in the `Messages` buffer so I'll have to switch buffers to read the message and switch back to fix whatever the cause was.

It'll be great if the message stating the cause of the formatting failure is displayed in the mini buffer.

**Comment by joaotavora** [comment]
`eglot-format` isn't meant for non-interactive use.  But I guess it it's in `*Messages*` it was _once_ a "message" that appeared in your minibuffer, however briefly.

Anyway, what are the messages you are getting in `*Messages*` when it fails, or, in other words, _why_ and _how_ is formatting failing?

**Comment by joaotavora** [comment]
Sorry, not "minibuffer".  I made the same mistake.  What you mean is "echo area".

**Comment by thepreacher** [comment]
> Anyway, what are the messages you are getting in `*Messages*` when it fails, or, in other words, _why_ and _how_ is formatting failing?

```
Saving file /Users/user/Code/learn/elixir/phinac/auction_umbrella/apps/auction/lib/auction.ex...
Error: (jsonrpc-error "request id=6 failed:" (jsonrpc-error-code . -32000) (jsonrpc-error-message . "an exception was raised:
    ** (SyntaxError) nofile:41: unexpectedly reached end of line. The current expression is invalid or incomplete
        (elixir) lib/code.ex:553: Code.format_string!/2
        (language_server) lib/language_server/providers/formatting.ex:13: ElixirLS.LanguageServer.Providers.Formatting.format/3
        (language_server) lib/language_server/server.ex:443: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2") (jsonrpc-error-data))
Wrote /Users/user/Code/learn/elixir/phinac/auction_umbrella/apps/auction/lib/auction.ex
```
It will be nice if this bit of the message ``` ** (SyntaxError) nofile:41: unexpectedly reached end of line. The current expression is invalid or incomplete``` would be displayed in the "echo area". It tells me what line the error is on and what it is.

**Comment by joaotavora** [comment]
Well, the message _was_ there as we have concluded, it's just that another message superseeded it (the final "Wrote" message).  Apparently, `before-save-hook` has that behaviour, and it even proceeded after an error was triggered inside it. If you really want to do something like this, I sugest writing a function like this
```
(defun thepreacher/format ()
   (condition-case err
      (eglot-format (point-min) (point-max))
    (jsonrpc-error <handle the error here and maybe scheduler a timer for a deffered display of message>)))
```
And putting that in the `before-save-hook`.  I don't think Eglot should be taking care of this directly, though.
