### ISSUE TITLE
eglot causes issue when reading dir-locals

### ISSUE THREAD

**Issue by r-zip** [joaotavora/eglot#396]
If I'm in a project where I have directory-local variables, and I've added `eglot-ensure` as a hook, opening a buffer will cause the following error:

```
Directory-local variables error: (error Command attempted to use minibuffer while in minibuffer)
```

Eglot should wait until the minibuffer is unused by an interactive command before trying to send anything to it.

**Comment by joaotavora** [comment]
Well, exactly where did you add `eglot-ensure`?  Can you follow the advice of the README on [reporting bugs](https://github.com/joaotavora/eglot#reporting-bugs), to help the maintainers help you?

**Comment by joaotavora** [comment]
Point 3 of said advice (the backtrace), would be especially valuable here.  But other points also hold, especially point 1.

**Comment by skangas** [comment]
More information was requested, but none was given within two years. I'm therefore closing this bug report.

If you are still seeing this issue, please reopen as a new issue with all details asked for in the bug reporting form. Thanks!
