### ISSUE TITLE
bug about eglot-rename in javascript

### ISSUE THREAD

**Issue by zerolee** [joaotavora/eglot#4]
![byzanz_record](https://user-images.githubusercontent.com/4004082/40266025-68b2098e-5b76-11e8-93eb-69b257344db8.gif)

**Comment by joaotavora** [comment]
Oh, what an eloquent bug report :-) I'm on it!

**Comment by joaotavora** [comment]
Should be fixed in master. Please verigy. I'll be pushing a 0.4 version to GNU ELPA with this fix later today

**Comment by zerolee** [comment]
The problem is solved, thank you for time on this.

**Comment by ElleNajt** [comment]
Just wanted to comment here that I'm having a similar problem in python with pyright, though it's been tricky to reproduce. Opened a discussion here: https://github.com/joaotavora/eglot/discussions/1373
