### ISSUE TITLE
is it possible to use company-box

### ISSUE THREAD

**Issue by atanasj** [joaotavora/eglot#419]
I know that `eglot` can use `company-quickhelp` for popup help, but is it possible to use `company-box` instead?

**Comment by joaotavora** [comment]
Hello @atanasj, I can't help you, sorry. I don't use `company-box`, so I can't tell you.  Why don't you try it? So you can go to its webpage, try it, and if you notice something wrong that you think is related to Eglot, you can make an issue here. But, if you need to ask questions, I would first ask them in the website for the `company-box` project before asking them here or in Company's github page.

**Comment by atanasj** [comment]
Thanks, will do. I've tried it and it doesn't work with `elgot`. It follow up with `company-box`.
