### ISSUE TITLE
Any plan to support newer LSP?

### ISSUE THREAD

**Issue by linux40** [joaotavora/eglot#421]
I want to try another language server for java [here](https://github.com/georgewfraser/java-language-server), and the readme of this server shows that it is not compatible with client which just support LSPv2.0.

I place `lang_server_linux.sh` as the server for `java-mode` and this server crashed. It presumably crash for compatibility.

But I am not familiar with LSP, and it seems that no matter what version client support, the version of jsonrpc will always be 2.0. And if eglot support a very new version of LSP, I will open an issue for server.

**Comment by joaotavora** [comment]
Hi, I've been very busy elsewhere lately, and things have moved on elsewhere.

However Eglot, has, and has always supported version 3.x of the LSP protocol.  In fact, I don't think it ever supported 2.x, whatever that may have been.  JSONRPC is another thing, and is always 2.0.

If you server crashed, maybe you need to show how it crashed by showing us the contents of the Eglot events buffer and Eglot stderr buffer.

**Comment by linux40** [comment]
I have report [this](https://github.com/georgewfraser/java-language-server/issues/139). Feel free to close this issue or keep it open if there are somethings to follow.

**Comment by joaotavora** [comment]
Yes, I'm going to close it as there doesn't seem to be any problem here.  I'll try out that server though, since it seems much easier to setup than the one Eglot uses by default.
