### ISSUE TITLE
Cannot configure java 

### ISSUE THREAD

**Issue by anquegi** [joaotavora/eglot#424]
Hi, thanks for this project

I'm trying to configure this for java. I'm using recommendations from #176 I did this:
```

(defconst my-eclipse-jdt-home
  "/Users/toni/.emacs.d/jdt-language-server-0.52.0-202003111128/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar"
  "Point to eclipse jdt jar.")

(defun my-eclipse-jdt-contact ()
    "Contact with the jdt server."
  (interactive)
  (let ((cp (getenv "CLASSPATH")))
    (setenv "CLASSPATH" (concat cp ":" my-eclipse-jdt-home))
    (unwind-protect (eglot--eclipse-jdt-contact nil)
      (setenv "CLASSPATH" cp))))

(add-to-list 'eglot-server-programs '(java-mode . #'my-eclipse-jdt-contact))
```
 I get the following error:
```

cl-no-applicable-method: No applicable method: make-instance, function, :name, "EGLOT (my-app/java-mode)", :events-buffer-scrollback-size, 2000000, :notification-dispatcher, #[771 "ÁÀÂÃ\"$" [eglot-handle-notification apply append nil] 10 "

(fn SERVER METHOD PARAMS)"], :request-dispatcher, #[771 "ÁÀÂÃ\"$" [eglot-handle-request apply append nil] 10 "

(fn SERVER METHOD PARAMS)"], :on-shutdown, eglot--on-shutdown
```
¿I need some local configuration for project?

**Comment by joaotavora** [comment]
Thsi line has a bug in it:
```
(add-to-list 'eglot-server-programs '(java-mode . #'my-eclipse-jdt-contact))
```

remove the `#'`.  Tell me if it works and I'll reopen if it doesn't.

**Comment by anquegi** [comment]
Hi thanks for your quick response. I change that and the error is different,
`eglot--guess-contact: Wrong number of arguments: ((t) nil "Contact with the jdt server." (interactive) (let ((cp (getenv "CLASSPATH"))) (setenv "CLASSPATH" (concat cp ":" my-eclipse-jdt-home)) (unwind-protect (eglot--eclipse-jdt-contact nil) (setenv "CLASSPATH" cp)))), 1`

I also updated that without using this configuration
eglot works well

**Comment by joaotavora** [comment]
I don't have time to debug this right now.  Try to copy the default configuration (the one you have witnessed to work unproblematically) as close as possible.  For example, I think your function has to be able to receive one argument, and it doesn't.

**Comment by anquegi** [comment]
Ok I will do some tests, thanks for the suggestions

**Comment by anquegi** [comment]
Thanks with this configuration it is working well:

;;; Java development
(defconst my-eglot-eclipse-jdt-home
  "/Users/toni/.emacs.d/jdt-language-server-0.52.0-202003111128/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar"
  "Point to eclipse jdt jar.")

```
(defun my-eglot-eclipse-jdt-contact (interactive)
  "Contact with the jdt server input INTERACTIVE."
  (let ((cp (getenv "CLASSPATH")))
    (setenv "CLASSPATH" (concat cp ":" my-eglot-eclipse-jdt-home))
    (unwind-protect (eglot--eclipse-jdt-contact nil)
      (setenv "CLASSPATH" cp))))

(setcdr (assq 'java-mode eglot-server-programs) #'my-eglot-eclipse-jdt-contact)

(add-hook 'java-mode-hook 'eglot-ensure)
```

**Comment by manuel-uberti** [comment]
@anquegi Is this still working for you? I am getting.
```
Error in post-command-hook (#1=#[0 "\303\304\301\242\305#\210\300\306!\205\0r\211q\210
?\205\0\307\310\311 \")\207" [#<buffer HelloWorld.java> (#1#) eglot--managed-mode remove-hook post-command-hook nil buffer-live-p apply eglot--connect eglot--guess-contact] 4]): (error "Process EGLOT (tmp/java-mode) not running")
[jsonrpc] Server exited with status 1
```

**Comment by manuel-uberti** [comment]
@anquegi sorry for the noise, just me wrongly setting my-eglot-eclipse-jdt-home to a relative path.
