### ISSUE TITLE
RLS shows `: ` in eldoc on lines that have no actual documentation

### ISSUE THREAD

**Issue by andreyorst** [joaotavora/eglot#425]
Can such thing be filtered? It doesn't really bothers me when using plain eldoc, because it just pops up in echo line, but with `eldoc-box` package it's kinda annoying:

![image](https://user-images.githubusercontent.com/19470159/76698898-cbf3f580-66b8-11ea-9e92-ec44e2b94487.png)

This only happens with `RLS` as far as I'm concerned.

**Comment by nemethf** [comment]
Please read and follow the instructions of https://github.com/joaotavora/eglot#reporting-bugs

**Comment by joaotavora** [comment]
@andreyorst, I can understand the annoyance, but it's very unlikely such a thing would be filtered by Eglot, it's just a feature that doesn't belong here.

You might have best results if you:

* report this to RLS 
* look into Emacs's `eldoc` for ways to filter it out
* look into `eldoc-box` for ways to filter it out

**Comment by andreyorst** [comment]
Thanks, @joaotavora

**Comment by andreyorst** [comment]
@jaotavora Actually, this does not happen in other LSP clients. I've tried:

- Atom's [ide-rust](https://atom.io/packages/ide-rust)
- Kakoune's [kak-lsp](https://github.com/ul/kak-lsp)
- Emacs [lsp-mode](https://github.com/emacs-lsp/lsp-mode)

So I think it is Eglot bug.

**Comment by joaotavora** [comment]
> So I think it is Eglot bug.

How can we know if you haven't yes followed @nemethf 's very good advice?  Please do so before continuing, yes?

But if, and only if, RLS is continuously sending the string `": "` as a doc, I mantain that this shouldn't be fixed in Eglot. I don't care if other clients have special rules for RLS, Eglot won't. (it has enough for more difficult matters). Again: Emacs, Eldoc Box and RLS are the places to fix this.  

But this is again, presuming the problem to be what I think it is.  So please make a proper bug report of it.

**Comment by andreyorst** [comment]
Happens with:

```
emacs -q --eval "(progn (package-initialize) (require 'eglot))"
```

sample Rust code with latest RLS installed with `cargo` (`█` represents point):

```rust
fn main() {
}█
```

Resulting docstring:
```
:
```

<details>
<summary><code>eglot-events-buffer</code></summary>

```
client-request (id:1) Mon Mar 16 11:49:29 2020:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
	  (:processId 10939 :rootPath "/home/andreyorst/Git/grscheme/" :rootUri "file:///home/andreyorst/Git/grscheme/" :initializationOptions nil :capabilities
		      (:workspace
		       (:applyEdit t :executeCommand
				   (:dynamicRegistration :json-false)
				   :workspaceEdit
				   (:documentChanges :json-false)
				   :didChangeWatchedFiles
				   (:dynamicRegistration t)
				   :symbol
				   (:dynamicRegistration :json-false)
				   :configuration t)
		       :textDocument
		       (:synchronization
			(:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
			:completion
			(:dynamicRegistration :json-false :completionItem
					      (:snippetSupport :json-false)
					      :contextSupport t)
			:hover
			(:dynamicRegistration :json-false :contentFormat
					      ["markdown" "plaintext"])
			:signatureHelp
			(:dynamicRegistration :json-false :signatureInformation
					      (:parameterInformation
					       (:labelOffsetSupport t)))
			:references
			(:dynamicRegistration :json-false)
			:definition
			(:dynamicRegistration :json-false)
			:declaration
			(:dynamicRegistration :json-false)
			:implementation
			(:dynamicRegistration :json-false)
			:typeDefinition
			(:dynamicRegistration :json-false)
			:documentSymbol
			(:dynamicRegistration :json-false :symbolKind
					      (:valueSet
					       [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
			:documentHighlight
			(:dynamicRegistration :json-false)
			:codeAction
			(:dynamicRegistration :json-false :codeActionLiteralSupport
					      (:codeActionKind
					       (:valueSet
						["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"])))
			:formatting
			(:dynamicRegistration :json-false)
			:rangeFormatting
			(:dynamicRegistration :json-false)
			:rename
			(:dynamicRegistration :json-false)
			:publishDiagnostics
			(:relatedInformation :json-false))
		       :experimental nil)))

server-reply (id:1) Mon Mar 16 11:49:29 2020:
(:jsonrpc "2.0" :id 1 :result
	  (:capabilities
	   (:textDocumentSync 2 :hoverProvider t :completionProvider
			      (:resolveProvider t :triggerCharacters
						["." ":"])
			      :definitionProvider t :implementationProvider t :referencesProvider t :documentHighlightProvider t :documentSymbolProvider t :workspaceSymbolProvider t :codeActionProvider t :codeLensProvider
			      (:resolveProvider :json-false)
			      :documentFormattingProvider t :documentRangeFormattingProvider :json-false :renameProvider t :executeCommandProvider
			      (:commands
			       ["rls.applySuggestion-10953" "rls.deglobImports-10953"]))))

client-notification Mon Mar 16 11:49:29 2020:
(:jsonrpc "2.0" :method "initialized" :params #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
							    ()))

client-notification Mon Mar 16 11:49:29 2020:
(:jsonrpc "2.0" :method "textDocument/didOpen" :params
	  (:textDocument
	   (:uri "file:///home/andreyorst/Git/grscheme/src/main.rs" :version 0 :languageId "rust" :text "mod evaluator;\nmod reader;\nmod runner;\nmod tree;\n\nfn main() -> Result<(), u32> {\n    runner::run()\n}\n")))

client-notification Mon Mar 16 11:49:29 2020:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
	  (:settings nil))

server-notification Mon Mar 16 11:49:29 2020:
(:jsonrpc "2.0" :method "window/progress" :params
	  (:done nil :id "progress_1" :message nil :percentage nil :title "Building"))

server-notification Mon Mar 16 11:49:29 2020:
(:jsonrpc "2.0" :method "window/progress" :params
	  (:done nil :id "progress_1" :message "grscheme cfg(test)" :percentage nil :title "Building"))

server-notification Mon Mar 16 11:49:29 2020:
(:jsonrpc "2.0" :method "window/progress" :params
	  (:done nil :id "progress_1" :message "grscheme" :percentage nil :title "Building"))

server-request (id:1) Mon Mar 16 11:49:30 2020:
(:jsonrpc "2.0" :method "client/registerCapability" :id 1 :params
	  (:registrations
	   [(:id "rls-watch" :method "workspace/didChangeWatchedFiles" :registerOptions
		 (:watchers
		  [(:globPattern "/home/andreyorst/Git/grscheme//Cargo.lock")
		   (:globPattern "/home/andreyorst/Git/grscheme//target" :kind 4)
		   (:globPattern "/home/andreyorst/Git/grscheme/Cargo.toml")]))]))

client-reply (id:1) Mon Mar 16 11:49:30 2020:
(:jsonrpc "2.0" :id 1 :result nil)

server-notification Mon Mar 16 11:49:31 2020:
(:jsonrpc "2.0" :method "window/progress" :params
	  (:done t :id "progress_1" :message nil :percentage nil :title "Building"))

server-notification Mon Mar 16 11:49:31 2020:
(:jsonrpc "2.0" :method "window/progress" :params
	  (:done nil :id "progress_0" :message nil :percentage nil :title "Indexing"))

server-notification Mon Mar 16 11:49:31 2020:
(:jsonrpc "2.0" :method "window/progress" :params
	  (:done t :id "progress_0" :message nil :percentage nil :title "Indexing"))

client-request (id:2) Mon Mar 16 11:49:31 2020:
(:jsonrpc "2.0" :id 2 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///home/andreyorst/Git/grscheme/src/main.rs")
	   :position
	   (:line 7 :character 0)))

client-request (id:3) Mon Mar 16 11:49:31 2020:
(:jsonrpc "2.0" :id 3 :method "textDocument/documentHighlight" :params
	  (:textDocument
	   (:uri "file:///home/andreyorst/Git/grscheme/src/main.rs")
	   :position
	   (:line 7 :character 0)))

server-reply (id:2) Mon Mar 16 11:49:32 2020:
(:jsonrpc "2.0" :id 2 :result
	  (:contents
	   []
	   :range
	   (:start
	    (:line 7 :character 0)
	    :end
	    (:line 7 :character 0))))

server-reply (id:3) Mon Mar 16 11:49:32 2020:
(:jsonrpc "2.0" :id 3 :result
	  [])

client-request (id:4) Mon Mar 16 11:50:10 2020:
(:jsonrpc "2.0" :id 4 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///home/andreyorst/Git/grscheme/src/main.rs")
	   :position
	   (:line 7 :character 1)))

client-request (id:5) Mon Mar 16 11:50:10 2020:
(:jsonrpc "2.0" :id 5 :method "textDocument/documentHighlight" :params
	  (:textDocument
	   (:uri "file:///home/andreyorst/Git/grscheme/src/main.rs")
	   :position
	   (:line 7 :character 1)))

server-reply (id:4) Mon Mar 16 11:50:10 2020:
(:jsonrpc "2.0" :id 4 :result
	  (:contents
	   []
	   :range
	   (:start
	    (:line 7 :character 1)
	    :end
	    (:line 7 :character 1))))

server-reply (id:5) Mon Mar 16 11:50:10 2020:
(:jsonrpc "2.0" :id 5 :result
	  [])
```

</details>

`eglot-stderr-buffer` buffer is empty.

> I don't care if other clients have special rules for RLS, Eglot won't. (it has enough for more difficult matters). Again: Emacs, Eldoc Box and RLS are the places to fix this.

Perhaps this should be reported to RLS, but given that this doesn't happen in any other client, I slightly suspect that perhaps just maybe there is a tiny possibility of a small chance that there is actually a bug in this particular client. If it's not the case, I'm going to report this to RLS.

**Comment by andreyorst** [comment]
Also. Launching RLS in command line `rls --cli` and executing `hover file line col` command I see, that for lines that do have hover info the ouput is this:
```
> hover src/main.rs 6 12
2: Hover {
    contents: Array(
        [
            LanguageString(
                LanguageString {
                    language: "rust",
                    value: "pub fn run() -> Result<(), u32>",
                },
            ),
        ],
    ),
    range: Some(
        Range {
            start: Position {
                line: 6,
                character: 12,
            },
            end: Position {
                line: 6,
                character: 15,
            },
        },
    ),
}
```

And for lines with no info, output is:
```
> hover src/main.rs 8 1
3: Hover {
    contents: Array(
        [],
    ),
    range: Some(
        Range {
            start: Position {
                line: 8,
                character: 0,
            },
            end: Position {
                line: 8,
                character: 1,
            },
        },
    ),
}
```

With empty array, which makes sense. Maybe `eglot` interpreters this response in a wrong way?

**Comment by joaotavora** [comment]
> If it's not the case, I'm going to report this to RLS.

Good idea.  But to know if it's the case or not, we need to examine your bug report, for which we are very thankful, but don't have time just right now.

**Comment by nemethf** [comment]
The immediate fix is simple:
```diff
diff --git a/eglot.el b/eglot.el
index 8d1d2d7..fe06e0c 100644
--- a/eglot.el
+++ b/eglot.el
@@ -2296,7 +2296,7 @@ potentially rename EGLOT's help buffer."
          :success-fn (eglot--lambda ((Hover) contents range)
                        (unless sig-showing
                          (when-buffer-window
-                          (when-let (info (and contents
+                          (when-let (info (and (not (seq-empty-p contents))
                                                (eglot--hover-info contents
                                                                   range)))
                             (eglot--update-doc info thing-at-point)))))
```
It just copies a similar check from `eglot-help-at-point`.  However, this will leave the previous hover info in eldoc, which I think is not very useful.  On the other hand, the `*eglot-help*` always remains visible (if I remember correctly), and I don't like that either, but I assume others do.   So I don't know what's the intended UI here, and therefore I cannot give a proper fix.  Nevertheless,  @andreyorst, please, try the patch out and report back.

**Comment by joaotavora** [comment]
@nemethf fix looks good except for `not seq-empty-p`.  Use `(zerop (length contents))`. I'd rather not introduce `seq-` vocabulary if I can.

**Comment by joaotavora** [comment]
> So I don't know what's the intended UI here,

Neither do I :-), but whatever happens, it's also what happens to other servers who don't reply to the hover request, right?

>  and therefore I cannot give a proper fix.

Your fix is decent enough.  You can push it, especially if @andreyorst reports that it works for him.

**Comment by nemethf** [comment]
>  fix looks good except for `not seq-empty-p`. Use `(zerop (length contents))`. I'd rather not introduce `seq-` vocabulary if I can.

But `eglot-help-at-point` already has the very same `(seq-empty-p contents)` check.  And there are two `seq-group-by` calls in `eglot-imenu`.

**Comment by joaotavora** [comment]
> But eglot-help-at-point already has the very same (seq-empty-p contents) check. And there are two seq-group-by calls in eglot-imenu.

Then never mind :man_facepalming:

**Comment by andreyorst** [comment]
>  However, this will leave the previous hover info in eldoc, which I think is not very useful

I guess you've been talking about this instance of not updated documentation:

![image](https://user-images.githubusercontent.com/19470159/76794427-0c966080-67d8-11ea-976e-b72292c2c2b4.png)
(cursor is on the `}`)

I also think that this is not quite useful and can lead to confusion. Perhaps it should be cleared?

**Comment by nemethf** [comment]
I pushed this fix to the master.  However, it seems the automatic checks haven't run for some reason.  

I think "not clearing the hover info automatically" is a different (and already existing) problem.  Can you, @andreyorst, please, open a new issue for it.  Thanks.

**Comment by andreyorst** [comment]
thanks for the fix!

**Comment by nemethf** [comment]
> I think "not clearing the hover info automatically" is a different (and already existing) problem. Can you, @andreyorst, please, open a new issue for it. Thanks.

There's already an issue about this: #380.
