### ISSUE TITLE
 "No such file or directory" "pyls"

### ISSUE THREAD

**Issue by michael-angelozzi** [joaotavora/eglot#426]
What is the way to work with various python environments. I activate my venv, started emacs, but it still can't find pyls (done as follows):

```
michael@m2800:~/project$ source venv/bin/activate
(venv) michael@m2800:~/project$ python
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyls
>>> dir(pyls)
['IS_WIN', 'PYLS', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_version', 'hookimpl', 'hookspec', 'os', 'pluggy', 'sys']
>>> 
[9]+  Stopped                 python
(venv) michael@m2800:~/project$ emacs -Q
```
Then run these commands
```
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
```

`M-x` `package-install` RET `eglot` RET
open a python file
`Mx` `eglot`

```
[eglot] I guess you want to run `pyls', but I can't find `pyls' in PATH!
Enter program to execute (or <host>:<port>): pyls
```

**Comment by nemethf** [comment]
Until someone proposes a proper solution you can start pyls from the commandline as `pyls --tcp -v` and start eglot with `C-u M-x eglot RET 127.0.0.0:2087 RET`

**Comment by joaotavora** [comment]
@michael-angelozzi This problem isn't specific to Eglot.  _Any_ Emacs development exercise where you expect to call a Python binary (it may be `pyls` or something else like the `python` program interpreter itself) can run into these problems and that's because, by default,  Emacs doesn't know  that you ran `source venv/bin/activate` in a particular project.

There are some third-party Emacs packages that fix this (look [here](https://emacs.stackexchange.com/questions/13489/how-do-i-get-emacs-to-recognize-my-python-3-virtual-environment) maybe), or you could try `C-u M-x eglot` and point Eglot to the correct path.

So it's not really an Eglot problem. So, unless you demosntrate otherwise, I'm closing this. We can continue discussion, regardless.

**Comment by michael-angelozzi** [comment]
Thanks for the tips @nemethf and @joaotavora 
I didn't understand how Language servers work. The issue occurred  when I was installing pyls with pip; I used `--system-site-packages` with `venv` (pyls installed in the default installation, so it can be shared across projects), and my `$PATH` for some unknown reason does not include the original system site packages path `~/.local/bin`. After activating the venv, and then loading emacs from that shell, it can find pyls (and conversely if I dont activate the venv, then it can't find it) as expected.

**Comment by joaotavora** [comment]
> then loading emacs from that shell

Yes, this works, but it's kind of silly to have to run and shutdown an emacs for every project/environment.

So I encourage you to do try one of those alternatives I linked to.  And you can post back the results here of the one that worked best for you, and help fellow Pythonistas.

**Comment by michael-angelozzi** [comment]
I generally work on one large project so its no problem for me. The links (and my googling) are for `virtualenv`, whereas I use the default `venv` that comes with python3. Still trying to figure out a way to source the activate scripts from emacs.
pyvenv doesn't support venv (just tried and confirmed by https://github.com/jorgenschaefer/pyvenv/issues/86)

**Comment by joaotavora** [comment]
> The links (and my googling) are for virtualenv, whereas I use the default venv that comes with python3. Still trying to figure out a way to source the activate scripts from emacs.
pyvenv doesn't support venv 

Pity, I'd favour `venv` too.  Well maybe we'll just have to write the thing ourselves...

How does  it work, i.e. do you know how run python commands to query the current directory as to what project is loaded, where are libraries and executables?

**Comment by falloutphil** [comment]
I prefer venv too as it's core python, but see my comment on https://github.com/jorgenschaefer/pyvenv/issues/86 - I think this should be supported as of Sept 2019.  Do people disagree?

**Comment by orontee** [comment]
May this help others. 

I use the `venv` module from the standard library, and install `python-lsp-server` in the virtual environment.

Finally:
```
(defun my-eglot-python-server-program (&optional interactive project)
  (cond
   (python-shell-virtualenv-root
    `(,(expand-file-name "bin/pylsp" python-shell-virtualenv-root)))
   (t '("pylsp"))))

(add-to-list 'eglot-server-programs
	     '((python-mode python-ts-mode) .
	       my-eglot-python-server-program))
```
