### ISSUE TITLE
Python: Show method/function signature next to list company-mode popup menu

### ISSUE THREAD

**Issue by michael-angelozzi** [joaotavora/eglot#428]
When using pyls with all the extensions, when the company-mode menu pops up its show a list of possible methods, many types of autocomplete providers also show detail about the currently selected autocomplete recommendation, but none are shown for me with python. 

I have tried to google images or youtube videos of what I should be seeing when using pyls, but could not find anything. I see the [animated gif for completion](https://github.com/joaotavora/eglot#completion) shows function signature info (for C++). Is there any way to get similar info for python?

**Comment by nemethf** [comment]
pyls does return some info that eglot relays to company.  See, for example, this image: ![pyls-bess](https://raw.githubusercontent.com/nemethf/pyls-bess/master/resources/bess-auto-complete-bess.png)

If you want more, [company-quickhelp](https://github.com/company-mode/company-quickhelp) might work for you.  (I have tried to use it.)

**Comment by joaotavora** [comment]
I suppose this is resolved?  @michael-angelozzi let me know if it is not.

**Comment by michael-angelozzi** [comment]
I never managed to get that extra info e.g. `pybess.bess.BESS` above. I did try company-quickhelp thanks, but I couldn't get the results I had hoped, and eventually switched from eglot, but its a great project. Cheers!

**Comment by joaotavora** [comment]
Are you still using "pyls with all the extensions"?
