### ISSUE TITLE
How to import go projects?

### ISSUE THREAD

**Issue by 404cn** [joaotavora/eglot#429]
> [eglot] Server reports (type=2): You neither in a module nor in your GOPATH. Please see https://github.com/golang/go/wikiModules for information on how to set up your Go project.

But I already init go mod in my project's root folder.

When I use lsp-mode it will ask whether if import project and it works well (just too slow).

So how to import go project in eglot?

**Comment by nemethf** [comment]
Can you, please, follow the instructions of https://github.com/joaotavora/eglot#reporting-bugs 

There's not enough detail in this bug report.  I don't program in go, but most probably you haven't defined your project correctly.  Reading the documentation of project.el might help you.

**Comment by joaotavora** [comment]
Yup, this needs more information. @ilohmar  I'm sorry to bother, but didn't you use Gopls with Eglot? Any idea what's happening to @404cn?

**Comment by joaotavora** [comment]
Just a note: I'll reopen if/when more info comes in.

**Comment by ilohmar** [comment]
No worries, I'm actually sorry that I haven't managed to get some stuff on eglot done lately :)

Yes, I use eglot w/ gopls, and I ran across that warning when I updated to 0.4.0.  I don't recall the exact circumstances, but I think that it was some temporary issue.  Unfortunately, as is all too common with the LSP, information tends to be buried in VS-Code issues and posts that I don't care about..  and uses VS-Code-specific (IIUC) "solutions" like "open the directory" containing the go.mod file.

@404cn Could you show the tree of directories and files of your Go project, and which file you are opening?  I do not get your problem when I am working in a Go module with a proper go.mod file, or when following a reference to a dependency or to the standard library.
