### ISSUE TITLE
Add support for cross file symbol rename with clangd

### ISSUE THREAD

**Issue by wailo** [joaotavora/eglot#431]
**Current behaviour:**
In a C++ project, `eglot-rename` fails due to clangd server limitation prior to version 10. Here is an output log:
`I[13:12:47.984] <-- textDocument/rename(23)
I[13:12:47.984] --> reply:textDocument/rename(23) 0 ms, error: Cannot rename symbol: the symbol is used outside main file`

**Desired behaviour**
Add support for renaming symbols. As per this link: https://clangd.llvm.org/features.html#rename clangd now supports cross file renaming. using `cross-file-rename`. flag

**Comment by nemethf** [comment]
Currently, Eglot does not start clangd for c++ projects.  So, most probably you should change your own customization to add the desired flag.  Post it here if you have problems with it.

**Comment by wailo** [comment]
My emacs configuration:
` (add-to-list 'eglot-server-programs '((c++-mode c-mode) "clangd"))`
So whenever I open a c++ file, eglot starts clangd.

But I am pointing at the rename functionality, which fails when used with clangd.

**Comment by nemethf** [comment]
The documentation you referenced says that the feature is available if clangd is stared with an additional command line flag.  Your configuration does not set that flag.

**Comment by wailo** [comment]
> it is enabled with the command-line flag -cross-file-rename.
I think I misunderstood this sentence.
Starting the server with `(add-to-list 'eglot-server-programs '((c++-mode c-mode) "clangd" "-cross-file-rename")` worked for me.
Closing this issue, thanks for your help
