### ISSUE TITLE
nil results field of workspace/configuration response crashes Julia language server

### ISSUE THREAD

**Issue by non-Jedi** [joaotavora/eglot#432]
Julia's language server crashes when sent a nil results field in a response to a `workspace/configuration` request. I have personally not seen this behavior, but @vvpisarev has:

https://github.com/non-Jedi/eglot-jl/issues/3#issuecomment-613044263

By my reading of [the specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_configuration), the results field should always be a list/collection/array even if empty.

Events and stderr: https://gist.github.com/vvpisarev/293c5ff793fbe84ea396c1d38edea3c2

EDIT: just noticed this is similar to #340 which I also submitted. In this case though, result field is nil despite no error being present.

**Comment by nemethf** [comment]
Can you investigate why [you had success with this in the past](https://github.com/joaotavora/eglot/issues/340#issuecomment-550297478) and now you haven't?  Git-bisect would probably be a good approach.  Thanks.

**Comment by non-Jedi** [comment]
I can't replicate the error on my machine. I don't think @vvpisarev has ever gotten it to work.

**Comment by non-Jedi** [comment]
Just noticed that @vvpisarev is using eglot 1.5 which doesn't include 5de7c55. This issue is likely fixed on master.
