### ISSUE TITLE
travis: PR is being built but result is not shown in github

### ISSUE THREAD

**Issue by nemethf** [joaotavora/eglot#434]
I know it's not a big deal as I can read the results at https://travis-ci.org/github/joaotavora/eglot.
Anyway, these links might help you if you want to fix this:

https://travis-ci.community/t/github-pr-is-being-built-but-result-is-not-shown/7025
https://travis-ci.community/t/travis-ci-build-no-longer-showing-as-check-on-github-pull-request-page/6955

**Comment by joaotavora** [comment]
Thanks. I don't have time to read that.  If I give you administrative right over this repo, do you think you could fix it?

**Comment by nemethf** [comment]
I can give it a try.  But what you have just done is not enough.  Travis says I have "insufficient permission" to tweak the settings of Eglot.

**Comment by joaotavora** [comment]
yeah, I messed it up.

**Comment by joaotavora** [comment]
I don't even know if it's possible.  I seem to have done that for yasnippet some years ago.

**Comment by nemethf** [comment]
Don't worry.  It's really just a convenience feature.  Now that I know where to look for the results, I can live with the current situation.

**Comment by joaotavora** [comment]
I'll have a look at those links later on, maybe it's simple to do.

**Comment by nemethf** [comment]
I close this as your procrastinating strategy worked.  The results are shown next to the new pull requests and commits.

**Comment by joaotavora** [comment]
Hehe, but I didn't procrastinate, I followed your links and did some stuff, jsut forgot to comment here, thanks.
