### ISSUE TITLE
Eglot xref backend returns plain xrefs, not match xrefs

### ISSUE THREAD

**Issue by tmurph** [joaotavora/eglot#436]
Maybe this should be a feature request, not a bug report?  Either way, I hope it's easy enough.

The xref library defines a special kind of xref called a "match xref" (created with `xref-make-match`) that corresponds to search results.  Match xrefs support all the same things that plain xrefs do, plus they allow users to do query-replace-regexp from an xref buffer.

Eglot's xref support returns plain xrefs even when it could return match xrefs.  I've opened #435 to return match xrefs instead.

**Comment by joaotavora** [comment]
> Maybe this should be a feature request, not a bug report?

Can be both, but since you opened the PR. Lets close this and follow up there.
