### ISSUE TITLE
scroll-other-window for eglot--help-buffer

### ISSUE THREAD

**Issue by nemethf** [joaotavora/eglot#445]
I have a python file with `import sys` and `eglot-put-doc-in-help-buffer` is set to `t`.  I put the point on "sys", wait for the help to arrive from the lsp server, then `(switch-to-buffer-other-window "*eglot-help for sys*")`, and return to the python buffer with `other-window`.  Now if I `C-M-v` (scroll-other-window) the help buffer shows the second page of the help, but Eglot re-requests the help from the server and after one second the point jumps to point-min in the eglot--help-buffer.

I think C-M-v shouldn't trigger textDocument/hover one more time and the point shouldn't be moved back to the beginning of the help buffer.

**Comment by joaotavora** [comment]
Indeed I see the problem.  I'm going to say it's Emacs's fault, and I think it is, but the truth is that in #443 we see that Eglot (and others) are abusing a very limited eldoc API.  So maybe this fixes it, can you test?
```

**Comment by muffinmad** [comment]
@nemethf This issue can be avoided by setting `eglot-put-doc-in-help-buffer` to `nil` and using `M-x eglot-help-at-point`. This workflow will work if you don't need to content of the `eglot-help` buffer to follow point.

**Comment by nemethf** [comment]
@joaotavora: Yes, it indeed fixes the problem.  

I wonder whether it's possible to get different `string`s for the same `hint`, for example, by searching the buffer for a symbol and having different localized help strings.  In this case, Eglot would always show the help of the first symbol.  Or would it?

@muffinmad, thank you. That's a good way to circumvent the issue.

**Comment by nemethf** [comment]
I'm experimenting with the new eldoc elpa package and I think this issue reappeared.  If I set `eldoc-prefer-doc-buffer` to t  instead of `eglot-put-doc-in-help-buffer` to t and repeat the steps detailed of the original report, the buggy behavior returns: the point jumps to the top in the *eldoc* buffer after a C-M-v.

(Additionally, this is not an Eglot issue, but if I set `eldoc-perfer-doc-buffer` to t and the *eldoc* buffer is visible, then the echo area should never show eldoc messages, right?  At least that's how I understand the docstring of `eldoc-perfer-doc-buffer`.  But I see docstrings in the echo area in this case.  So is this a bug in eldoc?)

**Comment by joaotavora** [comment]
> Additionally, this is not an Eglot issue, but if I set eldoc-perfer-doc-buffer to t and the eldoc buffer is visible, then the echo area should never show eldoc messages, right? At least that's how I understand the docstring of eldoc-perfer-doc-buffer. But I see docstrings in the echo area in this case. So is this a bug in eldoc?

Very likely it is a bug.  I'm out of time again now. But I encourage you to open an Emacs bug report and to propose fixes to `eldoc.el` directly.  You can even propose a mock PR on https://github.com/emacs-mirror/emacs/pull, if  you want to discuss it in github.

My idea was to have Eglot moved to Emacs by now (and for you all to become Emacs contributors) but I wasted most of my time budget in silly sparring discussions (fortunately over), so I'll have to wait some weeks.

**Comment by joaotavora** [comment]
Following up here https://debbugs.gnu.org/cgi/bugreport.cgi?bug=42421.  I have a patch there, check it out.
