### ISSUE TITLE
host-and-port contact spec fails

### ISSUE THREAD

**Issue by dandavison** [joaotavora/eglot#447]
The documentation states:

```
* A list (HOST PORT [TCP-ARGS...]) where HOST is a string and PORT is
  na positive integer number for connecting to a server via TCP.
```
however `("localhost" 7777)` fails with `(wrong-type-argument stringp 7777)`.

I've added unit tests that demonstrate this in #446 (but have not added a fix yet).

**Comment by joaotavora** [comment]
OK, well let's make that PR a two parter (two commits): Add tests and fix this problem.  

Oh and also I see a typo in the docstring.  That can be a third commit.  So closing this one and let's handle this in #446, OK?
