### ISSUE TITLE
Double completions when function is declared and defined

### ISSUE THREAD

**Issue by gcohara** [joaotavora/eglot#455]
Hi,

Firstly, thanks for writing this addon, I've found it simple to set up and use.
However, when using completions (in C code, and with a `clangd` backend), I am seeing some functions appear twice:

![pic](https://i.imgur.com/hoIAfxL.png)

This happens with functions which are declared in a header file, and then have been defined in a source file.
I'm guessing what's happening is that the functions are being counted twice, since I've also defined them.
Is there a way around this?
(Apologies for not including the events log, but there's absolutely loads of it, and I'm not sure which bits are relevant!)

**Comment by muffinmad** [comment]
Hi @gcohara !

The relevant parts of the log are the client `textDocument/completion` request and server response. The looks like this:

```
client-request (id:6) Wed May  6 23:44:12 2020:
(:jsonrpc "2.0" :id 6 :method "textDocument/completion" :params
...

server-reply (id:6) Wed May  6 23:44:13 2020:
(:id 6 :jsonrpc "2.0" :result
...
```

You may find them in the `*EGLOT events*` buffer near the bottom right after completions are shown.

If you see duplicate completions in the server response then try to ask in `clangd` bug tracker.

**Comment by gcohara** [comment]
Hi Andrii!

Thanks for your response. I can confirm that the server is sending duplicate responses, so I'll try and chase it up with `clangd`.

Thanks for your help!
