### ISSUE TITLE
How to temporarily silence flymake?

### ISSUE THREAD

**Issue by dandavison** [joaotavora/eglot#468]
Often when working with eglot I want to temporarily silence flymake. For example, when a section of Rust code is failing to compile, I need a few minutes to work on it without it being covered in squiggly lines.

I've had two thoughts so far:

1. I've tried issuing `M-x flymake-mode` to disable. This does make the flymake annotations disappear initially. However, although the mode-line lighter reports that flymake is not active, they start appearing again after a short while (with no flymake mode line lighter).  

2. I've tried using `M-x eglot-shutdown`. However, if there are already flymake errors in the buffer, then they are not removed.

So the only way I've discovered so far is to do `M-x eglot-shutdown` followed by `M-x flymake-mode`. I can do that, but I'd like to ask: what is the recommended way to tell eglot that I temporarily need a break? (I'm asking that question specifically for flymake here, but a similar question could be asked for other eglot activity such as eldoc minibuffer content.)

**Comment by muffinmad** [comment]
> I need a few minutes to work on it without it being covered in squiggly lines.

Another option: disable `Underline` for `flymake-error` face or at least make it less distracting.

**Comment by dandavison** [comment]
Thanks @muffinmad.

I do think that, if there's not a convenient way already, then we should add to eglot a convenient way to enter a sort of "focus" or "yes yes I'm fixing it" mode, with no flymake distractions. (This would align with one of eglot's stated aims: to be a "LSP client that stays out of your way").

A related issue is that I believe that `eglot-shutdown` (and `(eglot--managed-mode -1)`) should remove the flymake overlays that eglot is responsible for. I need to look into it a bit more, but it looks like it is possible for eglot to identify the subset of flymake overlays that were created due to eglot activities.

**Comment by joaotavora** [comment]
M-x flymake should do what you want @dandavison.  If it doesn't it's a bug. Probably in flymake.

**Comment by joaotavora** [comment]
So let's not complicate Eglot with new things that should be reliased by other packages.

**Comment by dandavison** [comment]
> M-x flymake should do what you want @dandavison. If it doesn't it's a bug. Probably in flymake.

Thanks @joaotavora you're right, for some reason I was assuming the persistence of the flymake annotations was deliberate behavior on eglot's part. I believe #472 fixes the bug.
