### ISSUE TITLE
Select which language server to used based on more than just the major mode

### ISSUE THREAD

**Issue by proofit404** [joaotavora/eglot#47]
HI,

I use `web-mode` both for `html` and `vue` files. 

There are two different language servers for each file format.

* https://github.com/vscode-langservers/vscode-html-languageserver-bin
* https://github.com/vuejs/vetur/tree/master/server

Is there a way to configure `eglot-server-programs` based on the engine of the `web-mode` buffer?

It may be useful for other languages too.

Regards, Artem.

**Comment by joaotavora** [comment]
> Is there a way to configure eglot-server-programs based on the engine of the web-mode buffer?

No, not currently. 

Currently the solution is to make a trivial new major-mode for each type, so

```
(define-derived-mode vue-mode web-mode "Vue")
```

And nothing else. Then set your `vue` files to `vue-mode` and configure an entry in `eglot-server-programs`.

This may or not work for you.  If it doesn't you'll just have to wait until I or someone can come up with a good way of augmenting `eglot-server-programs` even more to allow it.

I'm also looking for ways to have more than one server manage a buffer, but that's another feature.

**Comment by proofit404** [comment]
Hi,

In addition to the troubles described above, I found the new one. If I understand correctly, mode comparison is done by the derived property.

If I add this to my config file:

```lisp
(add-hook 'typescript-mode-hook 'eglot-ensure)

(add-to-list 'eglot-server-programs
             '(typescript-mode . ("javascript-typescript-stdio")))
```

my js2-mode buffers start showing me errors (flymake) related to the typescript language.

Any ideas why this can happen?

**Comment by MaskRay** [comment]
It will be useful when e.g. there are HTML,CSS,JavaScript files in a project.

**Comment by dustinpaluch** [comment]
Isn't this possible since https://github.com/joaotavora/eglot/commit/2355e171328d09628629cc990894efa014019874 with a custom function for CONTACT that determines which server to use?

**Comment by joaotavora** [comment]
Yeah, you're right. Maybe I should look into closing this.

**Comment by joaotavora** [comment]
Closing this.  As noted before, this is already possible in `eglot-server-programs`.
