### ISSUE TITLE
The behaviour of "M-x eglot RET" has been changed

### ISSUE THREAD

**Issue by nemethf** [joaotavora/eglot#474]
When the predefined program for a given major mode is not found, "M-x eglot RET" now shows an error and that's all.  It used to say: "Can't guess mode to manage for ..."  and then offered a prompt to enter the connection details.  I think the current situation is less useful than the old one.

I'm guessing commit 9bc58df7 by @dandavison changed this.   Dan, was this change intentional?

(I have an additional, independent, and not so important question: why there's a copyright-paperwork-exempt line in Dan's recent commit of da7ff48?)

**Comment by dandavison** [comment]
Hi @nemethf, thanks for pointing this out. My PR did not intentionally change this behaviour. I can confirm that reverting 9bc58df7add8ad36e95a758d25854732ffe9098a does bring back the previous behaviour, so I think you're right that it is responsible. I can look into the best course of action. For the record, 9bc58df7add8ad36e95a758d25854732ffe9098a did fix a bug in eglot -- support for `(host, port)` connection specifications was broken, as demonstrated by the new unit tests.

> why there's a copyright-paperwork-exempt line in Dan's recent commit of da7ff48?

That was added by @joaotavora (I don't have any complaints here, happy for project bureaucratic aspects to be managed as necessary!).

```
$ eglot(master) git log --author=dandavison7 --format='%H %ae %ce'
da7ff4883d3108468265fdc16a217d8e6aff92f2 dandavison7@gmail.com noreply@github.com
9bc58df7add8ad36e95a758d25854732ffe9098a dandavison7@gmail.com joaotavora@gmail.com
b6519a5c1ba965bbb3b2853318b28da5e5faa811 dandavison7@gmail.com joaotavora@gmail.com
f7a7e33c1e846cb09d93ff63cf2dafa398410d8f dandavison7@gmail.com joaotavora@gmail.com
```

**Comment by joaotavora** [comment]
Dan Davison <notifications@github.com> writes:

> Hi @nemethf, thanks for pointing this out. My PR did not intentionally
> change this behaviour. I can confirm that reverting 9bc58df does bring
> back the previous behaviour, so I think you're right that it is
> responsible. I can look into the best course of action. For the
> record, 9bc58df did fix a bug in eglot -- support for (host, port)
> connection specifications was broken, as demonstrated by the new unit
> tests.

I think the best way now is to first add a test for the behaviour that
Felicián is missing, then fix it.

>  why there's a copyright-paperwork-exempt line in Dan's recent commit of da7ff48?
>
> That was added by @joaotavora (I don't have any complaints here, happy
> for project bureaucratic aspects to be managed as necessary!).

Indeed, I added that.  The change was trivial, and therefore it is
exempt of copyright.  However, I notice now that Dan has more changes
(I'm sorry but I didn't keep track or the correlation).

So Dan, can you confirm, if you have not done so already, that you have
a signed copyright assignment to the FSF?

João

**Comment by dandavison** [comment]
Hi João, we briefly discussed that [here](https://github.com/joaotavora/eglot/pull/446#issuecomment-622934792). I contributed to Emacs for a while about 10 years ago, and therefore had FSF copyright assignment at that time. I'm happy to get in contact with them again if needed.
