### ISSUE TITLE
How to know which server is in use?

### ISSUE THREAD

**Issue by garyo** [joaotavora/eglot#476]
As I'm setting up my eglot config, how can I check which server eglot chose for the current buffer? The events buffer doesn't have the server cmd line, nor does the *Messages* buffer. There's probably an eglot variable or function but I don't see it.

**Comment by dandavison** [comment]
Hi @garyo I also opened a similar issue: #465 . (Possibly it'll be simplest to treat this one as a dup.)

**Comment by joaotavora** [comment]
Yes, the two issues could be merged, but it is actually a slightly different request I think.  The events buffer _should_ have the command line.

**Comment by garyo** [comment]
I agree, even if the server shows some "info" it's best to record the actual command line somewhere for debugging. Thanks!

**Comment by skangas** [comment]
How does the above patch look?
