### ISSUE TITLE
Turn off message in new buffer

### ISSUE THREAD

**Issue by brotzeit** [joaotavora/eglot#48]
Every time I open a new file in a project with eglot running I get this message. Is there an option to disable it ?
```
`[eglot]` Automatically started `rustfmt' to manage `rustic-mode' buffers in project `rustfmt'
```

**Comment by joaotavora** [comment]
There are two problems here:
* First the message has a bug.  It should state the server name, and not the project nickname in the first space.
* Also, you seem to have `eglot-ensure` in your `rustic-mode-hook` That's fine (as long as you have it only in that hook and nowhere else, so please confirm this bit).  However, that particular message shouldn't be displayed if you open a file in the same project.  This is the message that should be displayed:

```
<buffer-name> is already managed by existing `rustfmt'
```

So now two more points:

1. Are you sure that isn't the message that you're seeing repeatedly and would like to hide?
2. If you answered yes to 1 and you *are* seeing the "Automatically started..." thing, then we have a more serious bug. To analyse that, I need you to try to reproduce the problem with a minimal emacs+eglot+rustic configuration and post the detailed steps here, without omitting anything.

**Comment by brotzeit** [comment]
1. I copied the message from the log
2. I just open emacs with the config below and open a file in a git repo.

Complete config:

```(setq package-archives '(("melpa" . "http://melpa.org/packages/")))

(require 'package)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package rustic :ensure t :pin melpa)
(use-package eglot :ensure t :pin melpa)
(setq rustic-rls-pkg 'eglot)
```

I realized that rustfmt is the project name. I've tried this in the rls git repo and and now the message contains rls.

But in the rls repo I also get an error:
 `[eglot] Server reports (type=1): Cargo failed: Error compiling dependent crate[eglot] Server reports (type=1): Cargo failed: Error compiling dependent crate`

**Comment by joaotavora** [comment]
@brotzeit,

Thanks.  So I tried your config and didn't spot the second more serious problem, which is good. Everything works as intended.

When I open a file on a previously untouched Rust project, I first get the message
```
[eglot] Automatically started `EGLOT (guessing_game/rustic-mode)' to manage `rustic-mode' buffers in project `guessing_game'
```
The, after each new opened file in that project I get the second message

```
[eglot] Buffer is already managed by existing `guessing_game'
[eglot] Buffer is already managed by existing `guessing_game'
[eglot] Buffer is already managed by existing `guessing_game'
[eglot] Buffer is already managed by existing `guessing_game'
...
```

I asked you this before: it is the _second_ repeating message that you want to get rid of. Not the first, right?

PS: the RLS problem doesn't seem to have anything to do with Eglot, which is just forwarding you the error message.

**Comment by brotzeit** [comment]
> I asked you this before: it is the second repeating message that you want to get rid of. Not the first, right?

I'm not sure about this. I think I only want to be informed if it doesn't work as expected. If I can see in the mode line that a server is running, I don't need an additional message. What do you think ?

> PS: the RLS problem doesn't seem to have anything to do with Eglot, which is just forwarding you the error message.

I know. I just wanted to mention it for completeness.

**Comment by joaotavora** [comment]
> What do you think ?

I fully agree. But you still haven't confirmed exactly _what_ message you are repeatedly seeing for which new file you open.  That's the question I've asked twice.  I suppose its _not_ the one you originally mention, but the other one I presented. Please confirm this.

**Comment by brotzeit** [comment]
Sorry, it's the second line.

```
[eglot] Buffer is already managed by existing `guessing_game'
```

**Comment by brotzeit** [comment]
I copied the wrong message in the first post...

**Comment by joaotavora** [comment]
> I copied the wrong message in the first post...

Yeah, I figured.  But I still had to make sure, because if you hadn't it would be an indication of a much more serious problem.  This is why I insisted so much with an analysis and reproduction recipe.

Anyway, I think I fixed the problem for you.

**Comment by brotzeit** [comment]
Thanks.
