### ISSUE TITLE
Eglot still ignores eldoc-echo-area-use-multiline-p

### ISSUE THREAD

**Issue by j-cr** [joaotavora/eglot#485]
Reporting this since #443 is closed and I couldn't find any open issues tracking this.

------------

Consider an example help string, obtained by `eglot-help-at-point`:

```rust
new: pub fn new(x: i32, y: i32) -> Point
Creates a new point from the given coordinates.
```

Given config:
```emacs-lisp
(setq max-mini-window-height 1
      eldoc-echo-area-use-multiline-p nil
      eglot-put-doc-in-help-buffer 'eglot-doc-too-large-for-echo-area)
```

**Expected** eldoc output in the minibuffer is:
```rust
pub fn new(x: i32, y: i32) -> Point
```

**Actual** eldoc output in the minibuffer is:
```
Creates a new point from the given coordinates.
```

------------------

Moreover, if `max-mini-window-height` is greater than `1` I still expect to see the *same* result (namely, this single line: `pub fn new(x: i32, y: i32) -> Point`) as per documentation of `eldoc-echo-area-use-multiline-p`:
>If value is nil, messages are always truncated to fit in a single line of display in the echo area.

Instead, given the config:
```emacs-lisp
(setq max-mini-window-height 2
      eldoc-echo-area-use-multiline-p nil)
```

**Actual** eldoc output in the minibuffer spawns 2 lines, like this:
```
new: pub fn new(x: i32, y: i32) -> Point
Creates a new point from the given coordinates.
```

------------

As a side note, I find the variable `eglot-put-doc-in-help-buffer` to be rather confusing; I believe it is practical to handle `*eglot-help*` buffer and eldoc display as two completely separate, orthogonal features (as it is done e.g. in lisp-related modes).

**Comment by muffinmad** [comment]
I believe #459 will solve this issue.

According to @joaotavora 
> We can look at the implementation tomorrow

:-)

**Comment by muffinmad** [comment]
Oh, wait. Current implementation must work as you want with the `eldoc-echo-area-use-multiline-p` set to `nil`.

**Comment by j-cr** [comment]
> Current implementation must work as you want with the `eldoc-echo-area-use-multiline-p` set to `nil`.

Ah, damn. My bad: I've installed the stable version instead of the latest one. Confirming that `eldoc-echo-area-use-multiline-p` plus `eglot-put-doc-in-help-buffer` both set to `nil` produce the desired behavior (in regards to this particular issue). The problematic cases in the current master are non-nil values of `eldoc-echo-area-use-multiline-p` (displaying the last line of the help string, as described in your pull request) and non-nil values of `eglot-put-doc-in-help-buffer` (displaying effectively garbage in the echo area, though on purpose).

**Comment by joaotavora** [comment]
> We can look at the implementation tomorrow

I meant tomorrow in [Venusian days](https://www.universetoday.com/84663/which-planet-has-the-longest-day/amp/?PageSpeed=noscript) obviously :trollface:
