### ISSUE TITLE
Eldoc isn't displayed when point is moved via keyboard macros

### ISSUE THREAD

**Issue by j-cr** [joaotavora/eglot#486]
Context: I have a minor mode for modal editing, which uses keyboard macros to translate keypresses to other keypresses (e.g. `j` is translated to `M-j`). Point movement commands are bound to the translated keys (e.g. `M-j` is bound to `backward-char`).

Problem: eldoc messages in the echo area are not displayed after point is moved via keys bound to keyboard macros (e.g. when my minor mode is enabled and `j` is pressed the echo area remains empty even if the point is on a symbol with a help string).

Note that if instead of a key bound to a keyboard macro I use the translated key directly (e.g. if I press `M-j` instead of `j`) then eldoc is displayed correctly. It's also displayed correctly in other cases, e.g. when mouse-clicking on a symbol, etc.

Also note that the problem is specific to eglot; with other modes (e.g. emacs-lisp) eldoc works correctly.

Possibly somewhat related: #437 

-------------------------

How to reproduce:

```emacs-lisp
(global-set-key (kbd "M-j") 'backward-char)
(global-set-key (kbd "M-l") 'forward-char)
(global-set-key (kbd "M-i") 'previous-line)
(global-set-key (kbd "M-k") 'next-line)

(defvar my-modal-keymap (make-keymap))

(define-minor-mode my-modal-keys-mode
  "Provides single-key bindings for cursor movement."
  :init-value nil
  :global t
  :keymap my-modal-keymap)

(define-key my-modal-keymap "j" (kbd "M-j"))
(define-key my-modal-keymap "l" (kbd "M-l"))
(define-key my-modal-keymap "i" (kbd "M-i"))
(define-key my-modal-keymap "k" (kbd "M-k"))
```

Then: 
- open an eglot-handled buffer and put a point on a documented symbol 
- (eldoc should display help in the echo area)
- `C-u 1 M-x my-modal-keys-mode`
- move the point by pressing ijkl
- (the echo area clears and eldoc doesn't display anything)

**Comment by j-cr** [comment]
Hmm, wait a minute. This report is invalid too (it's too late, I should've gone to sleep, sigh).

Eldoc in other modes works just like this as well (no eldoc after keyboard macros), thus it's an eldoc quirk (possibly due to how eldoc-edit-message-commands works) and has nothing to do with eglot per se.

Eglot does, however, display flymake messages in the echo area even after a keyboard macro, but that's due to this little hack stolen from another issue:

```
(custom-set-variables
 '(help-at-pt-timer-delay 0.1)
 '(help-at-pt-display-when-idle '(flymake-diagnostic)))
```

Also (unlike in lisp-derived modes) eldoc help isn't displayed when the point is inside the parens in a function call, but that's another issue/feature request completely.

Sorry for the noise.

**Comment by joaotavora** [comment]
If you find stuff that you suspect should be fixed in Emacs, say in `eldoc` or `flymake` or `xref``, really don't hold back and report it to `bug-gnu-emacs@gnu.org` by either typing `M-x report-emacs-bug` or just sending mail to that address. Put _only_ that address in the bug report you make, but once you get the confirmation mail back (which should happen within seconds), you can reply to _that_  adding me as a CC or anyone else whose attention you want to call specifically.
