### ISSUE TITLE
Error in post-command-hook  (void-function project-root)

### ISSUE THREAD

**Issue by jiaxiyang** [joaotavora/eglot#491]
I have installed project.el and error still occurs.
Error in post-command-hook (#[0
"\303\304\301\242\305#\210\300\306!\205r\211q\210
?\205\307\310\311 \")\207" [#<buffer test.cc> (#0) eglot--managed-mode
remove-hook post-command-hook nil buffer-live-p apply eglot--connect
eglot--guess-contact] 4]): (void-function project-root)

Here is my configuration:
`(use-package eglot
  :defines (eglot-mode-map eglot-server-programs)
  :hook (((c-mode c++-mode) . eglot-ensure))
  :bind (:map eglot-mode-map
              ("C-c h" . eglot-help-at-point)
              ("C-c f r" . xref-find-references)
              ("C-c f d" . eglot-find-declaration ;; xref-find-definitions
               )
              ("C-c f D" . xref-find-definitions-other-window)
              ("C-c f t" . eglot-find-typeDefinition)
              ("C-c f i" . eglot-find-implementation)
              ("C-c =" . eglot-format-buffer)
              ("C-c c" . eglot-completion-at-point)
              ("C-c r" . eglot-rename)
              ("C-c a" . eglot-code-actions))
  :config
  (add-to-list 'eglot-server-programs '((c++-mode c-mode) "clangd"))
  )`

**Comment by jiaxiyang** [comment]
Here is the better format configuration:

(use-package eglot
  :defines (eglot-mode-map eglot-server-programs)
  :hook (((c-mode c++-mode) . eglot-ensure))
  :bind (:map eglot-mode-map
              ("C-c h" . eglot-help-at-point)
              ("C-c f r" . xref-find-references)
              ("C-c f d" . eglot-find-declaration ;; xref-find-definitions
               )
              ("C-c f D" . xref-find-definitions-other-window)
              ("C-c f t" . eglot-find-typeDefinition)
              ("C-c f i" . eglot-find-implementation)
              ("C-c =" . eglot-format-buffer)
              ("C-c c" . eglot-completion-at-point)
              ("C-c r" . eglot-rename)
              ("C-c a" . eglot-code-actions))
  :config
  (add-to-list 'eglot-server-programs '((c++-mode c-mode) "clangd"))
  )

**Comment by joaotavora** [comment]
You didn't say which `project.el` version you installed or how, but I will assume it is version 0.3.0 and you used `package-install`. Please try `M-x load-library RET project RET` or restart your Emacs.

**Comment by jiaxiyang** [comment]
Thanks for replying.
I can not choose project when I using `package-install`.
I installed the version 0.3.0 using `list-packages` and chose project 0.3.0. 

I tried `M-x load-library RET project RET`  and restart Emacs, the error still occurs.
What else could I try? Thanks a lot.

**Comment by joaotavora** [comment]
Can you try `M-x find-library RET project RET` and tell me what happens?  What file does this land you in?

**Comment by joaotavora** [comment]
Also, I have no idea what `use-package` does.  I know it's popular, but it's not officially supported.  Can you try moving your elpa dir to the side temporarily, starting an Emacs with the `-Q` flag, setting up MELPA (I assume you're installing from MELPA) and trying `M-x package-install RET eglot RET`?

**Comment by jiaxiyang** [comment]
Thanks joaotavora . I can use eglot now.

I followed https://github.com/wcy123/100ms_dot_emacs to use `straight.el` and `use-package` to build *.el to *.elc for speeding up Emacs. It will build project 0.1.3 by default. Though I install project 0.3.0. It still load 0.1.3 when I restart Emacs.  I use `load-library` to load 0.3.0  manually and then reload eglot. No error appears. I will change the configuration to use 0.3.0 by default.

**Comment by joaotavora** [comment]
Can you show me this file "project 0.1.3" ? I suspect this is a another case of #490

**Comment by jiaxiyang** [comment]
Here is the file:
[project-0.1.3.zip](https://github.com/joaotavora/eglot/files/4711125/project-0.1.3.zip)

**Comment by jiaxiyang** [comment]
I saw this line in elgot `;; Package-Requires: ((emacs "26.1") (jsonrpc "1.0.9") (flymake "1.0.8") (project "0.3.0") (xref "1.0.1") (eldoc "1.0.0"))`. It need project 0.3.0. While I install elgot with `use-package`. 0.1.3 is installed by default.

**Comment by joaotavora** [comment]
> Here is the file:  project-0.1.3.zip

Thanks.  I had a look. I was supposing it to be something else.

> I followed https://github.com/wcy123/100ms_dot_emacs to use straight.el and use-package to build *.el to *.elc for speeding up E
> While I install elgot with use-package. 0.1.3 is installed by default.

That's either a bug in `use-package`, or `straight.el` or in the special use you make of those packages in your configuration.  I'm trying to page @jwiegley and @raxod502 here, perhaps they can offer some advice.  Personally, I don't use these packages and I can only support the simple `package-install` use case.

**Comment by raxod502** [comment]
See https://github.com/joaotavora/eglot/issues/492#issuecomment-643622639.

**Comment by jiaxiyang** [comment]
> See [#492 (comment)](https://github.com/joaotavora/eglot/issues/492#issuecomment-643622639).

**Comment by jiaxiyang** [comment]
@raxod502 thanks a lot
