### ISSUE TITLE
How to jump back to function after finding definition with xref-find-definition?

### ISSUE THREAD

**Issue by jivanmukti** [joaotavora/eglot#495]
I can jump to the definition with xref-find-definition, but how do I go back to the function? Currently I'm switching buffers, but is there a function I can call?

**Comment by muffinmad** [comment]
See `xref-pop-marker-stack`

> `M-,` runs the command `xref-pop-marker-stack` (found in global-map),
which is an autoloaded interactive Lisp function in `xref.el`.

**Comment by muffinmad** [comment]
Also you can ask this question in the various Emacs communities or in the [help-gnu-emacs](https://lists.gnu.org/mailman/listinfo/help-gnu-emacs) mailing list.
