### ISSUE TITLE
Support for snippet based completion

### ISSUE THREAD

**Issue by amol-mandhane** [joaotavora/eglot#50]
LSP servers support snippet based completion which can insert template arguments of the functions while completion.

Example of snippet based completion:  https://i.stack.imgur.com/4gKHP.gif

The capability of snippet completion can be registered by setting TextDocumentClientCapabilities.completion.completionItem.snippetSupport to true, which is false by default.

Whether the completion item is plaintext or snippet is given by CompletionItem.kind field.

Yasnippet can be used to manage completion snippets.  The support can be conditionally enabled if user has yasnippet installed so that package doesn't have hard dependency on yasnippet.

**Comment by amol-mandhane** [comment]
I hacked together a short solution for this.  You can use the concept behind this and implement in eglot code convention.  Here's a screenshot of the diff.

![doumhs5apvp](https://user-images.githubusercontent.com/1002513/43292061-abe1cc06-90e8-11e8-80e5-5985996403ac.png)

**Comment by rgrinberg** [comment]
> Ideally, It should use snippet.el, not yasnippet.el, but I never finished that refactoring...

Curious, why is that? yasnippet is your package so you obviously know, but I've never even heard of snippet.el

**Comment by joaotavora** [comment]
@amol-mandhane, can you test the newest version?

**Comment by amol-mandhane** [comment]
There is a minor bug in the completion.  Created #82 for it.

**Comment by garyo** [comment]
I'm using vue mode with vue-language-server. I can't seem to trigger `completionItem/resolve` with eglot (I'm using the latest github head from yesterday, Oct 28, 2019). This issue says it should work, but I don't know how to make it happen. When I try the same server with lsp-mode, the server returns snippets in `completionItem/resolve` when you complete a completion, like this:
```
	[Trace - 05:33:09 PM] Sending request 'completionItem/resolve - (47)'.
	Params: {
	  "data": {
	    "entryName": "entries",
	    "offset": 56,
	    "uri": "file:///c:/tmp/vls-lsp-problem/test.ts"
	  },
	  "sortText": "0",
	  "kind": 3,
	  "label": "entries"
	}
	
	
	[Trace - 05:33:09 PM] Received response 'completionItem/resolve - (47)' in 20ms.
	Result: {
	  "insertTextFormat": 2,
	  "insertText": "entries(${1:obj}, ${2:key})",
	  "detail": "function entries<T>(obj: {\n    [key: string]: T;\n} | ArrayLike<T>): {\n    key: string;\n    value: T;\n}[] (+1 overload)",
	  "documentation": "Returns an array containing the property keys and values of the specified object (an associative array).\nEach entry is an object with a key and value attribute.The order of the returned array is undefined.\n\nThe generic refers to the data type of the values.",
	  "sortText": "0",
	  "kind": 3,
	  "label": "entries"
	}
```
It has an `insertText` snippet with format 2, which is right, and then `yasnippet` lets me fill in the args. Does eglot send `completionItem/resolve`? How do I trigger it to do that?

**Comment by joaotavora** [comment]
GaryO <notifications@github.com> writes:

> It has an insertText snippet with format 2, which is right, and then
> yasnippet lets me fill in the args. Does eglot send
> completionItem/resolve?

It does, but not in this particular context.  It is something that needs
to be fixed in Eglot.  I'll have a look, shouldn't be terribly hard.

Do you have the rest of the log?  Actually only the immediately
preceding textDocument/completion request and response, if you can.

Thanks,
João

**Comment by joaotavora** [comment]
@garyo , this is a totally "blind"  since I very much want to avoid installing that Vue thing as much as I can :-).

So I created a new branch and did a commit there which you should test. Maybe it fixes your issue.  If it doesn't we'll iterate until it does.

**Comment by garyo** [comment]
Progress -- I now get snippets in a pure typescript buffer. Per your other message, I already had yasnippet and yas-global-mode set up, and I can confirm eglot is telling the server it supports snippets. Also, the log above is actually from a typescript (jsts-ls) server (my mistake, sorry), and with your patch eglot is working fine with that server now.

I guess vetur/vls doesn't support function completion snippets though. I don't have them working with `lsp-mode` either. I'm not getting any `insertText` in the `completionItem/resolve` reply for a function completion. Hmm, I thought it did -- it has its own global snippets, which are working, but who knows.

```
client-request (id:75) Wed Oct 30 11:54:38 2019:
(:jsonrpc "2.0" :id 75 :method "textDocument/completion" :params
          (:textDocument
           (:uri "file:///c:/tmp/vls-lsp-problem/test.vue")
           :position
           (:line 12 :character 11)
           :context
           (:triggerKind 1)))

server-reply (id:75) Wed Oct 30 11:54:39 2019:
(:jsonrpc "2.0" :id 75 :result
          (:isIncomplete :json-false :items
                         [(:uri "file:///c:/tmp/vls-lsp-problem/test.vue" :position
                                (:line 12 :character 11)
                                :label "arguments" :sortText "00" :kind 6 :data
                                (:languageId "typescript" :uri "file:///c:/tmp/vls-lsp-problem/test.vue" :offset 194))
                          (:uri "file:///c:/tmp/vls-lsp-problem/test.vue" :position
                                (:line 12 :character 11)
                                :label "fooFunction" :sortText "01" :kind 3 :data
                                (:languageId "typescript" :uri "file:///c:/tmp/vls-lsp-problem/test.vue" :offset 194))
              ...(lots more here)...

client-request (id:82) Wed Oct 30 11:54:39 2019:
(:jsonrpc "2.0" :id 82 :method "completionItem/resolve" :params
          (:uri "file:///c:/tmp/vls-lsp-problem/test.vue" :position
                (:line 12 :character 11)
                :label
                #("fooFunction" 0 1
                  (eglot--lsp-item #1))
                :sortText "01" :kind 3 :data
                (:languageId "typescript" :uri "file:///c:/tmp/vls-lsp-problem/test.vue" :offset 194)))

server-reply (id:82) Wed Oct 30 11:54:39 2019:
(:jsonrpc "2.0" :id 82 :result
          (:uri "file:///c:/tmp/vls-lsp-problem/test.vue" :position
                (:line 12 :character 11)
                :label "fooFunction" :sortText "01" :kind 3 :detail "function fooFunction(alpha: string, beta: number): string" :documentation
                (:kind "markdown" :value "")))
```

**Comment by joaotavora** [comment]
> Also, the log above is actually from a typescript (jsts-ls) server (my mistake, sorry), and with your patch eglot is working fine with that server now.

So if I understand correctly the semi-blind untested `completionItem/resolve` thing is working.

> And, I just tested vls in VS Code: same thing. The "special" vue snippets work there (as they do now with your patch in eglot), but no snippets on function completion. So I think your patch in your scratch branch is fine!

Cool!
