### ISSUE TITLE
[Question] workaround for xref-backend-identifier-at-point ?

### ISSUE THREAD

**Issue by gagbo** [joaotavora/eglot#503]
Looking at these lines : https://github.com/joaotavora/eglot/blob/ac9239bed5e3bfbf057382d1a75cdfa23f2caddd/eglot.el#L1931-L1936

It seems that any time we try to call `(xref-backend-identifier-at-point 'eglot)` we will always get back `"LSP identifier at point"`. Is there a way to change that (or not call it at all) in order to actually get the identifier at point ?

Context : In Doom Emacs we're trying to use xref to get the "thing at point" before falling back to the default, so if the backend for eglot always returns this dummy value we can't use it https://github.com/hlissner/doom-emacs/blob/847bbf380c25418de1c3cbe4db35c43697f8b052/core/autoload/text.el#L108-L111

A possible workaroud in Doom would be to filter out in this function `'eglot` backend ; I'm just wondering if there's any better solution for this

**Comment by karbiv** [comment]
It looks like Eglot doesn't use that method anywhere.
Perhaps it was forgotten after a rewrite 8 month ago.

If it's not used by Eglot, then it only pollutes `xref-backend-identifier-at-point` cl-defgeneric of xref.el;

Filter out, do not call it.

**Comment by joaotavora** [comment]
> It looks like Eglot doesn't use that method anywhere.

The fact that it's not called directly by Eglot doesn't mean it's useless. Very frequently this is how methods of generic functions are meant to be used.  

> Perhaps it was forgotten after a rewrite 8 month ago.

No it was not.

Eglot's xref backend does not, by the very nature of LSP (at least in its current version), have a way to know _what the identifier at point is_.  Yes, this is how LSP works: for cross-referencing (x-referencing), you simply give the LSP server a location in a file and _it_ decides, without ever telling you explicitly what it thinks the thing at point is and how to find its definition or references.

> Is there a way to change that (or not call it at all) in order to actually get the identifier at point ?

It's "Doom" Emacs who is calling it (I don't know for what purpose but it's besides the point), not Eglot.  I think you ("Doom" Emacs) should not call this generic function.  It is meant for adding methods to it, and for xref to call  when it needs this information. There are more good reasons not to call it directly: there's no guarantee it will finish quickly, i.e. in the future it might be that the LSP implementation does support a way to know the current identifier at point but that answer might take a while to be computed.

**Comment by karbiv** [comment]
> Yes, this is how LSP works

LSP client sends JSON request with line's number and char position in it.
Identifier can be retrieved by  **_document/documentHighlight_**, I suppose.
_Xref_ uses `xref-backend-identifier-at-point` in order to pass its 
return value to `xref-find-definitions`. LSP clients skip first step, only line line-num and char-pos is required for a server.

There are no other uses of `xref-backend-identifier-at-point` inside _xref_, afaik.
`xref-find-definitions-at-mouse` simple function should be redefined in LSP buffers as `textDocument/definition`.(because it uses `xref-backend-identifier-at-point` in its body)

...
Currently I debug Eglot, it returns empty vector from Eclipse JDT server for _textDocument/definition_, but other requests work, help-at-point.
Lsp-java works, but I can't debug its logic in elisp with unreadable callbacks and hashes. JSON requests to the same Eclipse server are identical, but Eglot returns empty vector, unlike lsp-java that works.

**Comment by joaotavora** [comment]
> Identifier can be retrieved by document/documentHighlight, I suppose.

Yes, if the server supports it.  I had never thought of that.

The rest of your analysis is correct (though I don't understand the redefinition advice).

I haven't looked at `lsp-java`.  Maybe it returns simply `thing-at-point` or something like that.    

But why are you using `xref-backend-identifier-at-point` at all in "Doom" Emacs?  What are you ultimately trying to achieve there?  The last sentence seems to indicate you are you having problems connecting Eglot to an Eclipse server, but that seems a completely different request.

Please be concise and clear.

**Comment by karbiv** [comment]
> Yes, if the server supports it. I had never thought of that.

_document/documentHighlight_ is very helpful on its own(not for _xref_).

`xref-backend-identifier-at-point` is needed by _xref_ itself. Using LSP for xref that is already a proxy-lib to LSP client - would not be rational.

The simplest way to get identifier is `(thing-at-point 'symbol)`, info provided by font-lock I guess.
Lsp-java uses it with some other alternative.

**Comment by joaotavora** [comment]
> The simplest way to get identifier is (thing-at-point 'symbol), data provided by font-lock I guess.

No, it's not font-lock. It's the syntax table.  Do that in "Doom" then.  

> xref-backend-identifier-at-point is needed only by xref itself.
> Using LSP for xref which is already a proxy-lib to LSP client - would not be rational.

I know how xref.el works. What you said doesn't make sense: there could be a reason to, but let's not enter into this here (there is a linked issue in the comment if you want to add your opinion).

> document/documentHighlight is very helpful on its own(not for xref).
> Though Emacs does it without servers using libs like highlight-symbol.

I know that: I implemented it Eglot.  I also know how Emacs does it: but the major-mode's view of what the current thing at point is might not agree with LSP's.  There are issues about this, and in the LSP spec they are coming up with a solution (if you really must have them I'll look for them, or you can).

Are your questions answered here?

**Comment by karbiv** [comment]
> Are your questions answered here?

It wasn't my question but of @gagbo 

I posted while debugging Eglot, investigating why "go to definition" with Eclipse JDT server doesn't work in Eglot. Lsp-java works.

**Comment by jdelStrother** [comment]
For some background context, I think this originally came up because I was asking why `SPC *` (https://github.com/hlissner/doom-emacs/blob/39bb3aa72da06187b35e64bdc55dbe7190de63da/modules/config/default/autoload/search.el#L49) searched my project for the string `"LSP identifier at point."` rather than the thing under my cursor.

Doom is calling `xref-backend-identifier-at-point` from here: https://github.com/hlissner/doom-emacs/blob/18d0198025a9d0dded87f5f6518060e07202af0e/core/autoload/text.el#L90

**Comment by joaotavora** [comment]
> I posted while debugging Eglot, investigating why "go to definition" with Eclipse JDT server doesn't work in Eglot. Lsp-java works.

Then you should make a new issue of this, following the advice in https://github.com/joaotavora/eglot#reporting-bugs.  Otherwise, it's very easy to mix up things and hard for me to help.

**Comment by joaotavora** [comment]
> Doom is calling xref-backend-identifier-at-point from here: https://github.com/hlissner/doom-emacs/blob/18d0198025a9d0dded87f5f6518060e07202af0e/core/autoload/text.el#L90

Are you the Doom maintainer? Have you asked its maintainer why it is doing such a thing? I don't think this is a problem in Eglot.

**Comment by karbiv** [comment]
Eglot doesn't use `xref-backend-identifier-at-point`, doesn't depend on its return value.

There's a default implemention in xref, but Eglot hides it by for all invocations "_LSP identifier at point._".

**Comment by joaotavora** [comment]
> Eglot doesn't use xref-backend-identifier-at-point, doesn't depend on its return value.
> There's a default implemention in xref, but Eglot hides it by for all invocations "LSP identifier at point.".

@karbiv, what do you pretend to reach with these statements.  Also Eglot doesn't "hide" any default implementation.  It's the generic function that calls the methods established in `eglot.el` when you pass the symbol `eglot` as the argument.  If you want to reach the default implementation, just pass anything that you know there's no implementation for.  Pass it `'doom` or `'karbiv` or something.

**Comment by karbiv** [comment]
> If you want to reach the default implementation, just pass anything that you know there's no implementation for.

`(xref-backend-identifier-at-point (xref-find-backend))`

`xref-find-backend` returns symbol `'eglot`.

Eglot doesn't use `xref-backend-identifier-at-point`, there's no need to touch it, let default xref implementation be invoked.

**Comment by joaotavora** [comment]
> Eglot doesn't use xref-backend-identifier-at-point, there's no need to touch it, let default xref implementation be invoked.

@karbiv, this is not how generic functions work.  Just because you don't use the return value for something doesn't mean you should not add a method to it.  Just see

```
(cl-defmethod xref-backend-definitions ..
```

For one of many examples.

**Comment by karbiv** [comment]
> this is not how generic functions work.

```
(cl-defgeneric NAME ARGS [DOC-STRING] [OPTIONS-AND-METHODS...] &rest
DEFAULT-BODY)
```
`xref-backend-identifier-at-point` is defined by _xref_ like this:
```
(cl-defgeneric xref-backend-identifier-at-point (_backend)
  "Return the relevant identifier at point.
The return value must be a string, or nil meaning no identifier
at point found."
  (let ((thing (thing-at-point 'symbol)))
    (and thing (substring-no-properties thing))))
```
**DEFAULT-BODY** is invoked for (xref-backend-identifier-at-point 'eglot) **if** Eglot's cl-defmethod is removed.

**Comment by joaotavora** [comment]
> 'eglot argument then becomes unknown to xref-backend-identifier-at-point and default body is invoked.

I don't think we're making progress. And we're just littering this discussion with this  ¯\_(ツ)_/¯.

**Comment by gagbo** [comment]
I think that basically the goal was to get an interactive function that gets the current identifier at point.

With that simple goal in mind, the idea in Doom was to gracefully fallback from most specific method to `thing-at-point`, trying in various `cond` branches if the "better" method is available.

-- Personal opinion
I don't think that it matters at this point if xref-backend-identifier-at-point is "longer" with eglot backend, since we're using LSP anyways and I expect some delays
-- Personal opinion

As I don't know much elisp, that was really just a question : is there an idiomatic way to either fix it or change it in client code I guess ? Because even if the function returns a dummy value, it's also fair (from an API consumer point of view) to expect that `(xref-backend-identifier-at-point (xref-find-backend))` returns `nil` or a string with the identifier at point.

But I guess we'll just add a special case to avoid using xref if the backend is eglot, no biggie ( Doom's maintainer is @hlissner )

**Comment by joaotavora** [comment]
First, let me make something clear: Eglot is using a hack, a trick.  Backends _are_ supposed to add methods to that GF, but the contract is that those methods returns "identifiers", which isn't the case in Eglot.  The reason why Eglot hacks it like that boils down to a limitation in LSP and to a limitation in xref.

Second:  Doom is using a hack, too, arguably an uglier one, because third parties aren't supposed to call that method at all, as I've been trying to explain/ I cannot see the point in doing it, but then I don't know Doom at all .  (Or rather I just know the game).

**Comment by dgutov** [comment]
> third parties aren't supposed to call that method at all

While the use by Doom is unexpected, it's not like they're doing something outrageous. They're calling a generic method that is documented to behave in a certain way.

But their current workaround should serve them fine, unless they find out some real, practical problems with it.

**Comment by joaotavora** [comment]
> While the use by Doom is unexpected, it's not like they're doing something outrageous

Why should it want to have the same view as Xref of what the "thing at point" is?  Xref is not in the business of supplying that information, it's in the business of needing it to find cross references.   And in fact, LSP shows that it is not strictly necessary to perform that job.  But, if there was a way for Eglot to leverage Xref correctly without needing to do its hack and somehow tell it: "Think at point doesn't matter for this backend" everyone would be happy, even "unexpected but not outrageous" such as Doom's (though I have no idea why Doom is using this anyway).

Anyway, closing this as the question is more than answered.

**Comment by joaotavora** [comment]
(but feel free to continue discussing)

**Comment by dgutov** [comment]
> Why should it want to have the same view as Xref of what the "thing at point" is?

Perhaps to try to avoid the problem of some major modes where the syntax table is not specified carefully enough that "symbol at point" always makes sense.

Not sure how successful they are at that, but Xref backends, unless faces with problems like LSP protocol, should in theory generally return better info than `symbol-at-point`. Though they might return more arbitrary strings like qualified symbol names as well (and those would not be helpful to grep). But that's also currently only in theory.

> But, if there was a way for Eglot to leverage Xref correctly without needing to do its hack and somehow tell it: "Think at point doesn't matter for this backend" everyone would be happy

I don't have the time for this now, but we should return to this.

**Comment by joaotavora** [comment]
> Perhaps to try to avoid the problem of some major modes where the syntax table is not specified carefully enough that "symbol at point" always makes sense.

Sounds like a bug in these major modes, or lack of power in `thingatpt.el`.  Any specific cases?

**Comment by dgutov** [comment]
> Sounds like a bug in these major modes

I would imagine so. But we don't document this aspect (how to choose syntax table well).

> Any specific cases?

E.g. in `elixir-mode` `:thingy` is the full symbol. Whereas `(thing-at-point 'symbol)` should return `thingy` for it because it much better greppable (the same symbol can appear in text without color or with colon at the end). I made such change in `ruby-mode` several years ago with much success (and zero user feedback, as per usual).

**Comment by joaotavora** [comment]
Then maybe there should be `thing-at-point 'xref` that calls a GF in `thingatpt.el` with `major-mode`. That GF defaults to `thing-at-pt 'symbol`. Xref's default implementation would call `(thing-at-pt 'xref)`.  Hopefully not too confusing.

**Comment by dgutov** [comment]
It would either delegate to `xref-backend-identifier-at-point`, or... I don't know what else it would do.

It would be better to fix major modes (and the manual), if we start improving things in that area.

**Comment by joaotavora** [comment]
Sorry, it was late in the night and I see it was confusing.  I've simplified it:

- Make a GF, `thing-at-pt-high-quality-symbol`, whose default implementation does what `thing-at-pt 'symbol` does.' 

- Whoever (major modes?) is now doing high-quality customization of `xref-backend-identifier-at-point` should start doing those high-quality customization for `thing-at-pt-high-quality-symbol`;

- Have Doom call `thing-at-pt-qualified-symbol` with the value for `major-mode` for whatever purposes it needs.  Or it could call that GF with some object for which a method makes sense, doesn't have to be `major-mode`. _Don't have it call Xref stuff for symbol at point_

- Have the default implementation of `xref-backend-identifier-at-point` also call `thing-at-pt-high-quality-symbol`.

- Eglot can keep on doing its hack.  Until we find a solution for _that_ particular problem.

- Eglot can do its

**Comment by dgutov** [comment]
> Whoever (major modes?)

Eglot is an obvious counter-example. And not the sole one, of course.

>  Or it could call that GF with some object for which a method makes sense, doesn't have to be major-mode

This is the most murky part. Aside from the extra complexity and having third-party code guess that xref backends' methods are somehow untouchable.

> Eglot can keep on doing its hack. Until we find a solution for that particular problem.

Yes, let's.

**Comment by joaotavora** [comment]
bq. Eglot is an obvious counter-example. And not the sole one, of course.

Yes, but you're not following.  Eglot would _not_ add a method to `thing-at-pt-high-quality-symbol` at all.  It would only add a method to `xref-backend-identifier-at-point` (unless we fix the other problem).  Thus no contradiction.

But regardless of Eglot, my point is that "knowing the thing at point" is NOT Xref's business, it's `thingatpt.el` 's.

**Comment by dgutov** [comment]
> Yes, but you're not following. Eglot would not add a method to thing-at-pt-high-quality-symbol at all. Its customization is NOT "high quality" at all. It's quite the contrary, a good ol' hack. So Eglot would only add a method to xref-backend-identifier-at-point (unless we fix the other problem). Thus no contradiction.

I got that, of course. Just saying Eglot (and similar packages) are often not major modes.

**Comment by joaotavora** [comment]
> Just saying Eglot (and similar packages) are often not major modes.

Ah, so you're objecting to calling `thing-at-pt-high-quality-symbol` with the value of `major-mode`? OK that makes sense, then make a `thing-at-pt-backend` abstraction or something like that.  Eglot would certainly _not_ add to that (because it hasn't got a clue about things at point).

...

Let me just slightly correct myself and go on a tangent: Eglot hasn't got a clue _now_, at time of writing.  It may still develop one, _if_ LSP develops it.    And this will impact completion as well, which is another place where the lack of agreement on what the "thing at point" is makes itself heard.

Now, last time I checked the LSP repo the maintainer was pretty set on doing this.  He wants servers to supply symbol-at-point-gathering regexps, for completion _and other_ purposes.  He seems to call it "word boudaries of a language".

If that ever happens, and if Eglot implements that interface, then it will have something valuable to add to thing-at-point calculations.  

For the LSP's maintainer proposal, see https://github.com/microsoft/language-server-protocol/issues/937 and my personal take on it https://github.com/microsoft/language-server-protocol/issues/937#issuecomment-595803853

**Comment by dgutov** [comment]
Thanks for the links. FWIW, all of the options should be sufficient for the purpose of this discussion. So let's just hope one of them sees the light of day.

**Comment by joaotavora** [comment]
They fixed it in Doom already, I think.

**Comment by dgutov** [comment]
Kind of, by blacklisting Eglot. :-)

They did that before my first message in this thread, too.

**Comment by joaotavora** [comment]
I never did understand why they were trying to do, anyway.  And breaking Eglot's working hack for a purpose I don't understand _and_ a technique I don't agree with is a no-brainer for me.
