### ISSUE TITLE
Godot Engine Support

### ISSUE THREAD

**Issue by rushsteve1** [joaotavora/eglot#511]
The [Godot Game Engine](https://godotengine.org/) supports acting as an LSP server for its native GDScript programming language, support for which is already provided by [`gdscript-mode`](https://github.com/GDQuest/emacs-gdscript-mode). The server is accessible on the local machine via a TCP port on the local machine, port `6008` by default though this is user configurable.

Godot should probably not be launched by Eglot, instead Eglot should simply try to connect to the port when `gdscript-mode` is activated.

Relevant PRs/Issues on Godot:
https://github.com/godotengine/godot/pull/29780
https://github.com/godotengine/godot/pull/35864

**Comment by joaotavora** [comment]
Right. This makes sense. Then probably the `gdscript-mode` entry in `eglot-server-programs` should reflect the "localhost/6008" combination.
