### ISSUE TITLE
Windows 10: Package `Emacs 26.3` required

### ISSUE THREAD

**Issue by Vd86xkht** [joaotavora/eglot#516]
Hello,

I am confused because when I try to install eglot using `package-install`. I get the following message:
`package-compute-transaction: Package ‘emacs-26.3’ is unavailable`

I am running Emacs 26.3 and 27.0.91 under Windows 10.

The command is: `C:\Users\visua\AppData\Local\Programs\emacs-27.0.91-x86_64\bin\emacsclientw.exe -c -n -a runemacs.exe` to start emacs

If I start emacs with `emacs -q` using the Terminal, the installation is working without errors.

---
Best regards!

**Comment by skangas** [comment]
Thanks for the bug report!

This sounds like a bug in Emacs or `package.el`. If you are still seeing this, could you please `M-x report-emacs-bug` or email bug-gnu-emacs@gnu.org? Thanks.
