### ISSUE TITLE
Show context of references

### ISSUE THREAD

**Issue by brotzeit** [joaotavora/eglot#52]
eglot:
![eglot](https://user-images.githubusercontent.com/25367303/43354442-248626b0-924d-11e8-9a3b-192695389fc8.png)
lsp-mode:
![lsp-mode](https://user-images.githubusercontent.com/25367303/43354444-2b4a818a-924d-11e8-8392-0c470135de9a.png)

Eglot also displays the definition as a reference.

**Comment by joaotavora** [comment]
Hmmm, right, more or less.  To understand what you mean, exactly, tell me what you did before getting the prompt in both situations.  Does it also happen without helm?

> Eglot also displays the definition as a reference

Are you describing a second problem here?
