### ISSUE TITLE
eglot.el doesn't compile

### ISSUE THREAD

**Issue by mwotton** [joaotavora/eglot#521]
apologies if i've messed something up, but when i package-install eglot from melpa on a fresh doom-emacs setup, i get 
```
eglot.el:97:1: Error: End of file during parsing
```

and it does seem like there are some unbalanced parens when i check eglot.el out from github.

```
➜ cat eglot.el| tr -d -c '(' | wc -c
3182
➜ cat eglot.el| tr -d -c ')' | wc -c
3181
```

**Comment by mwotton** [comment]
looks like https://github.com/joaotavora/eglot/commit/5a2cde98d4b629a14370bf4ce52449bbf3294838 drops a paren, and i see you've got a failure in travis so i assume you know about it.

**Comment by joaotavora** [comment]
Thanks. Indeed should have paid more attention to Travis. Fixed.
