### ISSUE TITLE
README appears to be out-of-date

### ISSUE THREAD

**Issue by notmgsk** [joaotavora/eglot#531]
For example `eglot-help-at-point` is not defined in the library but is referenced by the README.

**Comment by narendraj9** [comment]
Looks like this has been replaced with the built-in `display-local-help`.

**Comment by pbgc** [comment]
@narendraj9 don't think so .. at least for me and with Rust (with rust-analyser) display-local-help does not work (don't show nothing) and if I use eglot stable eglot-help-at-point works!

**Comment by joaotavora** [comment]
The binding previously bound to `eglot-help-at-point` has been replaced to point to `eldoc-doc-buffer` in newer versions of Eglot, which use the newer Eldoc system.

So:

1. The README is indeed out of date
2. `M-x eglot-help-at-point` has been replaced by `M-x eldoc-doc-buffer` but will probably be replaced by `M-x eldoc` in the near future.

**Comment by joaotavora** [comment]
Just wanted to add that `M-x eldoc` is now a thing.  I'll take a README.md PR
