### ISSUE TITLE
Eldoc pops up on completion even with Eldoc mode disabled

### ISSUE THREAD

**Issue by gcohara** [joaotavora/eglot#532]
Hi,

When using Eglot on C++, I am finding that after accepting an autocompletion the Eldoc help still pops up despite being disabled.
I'm not sure if this is actually intentional, but I've managed to disable the pop-up on hover so I thought it would disable this too.
 
Before hitting enter:
![](https://i.imgur.com/yZxYYS9.png)
And after:
![](https://i.imgur.com/ecTsCPn.png)

Here is the events log:

```
[client-notification] Thu Sep  3 12:27:27 2020:
(:jsonrpc "2.0" :method "textDocument/didChange" :params
          (:textDocument
           (:uri "file:///Users/georgeohara/source-code/projects/guac/src/file_interface.cpp" :version 78)
           :contentChanges
           [(:range
             (:start
              (:line 24 :character 11)
              :end
              (:line 24 :character 12))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 24 :character 11)
              :end
              (:line 24 :character 11))
             :rangeLength 0 :text "frequencies")
            (:range
             (:start
              (:line 24 :character 12)
              :end
              (:line 24 :character 22))
             :rangeLength 10 :text "")
            (:range
             (:start
              (:line 24 :character 11)
              :end
              (:line 24 :character 12))
             :rangeLength 1 :text "")
            (:range
             (:start
              (:line 24 :character 11)
              :end
              (:line 24 :character 11))
             :rangeLength 0 :text "frequencies")]))
[client-request] (id:38) Thu Sep  3 12:27:27 2020:
(:jsonrpc "2.0" :id 38 :method "textDocument/signatureHelp" :params
          (:textDocument
           (:uri "file:///Users/georgeohara/source-code/projects/guac/src/file_interface.cpp")
           :position
           (:line 24 :character 22)))
[client-request] (id:39) Thu Sep  3 12:27:27 2020:
(:jsonrpc "2.0" :id 39 :method "textDocument/hover" :params
          (:textDocument
           (:uri "file:///Users/georgeohara/source-code/projects/guac/src/file_interface.cpp")
           :position
           (:line 24 :character 22)))
[stderr] I[12:27:27.513] <-- textDocument/didChange
[stderr] I[12:27:27.515] <-- textDocument/signatureHelp(38)
[stderr] I[12:27:27.515] Updating file /Users/georgeohara/source-code/projects/guac/src/file_interface.cpp with command 
[stderr] [/Users/georgeohara/source-code/projects/guac]
[stderr] /usr/local/Cellar/llvm/10.0.0_3/bin/clang-tool -std=c++20 /Users/georgeohara/source-code/projects/guac/src/file_interface.cpp -fsyntax-only -resource-dir=/usr/local/Cellar/llvm/10.0.0_3/lib/clang/10.0.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
[stderr] I[12:27:27.515] <-- textDocument/hover(39)
[stderr] I[12:27:27.582] --> textDocument/publishDiagnostics
[server-notification] Thu Sep  3 12:27:27 2020:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:diagnostics
           [(:code "expected_semi_after_stmt" :message "Expected ';' after return statement (fix available)" :range
                   (:end
                    (:character 1 :line 25)
                    :start
                    (:character 0 :line 25))
                   :severity 1 :source "clang")]
           :uri "file:///Users/georgeohara/source-code/projects/guac/src/file_interface.cpp"))
[server-reply] (id:39) Thu Sep  3 12:27:27 2020:
(:id 39 :jsonrpc "2.0" :result
     (:contents
      (:kind "markdown" :value "### variable `frequencies`  \n\n---\nType\\: `CharFreqHashMap`  \n\n---\n```cpp\n// In get_frequencies\nCharFreqHashMap frequencies {}\n```")
      :range
      (:end
       (:character 22 :line 24)
       :start
       (:character 11 :line 24))))
[stderr] I[12:27:27.583] --> reply:textDocument/hover(39) 67 ms
[stderr] I[12:27:27.645] --> reply:textDocument/signatureHelp(38) 129 ms
[server-reply] (id:38) Thu Sep  3 12:27:27 2020:
(:id 38 :jsonrpc "2.0" :result
     (:activeParameter 0 :activeSignature 0 :signatures
                       []))
```

**Comment by joaotavora** [comment]
Thanks for reporting this. Eglot unconditionally makes an `eldoc` request after finishing a completion.  This because sometimes it wouldn't happen.  Maybe this behaviour should be conditional to having ElDoc enabled at all.  How did you disable it?

**Comment by joaotavora** [comment]
By the way, if it's the multi-line, echo-area jumping nature of the on-line documentation that's bothering you, you can probably try to set `eldoc-echo-area-use-multiline-p` to 1 or maybe 2.

**Comment by gcohara** [comment]
I have `global-eldoc-mode` set to `nil` in my `init.el`.
I've managed to get rid of the pop-up now after going into `Customize Group: Eglot` and adding 'Documentation on hover' to 'Ignored Server Capabilities'.

I really should've tried this first but I always forget about the easy customise options existing!

**Comment by gcohara** [comment]
My previous comment together with setting `eldoc-echo-area-use-multiline-p` to 1 have solved this.

**Comment by muffinmad** [comment]
> By the way, if it's the multi-line, echo-area jumping nature of the on-line documentation that's bothering you, you can probably try to set `eldoc-echo-area-use-multiline-p` to 1 or maybe 2.

I miss show-full-first-line option from old Eldoc/Eglot. Actually is the reason why I stick with old Eglot version for now.

```elisp
(setq eldoc-echo-area-use-multiline-p 1)
```

<img width="595" alt="Знімок екрана 2020-09-18 о 21 47 48" src="https://user-images.githubusercontent.com/2702727/93634236-f2447600-f9f8-11ea-9e50-6916eb801c41.png">

Can't see full signature info.

```elisp
(setq eldoc-echo-area-use-multiline-p 2)
```

<img width="595" alt="Знімок екрана 2020-09-18 о 21 48 05" src="https://user-images.githubusercontent.com/2702727/93634333-1b650680-f9f9-11ea-9bd3-53ce721f423e.png">

No signature info at all.

@joaotavora Can you please advice me on in which function desired behavior can be implemented? New value for the `eldoc-echo-area-use-multiline-p` or something?

**Comment by joaotavora** [comment]
Would you like to see the line wrap? Is that it?

**Comment by muffinmad** [comment]
> Would you like to see the line wrap? Is that it?

Yes. Like this:

<img width="595" alt="Знімок екрана 2020-09-19 о 13 26 54" src="https://user-images.githubusercontent.com/2702727/93665019-df26ba00-fa7b-11ea-9a04-46057d5cb807.png">

The full first line.

**Comment by muffinmad** [comment]
> Would you like to see the line wrap? Is that it?

Many thanks for [bug#43543](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=43543)!
