### ISSUE TITLE
ElDoc echo area message won't clear after cursor movements

### ISSUE THREAD

**Issue by yuezhu** [joaotavora/eglot#533]
Hello, I just started using eglot, and it looks great! My configured is the following:
```elisp
(use-package eglot
  :ensure t
  :hook
  ((go-mode python-mode) . eglot-ensure)
  (eglot-managed-mode . (lambda () (flymake-mode -1)))
  :defer t
  :config
  (add-to-list 'eglot-stay-out-of 'flymake))
```

And 
```elisp
'(eglot-ignored-server-capabilites '(:documentHighlightProvider :hoverProvider))
```
A minor issue I noticed is that the ELDoc echo area message won't clear itself after cursor movements, which is different than other modes that use ELDoc, where it clears itself right after a cursor movement.

I made a screen record demonstrating that:

![output](https://user-images.githubusercontent.com/1224535/92143431-48070480-ede3-11ea-9e3a-0e0747a76bc3.gif)

**Comment by muffinmad** [comment]
I believe it's the consequence of the #527 fix.

**Comment by joaotavora** [comment]
Thanks, Andrii.  Indeed it was. That fix was incomplete: i've followed up with another fix to Emacs's eldoc.el, which should be in GNU Elpa shortly, fixing this issue.  Look for version 1.10.0 of eldoc.el. Closing this. @yuezhu if you find the problem persists after tomorrow, let us know here.

**Comment by yuezhu** [comment]
Thanks! I could verify this has been fixed.
