### ISSUE TITLE
[Feature request] Make eglot works with speedbar

### ISSUE THREAD

**Issue by BooAA** [joaotavora/eglot#536]
Speedbar can use imenu to get definitions in a file and display them as tags. (if the return value of `imenu-create-index-function` is of the from `(INDEX-NAME POSITION)`, speedbar can handle this for free) However, when I tried using speedbar with eglot, speedbar complained _**"speedbar-insert-generic-list: malformed list!"**_  since it didn't know how to insert the result of `eglot-imenu `as tags.

It might be useful to make eglot work with speedbar so that we will have tree-like structure to show major definitions for each file.

**Comment by arbv** [comment]
That would be a good addition. Speedbar is very handy when working with files with a lot of definitions.

**Comment by joaotavora** [comment]
Or maybe speedbar can understand the correct format of imenu.  Eglot is doing nothing more than follow the established format:

```
imenu--index-alist is a variable defined in `imenu.el'.
Its value is nil

  Automatically becomes buffer-local when set.
  This variable may be risky if used as a file-local variable.

Documentation:
The buffer index alist computed for this buffer in Imenu.

Simple elements in the alist look like (INDEX-NAME . POSITION).
POSITION is the buffer position of the item; to go to the item
is simply to move point to that position.

POSITION is passed to `imenu-default-goto-function', so it can be
a non-number if that variable has been changed (e.g. Semantic
uses overlays for POSITIONs).

Special elements look like
(INDEX-NAME POSITION FUNCTION ARGUMENTS...).
To "go to" a special element means applying FUNCTION to
INDEX-NAME, POSITION, and the ARGUMENTS.

A nested sub-alist element looks like (INDEX-NAME . SUB-ALIST).
The function `imenu--subalist-p' tests an element and returns t
if it is a sub-alist.

There is one simple element with negative POSITION; selecting that
element recalculates the buffer's index alist.
```

**Comment by tomfitzhenry** [comment]
sb-imenu as described in https://stackoverflow.com/a/36893492 can do this. I'm using eglot with it.

**Comment by joaotavora** [comment]
A now-deleted I received this morning by one "Tom F"  stated the following:

"sb-imenu as described in https://stackoverflow.com/a/36893492 can do this. I'm using eglot with it."

**Comment by BooAA** [comment]
> "sb-imenu as described in https://stackoverflow.com/a/36893492 can do this. I'm using eglot with it."

After `(require 'sb-imenu)` and `(setq speedbar-initial-expansion-list-name "sb-imenu") ` according to the comment in that stackoverflow question, I got speedbar display imenu index correctly

![Screenshot_2020-12-15_19-12-16](https://user-images.githubusercontent.com/32809182/102208004-d5411580-3f09-11eb-9ab3-423f3c7b43a3.png)

But when I click or press return on the item, it reports error:


`funcall-interactively: Wrong number of arguments: (lambda (text node indent) "Goto the current tag." (interactive) (condition-case nil (progn (speedbar-select-attached-frame) (raise-frame) (select-frame-set-input-focus (selected-frame))) (error nil)) (switch-to-buffer sb-imenu-active-buffer) (goto-char node)), 0
`

**Comment by joaotavora** [comment]
That probably explains why the poster deleted the comment.  Get someone with Elisp skills to fix speedbar-imenu.  Maybe talk to its author.  It shouldn't be hard, but unfortunately, I have no time for this.  

I do know that M-x imenu works.That's the thing that exists in Emacs, and that's what I'm coding for.  Other extensions must also code for Emacs, then they will work with Eglot.

**Comment by BooAA** [comment]
@joaotavora  Below is my attempt to make eglot-imenu work with speedbar by transform the complex alist form to the simple form.

```emacs-lisp
;; borrow from eglot-imenu
(defun eglot-imenu-get-point (one-obj-array)
  (car (eglot--range-region
        (eglot--dcase (aref one-obj-array 0)
          (((SymbolInformation) location)
           (plist-get location :range))
          (((DocumentSymbol) selectionRange)
           selectionRange)))))

(defun eglot-imenu-to-simple-form (menu)
  (cl-loop for form in menu
           collect (cons (car form)
                         (if (imenu--subalist-p form)
                             (eglot-imenu-to-simple-form (cdr form))
                           (eglot-imenu-get-point (cadr form))))))

(advice-add #'eglot-imenu :filter-return #'eglot-imenu-to-simple-form)

;; optional, prevent speedbar from creating additional tags for long entries
(setq speedbar-tag-regroup-maximum-length 100)
```
Testing on linux kernel with clangd, looks ok to me:
![eglot_with_speedbar](https://user-images.githubusercontent.com/32809182/126043674-f6f9f84e-6ea9-45fa-b7ec-4644f9d67dcf.png)

I've made a bug report to ask support for complex imenu form in speedbar, see https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-06/msg01058.html.
