### ISSUE TITLE
Missing "non-prefix" company candidates

### ISSUE THREAD

**Issue by haoyuan80s** [joaotavora/eglot#538]
Is that possible to have non-prefix company candidates (figure below)?
![image](https://user-images.githubusercontent.com/9064146/92961914-f1be4500-f424-11ea-8e1f-cd19ef8a7d4a.png)

**Comment by joaotavora** [comment]
Yes.  I call these "flex" completions.  But the support varies with the server.  Are you already trying with Eglot? If so, and if it's not working, submit a bug report.
