### ISSUE TITLE
lsp server for java fails to start in java mode

### ISSUE THREAD

**Issue by auppar** [joaotavora/eglot#540]
Whenever i open the java file i get this error and the connection to language server is not set .

the configuration is as follows :

(defconst my-eclipse-jdt-home "<path_to>/.emacs.d/elpa/eglot-20200830.1254/plugins/org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar" "Point to eclipse jdt jar")

i have placed the jdt specifically in the folder containing the eglot.

    (defun my-eglot-eclipse-jdt-contact (interactive)
      "Contact with the jdt server input INTERACTIVE."
      (let ((cp (getenv "CLASSPATH")))
	(setenv "CLASSPATH" (concat cp ":" my-eclipse-jdt-home))
	(unwind-protect (eglot--eclipse-jdt-contact nil)
	  (setenv "CLASSPATH" cp))))

   (setcdr (assq 'java-mode eglot-server-programs) #'my-eglot-eclipse-jdt-contact)

   (add-hook 'java-mode-hook 'eglot-ensure)

[jsonrpc] Server exited with status 13
Error in post-command-hook (#[0 "\303\304\301\242\305#\210\300\306!\205r\211q\210
?\205\307\310\311 \")\207" [#<buffer b.java> (#0) eglot--managed-mode remove-hook post-command-hook nil buffer-live-p apply eglot--connect eglot--guess-contact] 4]): (error "[eglot] -1: Server died")
user-error: Minibuffer window is not active
Quit

Please let me know if you find any anomaly in the setting.

**Comment by auppar** [comment]
The eglot settings work fine for c, c++ and python modes.

**Comment by auppar** [comment]
The eglot settings work fine for c, c++ and python modes.

**Comment by auppar** [comment]
The eglot settings work fine for c, c++ and python modes.

**Comment by auppar** [comment]
If i set the class path manually the server dies. by Alt-x eglot and then it asks to add to class path for a folder but dies after adding it to the class path.

**Comment by narendraj9** [comment]
What happens if you haven't set the location to the eglot server and using the command `eglot` asks you to interactively select the jar file? Does it work correctly post selection of the path manually?

**Comment by auppar** [comment]
Apologoies for a delayed reply, when i try to redirect to the folder manually the server exits with status 13. My setup is in macOS. The eglot looks for plugins folder for the jar. I have downloaded the the jdtls tar and i am pointing to the plugins folder containing the launcher jar. But the eglot(client) fails to connect to the server.

**Comment by narendraj9** [comment]
Abhishek Uppar <notifications@github.com> writes:

> Apologoies for a delayed reply, when i try to redirect to the folder
> manually the server exits with status 13. My setup is in macOS. The
> eglot looks for plugins folder for the jar. I have downloaded the the
> jdtls tar and i am pointing to the plugins folder containing the
> launcher jar. But the eglot(client) fails to connect to the server.

Pointing `eglot` to the top-level directory of the LSP server worked
for me. You can try doing that and see if it works. 


-- 
Narendra Joshi

**Comment by mkcms** [comment]
> (defconst my-eclipse-jdt-home "<path_to>/.emacs.d/elpa/eglot-20200830.1254/plugins/org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar" "Point to eclipse jdt jar")

Looks like you didn't copy the entire contents of the eclipse.jdt.ls tar. Try extracting _all_ the contents of the .tar to _one_ directory, like `~/.emacs.d/eclipse-jdt/`.

**Comment by auppar** [comment]
after doing as suggested i still fail to connect to the server. Below is the payload to the server see if you can find the problem.

[client-request] (id:1) Mon Sep 21 19:08:06 2020:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
	  (:processId 80648 :rootPath "/tmp/" :rootUri "file:///private/tmp/" :initializationOptions
		      (:workspaceFolders
		       ["file:///private/tmp/"]
		       :settings
		       (:java
			(:home "/System/Library/Frameworks/JavaVM.framework/Versions/Current")))
		      :capabilities
		      (:workspace
		       (:applyEdit t :executeCommand
				   (:dynamicRegistration :json-false)
				   :workspaceEdit
				   (:documentChanges :json-false)
				   :didChangeWatchedFiles
				   (:dynamicRegistration t)
				   :symbol
				   (:dynamicRegistration :json-false)
				   :configuration t)
		       :textDocument
		       (:synchronization
			(:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
			:completion
			(:dynamicRegistration :json-false :completionItem
					      (:snippetSupport t)
					      :contextSupport t)
			:hover
			(:dynamicRegistration :json-false :contentFormat
					      ["markdown" "plaintext"])
			:signatureHelp
			(:dynamicRegistration :json-false :signatureInformation
					      (:parameterInformation
					       (:labelOffsetSupport t)))
			:references
			(:dynamicRegistration :json-false)
			:definition
			(:dynamicRegistration :json-false)
			:declaration
			(:dynamicRegistration :json-false)
			:implementation
			(:dynamicRegistration :json-false)
			:typeDefinition
			(:dynamicRegistration :json-false)
			:documentSymbol
			(:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
					      (:valueSet
					       [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
			:documentHighlight
			(:dynamicRegistration :json-false)
			:codeAction
			(:dynamicRegistration :json-false :codeActionLiteralSupport
					      (:codeActionKind
					       (:valueSet
						["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"])))
			:formatting
			(:dynamicRegistration :json-false)
			:rangeFormatting
			(:dynamicRegistration :json-false)
			:rename
			(:dynamicRegistration :json-false)
			:publishDiagnostics
			(:relatedInformation :json-false))
		       :experimental nil)))
[internal] Mon Sep 21 19:08:08 2020:
(:message "Connection state changed" :change "exited abnormally with code 13\n")

----------b---y---e---b---y---e----------
[stderr] 
[stderr] 
[stderr] nil
[stderr] nil
[stderr] Process EGLOT (tmp/java-mode) stderr finished

**Comment by Freyr666** [comment]
Same problem here

> Server exited with status 13

**Comment by auppar** [comment]
was randomly trying the right jdtls version for jkd 8 and this version worked, jdt-language-server-0.50.0-202002171858.tar.
