### ISSUE TITLE
Compile warnings

### ISSUE THREAD

**Issue by joakim-tjernlund** [joaotavora/eglot#552]
Compiling eglot master yields a few warnings:
```
 * Compiling GNU Emacs Elisp files ...

In eglot--managed-mode:
eglot.el:1376:23:Warning: assignment to free variable
    ‘eldoc-documentation-functions’
eglot.el:1350:27:Warning: assignment to free variable
    ‘eldoc-documentation-strategy’

In end of data:
eglot.el:2724:1:Warning: the following functions are not known to be defined:
    project-root, eldoc-documentation-enthusiast, eldoc

**Comment by joaotavora** [comment]
How are you compiling?  If you compile `eglot.el` in say Emacs 21, it's likely to yield a more than a few warnings, right? So this report has too few information.  The only supported way to compile Eglot is to `make` in the git checkout directory, or use `package-install`.  I don't know if you are doing those things.  Bring me back more information and I will reopen.

**Comment by joakim-tjernlund** [comment]
Test has some more:
```
In toplevel form:
eglot-tests.el:825:1:Warning: Unknown LSP interface FooObject
eglot-tests.el:825:1:Warning: Unknown LSP interface FooObject
eglot-tests.el:825:1:Warning: Unknown LSP interface FooObject
eglot-tests.el:825:1:Warning: Unknown LSP interface FooObject
eglot-tests.el:825:1:Warning: Unknown LSP interface FooObject
eglot-tests.el:866:1:Warning: Unknown LSP interface FooObject
eglot-tests.el:866:1:Warning: Destructuring for Command has extraneous
    (:_title :_command :_arguments)
eglot-tests.el:866:1:Warning: Destructuring for CodeAction has extraneous
    (:_title :_edit :_command)
eglot-tests.el:894:1:Warning: Destructuring for Command has extraneous
    (:_title :_command :_arguments)

In end of data:
eglot-tests.el:1033:1:Warning: the following functions are not known to be
    defined: eldoc, eldoc-doc-buffer, yas-minor-mode
```
emacs-27.1

**Comment by joakim-tjernlund** [comment]
> How are you compiling? If you compile `eglot.el` in say Emacs 21, it's likely to yield a more than a few warnings, right? So this report has too few information. The only supported way to compile Eglot is to `make` in the git checkout directory, or use `package-install`. I don't know if you are doing those things. Bring me back more information and I will reopen.

Oh, you are to quick for me :) Will look at make, I just used the standard emacs build in Gentoo

**Comment by joaotavora** [comment]
If you are interested in _developing_ Eglot, you should acquaint yourself with the Makefile.  If you are interested in _using_ Eglot efficiently (by having it compiled), you should probably just `M-x package-install`.

**Comment by joakim-tjernlund** [comment]
I want to do a proper Gentoo package so my users where I work can just install a Gentoo pkg

**Comment by joaotavora** [comment]
Okay, that's reasoanble. Two things though. 1. You have to give good instructions to your users on how to report bugs to the Eglot project, so that Gentoo-specific bugs don't end up here. 2. You need to make sure to bundle the dependencies of Eglot with your package.

**Comment by joakim-tjernlund** [comment]
Didn't get very far though:
```
make -s -j8 ELFILES=eglot.el 
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Package refresh done
Failed to download ‘gnu’ archive.
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Package ‘nil-’ is unavailable
make: *** [Makefile:41: eglot.elc] Error 255
```
The build tries to contact elpa.org to download stuff. I would just like to see a list of missing deps

**Comment by joaotavora** [comment]
Those are listed int he `eglot.el` file.  You have to imitate what `package-install` in Emacs does.  As to `make`, it needs those dependencies.  You can read them in the makefile.  As of writing, mandatory dependencies are `eldoc`, `project`, `xref`, `flymake` and `jsonrpc`.  Optional dependencies are `yasnippet` and `company`.

**Comment by joakim-tjernlund** [comment]
Only missing eldoc and project it seems. package-install fixed eldoc but it cannot find project ?
project is listed as a new packet (as is eldoc) in package-list, odd

**Comment by joakim-tjernlund** [comment]
Oh, maybe you should document the needed packages and have a rule that just require them to be installed?

**Comment by joaotavora** [comment]
They are documented in the `eglot.el` file, in the "Package-Requires:" header. Presumably Elisp package builders are acquainted with those indications.  Also, mind you that the Makefile, like I said is for **developing** Eglot, i.e. for helping you make improvements **to Eglot**.  I have no idea how Gentoo packaging works, and I don't know if the Makefile is a good instrument to use there.  Maybe you could check how Gentoo packages other Emacs packages?
