### ISSUE TITLE
request for startup hook

### ISSUE THREAD

**Issue by brown** [joaotavora/eglot#554]
Thanks very much for implementing Eglot!  I'm having a lot of fun using it.

I would like to modify eglot-server-programs, so that I can use a different LSP server for Java.  Ideally, Eglot would have a hook that's executed when it starts, but before it looks at eglot-server-programs to select a server.  With such a hook, I could mutate eglot-server-programs so that the server I want is present in eglot-server-programs.

Without such a hook, I either need to set eglot-server-programs in my .emacs file or alternatively load Eglot in my .emacs file, then mutate eglot-server-programs.  The first approach means my setting will become stale as Eglot evolves.  The second approach makes Emacs start more slowly.

Again, thanks for creating Eglot.  I am successfully using it with java-language-server instead of eclipse-jdt.

**Comment by joaotavora** [comment]
Hi.  I don't understand your problem fully ,I admit, but have a look at `with-eval-after-load` which is a way to run code just after Eglot loads, even if it loads lazily (which seems to be what you want.)

```lisp
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs (thingy)))
```

let me know if this works, and if it doesn't I'll reopen.

**Comment by brown** [comment]
Thanks very much for that suggestion.  I didn't know about
with-eval-after-load.
It's just what I needed.

Please consider mentioning it in the README.md where you discuss changing
eglot-server-programs ... the "foo-mode" "foo-language-server" example.

Thanks again!

**Comment by joaotavora** [comment]
> Please consider mentioning it in the README.md where you discuss changing eglot-server-programs ... the "foo-mode" "foo-language-server" example.

As you have seen, this functionality is generic to every package, not just Eglot, so I'm not too sure it belongs in its readme.

**Comment by brown** [comment]
I know it's not Eglot specific, but wrapping the add-to-list form with an
eval-after-load only increases the length of the README by one line and may
help other users who want to change eglot-server-programs.  I've been using
various versions of Emacs since the late 70s, but have never used
with-eval-after-load.  Emacs is complicated enough that no one knows every
feature.  It seems that most users who want to change eglot-server-programs
would also want to do so using with-eval-after-load.

Thanks again for working on Eglot and responding to my issue posting.

I sent a pull request your way to add a bit more information about the use
of .dir-locals.el.  It's also not Eglot specific, but would have saved me
some time as I was configuring .dir-locals.el files for various projects.
The PR is https://github.com/joaotavora/eglot/pull/555

**Comment by lolbinarycat** [comment]
> I know it's not Eglot specific, but wrapping the add-to-list form with an
eval-after-load only increases the length of the README by one line and may
help other users who want to change eglot-server-programs.  I've been using
various versions of Emacs since the late 70s, but have never used
with-eval-after-load.  Emacs is complicated enough that no one knows every
feature.  It seems that most users who want to change eglot-server-programs
would also want to do so using with-eval-after-load.

seconding this, i knew this function existed, but i was struggling to find it.  all my searching kept pointing me towards `add-package`.
