### ISSUE TITLE
Digestify not working out of box

### ISSUE THREAD

**Issue by HumHongeKamyaab** [joaotavora/eglot#559]
Tried following,

$ emacs -Q
$$ package-install eglot
$$ find-file foo.tex
$$ M-x eglot

Getting following error
```
Searching for program: No such file or directory, digestif
```

The documentation says it should run out of box.

I am using GNU Emacs 27.1

**Comment by muffinmad** [comment]
How did you install `digestif`?

Is the folder containing `digestif` listed in `exec-path`?

In other words `(executable-find "digestif")` must return absolute file name of `digestif` executable so Eglot be able to execute it.

**Comment by skangas** [comment]
More information was requested, but none was given within 12 months, so I'm closing this bug. Please report back with more information and we can re-open. Thanks!
