### ISSUE TITLE
Question: adding more servers ; texlab for latex

### ISSUE THREAD

**Issue by ssnnoo** [joaotavora/eglot#561]
eglot already supports digestif for latex-mode, but [texlab](https://texlab.netlify.app) would work as well:

(add-to-list 'eglot-server-programs '((tex-mode context-mode texinfo-mode bibtex-mode) . ("texlab")))

do you plan to add multiple servers as defaults to eglot? or should these just be mentioned in the readme as further options users can add themselves?

**Comment by joaotavora** [comment]
> do you plan to add multiple servers as defaults to eglot? o

No, there's only one "default" servers. If you don't do anything else, Eglot assumes you might like that one, in case you have it installed. Configuring different servers is supposed to be easy enough.

> or should these just be mentioned in the readme as further options users can add themselves?

I don't understand what you're proposing, but I'd say, in general, there's no need to change Eglot's README, unless you want to change the default recommendation from digestif to texlab. Or if texlab is extremely popular, or something.

**Comment by ssnnoo** [comment]
Was just thinking about users searching for e.g. texlab emacs. For beginners it would be nice if one would find a mention that this works with eglot. Hence, a list of known working servers that are not the default servers. Sorry, this was not very clear in my message.

**Comment by joaotavora** [comment]
> For beginners it would be nice if one would find a mention that this works with eglot.

Well, you can contact the server's page. And I guess if you propose a pull request, we can mention and link to texlab in the same bullet as "digestiv".

Anyway, if I may vent about this, your request is not the first time something like this comes up.  I must say I am always suprised at how the basic purpose of LSP continues to ilude us. LSP's point that every client works with every server, as long as both follow the protocol. So it doesn't make sense to ask for LSP client A to work with LSP server B. It doesn't help, in my opinion that some server devs and some client devs are frequently deviate from the protocol. That contributes to the misunderstanding.

**Comment by ssnnoo** [comment]
> So it doesn't make sense to ask for LSP client A to work with LSP server B. 

Very true! Though this might be a bit in contrast to the message from the eglot readme, where it says:

"Let me know how well it works and we can add it to the list."

Probably this would be more something for a wiki page "user reports of servers that work and how they got them to work" and not so much for the readme? Don't know.

> It doesn't help, in my opinion that some server devs and some client devs are frequently deviate from the protocol. That contributes to the misunderstanding.

Yes, this is a shame... I completely agree this should not be encouraged.

**Comment by joaotavora** [comment]
> Very true! Though this might be a bit in contrast to the message from the eglot readme, where it says:

> "Let me know how well it works and we can add it to the list."

You're right: the message doesn't help there.  In the beginning, Eglot's capabilities were limited, and I tested with very few servers.  Nowadays I am more confident in Eglot, so that could be rephrased a bit.  Maybe add "Any server should be supported by Eglot, but some servers are quirky, or maybe Eglot's being quirky.  If you suspect some non-conformance, let the Eglot team know."  Or something like that
