### ISSUE TITLE
project 0.3.0 requires emacs 26.3 which breaks Debian stable's emacs (26.1)

### ISSUE THREAD

**Issue by lbt** [joaotavora/eglot#562]
See: https://elpa.gnu.org/packages/project-0.3.0.el

Package-Requires: ((emacs "26.3"))

**Comment by joaotavora** [comment]
How is this an Eglot bug?  Where exactly is the breakage?  Are you saying you'd like project.el to only require 26.1? Maybe that can be arranged, but you should submit this as a bug to bug-gnu-emacs@gnu.org (when you get the bug confirmation mail, CC me in the reply.  Do not CC me in the original bug report, that doesn't work).

**Comment by lbt** [comment]
My mistake - thought you'd care about such a large user base especially given the "Doesn't *require* anything other than Emacs" philosophy.

**Comment by joaotavora** [comment]
`project.el` _is_ a part of Emacs.  I never said I don't care about anything or anyone.  I just want to understand what the problem is.

**Comment by lbt** [comment]
You closed the bug immediately which didn't signify that you wanted more information related to eglot :)

So when loading via MELPA I am getting:
  package-compute-transaction: Package ‘emacs-26.3’ is unavailable

I pulled in the latest git and noticed that dependency in this line:
  https://github.com/joaotavora/eglot/blob/master/eglot.el#L10
and assumed that was the issue
 
Although I just noticed that is not in the 1.6 tagged version so it's not (yet) that.

Following the package dependencies in MELPA it shoudl not be asking for 26.3

**Comment by joaotavora** [comment]
Please open the bug in Emacs as I suggested.

**Comment by joaotavora** [comment]
I've opened the bug. In principle there should be no great problem in asking for 26.1 in project.el and xref.el

**Comment by nemethf** [comment]
(João's bug report is here: https://lists.gnu.org/archive/html/bug-gnu-emacs/2020-11/msg01069.html)

#483 is related.  To circumvent the issue I put the following in my init file, which used to work but I'm not so sure about it.
```
(when (version= emacs-version "26.1")
  (setq emacs-version "26.3"))
```
