### ISSUE TITLE
yankpad support

### ISSUE THREAD

**Issue by arkhan** [joaotavora/eglot#564]
Greetings what a great job with this package, I would like to know if you can add support for [yankpad](https://github.com/Kungsgeten/yankpad) as an alternative to yasnippet.

Thanks

**Comment by muffinmad** [comment]
Does `yankpad` is able to handle snippets returned by LSP server?

Take a look at the `eglot--snippet-expansion-fn` function. You can try to make it work by overriding it, e.g.:

```elisp
(advice-add 'eglot--snippet-expansion-fn :override
	    (lambda ()
	      'some-yankpad-expand-snippet-function))
```

If this will work, then IMO snippet expansion function can be made customizable option.

**Comment by arkhan** [comment]
@muffinmad thanks for answering, but what I'm looking for is the autocompletion of snippets using yankpad, through company, when I deactivate eglot the autocompletion works fine, but when it is active it only autocompletes the keys of the programming language.
- **with eglot**
![imagen](https://user-images.githubusercontent.com/3141865/99072892-e43b4d80-2582-11eb-9847-3e1b7ae44529.png)
- **without eglot**
![imagen](https://user-images.githubusercontent.com/3141865/99072946-ff0dc200-2582-11eb-891a-00e9c126f54a.png)

**Comment by muffinmad** [comment]
Eglot is [overriding company-backends](https://github.com/joaotavora/eglot/blob/21726416e6e580b20dfa90833c6dab2a8a15ea48/eglot.el#L1358). The `eglot-stay-out-of` variable is what you are looking for.

> For example, to keep your Company customization use
> (add-to-list 'eglot-stay-out-of 'company)

**Comment by arkhan** [comment]
@muffinmad thanks, it works quite well, so I have my configuration:

- eglot
```emacs-lisp
(leaf eglot
  :straight t
  :require t
  :setq  ((eglot-ignored-server-capabilites . '(:hoverProvider))
          (eglot-sync-connect . 1)
          (eglot-connect-timeout . 10)
          (eglot-autoshutdown . t)
          (eglot-send-changes-idle-time . 0.5)
          (eglot-auto-display-help-buffer . nil))
  :config
  (add-to-list 'eglot-stay-out-of 'company))
```
- Snippeet
```emacs-lisp
(leaf yasnippet
  :straight t
  :leaf-defer nil
  :hook (after-init-hook . yas-global-mode))

(leaf yankpad
  :straight t
  :leaf-defer nil
  :setq ((yankpad-file . "~/.emacs.d/yankpad.org")
         (yankpad-category . "Category: Default"))
  :init
  (defun company-mode-backend-with-yas (backend)
    "Update BACKEND with YaSnippet."
    (if (or (and (listp backend) (member 'company-yankpad backend)))
        backend
      (append (if (consp backend) backend (list backend))
              '(:with company-yankpad))))

  (defun company-mode-update-backends-with-yasnippet ()
    "Update the backends of company and turn on YaSnippet."
    (setf company-backends (mapcar #'company-mode-backend-with-yas company-backends)))

  :hook (company-mode-hook . company-mode-update-backends-with-yasnippet))

```
