### ISSUE TITLE
javascript-typescript-stdio is deprecated

### ISSUE THREAD

**Issue by kouhin** [joaotavora/eglot#566]
`javascript-typescript-langserver` is no longer maintained, see https://github.com/sourcegraph/javascript-typescript-langserver 

[Theia's TypeScript language](https://github.com/theia-ide/typescript-language-server) server may be a better choice.

**Comment by muffinmad** [comment]
kouhin <notifications@github.com> writes:

> `javascript-typescript-langserver` is no longer maintained, see
> https://github.com/sourcegraph/javascript-typescript-langserver

Same thing for haskel-ide-engine:
https://lists.gnu.org/archive/html/emacs-devel/2020-11/msg00379.html

And for php: https://github.com/joaotavora/eglot/issues/537

I wonder how these issues may be solved.  Changing entry in the
eglot-server-programs variable will work for those new users who
installed new language server but will break setup for existing users
who uses old language server.  Maybe multiple entries in
eglot-server-programs (https://github.com/joaotavora/eglot/issues/90) is
the way to go?

**Comment by terlar** [comment]
Using the suggested typescript-language-server I got the following error, looking at the JSON serialize function it includes both `utf-16` and `utf-32`, the latter being used as a lookup symbol somewhere:
```
Debugger entered--Lisp error: (wrong-type-argument symbolp "utf-32")
```

```
json-serialize((:jsonrpc "2.0" :id 1 :method "initialize" :params (:processId 2839 :rootPath "/home/terje.larsen/src/github.com/terlar/exercism-workspace/" :rootUri "file:///home/terje.larsen/src/github.com/terlar/ex..." :initializationOptions #<hash-table eql 0/65 0x3d19d4d> :capabilities (:workspace (:applyEdit t :executeCommand (:dynamicRegistration :json-false) :workspaceEdit (:documentChanges :json-false) :didChangeWatchedFiles (:dynamicRegistration t) :symbol (:dynamicRegistration :json-false) :configuration t) :textDocument (:synchronization (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t) :completion (:dynamicRegistration :json-false :completionItem (:snippetSupport t) :contextSupport t) :hover (:dynamicRegistration :json-false :contentFormat ["markdown" "plaintext"]) :signatureHelp (:dynamicRegistration :json-false :signatureInformation (:parameterInformation (:labelOffsetSupport t))) :references (:dynamicRegistration :json-false) :definition (:dynamicRegistration :json-false) :declaration (:dynamicRegistration :json-false) :implementation (:dynamicRegistration :json-false) :typeDefinition (:dynamicRegistration :json-false) :documentSymbol (:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind (:valueSet [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26])) :documentHighlight (:dynamicRegistration :json-false) :codeAction (:dynamicRegistration :json-false :codeActionLiteralSupport (:codeActionKind (:valueSet ...)) :isPreferredSupport t) :formatting (:dynamicRegistration :json-false) :rangeFormatting (:dynamicRegistration :json-false) :rename (:dynamicRegistration :json-false) :publishDiagnostics (:relatedInformation :json-false)) :experimental #<hash-table eql 0/65 0x3d19d4d> :xfilesProvider t :xcontentProvider t :offsetEncoding ("utf-32" "utf-16")))) :false-object :json-false :null-object nil)
```

**Comment by jangid** [comment]
The default value can be overridden using following snippet and works really nice.

```
  (add-to-list 'eglot-server-programs
               '((js-mode typescript-mode)
                 "typescript-language-server" "--stdio"))
```

For the above code to work, you must install `typescript-language-server`:

```
npm install -g typescript-language-server
```

Yes. I install all the dev-tools globally.

`typescript-language-server` is well maintained - https://github.com/theia-ide/typescript-language-server. @joaotavora, what is the criteria to include that as default. I think that is a better choice. Although, that might break some friends' config. But we a warning this can be updated.

**Comment by joaotavora** [comment]
I'm using that one as well.  Feel free to make a pull request.

**Comment by joaotavora** [comment]
I tested a bit and pushed a commit that does this.
