### ISSUE TITLE
Feature request: ability to disable eglot xref backend

### ISSUE THREAD

**Issue by kevin8t8** [joaotavora/eglot#569]
First, I'd like to say thank you for making such a nice, and easy to get running, package.  I installed the eglot package from melpa, the ccls program, and things just started working!

I wasn't happy with how the new `M-.` functionality was working though.  I'm a long-time tags user, so I wanted a way to turn that part of eglot off and leave everything else running.

I'm a novice with elisp, but I looked through eglot, and found a few things to try:
``` elisp
(add-to-list 'eglot-stay-out-of 'xref-find-definitions)
;; -or-
(add-to-list 'eglot-stay-out-of 'xref)
```
didn't seem to do anything.

```elisp
(add-to-list 'eglot-ignored-server-capabilites :definitionProvider)
```
seemed to completely disable `M-.` from working.

In the end, I put
``` elisp
(use-package eglot
  :ensure t
  :config
  (defun eglot-xref-backend () "EGLOT xref backend." nil))
```
in my init.el, but I'm worried this is not a long-term reliable way of doing this.  Is there a better way, or if not, would you consider adding an "official" way to turn off the eglot xref backend?

Thank you!

**Comment by joaotavora** [comment]
Hi Kevin, thanks for the praise, what you described is really what I'm trying to put together.

> (add-to-list 'eglot-stay-out-of 'xref)

This, or something like this, should work.  That is doesn't can be viewed as a bug, and a hint that I never expected people to want to turn that part of.  But indeed, they may well want to.  So I'll change the `eglot.el` source code to allow for it.

> in my init.el, but I'm worried this is not a long-term reliable way of doing this. Is there a better way, or if not, would you consider adding an "official" way to turn off the eglot xref backend?

I'll add the interface above.  But this isn't a very bad way either.  It relies on an external Eglot symbol and an interface that is unlikely to change.

**Comment by kevin8t8** [comment]
> I'll add the interface above. But this isn't a very bad way either. It relies on an external eglot.el symbol and an xref.el interface that is unlikely to change.

Great!  I'll keep my workaround until the next release.  Thank you for the quick response. :)

**Comment by dgutov** [comment]
Note that you can turn on `xref-etags-mode` to force `xref` to use `etags` in the current buffer.

To do it automatically, I think you can use `eglot-managed-mode-hook`.

**Comment by kevin8t8** [comment]
Thank you, and also to @dgutov for the tip.
