### ISSUE TITLE
eglot reconnects automatically after desktop-clear 

### ISSUE THREAD

**Issue by xwl** [joaotavora/eglot#571]
I thought desktop-clear should close all buffers, kill all running subprocesses, etc, but I noticed eglot server will reconnect right after desktop-clear, even though there is not any file buffers opened.

Is this expected behavior?

More background info, i run ccls via ssh server, when i disconnect from the server, i'd like to clear all buffers in emacs, so that emacs is not blocking or hanging by running eglot.

**Comment by muffinmad** [comment]
See the `eglot-autoreconnect` and `eglot-autoshutdown` variables.

**Comment by xwl** [comment]
Thanks, (setq eglot-autoshutdown t) is just what i need.
