### ISSUE TITLE
Not successful using with OmniSharp

### ISSUE THREAD

**Issue by intrasight** [joaotavora/eglot#573]
Hi,

I'm attempting to use eglon for C# development. Not having much success.

I have VSCode installed and also the omnisharp extension. So I pointed eglot
to OmniSharp.exe in my init.el:

(use-package csharp-mode)

(use-package company)

(use-package eglot
    :commands eglot
    :config
    (add-to-list 'eglot-server-programs '(csharp-mode . ("C:/Users/chris/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/OmniSharp.exe" "-stdio" "-lsp")))
)

When I try to run an eglot command, I get the error

jsonrpc-error: jsonrpc-error: "No current JSON-RPC connection", (jsonrpc-error-code . 32603), (jsonrpc-error-message . "No current JSON-RPC connection")
[jsonrpc] Server exited with status 9
Error running timer: (error "[eglot] Timed out")

Hoping that someone who has succeeded with OmniSharp can set me straight.

**Comment by joaotavora** [comment]
Do you have an Emacs buffer called `*EGLOT (<project>/csharp-mode) events*`?  If so, it would be nice to see its contents.  Most likely launching the exe failed and noone can help you unless they discover why.

**Comment by intrasight** [comment]
I do. an events buffer and a output buffer

events:

client-request (id:1) Fri Dec 18 11:13:43 2020:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 5780 :rootPath "c:/Users/chris/shufflepoint/test_eglot/" :rootUri "file:///c:/Users/chris/shufflepoint/test_eglot/" :initializationOptions nil :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges :json-false)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t)
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport :json-false)
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false :contentFormat
                                              ["markdown" "plaintext"])
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false)
                        :declaration
                        (:dynamicRegistration :json-false)
                        :implementation
                        (:dynamicRegistration :json-false)
                        :typeDefinition
                        (:dynamicRegistration :json-false)
                        :documentSymbol
                        (:dynamicRegistration :json-false :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"])))
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false))
                       :experimental nil)))

internal Fri Dec 18 11:14:13 2020:
(:message "Connection state changed" :change "unknown signal\n")


----------b---y---e---b---y---e----------


output buffer has two errors at the end:

{"Event":"error","Body":"\"Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: C. Path '', line 0, position 0.\\r\\n   at Newtonsoft.Json.JsonTextReader.ParseValue()\\r\\n   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)\\r\\n   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)\\r\\n   at OmniSharp.Protocol.RequestPacket.Parse(String json) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Protocol\\\\RequestPacket.cs:line 12\\r\\n   at OmniSharp.Stdio.Host.<HandleRequest>d__13.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:line 198\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Stdio.Host.<>c__DisplayClass12_0.<<Start>b__2>d.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:line 152\"","Seq":18,"Type":"event"}

{"Event":"error","Body":"\"Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.\\r\\n   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)\\r\\n   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)\\r\\n   at OmniSharp.Protocol.RequestPacket.Parse(String json) in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Host\\\\Protocol\\\\RequestPacket.cs:line 12\\r\\n   at OmniSharp.Stdio.Host.<HandleRequest>d__13.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:line 198\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at OmniSharp.Stdio.Host.<>c__DisplayClass12_0.<<Start>b__2>d.MoveNext() in D:\\\\a\\\\1\\\\s\\\\src\\\\OmniSharp.Stdio\\\\Host.cs:line 152\"","Seq":19,"Type":"event"}

**Comment by joaotavora** [comment]
Where did you get this "output buffer"?  What is the buffer's name?

**Comment by intrasight** [comment]
I see three EGLOT buffers in emacs:

  * *EGLOT (test_eglot/csharp-mode) stderr*                 56 Fundamental      
 %* *EGLOT (test_eglot/csharp-mode) output*               5804 Fundamental      
 %* *EGLOT (test_eglot/csharp-mode) events*               3560 Fundamental

**Comment by joaotavora** [comment]
You're likely using an older version of Eglot or have not yet updated some packages.  No matter.  Can you also post the contents of the stderr buffer, if any?

**Comment by intrasight** [comment]
I just installed everything (emacs, eglot, onmnisharp) yesterday.

contents of stderr:

`
Process EGLOT (test_eglot/csharp-mode) stderr finished
`

**Comment by joaotavora** [comment]
OK.  ANyway, no idea what omnisharp is speaking, but it sure doesn't seem to be LSP...

**Comment by intrasight** [comment]
Like I said, I just pointed eglot to the version of OmniSharp.exe that the VSCode extension installed.
The next thing I was planning to do was to install a separate version from 
https://awesomeopensource.com/project/OmniSharp/omnisharp-roslyn

**Comment by joaotavora** [comment]
I don't have windows and/or any of these servers.  I have no clue what VSCode installs or how it talks to processes.  Eglot just supports LSP.  I _think_ people have gotten it to work.  My basic googling brings me here: https://github.com/joaotavora/eglot/issues/241

**Comment by joaotavora** [comment]
INdeed, I think it's better to continue that discussion there, seems to be exactly the same problem.  Closing this one.

**Comment by joaotavora** [comment]
(also probably more people are notified of it and can help you)

**Comment by intrasight** [comment]
Thanks! That thread did have a config setting that worked for me.

**Comment by joaotavora** [comment]
Fantastic!
