### ISSUE TITLE
Broken fuzzy completion with gopls.

### ISSUE THREAD

**Issue by muirdm** [joaotavora/eglot#575]
eglot's completion integration does not seem compatible with gopls fuzzy completion. For example:

```go
package main

func fooBar() {}

func _() {
  fb<>
}
```

Completing at `<>` should offer "fooBar", but eglot does not offer it. It seems like eglot is filtering completion candidates client side, but that is not desirable in this case.

```
[server-reply] (id:114) Tue Dec 22 08:55:15 2020:
(:jsonrpc "2.0" :result
          (:isIncomplete t :items
                         [(:label "fooBar" :kind 3 :detail "func()" :preselect t :sortText "00000" :filterText "fooBar" :insertTextFormat 2 :textEdit
                                  (:range
                                   (:start
                                    (:line 5 :character 1)
                                    :end
                                    (:line 5 :character 3))
                                   :newText "fooBar()"))
                          (:label "fbsdutil" :kind 9 :detail "\"github.com/go-delve/delve/pkg/proc/fbsdutil\"" :sortText "00001" :filterText "fbsdutil" :insertTextFormat 2 :textEdit
                                  (:range
                                   (:start
                                    (:line 5 :character 1)
                                    :end
                                    (:line 5 :character 3))
                                   :newText "fbsdutil")
                                  :additionalTextEdits
                                  [(:range
                                    (:start
                                     (:line 1 :character 0)
                                     :end
                                     (:line 1 :character 0))
                                    :newText "\nimport \"github.com/go-delve/delve/pkg/proc/fbsdutil\"\n")])])
          :id 114)
```

**Comment by muffinmad** [comment]
What completion do you use? I.e. `company-mode`, `completion-at-point` etc.

**Comment by muirdm** [comment]
> What completion system do you use?

company-mode

**Comment by joaotavora** [comment]
I can't reproduce this.  Unfortunately, becasue I'm such a Go newbie, i can't tell which version of `glpls` I'm using though.  I think we need an Emacs -Q recipe, to rule out interference from external factors/  @muirdm you know how those go?  You can assume I have `gopls` in my path.

**Comment by joaotavora** [comment]
> company-mode

BTW I'm also using company mode.  here's my Emacs -Q recipe
```
emacs -Q -f package-initialize -L eglot/ -l eglot -L company-mode -l company -f global-company-mode main.go -f eglot
```

**Comment by joaotavora** [comment]
OK I got it.  It doesn't work with Emacs 26.3, only with Emacs >= 27, and you must add `flex` to your configuration of `completion-styles`.  

```
(add-to-list 'completion-styles 'flex)
```

Then it should work.

**Comment by muirdm** [comment]
Ah, great. I'll make sure the the gopls eglot documentation mentions this. Thanks!

**Comment by joaotavora** [comment]
> Ah, great. I'll make sure the the gopls eglot documentation mentions this. Thanks!

OK, though I think I'll just make `flex` the default completion style while Eglot-managing a buffer, so that bit of configuration will soon be useless, and you just need to ensure to have Emacs 27.

**Comment by muirdm** [comment]
OK - even better.

**Comment by muffinmad** [comment]
> > Ah, great. I'll make sure the the gopls eglot documentation mentions this. Thanks!
> 
> OK, though I think I'll just make `flex` the default completion style while Eglot-managing a buffer, so that bit of configuration will soon be useless, and you just need to ensure to have Emacs 27.

Does this means that user customization of the `completion-styles` variable will be overridden?

**Comment by joaotavora** [comment]
> Does this means that user customization of the completion-styles variable will be overridden?

Yes, but only buffer-locally, and you can use `eglot-stay-out-of` to avoid it.

**Comment by joaotavora** [comment]
> This doesn't appear to be the case anymore since a1fb92543ccd21375f21143939a29445016d56ee.

_What_ isn't the case anymore? Eglot doesn't even touch `completion-styles`  anymore.

**Comment by joaotavora** [comment]
> Instead of setting `completion-styles' using `eglot--setq-saving', the
> `eglot' category is unconditionally set as part of the completion metadata.

Good, no?  Much more elegant. Eglot sets up a category for use in Eglot's completion functions, which need the category.

**Comment by joaotavora** [comment]
Aha. I figured this was your doubt: but here's the thing: you could _not_ disable it anyway.  You do not have control over the style of completion when using LSP uses.  The reason `flex` is there is purely to provide semi-sensible highlighting.  It is just a guess as to what style of completion the server is doing. It may be wrong, but it isually correct. If the server does one of {flex,prefix,substring}, the `flex` logic highlights the pattern correctly.  But the selection of the completions itself based on the pattern is out of Eglot's control.

**Comment by joaotavora** [comment]
Unless you can convince the developers of the LSP spec and all the server implementations to somehow understand Emacs's Elisp completion styles, you're going to be slightly annoyed for a long time.

**Comment by Keisn1** [comment]
I've noticed recently that fuzzy matching with gopls didn't work anymore with my Configuration.  

This was my previous configuration
`(setq-default eglot-workspace-configuration
              '((:gopls .
                        ((staticcheck . t)
                         (matcher . "CaseSensitive")
                         (symbolScope . "workspace")
                         ))))
`

Commenting out ~(matcher . "CaseSensitive"~ helped resolving the problem. Maybe it's related to a gopls update. I leave this here if anyone comes by the same issue.

**Comment by Keisn1** [comment]
I've noticed recently that fuzzy matching with gopls didn't work anymore with my Configuration.

This was my previous configuration
```elisp
(setq-default eglot-workspace-configuration
              '((:gopls .
                        ((staticcheck . t)
                         (matcher . "CaseSensitive")
                         (symbolScope . "workspace")
                         ))))
```

Commenting out `(matcher . "CaseSensitive")` helped resolving the problem. Maybe it's related to a gopls update. I leave this here if anyone comes by the same issue.
