### ISSUE TITLE
Company doc buffer should be cleared between invocations

### ISSUE THREAD

**Issue by Kaali** [joaotavora/eglot#58]
In `eglot-completion-at-point` at `:company-doc-buffer`, eglot appends the documentation to the same buffer. Which means that company help and company-quickhelp will display increasingly large documentation which is shared between all eglot servers.

For example if I get documentation in a Javascript project and then in a Python project. The documentation shows a large buffer of both.

company-mode has a helper function `company-doc-buffer` which can be used to create a documentation buffer, which is erased. Or the current implementation should just call `erase-buffer` when showing completions.

**Comment by joaotavora** [comment]
Thanks!
