### ISSUE TITLE
eglot fortran

### ISSUE THREAD

**Issue by fab6** [joaotavora/eglot#581]
Hi,
I am trying out different options to handle some fortran projects; so I am still fairly new to any tagging or lsp.

With given fortls as the server tool I can connect to it 

![image](https://user-images.githubusercontent.com/3047695/103512207-a06d1200-4e68-11eb-8c56-e9b8b6ea4e1f.png)

```
Loading eldoc...done
[eglot] Connected! Server `EGLOT (fds/f90-mode)' now managing `f90-mode' buffers in project `fds'.
```
Though I am having some trouble get anything working with it:
```
helm-M-x-execute-command: [eglot] Sorry, this server doesn't do :textDocument/declaration
helm-M-x-execute-command: [eglot] Sorry, this server doesn't do :textDocument/typeDefinition
helm-M-x-execute-command: [eglot] Server can't execute code actions!
```
Do you have an idea?
I am not sure, if this is more related to fortls or eglot...
Thank you in advance!

**Comment by ssnnoo** [comment]
Hi, just tried eglot with fortls and everything works for me as expected. Just in case that helps.

**Comment by fab6** [comment]
Hi, thank you, do you have any special settings?
I am just thinking that the path is maybe not available (I am on macos) ... though python works.

**Comment by ssnnoo** [comment]
No special settings, simply started fortls -> (add-to-list 'eglot-server-programs '(f90-mode . ("fortls"))), you could check your path via (message (getenv "PATH")) and maybe set it with  (setenv "PATH" (concat "/usr/local/bin/" ":" "/Library/TeX/texbin" ":" (getenv "PATH"))) or something like that.

Does M-. work at all?

**Comment by fab6** [comment]
Thank you!
Path seem to work.
Now I get:
```
helm-M-x-execute-command: Lisp nesting exceeds ‘max-lisp-eval-depth’
```
And M-. does not work.

**Comment by skangas** [comment]
The above looks like a helm error, at a glance, so I would probably take that to the helm developers.

If you are still seeing this, could you say `M-x toggle-debug-on-error` and post the resulting backtrace?

**Comment by fab6** [comment]
Hi, just saw your reply,  fyi: I am not using `helm` anymore, but `vertico/consult/embark/marginalia` in combination with `lsp-mode`

**Comment by skangas** [comment]
OK, it unfortunately seems like we can't make any further progress here, so I'm closing this issue. Thanks.
