### ISSUE TITLE
Define a face for symbol highlight

### ISSUE THREAD

**Issue by astoff** [joaotavora/eglot#583]
I think Eglot should define its own face for the "Highlight symbols automatically" feature instead directly using the generic `highlight` face.

Since, as far as I know, Emacs doesn't have a similar built-in feature, there must not be a more specific predefined face to choose from.  On the other hand, the `highlight` face is used and works well at many places (so one might not want to change it) but is too salient for the "highlight symbols" feature (at least to my taste).

The safest default value for the new face would probably still be `:inherit highlight`, although `:inherit bold` might be a nicer option for most themes.

**Comment by joaotavora** [comment]
> Since, as far as I know, Emacs doesn't have a similar built-in feature, there must not be a more specific predefined face to choose from. 

Yes, you are right.  Do you have a copyright assignment? A clean pull request where I can just press the big green button would be nice.  The name should be, I guess, `eglot-highlight-symbol-face`?

> The safest default value for the new face would probably still be :inherit highlight, although :inherit bold might be a nicer option for most themes.

I'll let you decide on that.

**Comment by astoff** [comment]
Ok, I'll work on this (including getting the copyright assignment, which might take some time). The linked issue suggests something other than inheriting from highlight might indeed be a better default, I'll think about the alternatives.

**Comment by joaotavora** [comment]
> (including getting the copyright assignment, which might take some time).  

You should work on that, but you can skip it for this, becasue this should be around 4 or 5 lines.  I'll mark your change `Copyright-paperwork-exempt: yes`.

**Comment by rvlo** [comment]
@astoff, I'll answer your question here: I tested with :weight bold and it didn't cause any visual disruptions. But I thought it didn't really serve the purpose of making the occurrences evident. What I'm using is a not so "in your face" (pun intended) background color, but enough to make it clear where are the other usages. Something like lsp-mode's: https://emacs-lsp.github.io/lsp-mode/examples/references.png
