### ISSUE TITLE
Eglot with project in Emacs 26.3

### ISSUE THREAD

**Issue by alfons4966** [joaotavora/eglot#585]
If I do:

Emacs -Q (Emacs 26.3)
M-x package-list-packages
install eglot 1.7
It installs:
  eglot              1.7           installed  Client for Language Server Protocol (LSP) servers
  eldoc              1.11.0        dependency Show function arglist or variable docstring in echo area
  flymake            1.0.9         dependency A universal on-the-fly syntax checker
  jsonrpc            1.0.14        dependency JSON-RPC library
  project            0.5.3         dependency Operations on the current project
  xref               1.0.4         dependency Cross-referencing commands
Open a project directory with a .git directory in project root
M-x eglot

This results in:
eglot--connect: Symbol’s function definition is void: project-root

**Comment by joaotavora** [comment]
> project 0.5.3 dependency Operations on the current project

If project 0.5.3 was indeed installed, then I find this odd.  But it may be that you're bumping into a package.el bug.  Can you simply restart Emacs after that, evaluate `package-initialize`, and try again?

**Comment by alfons4966** [comment]
Thank you for you fast response!

I did a package-initialize. Exited. Removed my complete ~/.emacs.d/elpa dir. Restarted Emacs with -Q and did the same steps as written above ... with the same result.   But maybe this is an project.el bug.  Note, I usually use Straight as my package manager.  If I run Emacs with my Straight package manager (i.e. without -Q), project.el is version 0.5.1.  However, also with project 0.5.1 I have issues.

**Comment by joaotavora** [comment]
No, you're not following, I think. I mean, the very first _from scrach_ load of Eglot and its dependencies will fail to start Eglot.  But if you start Emacs again after that, it should work with _only_ the `package-initialize`.

There are some issues in this bug tracker describing similar situations, but I don't have time to get to them right now, sorry.

This is a `package.el` bug, I think, but again it takes too long to describe here.

**Comment by joaotavora** [comment]
Let me try to describe the situation briefly. `project.el` version 0.5.3 _has_ `project-root`, singular.  But `project.el` is also bundled with Emacs 26.3, in a version that doesn't have it.  When you install 0.5.3 in a new Emacs 26.3, it should also _load_ that version into memory, not just compile it.  I think `package.el` or maybe your Straight .el package manager has failed to do that.

There have been a fair number of issues with Straight before, so you might have luck asking its maintainer.

**Comment by joaotavora** [comment]
Ping @raxod502 and also see https://github.com/joaotavora/eglot/issues/492

**Comment by alfons4966** [comment]
I propose to close this ticket.  I did what you suggested, I did a package-initialize and it now works!  Thanks!   It is indeed a `package.e`l issue.

**Comment by joaotavora** [comment]
>    It is indeed a package.el issue.

Or maybe a Straight.el issue.  Didn't you say you used that? Anyway, good news.

**Comment by alfons4966** [comment]
Dear João Távora,

In eglot version 1.7, dependencies are listed as:

;; Package-Requires: ((emacs "26.1") (jsonrpc "1.0.14") (flymake "1.0.9") (project "0.3.0") (xref "1.0.1") (eldoc "1.11.0"))

Straight uses this to install project version 0.5.1. However, it needs version 0.5.3.  So is the package requires list not a bug?

Regards

**Comment by joaotavora** [comment]
Dear Alfons,

I believe that the package requires list is correct.  Eglot _needs_ version 0.3.0, but it can work with 0.5.3 which maintains so-called backward compatibility to 0.3.0.

You can verify this in the Emacs commits surrounding this one.
```
commit 3f66908ee0821d638ec9bf4360400cbd2e58f70a
Author: Dmitry Gutov <dgutov@yandex.ru>
Date:   Mon May 25 22:29:47 2020 +0300

    Bump project.el version [to 0.3.0]
    
    * project.el: Bump the version
  ```

My very best regards,

**Comment by alfons4966** [comment]
Dear João,

But there is no backwards compatibility as `project.0.5.1` doesn't define `project-root`:

`helm-M-x-execute-command: Symbol’s function definition is void: project-root`

but `project.0.5.3` does. How can Straight know that it must install project.0.5.3 instead of project.0.5.1 as the minimum dependency is 0.3.0?
 
Regards,

PS. I prefer `eglot` over `lsp-mode` but apart from that `lsp-mode` has a far more serious problem. (It seems always to ignore compile_commands.json in the root dir.)

**Comment by joaotavora** [comment]
> as project.0.5.1 doesn't define project-root

I don't know what file you are looking at but I quit certain I am looking at 0.5.1 and `project-root` is defined there, as it should be.  

https://github.com/emacs-mirror/emacs/blob/319463920ca8829dcdfa6c0c8c1c8ff15091f6f0/lisp/progmodes/project.el

You are experiencing some other sort of problem, surely.
