### ISSUE TITLE
C++ Standards

### ISSUE THREAD

**Issue by Spidy104** [joaotavora/eglot#601]
Before submitting an issue, please, read our guidelines
on reporting bugs here:
https://github.com/joaotavora/eglot#reporting-bugs
On default eglot gives auto completion based on c++11 but want to change the standard to c++17 and flymake alseo does checking based on c++11 standard, How to change this?

**Comment by joaotavora** [comment]
Change the way that the language server is invoked or configured.  I suppose some language servers will read this from your `Makefile` or some other kind of project configuration.  Discover which one you are using.  (clangd? ccls?), read its manual and ask about this there.  Maybe read the Eglot README for ways to configure Eglot to invoke these servers with different options.

**Comment by Spidy104** [comment]
Yeah, I am using clangd, but currently have have no make file, I went on its website, there was nothing said about changing the C++ Standards, Thanks and regards...

**Comment by Eason0210** [comment]
@Spidy104  You create a file named `Makefile` in your current directory and put the following code in the first line of the Makefile.
It works for me. 
`CXXFLAGS = -std=c++17`
