### ISSUE TITLE
Dependency on a very recent version of project.el

### ISSUE THREAD

**Issue by DamienCassou** [joaotavora/eglot#604]
eglot depends on `project-root` which *isn't* included in the project.el version provided by Emacs 27.1 (the latest release). Some suggestions:

1. Make eglot.el use whatever project.el provides in the latest release of Emacs;
2. Add an implementation of `project-root` when project.el doesn't define one;
3. Change the README so that it is clear that the user must download a more recent version of project.el.

**Comment by joaotavora** [comment]
It is clear: the README mentions `package-install`.  Eglot depends on lots of features of packages that aren't bundled directly with Emacs 27.1 or 26.3.  It's not just `project.el`.  I'm sorry `package-install` is so underused/misunderstood (and buggy, I guess)

Else, use Emacs master, where everything is.

This issue has been beaten to death in this tracker. So I'm closing.  It's fine to continue discussing, but try to find the other ones, please. Thanks.

**Comment by joaotavora** [comment]
I'm going to do number 3.

**Comment by DamienCassou** [comment]
I think that is an excellent choice. Thank you!

**Comment by yugaego** [comment]
I'm sorry to revive this "beaten to death" issue. Still, I believe it's a good idea to reference one more potential  *"fix"* somewhere.

I couldn't install `eglot` on different Emacs versions (including latest), always getting `not found` errors on variations of packages attempted loads. The solution appeared to be a simple (trivial?) one: `M-x package-refresh-contents`, which is even documented on [Emacs Wiki](https://www.emacswiki.org/emacs/InstallingPackages).

Hope it helps someone else too.
