### ISSUE TITLE
Q: turn off hover ?

### ISSUE THREAD

**Issue by glycerine** [joaotavora/eglot#607]
I love eglot for editing Go, but find the hover "variable definitions" that pops up when I have point on a variable quite distracting. Is there an easy way to turn it off?

**Comment by joaotavora** [comment]
See `eglot-ignored-server-capabilities`.

**Comment by glycerine** [comment]
thank you. this worked. In .emacs:
~~~
(custom-set-variables '(eglot-ignored-server-capabilites '(list :documentHighlightProvider :hoverProvider :signatureHelpProvider)))
~~~

**Comment by joaotavora** [comment]
Great.  You could also have used `setq` directly.  Or even put a `setq-local` in `go-mode-hook`
