### ISSUE TITLE
Allow using more than one language server at a time within a file

### ISSUE THREAD

**Issue by leungbk** [joaotavora/eglot#611]
When working with JavaScript, it is common to want to run the [vscode-eslint](https://github.com/microsoft/vscode-eslint) server for diagnostics, while running a more general-purpose server like the Flow or TypeScript server for definition-hopping and the like.

`lsp-mode.el` supports this kind of set up. It would be nice if `eglot` did as well.

**Comment by joaotavora** [comment]
There are multiple issues for this, try to find the active one and let's close this one. By the way, you can have multiple flymake backends. I have an eslint Flymake backend which can coexist with a language server managed by Eglot.  But I agree this is a desirable feature.  So closing this one, and it's up to you to search the issue archives and link this with the existing issues. Thank you.
