### ISSUE TITLE
flymake works fine but enters debugger when debug-on-error is t

### ISSUE THREAD

**Issue by jangid** [joaotavora/eglot#616]
I have searched through the archive and I understand that is probably due to some drawbacks in flymake. But noting it down for the sake of record. My setup is working fine with java-mode. I am using eclipse.jdt.ls. But whenever I open a java file with debug-on-error set to t, I get an error.

Steps to reproduce:
1. Save the attached file [init_eglot.txt](https://github.com/joaotavora/eglot/files/5904241/init_eglot.txt) as init_eglot.el and fix JAVA_HOME and eclipse.jtd.ls path. (I have added eclipse.jdt.ls git repo as submodule of my emacs init dir).
2. Launch emacs with init_eglot.el loaded
```
$ emacs -Q -l init_eglot.el
```
3. Open any java file

Note: I am using emacs from `master` branch.

Following is the debugger output:

```
Debugger entered--Lisp error: (file-missing "Removing directory" "No such file or directory" "/private/var/folders/lf/kn5fshdx4md8xcmv02rntfzr00...")
  signal(file-missing ("Removing directory" "No such file or directory" "/private/var/folders/lf/kn5fshdx4md8xcmv02rntfzr00..."))
  files--force(nil delete-directory-internal "/private/var/folders/lf/kn5fshdx4md8xcmv02rntfzr00...")
  delete-directory("/private/var/folders/lf/kn5fshdx4md8xcmv02rntfzr00...")
  flymake-proc--safe-delete-directory("/private/var/folders/lf/kn5fshdx4md8xcmv02rntfzr00...")
  flymake-proc--delete-temp-directory("/private/var/folders/lf/kn5fshdx4md8xcmv02rntfzr00...")
  flymake-proc-simple-java-cleanup()
  #f(compiled-function () #<bytecode 0xc1e307acb6ea3a3>)()
  flymake-proc-legacy-flymake(#f(compiled-function (&rest args) #<bytecode 0xa5adc9f6fb77086>))
  apply(flymake-proc-legacy-flymake #f(compiled-function (&rest args) #<bytecode 0xa5adc9f6fb77086>) nil)
  flymake--run-backend(flymake-proc-legacy-flymake nil)
  #f(compiled-function (backend) #<bytecode 0x19db6dba1e69ae55>)(flymake-proc-legacy-flymake)
  run-hook-wrapped(#f(compiled-function (backend) #<bytecode 0x19db6dba1e69ae55>) flymake-proc-legacy-flymake)
  flymake-start((on-display) nil)
  #f(compiled-function () #<bytecode -0x114b0dca89d572cf>)()

**Comment by joaotavora** [comment]
I don't know why but you're still running the legacy, deprecated `flymake-proc` backend.  I say I don't know why because in theory, Eglot is supposed to turn off that backend.  But you haven't shown me a reproducible error recipe like I ask for in the README.md so I don't know what's up.  Have a look and we'll reopen if necessary.

**Comment by jangid** [comment]
I have updated the issue with steps to reproduce.

**Comment by joaotavora** [comment]
Contrary to what I thought, Eglot was still running the global value of `flymake-diagnostic-functions` which includes the deprecated and frequently problematic `flymake-proc-legacy-flymake`.  In normal situations, it shouldn't bother users, but here it did (for some unknown reason).  It's very likely that you don't need it anyway, so now Eglot completely managed `flymake-diagnostic-functions`.  Users wishing to override this behavior can `(add-to-list 'eglot-stay-out-of 'flymake)`.

**Comment by jangid** [comment]
Thanks a lot for the fix. That was too fast. I just pulled from MELPA. And verified. Thanks for all your work.
