### ISSUE TITLE
eclipse.jdt.ls dying because of stale cache (exit code 13)

### ISSUE THREAD

**Issue by jangid** [joaotavora/eglot#617]
A lot of users have faced this issue. After giving it quite a bit of time I could reach to the conclusion that Eglot could not start eclipse.jdt.ls (exited with code 13) because the project cache directory under ~/.emacs.d/eglot-eclipse-jdt-cache had some issue.

I had deleted the cache directory and it started working again.

**Comment by joaotavora** [comment]
Please provide an error reproduction recipe, like the one suggested by the text that you deleted when you opened this issue.  https://github.com/joaotavora/eglot#reporting-bugs 

Otherwise it's very hard for me or another user to help you.
