### ISSUE TITLE
eglot-ensure throws error in post-command-hook

### ISSUE THREAD

**Issue by jojojames** [joaotavora/eglot#62]
This doesn't happen everytime for me (50%?) but I am getting an error around eglot-ensure. After the error pops up, if I run eglot manually, eglot will connect fine.

*configuration*

```
(use-package eglot
  :ensure t
  :commands (eglot eglot-ensure)
  :init
  (defun eglot-disable-other-modes ()
    "Disable other modes that would conflict with `eglot'."
    (flycheck-mode -1) ;; Use `flymake' instead.
    (ggtags-mode -1)
    (ycmd-mode -1))
  (add-hook 'eglot--managed-mode-hook #'eglot-disable-other-modes)

  (add-hook 'c-mode-hook #'eglot-ensure)
  (add-hook 'c++-mode-hook #'eglot-ensure))
```

*messages*
```
[eglot] (warning) Server sent unknown notification method `$cquery/progress'
[eglot] Asking EGLOT (emacs/c-mode) politely to terminate
[jsonrpc] Server exited with status 0
Error in post-command-hook 

 [#<buffer window.c> (#0) eglot--managed-mode major-mode remove-hook post-command-hook nil buffer-live-p apply eglot--connect eglot--guess-contact eglot--message "Automatically started `%s' to manage `%s' buffers in project `%s'" jsonrpc-name eglot--project-nickname] 8]): (error "Selecting deleted buffer")

```

I'm opening window.c in emacs' codebase after generating a compile_commands.json (for use with cquery) file with:

```
make clean; bear make;
```

**Comment by joaotavora** [comment]
It's not entirely clear how you're opening `window.c` and this is important. Can you give a recipe starting from Emacs -Q, perhaps from a git checkout of eglot.  Something like

```
cd path-to-eglot
path-to-emacs/emacs -Q -L . -l eglot.el -l some-attached-fancy-configuration.el
C-x C-f path-to-window.c
error happens
```

BTW `eglot--managed-mode-hook` is an internal variable, it could change and break you configuration.  I'm not saying a proper hook in place of it isn't useful, but if you have `eglot-ensure` in `c-mode` and `c++-mode`, isn't it funcionally equivalent to disable flycheck et al in those modes' hooks?

**Comment by jojojames** [comment]
Thanks! That helped, looks like ycmd-mode was the culprit. It throws a user-error when called willy-nilly.

> but if you have eglot-ensure in c-mode and c++-mode, isn't it funcionally equivalent to disable flycheck et al in those modes' hooks?

I was initially looking for eglot-mode-hook but found eglot--managed-mode-hook instead. I agree with your comment, but I didn't want to write a wrapper to call eglot-ensure & eglot-disable-other-modes.
