### ISSUE TITLE
null textDocument/definition response not handled correctly

### ISSUE THREAD

**Issue by brown** [joaotavora/eglot#625]
A language server can return null to a textDocument/definition request.  The code in eglot--lsp-xrefs-for-method handles a NIL result from jsonrpc-request incorrectly.  It loops over (list nil) instead of skipping the eglot--collecting-xrefs loop.  Here is a version of eglot--lsp-xrefs-for-method that has been working better for me:

(cl-defun eglot--lsp-xrefs-for-method (method &key extra-params capability)
  "Make `xref''s for METHOD, EXTRA-PARAMS, check CAPABILITY."
  (unless (eglot--server-capable
           (or capability
               (intern
                (format ":%sProvider"
                        (cadr (split-string (symbol-name method)
                                            "/"))))))
    (eglot--error "Sorry, this server doesn't do %s" method))
  (let ((response
         (jsonrpc-request
          (eglot--current-server-or-lose)
          method (append (eglot--TextDocumentPositionParams) extra-params))))
    (when response
      (eglot--collecting-xrefs (collect)
        (mapc
         (eglot--lambda ((Location) uri range)
           (collect (eglot--xref-make-match (symbol-name (symbol-at-point))
                                            uri range)))
         (if (vectorp response) response (list response)))))))

**Comment by joaotavora** [comment]
Thanks, but can you also provide the transcript of the events buffer that has caused you this trouble, as requested in the new issue template?  Also provide the other data elements, please (version, server being used, etc...)

**Comment by brown** [comment]
Thanks for responding to my issue!  Here is some additional info  Let me know if you need anything else.

I am using Eglot 1.7 from elpa with Emacs 27.1 and https://github.com/georgewfraser/java-language-server.

The part of the spec that indicates null is a valid response for testDocument/definition:  https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_definition

Backtrace and events buffer contents:

==========
backtrace
==========
Debugger entered--Lisp error: (file-error "Read error" "Is a directory" "/home/brown/local/software/source-trees/java-langu...")
  insert-file-contents("")
  (save-current-buffer (set-buffer (puthash uri (generate-new-buffer " *temp*") eglot--temp-location-buffers)) (insert-file-contents file) (funcall collect))
  (cond (visiting (save-current-buffer (set-buffer visiting) (funcall collect))) ((file-readable-p file) (save-current-buffer (set-buffer (puthash uri (generate-new-buffer " *temp*") eglot--temp-location-buffers)) (insert-file-contents file) (funcall collect))) (t (let* ((start (cl-getf range :start)) (line (1+ (cl-getf start :line))) (start-pos (cl-getf start :character)) (end-pos (cl-getf (cl-getf range :end) :character))) (list name line start-pos (- end-pos start-pos)))))
  (let* ((file (eglot--uri-to-path uri)) (visiting (or (find-buffer-visiting file) (gethash uri eglot--temp-location-buffers))) (collect #'(lambda nil (save-excursion (save-restriction (widen) (let* ... ...))))) (val (cond (visiting (save-current-buffer (set-buffer visiting) (funcall collect))) ((file-readable-p file) (save-current-buffer (set-buffer (puthash uri ... eglot--temp-location-buffers)) (insert-file-contents file) (funcall collect))) (t (let* ((start ...) (line ...) (start-pos ...) (end-pos ...)) (list name line start-pos (- end-pos start-pos)))))) (x30 (car val)) (x31 (cdr val)) (x32 (car x31)) (x33 (cdr x31)) (x34 (car x33)) (x35 (cdr x33)) (x36 (car x35)) (x37 (cdr x35))) (let ((length x36) (column x34) (line x32) (summary x30)) (xref-make-match summary (xref-make-file-location file line column) length)))
  eglot--xref-make-match(#("Path" 0 3 (face font-lock-type-face fontified t) 3 4 (face font-lock-type-face c-type c-decl-id-start fontified t)) nil nil)
  (funcall --cl-collect-- (eglot--xref-make-match (symbol-name (symbol-at-point)) uri range))
  (progn (eglot--check-object 'Location object-once (memq 'enforce-required-keys eglot-strict-mode) (memq 'disallow-non-standard-keys eglot-strict-mode) (memq 'check-types eglot-strict-mode)) (funcall --cl-collect-- (eglot--xref-make-match (symbol-name (symbol-at-point)) uri range)))
  (let* ((--cl-rest-- object-once) (uri (car (cdr (plist-member --cl-rest-- ':uri)))) (range (car (cdr (plist-member --cl-rest-- ':range))))) (progn (eglot--check-object 'Location object-once (memq 'enforce-required-keys eglot-strict-mode) (memq 'disallow-non-standard-keys eglot-strict-mode) (memq 'check-types eglot-strict-mode)) (funcall --cl-collect-- (eglot--xref-make-match (symbol-name (symbol-at-point)) uri range))))
  (let ((object-once jsonrpc-lambda-elem7)) (let* ((--cl-rest-- object-once) (uri (car (cdr (plist-member --cl-rest-- ':uri)))) (range (car (cdr (plist-member --cl-rest-- ':range))))) (progn (eglot--check-object 'Location object-once (memq 'enforce-required-keys eglot-strict-mode) (memq 'disallow-non-standard-keys eglot-strict-mode) (memq 'check-types eglot-strict-mode)) (funcall --cl-collect-- (eglot--xref-make-match (symbol-name (symbol-at-point)) uri range)))))
  (closure ((--cl-collect-- closure ((collected6) (response) (capability) (extra-params) (--cl-rest--) (method . :textDocument/definition) revert-buffer-preserve-modes eglot--managed-mode markdown-fontify-code-blocks-natively t) (xref) (setq collected6 (cons xref collected6))) (collected6) (response) (capability) (extra-params) (--cl-rest--) (method . :textDocument/definition) revert-buffer-preserve-modes eglot--managed-mode markdown-fontify-code-blocks-natively t) (jsonrpc-lambda-elem7) (let ((object-once jsonrpc-lambda-elem7)) (let* ((--cl-rest-- object-once) (uri (car (cdr ...))) (range (car (cdr ...)))) (progn (eglot--check-object 'Location object-once (memq 'enforce-required-keys eglot-strict-mode) (memq 'disallow-non-standard-keys eglot-strict-mode) (memq 'check-types eglot-strict-mode)) (funcall --cl-collect-- (eglot--xref-make-match (symbol-name ...) uri range))))))(nil)
  mapc((closure ((--cl-collect-- closure ((collected6) (response) (capability) (extra-params) (--cl-rest--) (method . :textDocument/definition) revert-buffer-preserve-modes eglot--managed-mode markdown-fontify-code-blocks-natively t) (xref) (setq collected6 (cons xref collected6))) (collected6) (response) (capability) (extra-params) (--cl-rest--) (method . :textDocument/definition) revert-buffer-preserve-modes eglot--managed-mode markdown-fontify-code-blocks-natively t) (jsonrpc-lambda-elem7) (let ((object-once jsonrpc-lambda-elem7)) (let* ((--cl-rest-- object-once) (uri (car (cdr ...))) (range (car (cdr ...)))) (progn (eglot--check-object 'Location object-once (memq 'enforce-required-keys eglot-strict-mode) (memq 'disallow-non-standard-keys eglot-strict-mode) (memq 'check-types eglot-strict-mode)) (funcall --cl-collect-- (eglot--xref-make-match (symbol-name ...) uri range)))))) (nil))
  (progn (mapc #'(lambda (jsonrpc-lambda-elem7) (let ((object-once jsonrpc-lambda-elem7)) (let* ((--cl-rest-- object-once) (uri ...) (range ...)) (progn (eglot--check-object ... object-once ... ... ...) (funcall --cl-collect-- ...))))) (if (vectorp response) response (list response))))
  (let* ((--cl-collect-- #'(lambda (xref) (setq collected6 (cons xref collected6))))) (progn (mapc #'(lambda (jsonrpc-lambda-elem7) (let ((object-once jsonrpc-lambda-elem7)) (let* (... ... ...) (progn ... ...)))) (if (vectorp response) response (list response)))))
  (let (collected6) (let* ((--cl-collect-- #'(lambda (xref) (setq collected6 (cons xref collected6))))) (progn (mapc #'(lambda (jsonrpc-lambda-elem7) (let (...) (let* ... ...))) (if (vectorp response) response (list response))))) (sort collected6 eglot-xref-lessp-function))
  (unwind-protect (let (collected6) (let* ((--cl-collect-- #'(lambda (xref) (setq collected6 ...)))) (progn (mapc #'(lambda (jsonrpc-lambda-elem7) (let ... ...)) (if (vectorp response) response (list response))))) (sort collected6 eglot-xref-lessp-function)) (maphash #'(lambda (_uri buf) (kill-buffer buf)) eglot--temp-location-buffers) (clrhash eglot--temp-location-buffers))
  (let ((response (jsonrpc-request (eglot--current-server-or-lose) method (append (eglot--TextDocumentPositionParams) extra-params)))) (unwind-protect (let (collected6) (let* ((--cl-collect-- #'(lambda ... ...))) (progn (mapc #'(lambda ... ...) (if (vectorp response) response (list response))))) (sort collected6 eglot-xref-lessp-function)) (maphash #'(lambda (_uri buf) (kill-buffer buf)) eglot--temp-location-buffers) (clrhash eglot--temp-location-buffers)))
  (progn (if (eglot--server-capable (or capability (intern (format ":%sProvider" (car (cdr ...)))))) nil (eglot--error "Sorry, this server doesn't do %s" method)) (let ((response (jsonrpc-request (eglot--current-server-or-lose) method (append (eglot--TextDocumentPositionParams) extra-params)))) (unwind-protect (let (collected6) (let* ((--cl-collect-- #'...)) (progn (mapc #'... (if ... response ...)))) (sort collected6 eglot-xref-lessp-function)) (maphash #'(lambda (_uri buf) (kill-buffer buf)) eglot--temp-location-buffers) (clrhash eglot--temp-location-buffers))))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:extra-params :capability :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:extra-params :cap..." (car --cl-keys--)))))) (progn (if (eglot--server-capable (or capability (intern (format ":%sProvider" (car ...))))) nil (eglot--error "Sorry, this server doesn't do %s" method)) (let ((response (jsonrpc-request (eglot--current-server-or-lose) method (append (eglot--TextDocumentPositionParams) extra-params)))) (unwind-protect (let (collected6) (let* ((--cl-collect-- ...)) (progn (mapc ... ...))) (sort collected6 eglot-xref-lessp-function)) (maphash #'(lambda (_uri buf) (kill-buffer buf)) eglot--temp-location-buffers) (clrhash eglot--temp-location-buffers)))))
  (let* ((extra-params (car (cdr (plist-member --cl-rest-- ':extra-params)))) (capability (car (cdr (plist-member --cl-rest-- ':capability))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '...) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:extra-params :cap..." (car --cl-keys--)))))) (progn (if (eglot--server-capable (or capability (intern (format ":%sProvider" ...)))) nil (eglot--error "Sorry, this server doesn't do %s" method)) (let ((response (jsonrpc-request (eglot--current-server-or-lose) method (append ... extra-params)))) (unwind-protect (let (collected6) (let* (...) (progn ...)) (sort collected6 eglot-xref-lessp-function)) (maphash #'(lambda ... ...) eglot--temp-location-buffers) (clrhash eglot--temp-location-buffers))))))
  eglot--lsp-xrefs-for-method(:textDocument/definition)
  (progn (eglot--lsp-xrefs-for-method :textDocument/definition))
  (closure (revert-buffer-preserve-modes eglot--managed-mode markdown-fontify-code-blocks-natively t) (_backend _identifier) (progn (eglot--lsp-xrefs-for-method :textDocument/definition)))(eglot "LSP identifier at point.")
  apply((closure (revert-buffer-preserve-modes eglot--managed-mode markdown-fontify-code-blocks-natively t) (_backend _identifier) (progn (eglot--lsp-xrefs-for-method :textDocument/definition))) eglot "LSP identifier at point.")
  xref-backend-definitions(eglot "LSP identifier at point.")
  #f(compiled-function () #<bytecode 0x1566af6b00bd>)()
  xref--show-defs-buffer(#f(compiled-function () #<bytecode 0x1566af6b00bd>) ((window . #<window 1 on Cache.java>) (display-action)))
  xref--show-defs(#f(compiled-function () #<bytecode 0x1566af6b00bd>) nil)
  xref--find-definitions("LSP identifier at point." nil)
  xref-find-definitions("LSP identifier at point.")
  funcall-interactively(xref-find-definitions "LSP identifier at point.")
  call-interactively(xref-find-definitions nil nil)
  command-execute(xref-find-definitions)
==========
events
==========
[client-request] (id:1) Sat Feb 20 20:02:51 2021:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
          (:processId 38237 :rootPath "/home/brown/local/software/source-trees/java-language-server/" :rootUri "file:///home/brown/local/software/source-trees/java-language-server/" :initializationOptions #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                                                                                                                                                                                           ())
                      :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges :json-false)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t)
                       :textDocument
                       (:synchronization
                        (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
                        :completion
                        (:dynamicRegistration :json-false :completionItem
                                              (:snippetSupport :json-false)
                                              :contextSupport t)
                        :hover
                        (:dynamicRegistration :json-false :contentFormat
                                              ["plaintext"])
                        :signatureHelp
                        (:dynamicRegistration :json-false :signatureInformation
                                              (:parameterInformation
                                               (:labelOffsetSupport t)))
                        :references
                        (:dynamicRegistration :json-false)
                        :definition
                        (:dynamicRegistration :json-false)
                        :declaration
                        (:dynamicRegistration :json-false)
                        :implementation
                        (:dynamicRegistration :json-false)
                        :typeDefinition
                        (:dynamicRegistration :json-false)
                        :documentSymbol
                        (:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
                                              (:valueSet
                                               [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
                        :documentHighlight
                        (:dynamicRegistration :json-false)
                        :codeAction
                        (:dynamicRegistration :json-false :codeActionLiteralSupport
                                              (:codeActionKind
                                               (:valueSet
                                                ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
                                              :isPreferredSupport t)
                        :formatting
                        (:dynamicRegistration :json-false)
                        :rangeFormatting
                        (:dynamicRegistration :json-false)
                        :rename
                        (:dynamicRegistration :json-false)
                        :publishDiagnostics
                        (:relatedInformation :json-false))
                       :experimental #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                   ()))))
[stderr] 20:02:52.076	INFO	LSP connect	Reading messages from queue...
[stderr] 20:02:52.076	INFO	LSP$1MessageReader run	Placing incoming messages on queue...
[server-reply] (id:1) Sat Feb 20 20:02:52 2021:
(:jsonrpc "2.0" :id 1 :result
          (:capabilities
           (:textDocumentSync 2 :hoverProvider t :completionProvider
                              (:resolveProvider t :triggerCharacters
                                                ["."])
                              :signatureHelpProvider
                              (:triggerCharacters
                               ["(" ","])
                              :referencesProvider t :definitionProvider t :workspaceSymbolProvider t :documentSymbolProvider t :documentFormattingProvider t :codeLensProvider nil :foldingRangeProvider t :codeActionProvider t :renameProvider
                              (:prepareProvider t))))
[client-notification] Sat Feb 20 20:02:52 2021:
(:jsonrpc "2.0" :method "initialized" :params #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
                                                            ()))
[client-notification] Sat Feb 20 20:02:52 2021:
(:jsonrpc "2.0" :method "textDocument/didOpen" :params
          (:textDocument
           (:uri "file:///home/brown/local/software/source-trees/java-language-server/src/main/java/org/javacs/Cache.java" :version 0 :languageId "java" :text "package org.javacs;\n\nimport java.nio.file.Path;\nimport java.time.Instant;\nimport java.util.HashMap;\nimport java.util.Map;\nimport java.util.Objects;\n\n/** Cache maps a file + an arbitrary key to a value. When the file is modified, the mapping expires. */\nclass Cache<K, V> {\n    private static class Key<K> {\n        final Path file;\n        final K key;\n\n        Key(Path file, K key) {\n            this.file = file;\n            this.key = key;\n        }\n\n        @Override\n        public boolean equals(Object other) {\n            if (other.getClass() != Cache.Key.class) return false;\n            var that = (Cache.Key) other;\n            return Objects.equals(this.key, that.key) && Objects.equals(this.file, that.file);\n        }\n\n        @Override\n        public int hashCode() {\n            return Objects.hash(file, key);\n        }\n    }\n\n    private class Value {\n        final V value;\n        final Instant created = Instant.now();\n\n        Value(V value) {\n            this.value = value;\n        }\n    }\n\n    private final Map<Key, Value> map = new HashMap<>();\n\n    boolean has(Path file, K k) {\n        return !needs(file, k);\n    }\n\n    boolean needs(Path file, K k) {\n        // If key is not in map, it needs to be loaded\n        var key = new Key<K>(file, k);\n        if (!map.containsKey(key)) return true;\n\n        // If key was loaded before file was last modified, it needs to be reloaded\n        var value = map.get(key);\n        var modified = FileStore.modified(file);\n        // TODO remove all keys associated with file when file changes\n        return value.created.isBefore(modified);\n    }\n\n    void load(Path file, K k, V v) {\n        // TODO limit total size of cache\n        var key = new Key<K>(file, k);\n        var value = new Value(v);\n        map.put(key, value);\n    }\n\n    V get(Path file, K k) {\n        var key = new Key<K>(file, k);\n        if (!map.containsKey(key)) {\n            throw new IllegalArgumentException(k + \" is not in map \" + map);\n        }\n        return map.get(key).value;\n    }\n}\n")))
[client-notification] Sat Feb 20 20:02:52 2021:
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
          (:settings
           (:java
            ((:classPath "/home/brown/local/software/source/java-language-server/dist/classpath/java-language-server.jar" "/home/brown/local/software/source/java-language-server/dist/classpath/gson-2.8.5.jar" "/home/brown/local/software/source/java-language-server/dist/classpath/protobuf-java-3.9.1.jar" "/home/brown/local/software/source/java-language-server/dist/linux/lib/jrt-fs.jar")))))
[server-notification] Sat Feb 20 20:02:52 2021:
(:jsonrpc "2.0" :method "client/registerCapability" :params
          (:id "785c55f4-f63a-416a-8c6b-c9c30c43ae02" :method "workspace/didChangeWatchedFiles" :registerOptions
               (:watchers
                [(:globPattern "**/*.java")
                 (:globPattern "**/pom.xml")
                 (:globPattern "**/BUILD")])))
[stderr] 20:02:52.806	INFO	JavaLanguageServer didChangeConfiguration	Received java settings {"classPath":["/home/brown/local/software/source/java-language-server/dist/classpath/java-language-server.jar","/home/brown/local/software/source/java-language-server/dist/classpath/gson-2.8.5.jar","/home/brown/local/software/source/java-language-server/dist/classpath/protobuf-java-3.9.1.jar","/home/brown/local/software/source/java-language-server/dist/linux/lib/jrt-fs.jar"]}
[stderr] 20:02:53.022	INFO	JavaLanguageServer lint	Lint 1 files...
[server-notification] Sat Feb 20 20:02:53 2021:
(:jsonrpc "2.0" :method "java/startProgress" :params
          (:message "Configure javac"))
[server-notification] Sat Feb 20 20:02:53 2021:
(:jsonrpc "2.0" :method "java/reportProgress" :params
          (:message "Finding source roots" :increment -1))
[server-notification] Sat Feb 20 20:02:53 2021:
(:jsonrpc "2.0" :method "java/endProgress" :params nil)
[stderr] 20:02:53.052	INFO	ScanClassPath jdkTopLevelClasses	Searching for top-level classes in the JDK
[stderr] 20:02:54.311	INFO	ScanClassPath jdkTopLevelClasses	Found 17458 classes in the java platform
[stderr] Class path:
[stderr]   /home/brown/local/software/source/java-language-server/dist/classpath/gson-2.8.5.jar
[stderr]   /home/brown/local/software/source/java-language-server/dist/classpath/java-language-server.jar
[stderr]   /home/brown/local/software/source/java-language-server/dist/linux/lib/jrt-fs.jar
[stderr]   /home/brown/local/software/source/java-language-server/dist/classpath/protobuf-java-3.9.1.jar
[stderr] Doc path:
[stderr] 20:02:54.445	WARNING	Docs findSrcZip	Couldn't find src.zip in /usr/lib/jvm/java-13-openjdk-amd64
[stderr] 20:02:54.448	INFO	ScanClassPath classPathTopLevelClasses	Searching for top-level classes in 4 classpath locations
[stderr] 20:02:54.511	INFO	ScanClassPath classPathTopLevelClasses	Found 643 classes in classpath
[stderr] 20:02:54.522	WARNING	ReusableCompiler getTask	Options changed from [-classpath, /home/brown/local/software/source/java-language-server/dist/classpath/gson-2.8.5.jar:/home/brown/local/software/source/java-language-server/dist/classpath/java-language-server.jar:/home/brown/local/software/source/java-language-server/dist/linux/lib/jrt-fs.jar:/home/brown/local/software/source/java-language-server/dist/classpath/protobuf-java-3.9.1.jar, --add-modules, ALL-MODULE-PATH, -proc:none, -g, -Xlint:cast, -Xlint:deprecation, -Xlint:empty, -Xlint:fallthrough, -Xlint:finally, -Xlint:path, -Xlint:unchecked, -Xlint:varargs, -Xlint:static] to [-classpath, /home/brown/local/software/source/java-language-server/dist/classpath/gson-2.8.5.jar:/home/brown/local/software/source/java-language-server/dist/classpath/java-language-server.jar:/home/brown/local/software/source/java-language-server/dist/linux/lib/jrt-fs.jar:/home/brown/local/software/source/java-language-server/dist/classpath/protobuf-java-3.9.1.jar, --add-modules, ALL-MODULE-PATH, -proc:none, -g, -Xlint:cast, -Xlint:deprecation, -Xlint:empty, -Xlint:fallthrough, -Xlint:finally, -Xlint:path, -Xlint:unchecked, -Xlint:varargs, -Xlint:static], creating new compiler
[client-request] (id:2) Sat Feb 20 20:02:54 2021:
(:jsonrpc "2.0" :id 2 :method "textDocument/signatureHelp" :params
          (:textDocument
           (:uri "file:///home/brown/local/software/source-trees/java-language-server/src/main/java/org/javacs/Cache.java")
           :position
           (:line 0 :character 0)))
[client-request] (id:3) Sat Feb 20 20:02:54 2021:
(:jsonrpc "2.0" :id 3 :method "textDocument/hover" :params
          (:textDocument
           (:uri "file:///home/brown/local/software/source-trees/java-language-server/src/main/java/org/javacs/Cache.java")
           :position
           (:line 0 :character 0)))
[stderr] 20:02:55.854	INFO	JavaLanguageServer lint	...compiled in 2821 ms
[server-notification] Sat Feb 20 20:02:55 2021:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/brown/local/software/source-trees/java-language-server/src/main/java/org/javacs/Cache.java" :diagnostics
                []))
[server-notification] Sat Feb 20 20:02:55 2021:
(:jsonrpc "2.0" :method "java/colors" :params
          (:uri "file:///home/brown/local/software/source-trees/java-language-server/src/main/java/org/javacs/Cache.java" :statics
                []
                :fields
                [(:start
                  (:line 11 :character 19)
                  :end
                  (:line 11 :character 23))
                 (:start
                  (:line 12 :character 16)
                  :end
                  (:line 12 :character 19))
                 (:start
                  (:line 15 :character 17)
                  :end
                  (:line 15 :character 21))
                 (:start
                  (:line 16 :character 17)
                  :end
                  (:line 16 :character 20))
                 (:start
                  (:line 23 :character 39)
                  :end
                  (:line 23 :character 42))
                 (:start
                  (:line 23 :character 49)
                  :end
                  (:line 23 :character 52))
                 (:start
                  (:line 23 :character 77)
                  :end
                  (:line 23 :character 81))
                 (:start
                  (:line 23 :character 88)
                  :end
                  (:line 23 :character 92))
                 (:start
                  (:line 28 :character 32)
                  :end
                  (:line 28 :character 36))
                 (:start
                  (:line 28 :character 38)
                  :end
                  (:line 28 :character 41))
                 (:start
                  (:line 33 :character 16)
                  :end
                  (:line 33 :character 21))
                 (:start
                  (:line 34 :character 22)
                  :end
                  (:line 34 :character 29))
                 (:start
                  (:line 37 :character 17)
                  :end
                  (:line 37 :character 22))
                 (:start
                  (:line 41 :character 34)
                  :end
                  (:line 41 :character 37))
                 (:start
                  (:line 50 :character 13)
                  :end
                  (:line 50 :character 16))
                 (:start
                  (:line 53 :character 20)
                  :end
                  (:line 53 :character 23))
                 (:start
                  (:line 56 :character 21)
                  :end
                  (:line 56 :character 28))
                 (:start
                  (:line 63 :character 8)
                  :end
                  (:line 63 :character 11))
                 (:start
                  (:line 68 :character 13)
                  :end
                  (:line 68 :character 16))
                 (:start
                  (:line 69 :character 71)
                  :end
                  (:line 69 :character 74))
                 (:start
                  (:line 71 :character 28)
                  :end
                  (:line 71 :character 33))
                 (:start
                  (:line 71 :character 15)
                  :end
                  (:line 71 :character 18))]))
[stderr] 20:02:55.906	INFO	JavaLanguageServer lint	...published in 2881 ms
[server-reply] (id:2) Sat Feb 20 20:02:55 2021:
(:jsonrpc "2.0" :id 2 :result nil)
[stderr] 20:02:55.914	INFO	JavaCompilerService compileBatch	...using cached compile
[stderr] 20:02:55.923	INFO	JavaCompilerService compileBatch	...using cached compile
[server-reply] (id:3) Sat Feb 20 20:02:55 2021:
(:jsonrpc "2.0" :id 3 :result nil)
[client-request] (id:4) Sat Feb 20 20:03:01 2021:
(:jsonrpc "2.0" :id 4 :method "textDocument/signatureHelp" :params
          (:textDocument
           (:uri "file:///home/brown/local/software/source-trees/java-language-server/src/main/java/org/javacs/Cache.java")
           :position
           (:line 2 :character 23)))
[client-request] (id:5) Sat Feb 20 20:03:01 2021:
(:jsonrpc "2.0" :id 5 :method "textDocument/hover" :params
          (:textDocument
           (:uri "file:///home/brown/local/software/source-trees/java-language-server/src/main/java/org/javacs/Cache.java")
           :position
           (:line 2 :character 23)))
[stderr] 20:03:01.770	INFO	JavaCompilerService compileBatch	...using cached compile
[server-reply] (id:4) Sat Feb 20 20:03:01 2021:
(:jsonrpc "2.0" :id 4 :result nil)
[stderr] 20:03:01.776	INFO	JavaCompilerService compileBatch	...using cached compile
[server-reply] (id:5) Sat Feb 20 20:03:01 2021:
(:jsonrpc "2.0" :id 5 :result
          (:contents
           [(:language "java" :value "interface java.nio.file.Path {\n  static java.nio.file.Path of(String, String[]);\n  static java.nio.file.Path of(java.net.URI);\n  java.nio.file.FileSystem getFileSystem();\n  boolean isAbsolute();\n  java.nio.file.Path getRoot();\n  java.nio.file.Path getFileName();\n  java.nio.file.Path getParent();\n  int getNameCount();\n  java.nio.file.Path getName(int);\n  java.nio.file.Path subpath(int, int);\n  boolean startsWith(java.nio.file.Path);\n  boolean startsWith(String);\n  boolean endsWith(java.nio.file.Path);\n  boolean endsWith(String);\n  java.nio.file.Path normalize();\n  java.nio.file.Path resolve(java.nio.file.Path);\n  java.nio.file.Path resolve(String);\n  java.nio.file.Path resolveSibling(java.nio.file.Path);\n  java.nio.file.Path resolveSibling(String);\n  java.nio.file.Path relativize(java.nio.file.Path);\n  java.net.URI toUri();\n  java.nio.file.Path toAbsolutePath();\n  java.nio.file.Path toRealPath(java.nio.file.LinkOption[]) throws java.io.IOException;\n  java.io.File toFile();\n  java.nio.file.WatchKey register(java.nio.file.WatchService, java.nio.file.WatchEvent.Kind<?>[], java.nio.file.WatchEvent.Modifier[]) throws java.io.IOException;\n  java.nio.file.WatchKey register(java.nio.file.WatchService, java.nio.file.WatchEvent.Kind<?>[]) throws java.io.IOException;\n  Iterator<java.nio.file.Path> iterator();\n  int compareTo(java.nio.file.Path);\n  boolean equals(Object);\n  int hashCode();\n  String toString();\n}")]))
[client-request] (id:6) Sat Feb 20 20:03:06 2021:
(:jsonrpc "2.0" :id 6 :method "textDocument/definition" :params
          (:textDocument
           (:uri "file:///home/brown/local/software/source-trees/java-language-server/src/main/java/org/javacs/Cache.java")
           :position
           (:line 2 :character 23)))
[stderr] 20:03:06.266	INFO	JavaCompilerService compileBatch	...using cached compile
[server-reply] (id:6) Sat Feb 20 20:03:06 2021:
(:jsonrpc "2.0" :id 6 :result nil)

**Comment by brown** [comment]
I've been reading through the LSP specification a bit more.  It looks like many protocol responses are allowed to return null and I have not yet found any guidance in the specification that indicates when an empty array needs to be returned instead.  So it looks like an empty array and a null often mean the same thing in a response.  The documentation for a few response types indicates a more special meaning for null.

**Comment by joaotavora** [comment]
Thanks, I'll look into this as soon as possible.
