### ISSUE TITLE
Freezing with with big projects

### ISSUE THREAD

**Issue by bertinatto** [joaotavora/eglot#633]
First of all, thank you so much for all your work on eglot. I'm new to emacs and I love that everything works out-of-the-box.

About the issue I'm having, emacs freezes for a while when working on the [kubernetes repo](https://github.com/kubernetes/kubernetes/).

What happens:

1. I open a random file:  `emacs ./pkg/controller/volume/attachdetach/util/util.go`
2. After some time `*Compile-Log*` window appears with the message: `Error: Variable binding depth exceeds max-specpdl-size`
3. `top` shows that the `emacs` process uses 100% of the CPU. Nothing unusual with `gopls` process. 
4. After a few minutes, emacs and eglot start working OK

This _seems_ to be an issue with eglot because it works OK with lsp-mode and vscode. Also, this started happening a few days ago.

* `eglot-events-buffer`: https://gist.github.com/bertinatto/8e17143e34d716b327716677bb98b19a
* `toggle-debug-on-error` doesn't show anything

**Comment by joaotavora** [comment]
> his seems to be an issue with eglot because it works OK with lsp-mode and vscode.

I don't know how you have Emacs configured.  You seem to have at least `eglot-ensure` stuff set up. But how? You have to show me your configuration, of course.  Then it will take me potentially a lot of time to go through it (if I ever can).

Ideally, reduce it down to a minimal example that you can run with `emacs -Q`.

Like:
```
$ emacs -Q -L path-to-eglot
(require 'eglot)
C-x C-f blabla.go
M-x eglot
```

Does this make emacs block for a few minutes?

**Comment by joaotavora** [comment]
I think I know where the potential culprit is.  Instead of sending a summarized glob pattern, Go seems to be sending a gigantic list in a very long glob. I'll have a better look at this later on, to see why it may be causing the error.  But please do still give me the simpler error recipe:

**Comment by joaotavora** [comment]
Just look at this beauty:
![image](https://user-images.githubusercontent.com/387011/109416142-53af3e80-79b4-11eb-8ed6-5c27b0d79d56.png)

**Comment by bertinatto** [comment]
My emacs is not freezing anymore, apparently I've done something that fixed the issue. I cleaned up my go cache (`go clean -cache -testcache -modcache`), perhaps it was that.

Here's the smaller recipe (sorry if the config is not minimal, that's the best I could come up with):

```sh
$ mkdir /tmp/foo
$ cd /tmp/foo
$ git clone https://github.com/kubernetes/kubernetes
$ cd kubernetes
$ cat << EOF > myinit.el
;; Workaround for "(void-function project-root)" error, from https://github.com/hlissner/doom-emacs/issues/3269#issuecomment-637945554
(defun project-root (project)
    (car (project-roots project)))
(require 'eglot)
(require 'go-mode)
(add-hook 'go-mode-hook 'eglot-ensure)
EOF
$ emacs -Q -L path-to-eglot -L path-to-go-mode --load myinit.el pkg/controller/volume/attachdetach/util/util.go
```
Like I said above, emacs is not freezing anymore even with my old config, but I still get a `Error: Variable binding depth exceeds max-specpdl-size` message.

Feel free to close if you think this is a `gopls` issue.

**Comment by joaotavora** [comment]
> Feel free to close if you think this is a gopls issue.

Likely an Eglot issue, but I still have to investigate.

**Comment by joaotavora** [comment]
I'm testing this.  Eglot glob-matcher eats that gigantic blob just fine.  I'm downloading the enormous kubernetes repo now, to see what else might be up.

**Comment by joaotavora** [comment]
Thanks for the very good recipe.

Downloaded it, tried it , navigated around a bit, didn't have any problems.  WIth Emacs 28 and some recentish version of `gopls` (I can't get it to report the version, maybe it's `go version go1.15.6 linux/amd64`).

I'm guessing that error is something else?  Can you try upgrading your Emacs?

**Comment by nemethf** [comment]
> (I can't get it to report the version, maybe it's `go version go1.15.6 linux/amd64`).

I think gopls returns its version in intializeVersion.serverInfo.version

**Comment by meain** [comment]
One other case where I am hitting this is when I navigate to the definition of a builtin or a library and it looks it up in the `$GOPATH` or `$HOME/go` which contains all the dependencies and no associated `.git` folders. It looks like `eglot` is loading the entire list of libs.
The events buffer was about 15000 lines within a few seconds and I had to kill it with `C-g` as emacs froze.

**Comment by mekeor** [comment]
when i open a go-project with many vendored dependencies, i also get `Error: Variable binding depth exceeds max-specpdl-size` in a `*Compile-Log*` buffer.
