### ISSUE TITLE
eglot causing /tmp directory to fill up with .pch files

### ISSUE THREAD

**Issue by bpstahlman** [joaotavora/eglot#634]
I have a very large (1TB) hard drive, which filled up after I'd been using eglot on a very large C++ project for a day or so. The culprit was 680 GB of preamble-xxxxxx.pch files in /tmp, which I'm fairly certain were created by eglot. AFAICT, precompiled headers are disabled in my project's build settings. This is on a Windows system running a WSL1 instance of Ubuntu. Does it make sense that eglot would be creating these files? And is there a mechanism for automatically deleting them when they're no longer needed?

**Comment by joaotavora** [comment]
>  preamble-xxxxxx.pch files in /tmp, which I'm fairly certain were created by eglot. 

How so?  The string`preamble` is not in my project.  Did Eglot just become sentient :robot: :thought_balloon: ?

**Comment by bpstahlman** [comment]
> 
> 
> > preamble-xxxxxx.pch files in /tmp, which I'm fairly certain were created by eglot.
> 
> How so? The string`preamble` is not in my project. Did Eglot just become sentient 🤖 💭 ?

I think it far more likely that whatever eglot is doing with clangd causes a lot of transient compiler output to be written to /tmp and never cleaned up. Whenever I have eglot enabled in emacs, a new pair of .pch and .pch.tmp is generated in /tmp every 2 or 3 seconds. Over the course of a day or two, these files consumed over half my Terabyte drive. I haven't yet looked at eglot's implementation, but I'm assuming that for a large C++ project, a lot of compiler output will be generated somewhere. Is this the case? Is the user responsible for purging it periodically, or does eglot attempt to clean up?

**Comment by joaotavora** [comment]
> I think it far more likely that whatever eglot is doing with clangd causes a lot of transient co

What it is doing with it is calling it, without arguments (I presume, though you may have tweaked that), and then initializing it with simple LSP protocol messages, without any special clangd specific behaviour.  Clangd would probably have to create some files to index your project, I suppose.  Supposing that project to be large of course. Anyway, I think whatever problems you are having in this combination are on Clangd's side. I know that Eglot is the user-facing front so you've come here before, but it's really just a messenger. I'm going to close this, but we can keep discussing, and if there is a suspicion that Eglot is somehow misbehaving (like secretly sending a `fillUpUsersHardDriveMuahaha` message to servers), we can reopen.  But for now, I'd suggest you ask about this in the clangd mailing list.

**Comment by bpstahlman** [comment]
Understood. I'll search the clangd issues list and log an issue there if appropriate...

**Comment by joaotavora** [comment]
Thanks.  You can link the two issues if you feel it's appropriate.

**Comment by bpstahlman** [comment]
Looks like the problem is that clangd is continually seg-faulting.
Every second or so, I see...
`
[eglot] Reconnected!
`
...in the minibuffer, and when I look in the eglot message buffer, I see a bunch of these:
```
[stderr] /usr/bin/clangd[0x65375e]
[stderr] /usr/bin/clangd[0x5cf1e4]
[stderr] /usr/bin/clangd[0x5cc663]
[stderr] /usr/bin/clangd[0x5c452b]
[stderr] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xd6d84)[0x7ff9ef996d84]
[stderr] /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609)[0x7ff9f6c06609]
[stderr] /lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7ff9ef662293]
[internal] Sun Feb 28 17:59:12 2021:
(:message "Connection state changed" :change "segmentation fault (core dumped)\n")

----------b---y---e---b---y---e----------
[stderr] 
[stderr] 
[stderr] nil
[stderr] nil
[stderr] Process EGLOT (gitAll/c++-mode) stderr<1> finished
```

[This clangd issue](https://github.com/clangd/clangd/issues/512) seems relevant. The issue I reported was occurring with the clangd version 10.0.0 installed by the Ubuntu package manager. I'm not seeing the issue when I use a source build of clangd version 13.0.0.
