### ISSUE TITLE
Flymake  lists wrong diagnostics

### ISSUE THREAD

**Issue by theothornhill** [joaotavora/eglot#638]
Hi! Yet another `elmLS` issue... sorry

How to reproduce:
- Use https://github.com/rtfeldman/elm-spa-example
- open `src/Api.elm`
- do some editing

## Eglots behavior (I have to `revert-buffer` at the end to make it report correctly)
![eglot](https://user-images.githubusercontent.com/26711805/109968453-03591900-7cf3-11eb-9c0b-8418a71112f8.gif)

## Lsp-mode behavior
![lspmode](https://user-images.githubusercontent.com/26711805/109968458-048a4600-7cf3-11eb-8080-2b30a2b4aa0b.gif)

[eglotlog.txt](https://github.com/joaotavora/eglot/files/6083552/eglotlog.txt)
[lsplog.txt](https://github.com/joaotavora/eglot/files/6083553/lsplog.txt)

Relevant code from `lsp-mode`: https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-diagnostics.el#L247

**Comment by theothornhill** [comment]
I see that the server throws a lot of junk back to eglot, and doesn't to lsp-mode. I'm not sure why this happens, but my hunch is on incremental sync. See this issue: https://github.com/elm-tooling/elm-language-server/issues/503. They clearly state that this is intended behavior, and is a client problem. 

The main differences I see between the transcripts are that eglot chunks on `didChange`, and lsp-mode sends one request per keypress. Not sure if any of that could cause this behavior though.

**Comment by theothornhill** [comment]
Interestingly, it only happens on my windows pc... could it be paths again?

**Comment by joaotavora** [comment]
> I see that the server throws a lot of junk back to eglot, and doesn't to lsp-mode. I'm not sure why this happens, but my hunch is on incremental sync. See this issue: elm-tooling/elm-language-server#503. They clearly state that this is intended behavior, and is a client problem.

I don't understand this part.  Eglot does send incremental sync as far as I know.  Non-incremental sync would be shooting over the whole file.  Chunking the individual changes with an idle timer is just good practice so you don't overwhelm emacs and block the UI.

**Comment by theothornhill** [comment]
> 
> 
> > I see that the server throws a lot of junk back to eglot, and doesn't to lsp-mode. I'm not sure why this happens, but my hunch is on incremental sync. See this issue: [elm-tooling/elm-language-server#503](https://github.com/elm-tooling/elm-language-server/issues/503). They clearly state that this is intended behavior, and is a client problem.
> 
> I don't understand this part. Eglot does send incremental sync as far as I know. Non-incremental sync would be shooting over the whole file. Chunking the individual changes with an idle timer is just good practice so you don't overwhelm emacs and block the UI.

Yeah, me neither. I just found the issue from elmls interesting, and saw that as a differentiator from lsp-mode

**Comment by joaotavora** [comment]
I'm not sure what you mean "a lot of junk", but if that's unexpected maybe you could ask the ELM ls devs why it is doing that.

**Comment by theothornhill** [comment]
> 
> 
> I'm not sure what you mean "a lot of junk", but if that's unexpected maybe you could ask the ELM ls devs why it is doing that.

Stuff like this:
```
 (:message "Could not find a module to import named `igation` in `dependencies` or `source-directories`." :source "Elm" :severity 1 :range
                           (:start
                            (:line 26 :character 7)
                            :end
                            (:line 26 :character 14))
                           :data
                           (:uri "file:///c:/Users/redacted/Git/elm-spa-example/src/Api.elm" :code "import_resolve"))
                 (:message "Could not find a module to import named `mport Http exposin` in `dependencies` or `source-directories`." :source "Elm" :severity 1 :range
                           (:start
                            (:line 27 :character 7)
                            :end
                            (:line 27 :character 25))
                           :data
                           (:uri "file:///c:/Users/redacted/Git/elm-spa-example/src/Api.elm" :code "import_resolve"))
                 (:message "Could not find a module to import named `\nimp` in `dependencies` or `source-directories`." :source "Elm" :severity 1 :range
                           (:start
                            (:line 28 :character 7)
                            :end
                            (:line 28 :character 11))
                           :data
                           (:uri "file:///c:/Users/redacted/Git/elm-spa-example/src/Api.elm" :code "import_resolve"))
```

This doesn't happen with eglot on mac, or lsp mode in general. I don't understand why it differs?

And by doesn't happen I mean it is not sent as a response. Same revision of `elmls`

**Comment by joaotavora** [comment]
Well, and are those diagnostics for real? This sounds like Eml LS is struggling to find those imports.  

I think you should ask the ElmLS people and show them a good and a bad transcripts of Windows and MacOSx.  Maybe they can spot an error in Eglot initialization.  I can't sorry, and I don't have a windows computer to look at this.  Or a lot of time, sorry.

**Comment by theothornhill** [comment]
> 
> 
> Well, and are those diagnostics for real?

No, they should be Navigation and import :)

> This sounds like Eml LS is struggling to find those imports.
> 
> I think you should ask the ElmLS people and show them a good and a bad transcripts of Windows and MacOSx. Maybe they can spot an error in Eglot initialization. I can't sorry, and I don't have a windows computer to look at this. Or a lot of time, sorry.

Will do - sorry for wasting your time!

**Comment by joaotavora** [comment]
You're not really "wasting my time", but I can't offer much more help . I really hope you can investigate this yourself and come to a conclusion.

**Comment by theothornhill** [comment]
> 
> 
> Interestingly, it only happens on my windows pc... could it be paths again?

I found it! It was paths :D

**Comment by joaotavora** [comment]
Great/ I see your commit, but can you explain exactly what was happening?  Is the that the colon was being incorrectly hexified? Can you make a simple unit test that:

1. Fails before your patch
2. Passes after your patch

?

These kinds of clarificationscan considerably speed up my analysis of your proposals.

**Comment by theothornhill** [comment]
Colons are generally allowed in uris, but they have special meanings, like discerning port from authority etc. However, the drive on windows is not one such case. The current implementation does _not_ convert the «drive-colon», thus creating an incorrect uri. 

It seems most servers handle that anyways, but elmLS does not. My commit ensures that colons _are_ hexified. 

I will add a test or two :)

**Comment by joaotavora** [comment]
> My commit ensures that colons are hexified.

That's the key piece of information that I was left guessing.  So to be clear:

* the colon in `file://` **must not** be hexified, but
*  the colon in `c:/` **must** be hexified.  

 Is that correct?

**Comment by theothornhill** [comment]
Yep!
