### ISSUE TITLE
Missing diagnostic using typescript-language-server

### ISSUE THREAD

**Issue by angrybacon** [joaotavora/eglot#641]
*I've seen #437 but it's almost one year old and mentions `eglot-help-at-point` which I think does not exist anymore.*

I'm not seeing any diagnostic after inserting a non-existing property on purpose in a `web-mode` buffer, as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/5608624/110398630-80c6b580-8074-11eb-88dc-bd8fdec6bc3a.png)

Flymake is turned on and correctly identifies the error in red, and deprecated key note in blue. 

This is how I set up Eglot:

`.dir-locals,el`
```lisp-data
((web-mode . ((eglot-server-programs . ((web-mode . ("typescript-language-server" "--stdio")))))))
```

`init.el`
```lisp
(use-package eglot
  :hook
  (web-mode . eglot-ensure)
  :init
  (put 'eglot-server-programs 'safe-local-variable 'listp))
```

Moving point on the error still shows the current TypeScript type accordingly, but I'm trying to have the diagnostic for the actual error. The error should be something along those lines:

> error TS2339: Property 'asdfcharCode' does not exist on type 'KeyboardEvent<Element>'.

<kbd>C-h</kbd><kbd>.</kbd> shows TypeScript typing instead of the error.

And finally, below are the Eglot logs where I can't see anything wrong besides the missing diagnostic for such a trivial error. Is it simply not yet supported by the server? It seems like an essential feature to me so I suspect something is wrong on my end.

<details>
  <summary>Logs</summary>

    [client-request] (id:9226) Tue Mar  9 01:27:23 2021:
    (:jsonrpc "2.0" :id 9226 :method "textDocument/signatureHelp" :params
              (:textDocument
               (:uri "file:///path/to/file.tsx")
               :position
               (:line 50 :character 22)))
    [client-request] (id:9227) Tue Mar  9 01:27:23 2021:
    (:jsonrpc "2.0" :id 9227 :method "textDocument/hover" :params
              (:textDocument
               (:uri "file:///path/to/file.tsx")
               :position
               (:line 50 :character 22)))
    [client-request] (id:9228) Tue Mar  9 01:27:23 2021:
    (:jsonrpc "2.0" :id 9228 :method "textDocument/documentHighlight" :params
              (:textDocument
               (:uri "file:///path/to/file.tsx")
               :position
               (:line 50 :character 22)))
    [server-reply] (id:9226) Tue Mar  9 01:27:23 2021:
    (:jsonrpc "2.0" :id 9226 :result nil)
    [server-reply] (id:9227) Tue Mar  9 01:27:23 2021:
    (:jsonrpc "2.0" :id 9227 :result
              (:contents
               [(:language "typescript" :value "any")
                ""]
               :range
               (:start
                (:line 50 :character 22)
                :end
                (:line 50 :character 34))))
    [server-reply] (id:9228) Tue Mar  9 01:27:23 2021:
    (:jsonrpc "2.0" :id 9228 :result
              [])

</details>

**Comment by joaotavora** [comment]
Supposing you're using a recent Eglot, try `M-x eldoc`.  If you want, you can bind that to `C-h .` if you want.

> C-h. shows TypeScript typing instead of the error.

What is "TypeScript typing"?

**Comment by angrybacon** [comment]
Manually calling Eldoc also shows the typing as opposed to the expected diagnostic. By "TypeScript typing" I'm referring to the currently evaluated type for the symbol. In the case of `event.asdfcharCode` like in my example, it shows:

> asdfcharCode: any

**Comment by joaotavora** [comment]
Now I'm confused, after reading:

> Flymake is turned on and correctly identifies the error in red, and deprecated key note in blue.

So how can it do that if the logs returned _no_ diagnostics as you say? Surely theres more of the log missing, the initialization sequence for one. And are you sure your `init.el` is just those 5 lines?

**Comment by angrybacon** [comment]
> Flymake is turned on and correctly identifies the error in red, and deprecated key note in blue.

I meant that the error is correctly highlighted with the `flymake-error` face, and that the lesser warning is correctly highlighted with the `flymake-note` face.

> And are you sure your `init.el` is just those 5 lines?

I've just tried disabling a number of things, mostly active modes including `eldoc-box` which I was trying at the time. It looks like the typing is overwriting the diagnostic in the minibuffer area that I can see for a brief moment only. After doing <kbd>M-x</kbd> <kbd>eglot-reconnect</kbd> I now see the diagnostics in the log :raised_hands: 

```
[server-notification] Tue Mar  9 01:54:47 2021:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/angrybacon/path/to/file.tsx" :diagnostics
                [(:range
                  (:start
                   (:line 50 :character 22)
                   :end
                   (:line 50 :character 34))
                  :message "Property 'asdfcharCode' does not exist on type 'KeyboardEvent<Element>'." :severity 1 :code 2339 :source "typescript")
                 (:range
                  (:start
                   (:line 50 :character 44)
                   :end
                   (:line 50 :character 51))
                  :message "'keyCode' is deprecated" :severity 4 :code 6385 :source "typescript")]))
```

The way I understand it, Flymake is responsible for displaying both the typing at point in a TypeScript buffer as well as diagnostic if any. Both provided by Eglot. Should both feedbacks be concatenated together or is that out of scope for Eglot?

**Comment by joaotavora** [comment]
> The way I understand it, Flymake is responsible for displaying both the typing at point in a TypeScript buffer as well as diagnostic if any. Both provided by Eglot. Should both feedbacks be concatenated together or is that out of scope for Eglot?

No.  Flymake is only responsible for providing diagnostics information and annotating things in your buffer.  It is Eldoc who is managing the display of the echo area, where you can find multiple elements of information, for example Flymake's diagnostics and other at-point documentation bits, such as "Typescript typing".  

By default, Eglot shows the piece with most priority, which appears to be whatever the server is returning for `textDocument/hover`, and which you call "Typescript typing".   You should be able to customize `eldoc-documentation-strategy` to the value `eldoc-documentation-compose`, so that it considers more than one such element in multiple lines.

However, if you decide that you don't want your echo area to expand and contract as multi-line, you will have to tweak `eldoc-echo-area-use-multiline-p`.  Another interesting variable will be `eldoc-echo-area-prefer-doc-buffer`.

**Comment by angrybacon** [comment]
> Eglot shows the piece with most priority

Oh ok, I wasn't aware of priority as a concept here. That makes sense. 

Thanks for the quick replies and for mentioning the specific Eldoc variables, I'll have a look :+1:
