### ISSUE TITLE
Initialization with haskell-language-server fails

### ISSUE THREAD

**Issue by kfiz** [joaotavora/eglot#642]
Hi,
I'm seeing the output below on eglot initialization with haskell source code. Initialization finishes but the functionality  is crippled. Apart from on the fly error checking nothing works as expected (company completion etc.). It looks like the server is expecting the key `languageServerHaskell` which is not provided in the client message.

possibly related: https://github.com/haskell/haskell-ide-engine/issues/369

``
(:jsonrpc "2.0" :params
          (:type 1 :message "haskell-lsp:configuration parse error. RequestMessage {_jsonrpc = \"2.0\", _id = IdInt 1, _method = Initialize, _params = InitializeParams {_processId = Just 5318, _rootPath = Just \"/Users/louis/dev/projects/haskell/empirical/\", _rootUri = Just (Uri {getUri = \"file:///Users/louis/dev/projects/haskell/empirical/\"}), _initializationOptions = Just (Object (fromList [])), _capabilities = ClientCapabilities {_workspace = Just (WorkspaceClientCapabilities {_applyEdit = Just True, _workspaceEdit = Just (WorkspaceEditClientCapabilities {_documentChanges = Just False}), _didChangeConfiguration = Nothing, _didChangeWatchedFiles = Just (DidChangeWatchedFilesClientCapabilities {_dynamicRegistration = Just True}), _symbol = Just (SymbolClientCapabilities {_dynamicRegistration = Just False, _symbolKind = Nothing}), _executeCommand = Just (ExecuteClientCapabilities {_dynamicRegistration = Just False}), _workspaceFolders = Nothing, _configuration = Just True}), _textDocument = Just (TextDocumentClientCapabilities {_synchronization = Just (SynchronizationTextDocumentClientCapabilities {_dynamicRegistration = Just False, _willSave = Just True, _willSaveWaitUntil = Just True, _didSave = Just True}), _completion = Just (CompletionClientCapabilities {_dynamicRegistration = Just False, _completionItem = Just (CompletionItemClientCapabilities {_snippetSupport = Just True, _commitCharactersSupport = Nothing, _documentationFormat = Nothing, _deprecatedSupport = Nothing, _preselectSupport = Nothing, _tagSupport = Nothing}), _completionItemKind = Nothing, _contextSupport = Just True}), _hover = Just (HoverClientCapabilities {_dynamicRegistration = Just False, _contentFormat = Just (List [MkMarkdown,MkPlainText])}), _signatureHelp = Just (SignatureHelpClientCapabilities {_dynamicRegistration = Just False, _signatureInformation = Just (SignatureInformationClientCapabilities {documentationFormat = Nothing})}), _references = Just (ReferencesClientCapabilities {_dynamicRegistration = Just False}), _documentHighlight = Just (DocumentHighlightClientCapabilities {_dynamicRegistration = Just False}), _documentSymbol = Just (DocumentSymbolClientCapabilities {_dynamicRegistration = Just False, _symbolKind = Just (DocumentSymbolKindClientCapabilities {_valueSet = Just (List [SkFile,SkModule,SkNamespace,SkPackage,SkClass,SkMethod,SkProperty,SkField,SkConstructor,SkEnum,SkInterface,SkFunction,SkVariable,SkConstant,SkString,SkNumber,SkBoolean,SkArray,SkObject,SkKey,SkNull,SkEnumMember,SkStruct,SkEvent,SkOperator,SkTypeParameter])}), _hierarchicalDocumentSymbolSupport = Just True}), _formatting = Just (FormattingClientCapabilities {_dynamicRegistration = Just False}), _rangeFormatting = Just (RangeFormattingClientCapabilities {_dynamicRegistration = Just False}), _onTypeFormatting = Nothing, _definition = Just (DefinitionClientCapabilities {_dynamicRegistration = Just False}), _typeDefinition = Just (TypeDefinitionClientCapabilities {_dynamicRegistration = Just False}), _implementation = Just (ImplementationClientCapabilities {_dynamicRegistration = Just False}), _codeAction = Just (CodeActionClientCapabilities {_dynamicRegistration = Just False, _codeActionLiteralSupport = Just (CodeActionLiteralSupport {_codeActionKind = CodeActionKindClientCapabilities {_valueSet = List [CodeActionQuickFix,CodeActionRefactor,CodeActionRefactorExtract,CodeActionRefactorInline,CodeActionRefactorRewrite,CodeActionSource,CodeActionSourceOrganizeImports]}})}), _codeLens = Nothing, _documentLink = Nothing, _colorProvider = Nothing, _rename = Just (RenameClientCapabilities {_dynamicRegistration = Just False, _prepareSupport = Nothing}), _publishDiagnostics = Just (PublishDiagnosticsClientCapabilities {_relatedInformation = Just False, _tagSupport = Nothing}), _foldingRange = Nothing}), _window = Nothing, _experimental = Just (fromList [])}, _trace = Nothing, _workspaceFolders = Nothing}} \"key \\\"languageServerHaskell\\\" not found\"")
          :method "window/logMessage")
``

**Comment by joaotavora** [comment]
If I'm not mistaken, event transcripts as produced by Eglot have new lines characters and indentation in them that make things easier to read for human beings. I'm a human being, please, make my life as easy as possible. :-)  if you can, consider the two other bullets of the event-reporting template.

**Comment by kfiz** [comment]
sorry for the lack of newlines, but I actually pasted that directly like this from the eglot event buffer. emacs doesn't error out so `debug-on-error` is  not  triggered.  I can reproduce this with a stripped down `.emacs.el`.
I've also tried this with a different project I get a slightly different error here:
``
(:type 1 :message "haskell-lsp:configuration parse error. NotificationMessage {_jsonrpc = \"2.0\", _method = WorkspaceDidChangeConfiguration, _params = DidChangeConfigurationParams {_settings = Null}} \"parsing Config failed, expected Object, but encountered Null\"")
          :method "window/logMessage")
``

result is the same -> eglot starts, but with crippled functionality.

**Comment by joaotavora** [comment]
> sorry for the lack of newlines, but I actually pasted that directly like this from the eglot event buffer.

But surely that is not the whole eglot event buffer before the error happened.  That seems to be haskell telling eglot that its initialization message is invalid and showing the whole message in a much more unreadable form.  Can you grab the first events of the events buffer in full?

**Comment by kfiz** [comment]
ah. Yes of course, please see this gist:
https://gist.github.com/kfiz/59ec61376858abeddbc4a6b5519e71ef

**Comment by joaotavora** [comment]
Also, I'm fairly sure that the `languageServerHaskell` key is _not_ in the LSP specification.  Perhaps you can grab another clients successful log interaction to see what's up.  Or hail @alanz here to explain what's happening.

**Comment by kfiz** [comment]
You were right, the message was probably a red herring. In the meantime I've updated my `haskell-language-server` package from `0.9.0.0` to `1.0.0.0` and now this issue is fixed. Sorry for the noise.
