### ISSUE TITLE
add eglot-shutdown-all

### ISSUE THREAD

**Issue by odanoburu** [joaotavora/eglot#643]
this a feature request for adding an interactive function `eglot-shutdown-all` (or similar), which does as the name says. some projects start a lot of servers and it's boring to shut them down one at a time (which I need to do to save memory). I could also write my own function, but I don't see how to do it without depending on internal definitions, which I dislike to do…

I can write a PR if you'd like!

**Comment by joaotavora** [comment]
> I could also write my own function, but I don't see how to do it without depending on internal definitions, 

Actually, I don't see you needing more than `eglot-shutdown`, `buffer-list`, `eglot-current-server` but `eglot-shutdown-all` is not a bad idea, if you can keep it around 5 lines or so.

**Comment by odanoburu** [comment]
thanks for the tip! indeed I overlooked using `buffer-list` because I was looking for somewhere in the library where the active servers were being kept.

there was a minor issue with `buffer-list` returning buffers that where killed (a process buffer from a server that was shutdown), so I had to check that buffers were alive:

```elisp
(defun my-eglot-shutdown-all (&optional timeout preserve-buffers)
  (interactive (list nil current-prefix-arg))
  (mapc (lambda (b)
	  (when (buffer-live-p b)
	    (with-current-buffer b
	      (let ((server (eglot-current-server)))
		(when server
		  (eglot-shutdown server nil timeout preserve-buffers))))))
	(buffer-list)))
```

for the PR, should we have a function shutting down all servers in the current project or all servers period? (or both?) I should only need `eglot-shutdown` and `eglot--servers-by-project`, né?

**Comment by joaotavora** [comment]
> for the PR, should we have a function shutting down all servers in the current project, or all servers period? (or both?) I

I don't know, you tell me! you can have more than one server per project in theory (because it's they're keyed by currently by project/major-mode, but is that really important?  If so, I'd say another argument to the new `eglot-shutdown-all`, else, don't bother with it.

I think soon we'll even have more than one server per buffer, but i still have to think about that, so you don't need to consider that scenario.

> I should only need eglot-shutdown and eglot--servers-by-project, né?

iá.
