### ISSUE TITLE
Is this setup correctly?

### ISSUE THREAD

**Issue by jkordani** [joaotavora/eglot#647]
Emacs *messages* says that company-clang can't find clang.  I need to update this variable with the path to clang.  This might be a really dumb question, but does this need to be clang or clangd?  How does company-clang interact with eglot's use of clangd?

**Comment by jkordani** [comment]
sorry for the noise.  I misclicked.  The answer  to my first question is "clang".  My second question still stands, how does eglot play with company-clang?  It seems I already had autocomplete on board even though at the time company-clang couldn't find clang.

**Comment by muffinmad** [comment]
The only company backend to work with Eglot needed is the `company-capf`. Eglot actually configure company backends [here](https://github.com/joaotavora/eglot/blob/b4ffcf26fb392ed83f6c40bc9b62cbe54483119c/eglot.el#L1421).

**Comment by joaotavora** [comment]
> how does eglot play with company-clang

It doesn't.  It's best to drop `company-clang`.  Even the clangd page used to have this advice, but now it doesn't since  Eglot does that for you, in principle.

**Comment by joaotavora** [comment]
To summarize, you only need `clangd` to work with the LSP server `clangd`, which is what Eglot does (talking to LSP servers).

**Comment by jkordani** [comment]
so is there a way to blacklist company-clang from working with eglot? or did I misunderstand, in that company-clang isn't used by eglot, and also therefore isn't active when eglot is in use?

**Comment by joaotavora** [comment]
> so is there a way to blacklist company-clang from working with eglot? or did I misunderstand, in that company-clang isn't used by eglot, and also therefore isn't active when eglot is in use?

Eglot should be taking care of that for you, unless you've got some special configuration. But we don't know that, since you've provided none of those details. Please mind the text that is presented to you when you open an issue. It contains tips on how to compose bug reports that we can help with.

**Comment by jkordani** [comment]
So this doesn't seem like a bug, but I'll try to provide as much info as possible.  I have everything in eglot working as far as I can tell. I have clangd installed, as well as clang, since in eglot events buffer company-clang mode was complaining that it couldn't be found.  I've installed eglot from the latest version in melpa.  In my .emacs config, I have the following per clangd setup guide.
note my addition of global company mode.  In eglot it seems that company-clang is getting activated due to the error in eglot events buffer.  my question is, is this innocuous?  Does company mode simply always start company-clang but eglot ignores it?  or is this a symptom of a problem that should be addressed.  While everything works for me, I am trying to build a setup that I can share with my coworkers and I don't want to give them instructions that cause subtle breakage.

```
(require 'eglot)
(add-to-list 'eglot-server-programs '((c++-mode c-mode) "clangd"))
(add-hook 'c-mode-hook 'eglot-ensure)
(add-hook 'c++-mode-hook 'eglot-ensure)

(require 'company)
(add-hook 'after-init-hook 'global-company-mode)
(add-hook 'c-mode-common-hook
          (lambda ()
            (define-key c-mode-base-map (kbd "<C-tab>") (function company-complete))))
```

**Comment by joaotavora** [comment]
> I am trying to build a setup that I can share with my coworkers and I don't want to give them instructions that cause subtle breakage.

That's a fine idea.

From what I can see, your configuration has nothing wrong with it, assuming it is indeed your complete configuration.  It doesn't seem to contain anything that would trigger the only symptom of a problem that you've posted so far, which is "_Emacs messages says that company-clang can't find clang._"

You also mentioned "_the error in eglot events buffer_" but have not provided a short transcript of those events, as suggested in the issue-opening text.

Now that you've shared a config, you also need to be more specific about the exact circumstances where this happens.  First, confirm that it happens.  Starting `Emacs -Q` and feeding it nothing but that latest config snippet, does it still happen? If so, _when exactly_?

**Comment by jkordani** [comment]
full emacs config below

I want to reiterate that I am not asking about an error.  I am asking if there are any problems with company-clang being able to find a clang executable while eglot mode is driving company mode.

But here are the outputs you wanted

```
(require 'package)

(add-to-list 'package-archives (cons "melpa" "http://melpa.org/packages/") t)

(package-initialize)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(company-clang-executable "nil")
 '(custom-enabled-themes '(misterioso))
 '(package-selected-packages
   '(realgud realgud-lldb eglot dockerfile-mode cmake-mode find-file-in-project org-journal noaa nov jedi elpy indent-tools yaml-mode multiple-cursors hydra lsp-treemacs company company-lsp flycheck avy lsp-mode lsp-ui slime slime-repl-ansi-color xquery-mode xquery-tool hideshow-org outshine ggtags restart-emacs magit magit-svn nyan-mode zone-nyan paredit)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(avy-setup-default)
(global-set-key (kbd "C-c C-j") 'avy-resume)

;; It will bind, for example, avy-isearch to C-' in isearch-mode-map, so that you can select one of the currently visible isearch candidates using avy.

(global-set-key (kbd "C-:") 'avy-goto-char)
(global-set-key (kbd "M-g g") 'avy-goto-line)
(global-set-key (kbd "M-g w") 'avy-goto-word-1)
(global-set-key (kbd "M-g e") 'avy-goto-word-0)

(load (expand-file-name "~/quicklisp/slime-helper.el"))
;; Replace "sbcl" with the path to your implementation
(setq inferior-lisp-program "~/Code/ccl-dev/lx86cl64")



(setq query-dbxml-pipeline "/home/jkordani/lib/db-xml/pipeline.pl")

(defun query-dbxml-with-region (beg end)
  "Query dbxml with selected text"
  (interactive "*r")
  (let ((newbuffer nil)
        (buffer (get-buffer "result"))
        (xquery (buffer-substring beg end)))
    (setq dbxml-result
          (cond
           ((buffer-live-p buffer) buffer)
           (t (setq newbuffer t) (generate-new-buffer "result"))))
    (with-current-buffer dbxml-result
      (with-timeout
          (10 (insert "Gave up because query was taking too long."))
        (erase-buffer)
        (insert (query-dbxml xquery t)))
      (nxml-mode)
      (format-xml)
      (goto-char (point-min))
      (when newbuffer (switch-to-buffer (current-buffer))))))

(defun query-dbxml (xquery &optional timed)
			   "Query the Momentum Berkeley DBXML database with an XQuery string"
			   (let ((file (make-temp-file "elisp-dbxml-")))
			     (write-region xquery nil file)
			     (let ((result (shell-command-to-string
					      (concat "cat " file " | " query-dbxml-pipeline))))
			       (delete-file file)
			       (concat
				(if timed (format "%.3f seconds\n\n" (car result)) nil)
				(cadr result)))))

;; (global-set-key (kbd "<C-S-return>") 'query-dbxml-with-region)
(global-set-key (kbd "<C-S-return>") 'set-mark-command)

(load "/home/jkordani/quicklisp/clhs-use-local.el" t)

(recentf-mode 1)
(setq recentf-max-menu-items 250)
(setq recentf-max-saved-items 250)
(global-set-key "\C-x\ \C-r" 'recentf-open-files)

(run-at-time nil (* 5 60) 'recentf-save-list)

(setq-default indent-tabs-mode nil)

(setq elpy-rpc-python-command "python3.8")

(defun insert-current-date () (interactive)
  (insert (shell-command-to-string "echo -n $(date +%Y-%m-%d)")))
(defun insert-current-time () (interactive)
  (insert (shell-command-to-string "echo -n $(date +%H:%M)")))
(defun insert-current-time-seconds () (interactive)
  (insert (shell-command-to-string "echo -n $(date +%H:%M:%S)")))

(global-set-key (kbd "C-c d") 'insert-current-date)
(global-set-key (kbd "C-c t") 'insert-current-time)
(global-set-key (kbd "C-c T") 'insert-current-time-seconds) 

;; (require 'eglot)
;; (add-to-list 'eglot-server-programs '((c++-mode c-mode) "clangd"))
;; (add-hook 'c-mode-hook 'eglot-ensure)
;; (add-hook 'c++-mode-hook 'eglot-ensure)

;; (require 'rtags)
;; (require 'company)
;; (require 'flycheck-rtags)

;; (add-hook 'after-init-hook #'global-flycheck-mode)

;; (setq rtags-completions-enabled t)
;; (push 'company-rtags company-backends)
;; (global-company-mode)
;; (define-key c-mode-base-map (kbd "<C-tab>") (function company-complete))

;; (rtags-enable-standard-keybindings)

;; (setq rtags-autostart-diagnostics t)
;; (defun my-flycheck-rtags-setup ()
;;   (flycheck-select-checker 'rtags)
;;   (setq-local flycheck-highlighting-mode nil) ;; RTags creates more accurate overlays.
;;   (setq-local flycheck-check-syntax-automatically nil))
;; (add-hook 'c-mode-hook #'my-flycheck-rtags-setup)
;; (add-hook 'c++-mode-hook #'my-flycheck-rtags-setup)
;; (add-hook 'objc-mode-hook #'my-flycheck-rtags-setup)

;; https://emacs-lsp.github.io/lsp-mode/page/performance/
(setq gc-cons-threshold 100000000)
(setq read-process-output-max (* 1024 1024))

;; https://www.reddit.com/r/emacs/comments/l0huvz/how_do_you_solve_merge_conflicts/
(setq ediff-window-setup-function 'ediff-setup-windows-plain)

(defun ask-before-closing ()
  "Prompt for confirmation for emacsclient(not daemon) like 'confirm-kill-emacs' for running Emacs without daemon."
  (interactive)
  (if (y-or-n-p (format "Really exit Emacs? "))
          (save-buffers-kill-terminal)
        (message "Canceled frame close!")))
(when (daemonp)
  (global-set-key (kbd "C-x C-c") 'ask-before-closing))

(setq confirm-kill-emacs #'y-or-n-p)


(require 'eglot)
(add-to-list 'eglot-server-programs '((c++-mode c-mode) "clangd"))
(add-hook 'c-mode-hook 'eglot-ensure)
(add-hook 'c++-mode-hook 'eglot-ensure)

(require 'company)
(add-hook 'after-init-hook 'global-company-mode)
(add-hook 'c-mode-common-hook
          (lambda ()
            (define-key c-mode-base-map (kbd "<C-tab>") (function company-complete))))

(require 're-builder)
(setq reb-re-syntax 'string)

```

sample output text ofmessages buffer (I was mistaken, its not eglot events buffer)r when this occurs when browsing to desired file and issuing eglot to start a server

```
Loading /home/jkordani/quicklisp/slime-helper.el (source)...done
Loading /home/jkordani/quicklisp/clhs-use-local.el (source)...done
Loading /home/jkordani/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
Loading eldoc...done
For information about GNU Emacs and the GNU system, type C-h C-a.
Saving file /home/jkordani/.emacs.d/recentf...
Wrote /home/jkordani/.emacs.d/recentf
mwheel-scroll: Beginning of buffer [2 times]
user-error: Beginning of history; no preceding item
Creating customization items...
Creating customization items ...done
Resetting customization items...done
Creating customization setup...done
You can run the command ‘customize-variable’ with M-x cu-var RET
Creating customization setup...done
mwheel-scroll: Beginning of buffer
Company backend ’company-clang’ could not be initialized:   <-------- THIS LINE
Searching for program: No such file or directory, nil
[eglot] Connected! Server `EGLOT (RME/c++-mode)' now managing `c++-mode' buffers in project `RME'.

```

I can't figure out how to start eglot with emacs -Q

**Comment by joaotavora** [comment]
> I want to reiterate that I am not asking about an error. 

Then I am confused, let me explain why.

From your very first post, you seem to be troubled, or at least slightly disquieted. that there is a `company-clang` error message in your `*Messages*` buffer. And, given my knowledge of Elglot and its history with `company-clangd`  there should, at present, be no reason for this to occur, at least within the context of the Eglot program. At least as long as you have what is considered a sane configuration, which is why I keep insisting on this point. 

Furthermore I must reasonably assume you are associating what clearly is an error or exceptional message with Eglot, because you are reporting it in Eglot's bug tracker.

If it's something else, I don't know what I can help you with.  The only way I can help is by examining the problem and since I'm not sitting next to you, I need you to help me debug this supposed problem with Eglot.  Therefore, I ask you to try to reproduce with the smallest possible configuration that includes Eglot + Company + Emacs _and nothing else_ so that we can either confirm that this is a problem in Eglot, or attribute it as a characteristic of your larger configuration.  

Have you experimented with completely removing Eglot from your configuration? Does the problem still persist when you do so?

If you are not interested in this assistance, that's perfectly fine.  But it is the only type of assistance that I can provide you with.

**Comment by jkordani** [comment]
I'm working in ubuntu 16.04, where we don't use clang for normal day to day operations and it must be installed separately.  Fortunately, clangd exists in a separate package.  At this point, I don't fully understand how Eglot handles all of the different modes, like flycheck and company (which apparently is optional), but my main concern is that originally, company-clang couldn't find clang (since it wasn't installed on my machine) and I was worried that that meant that company mode for use with eglot would be nonfunctional.  Furthermore, since it is said that eglot doesn't use company-clang as a backend, I was worried that allowing company-clang mode access to clang would mess up the operation of eglot's use of company mode.
