### ISSUE TITLE
Wrong Latex Syntax on Parenthesis Inserting the Snippet

### ISSUE THREAD

**Issue by OmarAshkar** [joaotavora/eglot#651]
Hello, 
I have this strange bug on using latex mode with TexLab backend. When I start typing something like 
1. Inside \begin{}, press TAB
3. Select article. RET
I got 
```
begin}article
\end{article}
```
  I don't know how to reproduce this. But there is my backend configuration.

```
(require 'eglot)
(add-to-list 'eglot-server-programs '((latex-mode Tex-latex-mode texmode context-mode texinfo-mode bibtex-mode) "texlab"))
```

Thank You

**Comment by joaotavora** [comment]
Is your backend configuration only those two lines? 

It can't be becasue it seems you're using some kind of yasnippet functionality, and I don't see yanisppet anywhere.  Please try to decipher the text that is presented to you when you open an issue.  Read this link https://github.com/joaotavora/eglot#reporting-bugs

If the text of the link is unclear, please let me know.  Again, I need:

- A minimal reproduction recipe, which is just that, a way to reproduce , to "make happen again" what is happening to you.
- The event transcript read the link to understand what it is
- A backtrace _if_ you saw or heard an error.

I'll reopen once you have supplied these elements, OK? Thanks.
