### ISSUE TITLE
Feature: Support candidate-kind backend call for completion-at-point function

### ISSUE THREAD

**Issue by mohkale** [joaotavora/eglot#652]
Forked from [company#1070](https://github.com/company-mode/company-mode/pull/1070)

Company recently added support for configuring a prefix for completion candidates in the company popup (see [company#756](https://github.com/company-mode/company-mode/issues/756)). The APIs also been updated to allow you to ask what type (in this case LSP kind) a candidate is. It'd be nice if eglot conformed to this new API change :smile:.

**Comment by joaotavora** [comment]
Mohsin Kaleem ***@***.***> writes:

> Forked from company#1070
>
> Company recently added support for configuring a prefix for completion candidates in the company popup (see company#756).
> The APIs also been updated to allow you to ask what type (in this case LSP kind) a candidate is. It'd be nice if eglot
> conformed to this new API change 😄.

Can you explain summarily what this allows, from a user's perspective?
Your sentences are maybe correct but very technical, they could mean
different things, and I don't have time to investigate.

So let's say I'm a user with zero Emacs Lisp experience and I've used
both current Eglot (A) and the imaginary Eglot with the support that you
envision (B).  What are the palpable differences between A and B?  Does
B have fancy icons, fix a known bug, or something like that?

Thanks,
João

**Comment by mohkale** [comment]
I don't think it'll make much of a difference to someone who doesn't know lisp, but to those that do they can configure icons to be shown in the company popup.

![Screenshot_20210329_004428](https://user-images.githubusercontent.com/23294780/112772317-00b6be80-9028-11eb-9114-dd916641df57.png)

**The icons prefixing the candidate in the company popup/tooltip is what I'm trying to setup**

These icons will generally be tied to a specific identifier type (such as keyword, variable, class etc.) so users will need to be able to associate candidates with types. Currently eglot supplies each candidate to company with a `eglot--lsp-item` text property that contains the `:kind` field as a property number. 

The problem with the current approach is firstly we need to know we're using eglot as the backend, we then need to extract the text property followed by the `:kind` field and then we need to associate that with an icon. If how eglot stores lsp-item information in completion candidates changes it'll break so firstly I'd like eglot to confirm with the new API change and add a `:company-kind` field to the result of `eglot-completion-at-point` which returns the `:kind` value.

So instead of end users having to put

```lisp
(plist-get (get-text-property 0 'eglot--lsp-item proxy) :kind)
```

They can use:

```lisp
(company-call-backend 'kind candidate)
```

which is both backend agnostic and synchronised by company itself.

Following this I'd like `eglot` to return the same value for `:kind` in this new API call that lsp-mode does just for consistency with the existing margin function. See reference 2 below.

### Further Links
Let me link you to the default vscode like [margin function](https://github.com/company-mode/company-mode/blob/5a12fa84ab6d81606e995c0ad4f1a8621d8beffc/company.el#L1437) in company.

[Here's](https://github.com/company-mode/company-mode/blob/5a12fa84ab6d81606e995c0ad4f1a8621d8beffc/company.el#L1365) the default alist mapping from lsp-kinds (as symbols) to icons (as SVG files). 

In LSP mode there's an [alist](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-completion.el#L270) mapping from numbers like `eglot--kind-names` to the keys here. Lastly here's `lsp-mode`s [implementation](https://github.com/emacs-lsp/lsp-mode/blob/b807fc934efe064be8ea1a7ca0389724e8a7648c/lsp-completion.el#L297) of `:company-kind`.

**Comment by joaotavora** [comment]
I see. Thank you for the clarification.

Well the first thing to make sure of is that the `company-capf` backend itself, which lives in the Company repository supports these kinds of things.  It seems to be the `:company-kind` key you speak of?  

The second step is figuring out what to feed to `:company-kind` based on each candidate.  Seems to be one of these symbols
```
(defvar company-vscode-icons-mapping
  '((array . "symbol-array.png")
    (boolean . "symbol-boolean.png")
    (class . "symbol-class.png")
    (color . "symbol-color.png")
    (constant . "symbol-constant.png")
    (enum-member . "symbol-enumerator-member.png")
    (enum . "symbol-enumerator.png")
    (event . "symbol-event.png")
    (field . "symbol-field.png")
    (interface . "symbol-interface.png")
    (key . "symbol-key.png")
    (keyword . "symbol-keyword.png")
    (method . "symbol-method.png")
    (function . "symbol-method.png")
    (misc . "symbol-misc.png")
    (module . "symbol-namespace.png")
    (numeric . "symbol-numeric.png")
    (operator . "symbol-operator.png")
    (parameter . "symbol-parameter.png")
    (property . "symbol-property.png")
    (ruler . "symbol-ruler.png")
    (snippet . "symbol-snippet.png")
    (string . "symbol-string.png")
    (struct . "symbol-structure.png")
    (variable . "symbol-variable.png")))
```

> So instead of end users having to put

Why would end users want to put anything or call Elisp. They just want to see pretty icons, right?

> (company-call-backend 'kind candidate)

No, no calls to company from within Eglot.  Eglot has to work entirely without company.  Company is opt-in.  Eglot is headed for Emacs core and my long term plan is to write something that replace company itself.

**Comment by mohkale** [comment]
> No, no calls to company from within Eglot. Eglot has to work entirely without company. Company is opt-in.

Sorry I was referencing users of company, not users of eglot. In this case eglot is just one of many backends.

> Eglot is headed for Emacs core and my long term plan is to write something that replace company itself.

Ooh, interesting :smile:.

> Why would end users want to put anything or call Elisp. They just want to see pretty icons, right?

Yes, in the company tooltip. So they need to assign `company-format-margin-function`. The default margin function only works on the GUI (because it uses SVGs for icons instead of unicode characters) so I've had to redefine it, but for the vast majority of users they'll probably be setting it to one of `company-vscode-dark-icons-margin` or `company-vscode-light-icons-margin`, which calls `(company-call-backend 'kind candidate)`, so if eglot adds a method for it users of company+eglot who're fine with the GUI won't have to configure anything else.

**Comment by mohkale** [comment]
I tried setting adding the `:company-kind` call to eglot and this is what it looks like in `python-mode` with company and pyls.

![Screenshot_20210329_173442](https://user-images.githubusercontent.com/23294780/112870159-d27fc000-90b5-11eb-9498-08114d154801.png)

 I'm using my own icon configuration which basically amounts to something like this:

```lisp
(defconst all-the-icons-lsp-kinds+
  '((text . "T")))

(defconst all-the-icons-default-completion-icon+
  "?")

(setq company-format-margin-function
      (defun company-format-margin-function+ (candidate selected)
        (concat
         (make-string company-tooltip-margin ? )
         (all-the-icons-pad+
          (or
           (when-let ((kind (company-call-backend 'kind candidate)))
             (alist-get kind all-the-icons-lsp-kinds+))
           all-the-icons-default-completion-icon+)))))
``` 

And here are the changes I made to eglot to get all the above screenshot actually working.

```diff
@@ -243,6 +243,26 @@ let the buffer grow forever."
     (13 . "Enum") (14 . "Keyword") (15 . "Snippet") (16 . "Color")
     (17 . "File") (18 . "Reference")))
 
+(defconst eglot--kind-symbols
+  '((1 . text)
+    (2 . method)
+    (3 . function)
+    (4 . constructor)
+    (5 . field)
+    (6 . variable)
+    (7 . class)
+    (8 . interface)
+    (9 . module)
+    (10 . property)
+    (11 . unit)
+    (12 . value)
+    (13 . enum)
+    (14 . keyword)
+    (15 . snippet)
+    (16 . color)
+    (17 . file)
+    (18 . reference)))
+
 (defconst eglot--{} (make-hash-table) "The empty JSON object.")
 
 (defun eglot--executable-find (command &optional remote)
@@ -2010,7 +2030,7 @@ Try to visit the target file for a richer summary line."
                                 (substring (buffer-substring bol (point-at-eol)))
                                 (hi-beg (- beg bol))
                                 (hi-end (- (min (point-at-eol) end) bol)))
-                     (add-face-text-property hi-beg hi-end 'highlight
+                     (add-face-text-property hi-beg hi-end 'xref-match
                                              t substring)
                      (list substring (1+ (current-line)) (eglot-current-column)
                            (- end beg))))))
@@ -2236,6 +2256,11 @@ is not active."
                (concat " "
                        (propertize annotation
                                    'face 'font-lock-function-name-face))))))
+       :company-kind
+       (lambda (proxy)
+         (when proxy
+           (alist-get (plist-get (get-text-property 0 'eglot--lsp-item proxy) :kind)
+                      eglot--kind-symbols)))
        :company-doc-buffer
        (lambda (proxy)
          (let* ((documentation
```

There's probably some room for some cleanup here, specifically with `eglot--kind-names` and `eglot--kind-symbols` both having the same keys, but otherwise this is what I was going for.

**Comment by joaotavora** [comment]
> There's probably some room for some cleanup here, specifically with eglot--kind-names and eglot--kind-symbols both having the same keys, but otherwise this is what I was going for.

Yup, it seems you can get one from the other (or the other from the one) with some `make-symbol`  and string-manupulation stuff.  So just start a PR for this (do you have a FSF copyright assignment?)

Please make a separate PR for this other bit of diff, and sorry I didn't reply in the other message, it slipped by.

> -                     (add-face-text-property hi-beg hi-end 'highlight
> +                     (add-face-text-property hi-beg hi-end 'xref-match

**Comment by mohkale** [comment]
> So just start a PR for this (do you have a FSF copyright assignment?)

Yep. Will get started soon.

> Please make a separate PR for this other bit of diff, and sorry I didn't reply in the other message, it slipped by.

Oh sorry, didn't realise that got mixed in that's from issue #650, I was still waiting for you to respond on it.

**Comment by mohkale** [comment]
@joaotavora 

Started the PRs, please review when you get a chance. I'll forward my FSF papers to you by email.
