### ISSUE TITLE
Can't get hover result if there is a diagnostic at the same position

### ISSUE THREAD

**Issue by firewall2142** [joaotavora/eglot#659]
When there is a diagnostic at a position, I can't get the result from hover to display in the minibuffer. Only the diagnostic message is displayed.
Can it be possible to get results from both hover and diagnostic to display or only hover?
[events buffer](https://pastebin.com/raw/j9yaf68r)

**Comment by joaotavora** [comment]
Have a look at `eldoc-documentation-strategy`, and set it to `#'eldoc-documentation-compose` either globally or locally. This ties with #648, let's continue there.
