### ISSUE TITLE
Request: Auto installing/building language server

### ISSUE THREAD

**Issue by jojojames** [joaotavora/eglot#69]
Trying out VsCode's integration of https://github.com/fwcd/KotlinLanguageServer, the install experience is very seemless. Upon entering a .kt (kotlin file), VsCode will open a small popup that asks to look up existing Kotlin extensions on the marketplace. Pressing 'install' on the list of available kotlin extensions 'installs' the extension/language server into a .vscode/extensions directory where the language server client then knows to point to that server.

It might be cool to try to provide some kind of auto-install/building which builds in some kind of custom user directory emacs users can set which eglot can then look for when trying to start the language server. I think there are a couple of other emacs packages that do auto install (or provide a command to do an install) (maybe rtags, irony-mode, meghanada, anaconda?, etc).

This might be out of scope for eglot but I thought I'd put a request in anyways.

Thanks!

**Comment by joaotavora** [comment]
> This might be out of scope for eglot 

Pretty much, yes

This is better done in an emacs package that auto-installs the server (if that's at all possible, as you say) and adds an entry to `eglot-server-programs` with the correct path an and arguments.

**Comment by jojojames** [comment]
Thanks, sounds good to me.
