### ISSUE TITLE
Using `eglot-alternatives` results in more calls to `executable-find` than necessary

### ISSUE THREAD

**Issue by jimporter** [joaotavora/eglot#703]
(Spun off from #702.) This is a *very* minor issue, and I'd be perfectly fine with you just closing this and saying it's not worth fixing. I'm also happy to file a PR if we agree on the solution.

There's a relatively-easy (I hope) opportunity to improve the speed at which `M-x eglot` starts up. When a mode's LSP servers in `eglot-server-programs` are defined via `eglot-alternatives`, Eglot will call `executable-find` at least once to determine which alternative to use: https://github.com/joaotavora/eglot/blob/5cc8df63d86a6c43134dd6e4e3ae26cfae14e66a/eglot.el#L107

Then it will call `executable-find` again in `eglot--guess-contact` with the chosen alternative: https://github.com/joaotavora/eglot/blob/5cc8df63d86a6c43134dd6e4e3ae26cfae14e66a/eglot.el#L836

We could avoid the last `executable-find` call, since we already *know* if the program exists. If we take [your patch](https://github.com/joaotavora/eglot/pull/702#issuecomment-859956184) and additionally enhance the `eglot-alternatives` lambda to return an absolute path for the program, that should fix this. That is, `(funcall (eglot-alternatives '("pyls" "pylsp")))` currently returns `'("pylsp")`, and after the patch, would return `'("/path/to/pylsp")`.

One other thing is what to do when the `eglot-alternatives` lambda can't find anything. (Note: I only mention all this for completeness; I think we can ignore the doubled call to `executable-find` here.) Currently, it just returns the first alternative. On the one hand, we already know `executable-find` failed, so there's no need to try again in `eglot--guess-contact`. On the other hand, we want to know the program name so we can mention it in the prompt:

https://github.com/joaotavora/eglot/blob/5cc8df63d86a6c43134dd6e4e3ae26cfae14e66a/eglot.el#L837-L840

Ultimately, this last bit is rare (assuming the user correctly configured things), and the performance doesn't matter much, since the majority of the user's time will be spent reading the prompt and entering the command they want to use. As mentioned, this is just here for completeness.

---

     
* Server used: pylsp              
* Emacs version: GNU Emacs 27.2 (build 1, x86_64-w64-mingw32) of 2021-03-26            
* Operating system: MS Windows         
* Eglot version: 20210611.2249            
* Eglot installation method: MELPA/use-package      
* Using Doom: No               

#### LSP transcript - M-x eglot-events-buffer (mandatory unless Emacs inoperable)

     
N/A: happens before the LSP server starts
    
#### Backtrace (mandatory, unless no error message seen or heard):

Here are the contents of `*trace-output*`. (See below for details about my setup.)
```lisp
======================================================================
1 -> (eglot--executable-find "pyls" t)
1 <- eglot--executable-find: nil
======================================================================
1 -> (eglot--executable-find "pylsp" t)
1 <- eglot--executable-find: "/home/jim/.virtualenvs/testenv/bin/pylsp"
======================================================================
1 -> (eglot--executable-find "pylsp" t)
1 <- eglot--executable-find: "/home/jim/.virtualenvs/testenv/bin/pylsp"
```
   
#### Minimal configuration (mandatory)

First, install `python-lsp-server` on the remote machine. Then:     
 ```sh
 # Type this in a shell to start an Emacs with Eglot configured
 $ /path/to/a/certain/version/of/emacs -Q -f package-initialize -L /path/to/git-cloned/eglot -l eglot.el 
 ```
 
 
 
 ```lisp
 ;; Configuration to evaluate:
 (require 'eglot)
 (trace-function-background #'eglot--executable-find)
  ```
```lisp
;; After setting the above up, do the following:
C-x C-f /ssh:server:/path/to/python-file.py
M-x eglot
C-x b *trace-output*  ;; See above for results
```

**Comment by jimporter** [comment]
Oh, while I'm thinking of it: another option would be to have a sentinel argument that you can put at the start of the LSP program arguments list to tell `eglot--guess-contact` not to call `executable-find`. Something like `'(no-executable-find "pylsp" ...)`. 

That resolves both the main issue *and* the edge case where `eglot-alternatives` can't find any of the options. (It also means that we don't have to modify the program name to be an absolute path, but I'm not sure that actually matters.)

**Comment by joaotavora** [comment]
@jimporter can you check that commit/branch?

**Comment by jimporter** [comment]
@joaotavora The branch doesn't quite work unfortunately. Before I explain what went wrong though, I wanted to mention the results of my more-extensive performance tests. I found that `(executable-find "program" t)` in a remote buffer is somewhat slow the first time you call it (about 0.1-0.15s on a fast connection from a Windows client to a Linux server on a LAN)[1]. However, if you call it again immediately with the same arguments, it's very fast (about 0.005s). That's how `eglot--guess-contact` works though, so (at least on my system), we should be ok and only waste about 0.005s on a superfluous `executable-find` call.

[1]: This is assuming `program` exists. If it doesn't, the call is *very* slow (~1.1s), but that doesn't matter for this issue. This slowness does matter for daily use though, since it means Eglot starts up a lot faster over TRAMP if you can ensure that your server of choice is the first alternative. This might be an argument for putting `pylsp` first in the alternatives list, since it seems to be the preferred Python LSP server going forward?

---

Like I said earlier, I have no problem if you decide that a fix for this is too complex for the seemingly-small performance benefit (though maybe it's worse over slow networks). If you're still interested, here what went wrong when I tested your patch:

As before, I'm running `M-x eglot` in a Python buffer with `pylsp` installed. This happens locally and over TRAMP. Once I run `M-x eglot`, I get `eglot--error: [eglot] -1: Server died`. The event buffer is below, but I dug into it a bit more and the issue is in the interactive branch of `eglot-alternatives`. If I run `(funcall (eglot-alternatives '("pyls" "pylsp")) t)`, I get `("pylsp" "/home/jim/.virtualenvs/testenv/bin/pylsp")`, which isn't right.

**M-x eglot-events-buffer**:
```
[client-request] (id:1) Sun Jun 13 10:26:34 2021:
(:jsonrpc "2.0" :id 1 :method "initialize" :params
	  (:processId 196355 :rootPath "/home/jim/src/pytest/" :rootUri "file:///home/jim/src/pytest" :initializationOptions #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
																	     ())
		      :capabilities
		      (:workspace
		       (:applyEdit t :executeCommand
				   (:dynamicRegistration :json-false)
				   :workspaceEdit
				   (:documentChanges :json-false)
				   :didChangeWatchedFiles
				   (:dynamicRegistration t)
				   :symbol
				   (:dynamicRegistration :json-false)
				   :configuration t)
		       :textDocument
		       (:synchronization
			(:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
			:completion
			(:dynamicRegistration :json-false :completionItem
					      (:snippetSupport :json-false)
					      :contextSupport t)
			:hover
			(:dynamicRegistration :json-false :contentFormat
					      ["markdown" "plaintext"])
			:signatureHelp
			(:dynamicRegistration :json-false :signatureInformation
					      (:parameterInformation
					       (:labelOffsetSupport t)
					       :activeParameterSupport t))
			:references
			(:dynamicRegistration :json-false)
			:definition
			(:dynamicRegistration :json-false)
			:declaration
			(:dynamicRegistration :json-false)
			:implementation
			(:dynamicRegistration :json-false)
			:typeDefinition
			(:dynamicRegistration :json-false)
			:documentSymbol
			(:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
					      (:valueSet
					       [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
			:documentHighlight
			(:dynamicRegistration :json-false)
			:codeAction
			(:dynamicRegistration :json-false :codeActionLiteralSupport
					      (:codeActionKind
					       (:valueSet
						["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
					      :isPreferredSupport t)
			:formatting
			(:dynamicRegistration :json-false)
			:rangeFormatting
			(:dynamicRegistration :json-false)
			:rename
			(:dynamicRegistration :json-false)
			:publishDiagnostics
			(:relatedInformation :json-false))
		       :experimental #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
						   ()))))
[stderr] usage: pylsp [-h] [--tcp] [--host HOST] [--port PORT] [--check-parent-process]
[stderr]              [--log-config LOG_CONFIG | --log-file LOG_FILE] [-v]
[stderr] pylsp: error: unrecognized arguments: /home/jim/.virtualenvs/testenv/bin/pylsp
[internal] Sun Jun 13 10:26:34 2021:
(:message "Connection state changed" :change "exited abnormally with code 2\n")

----------b---y---e---b---y---e----------
```

**Comment by joaotavora** [comment]
> If I run (funcall (eglot-alternatives '("pyls" "pylsp")) t), I get ("pylsp" "/home/jim/.virtualenvs/testenv/bin/pylsp"), which isn't right.

Ah, that's easily fixed.  Thanks for spotting this.

You mentioned that `executable-find` is fast, even remotely, if called with identical arguments .What if one calls with different arguments but still remotely? Slow again, or same speed?

**Comment by joaotavora** [comment]
> Like I said earlier, I have no problem if you decide that a fix for this is too complex for the seemingly-small performance benefit (though maybe it's worse over slow networks). 

When using `eglot-ensure` instead of `M-x eglot` (a lot of people use this), the call to `eglot-alternatives` is non-interactive.  It makes sense _not_ to search for all executables, especially if, as you say, a call to `executable-find` for something that doesn't exist is slow. Before this proposed version, all alternatives are passed to `executable-find`, which is sub-optimal.  Before this proposed version, it wouldn't matter if you put the existing version first in the list, the non-existing one would still be searched for.

**Comment by jimporter** [comment]
> You mentioned that `executable-find` is fast, even remotely, if called with identical arguments .What if one calls with different arguments but still remotely? Slow again, or same speed?

Slow again. Below are some tests with `M-x benchmark`.

Calling `(exectuable-find "pylsp" t)` twice in a row:
```
Elapsed time: 0.108894s (0.020249s in 1 GCs)
Elapsed time: 0.005331s
```

Calling `(executable-find "gcc" t)` twice in a row:
```
Elapsed time: 0.660305s (0.077172s in 4 GCs)
Elapsed time: 0.014340s
```

Calling `(executable-find "gcc" t)` and then `(executable-find "g++" t)`:
```
Elapsed time: 0.622032s (0.058182s in 3 GCs)
Elapsed time: 0.631826s (0.060202s in 3 GCs)
```

And just for completeness, calling `(executable-find "nonexist" t)`:
```
Elapsed time: 1.156021s (0.117547s in 6 GCs)
```

Interestingly, the results for `(executable-find "gcc" t)` are significantly slower than `(executable-find "pylsp" t)`. My guess is that this is because `pylsp` is found in the first entry in my `PATH`, whereas `gcc` is in the 6th.

It might even be worthwhile to see if `executable-find` itself can be improved, since 0.6s is surprisingly long for such a simple operation.

**Comment by joaotavora** [comment]
Thanks. let me know if the latest commit is better than last time or if you still find problems.

**Comment by jimporter** [comment]
@joaotavora Everything seems to work well for me with the latest commit (I tried both locally and over TRAMP). Thanks!

**Comment by jimporter** [comment]
I believe this can be closed now.

**Comment by joaotavora** [comment]
Hi. I just noticed I hadn't actually pushed the commits to master. I have now.
