### ISSUE TITLE
package-install failed on fetching xref-1.0.4

### ISSUE THREAD

**Issue by kkzhou** [joaotavora/eglot#714]
My emacs version is:

GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2020-08-12

helm-M-x-execute-command: https://elpa.gnu.org/packages/xref-1.0.4.el: Not found
Mark set

**Comment by joaotavora** [comment]
Doesn't seem to be an Eglot problem, does it? Try opening a conversation instead. The bug reporting template that you skipped entirely ,😉 also contains more information on where to report and get help for these problems.
