### ISSUE TITLE
No prompt for command when starting eglot without server programs on the exec path

### ISSUE THREAD

**Issue by dgarbuzov** [joaotavora/eglot#719]
Updated the package from melpa today and it looks like `M-x eglot` no longer prompts for a command to use, even with a prefix argument supplied, if none of the specified commands in `eglot-server-programs` for the mode are on the `exec-path`. Previously, I would run the lsp server in a container and connect through a socket without having the server installed on the host machine. Workaround is to add a noop executable on the `exec-path`.

     
* Server used:               pylsp via a socket
* Emacs version:            27.2
* Operating system:         arch linux
* Eglot version:             20210721.2323 (194b178e)
* Eglot installation method:       package.el (melpa)
* Using Doom:                no

#### LSP transcript - M-x eglot-events-buffer (mandatory unless Emacs inoperable)

     
n/a -- error connecting
    
#### Backtrace (mandatory, unless no error message seen or heard):

     
```lisp
Debugger entered--Lisp error: (error "None of ’pylsp, pyls’ are valid executables")
  signal(error ("None of ’pylsp, pyls’ are valid executables"))
  error("None of '%s' are valid executables" "pylsp, pyls")
  #f(compiled-function (alternatives) #<bytecode 0x156000856a89>)(("pylsp" "pyls"))
  #f(compiled-function (&optional interactive) #<bytecode 0x1560009c3185>)(t)
  eglot--guess-contact(t)
  byte-code("\300\301\302!\303\"\207" [append eglot--guess-contact t (t)] 3)
  call-interactively(eglot record nil)
  command-execute(eglot record)
  execute-extended-command((4) "eglot" "eglot")
  funcall-interactively(execute-extended-command (4) "eglot" "eglot")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
   
#### Minimal configuration (mandatory)

Neither `pylsp` nor `pyls` availble on the `exec-path` on the host

**Comment by joaotavora** [comment]
Thanks. Does seem like a regression, indeed
