### ISSUE TITLE
[Question] How to make xref prompt for input when using at blank line

### ISSUE THREAD

**Issue by BooAA** [joaotavora/eglot#735]
I think this is a feature of eglot (I saw the corresponding method in the source code to message "No definition found for...."), but I'm used to move to blank line and press `M-.`, then xref will prompt me for input. How can I reproduce this behavior in eglot?

**Comment by joaotavora** [comment]
Eglot doesn't support this. It might in the future, maybe. Originally, this was a hard limitation of LSP itself, but it seems some servers have surpassed it.

May I also ask if you didn't see the issue-creating template? Converting this to a discussion.
