### ISSUE TITLE
[Q,FR] How do I get the documentation for an arbitrary symbol (inputted as a string)?

### ISSUE THREAD

**Issue by NightMachinary** [joaotavora/eglot#743]
I want to implement some UI elements that show documentation. 
E.g., I like to add a docstring to `ivy`. An example follows for elisp:
![image](https://user-images.githubusercontent.com/36224762/134042304-e2755214-6c69-4396-9700-a05233d6aaf0.png)

Here is an eglot-managed Julia file, where the docstrings are shown as "not implemented":
![image](https://user-images.githubusercontent.com/36224762/134042409-873d9a75-a09c-4654-80ce-d444f1594f5a.png)

To accomplish this, I need to be able to query eglot for the docstrings of any symbol:
```elisp
(eglot-imaginary-query-docstring "include")
```

I can't find how to do this.

Doom has a handy function for getting the documentation of the thing at point:
```elisp
  (defun night/eglot-documentation-at-point ()
    (eglot--dbind ((Hover) contents range)
        (jsonrpc-request (eglot--current-server-or-lose) :textDocument/hover
                         (eglot--TextDocumentPositionParams))
      (let ((blurb (and (not (seq-empty-p contents))
                        (eglot--hover-info contents range)))
            (hint (thing-at-point 'symbol)))
        (if blurb
            blurb
          (help-at-pt-kbd-string)))))
```

But this obviously only works for the symbol at point.

**Comment by joaotavora** [comment]
> But this obviously only works for the symbol at point.

LSP only works for the symbol at point, so I don't think you'll be easily able to make a function with that API.

[By the way, did you miss the issue creating template altogether?  People are creating issues when I ask to create conversations.  Perhaps they are simply not seeing the template where I ask this]
