### ISSUE TITLE
References in xref buffer are in reversed order

### ISSUE THREAD

**Issue by muffinmad** [joaotavora/eglot#763]
Sorting was disabled in https://github.com/joaotavora/eglot/issues/220

But can we show the references in the same order the server sends them?

Looks like it's because of `push` here: https://github.com/joaotavora/eglot/blob/55c13a91378cdd7822c99bbbf340ea76b1f0bf38/eglot.el#L2134

<img width="595" alt="Знімок екрана 2021-11-24 о 10 19 35" src="https://user-images.githubusercontent.com/2702727/143209274-f738f315-3a49-4cce-9065-ce7bb16340c3.png">

* Server used: anakinls
* Emacs version: GNU Emacs 29.0.50 (build 2, x86_64-apple-darwin20.5.0, NS appkit-2022.50 Version 11.4 (Build 20F71)) of 2021-10-07
* Operating system: macos
* Eglot version:  20211116.823
* Eglot installation method: package.el
* Using Doom: No

#### LSP transcript
```lisp
[client-request] (id:17) Wed Nov 24 10:18:42 2021:
(:jsonrpc "2.0" :id 17 :method "textDocument/references" :params
	  (:textDocument
	   (:uri "file:///Users/mad/workspace/test/test.py")
	   :position
	   (:line 4 :character 0)
	   :context
	   (:includeDeclaration t)))
[server-reply] (id:17) Wed Nov 24 10:18:42 2021:
(:jsonrpc "2.0" :id 17 :result
	  [(:uri "file:///Users/mad/workspace/test/test.py" :range
		 (:start
		  (:line 0 :character 4)
		  :end
		  (:line 0 :character 8)))
	   (:uri "file:///Users/mad/workspace/test/test.py" :range
		 (:start
		  (:line 4 :character 0)
		  :end
		  (:line 4 :character 4)))])
```
       
#### Minimal configuration
Nothing special. Just eglot.
```lisp
(require 'package)
(add-to-list 'package-archives
            '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)

(package-install 'eglot)
```

**Comment by joaotavora** [comment]
Thanks @muffinmad . If it's just a `push` it sounds like not much thought was put into this, so go ahead and add a `reverse` somewhere (or if it makes sense and is easy enough, make it a `loop/collect` cycle).  Thanks!

**Comment by skangas** [comment]
This should now be fixed, please test and report back if it doesn't work for you. Thanks for the bug report!
