### ISSUE TITLE
Pyright and :company-docsig

### ISSUE THREAD

**Issue by fbergroth** [joaotavora/eglot#769]
One cool feature of pyright is that it gives completions in other modules and automatically inserts the import when committing such completions. Here I complete `isinf` from `numpy` (using corfu).

![rec](https://user-images.githubusercontent.com/1211003/146088988-6f13ddc3-b4a6-4100-bcbf-e4281ceab4ff.gif)

Pyright is sending `:data (... :autoImportText "from numpy import isinf" ...)`, so I had to do the following to get the stuff shown in the echo area:

```diff
@@ -2394,6 +2394,12 @@ is not active."
                      (kind (alist-get (plist-get lsp-item :kind)
                                       eglot--kind-names)))
            (intern (downcase kind))))
+       :company-docsig
+       (lambda (proxy)
+         (when-let* ((lsp-comp (get-text-property 0 'eglot--lsp-item proxy))
+                     (data (plist-get (funcall resolve-maybe lsp-comp) :data))
+                     (import-text (plist-get data :autoImportText)))
+           import-text))
        :company-doc-buffer
        (lambda (proxy)
          (let* ((documentation
```
Auto-import completions are not nearly as useful if you can't see where the symbol is coming from.

I understand that this is outside of the spec, but would it be possible to somehow support this?

**Comment by joaotavora** [comment]
Not sure I fully understand the problem, but supporting things outside the spec is fine as long as they don't clash with things inside the spec or other existing behaviour.  Was company `:docsig` unused totally?  if so, it doesn't clash with anyone, but leave at least a comment and a FIXME saying it is python-specific

**Comment by fbergroth** [comment]
The problem is that you don't really know if `inf` comes from `numpy` or `math` without seeing the `autoImportText` portion. It seems like corfu is dropping duplicates, otherwise there would be two indistinguishable completions for `inf`.

> Was company :docsig unused totally?

Yep.

>  if so, it doesn't clash with anyone, but leave at least a comment and a FIXME saying it is python-specific

Right, I opened a PR for this.
