### ISSUE TITLE
An API function for displaying list of xrefs

### ISSUE THREAD

**Issue by mkcms** [joaotavora/eglot#77]
Some servers like eclipse.jdt.ls and cquery provide with code lens information where a symbol is referenced etc. I wonder if we could have an API function that all servers could use, for example `eglot-show-xrefs` which would take a list of locations and display them in a buffer, like  `M-.`. There already is `xref--show-xrefs`, but it's xref's internal. Having such a function would make it easier to extend servers and would also make the UI consistent for all servers.

**Comment by MaskRay** [comment]
`textDocument/references` has an optional parameter: `context.includeDeclaration`. Not many language servers use this but they are meaningful in [ccls](https://github.com/maskray/ccls/blob/master/src/messages/textDocument_references.cc#L33) / cquery.

I prefer `false` because I don't want to see definitions / declarations in the reference list.

**Comment by joaotavora** [comment]
> eglot-show-xrefs which would take a list of locations and display them in a buffer, like M-.. There already is xref--show-xrefs, but it's xref's internal

@mkcms , why don't you propose this for Emacs itself?

**Comment by casouri** [comment]
Any progress on this? I agree that xref should be extended and let eglot support it, instead of adding a custom feature into eglot.

**Comment by mkcms** [comment]
OK, so I just had a look at `xref.el` and I noticed that there's a variable `xref-show-xrefs-function`.
It looks like it is public. It's not very documented though, and I don't know what it's second argument does.

@joaotavora Given that, should `typeDefinition` request be implemented in a new command, e.g. `eglot-show-type-definitions`?

**Comment by mkcms** [comment]
Still, maybe xref needs to be extended because I'm missing something? Although the variable I mentioned above seems like a good candidate for our use cases.

**Comment by MaskRay** [comment]
Another thing: `xref-file-location` encodes `file,line,column`, where the latter two `line,column` roughly correspond to `interface Position`. But how does it encode a range (with two positions)?

LSP 3.14 added `LocationLink` as an alternative return type of `textDocument/{definition,references,implementation,typeDefinition}`:

```typescript
interface LocationLink {

	/**
	 * Span of the origin of this link.
	 *
	 * Used as the underlined span for mouse interaction. Defaults to the word range at
	 * the mouse position.
	 */
	originSelectionRange?: Range;

	/**
	 * The target resource identifier of this link.
	 */
	targetUri: string;

	/**
	 * The full target range of this link.
	 */
	targetRange: Range;

	/**
	 * The span of this link.
	 */
	targetSelectionRange?: Range;
}
```

I believe only `targetUri` and `(or targetSelectionRange targetRange)` are really useful for Emacs.

**Comment by nemethf** [comment]
It's not a public API, but Eglot now has eglot--lsp-xref-helper which shows how it is possible to use the public API of xref.el to display an arbitrary list of xref items.  So do you think, @mkcms, we can close this issue?
