### ISSUE TITLE
Release version 1.8

### ISSUE THREAD

**Issue by skangas** [joaotavora/eglot#782]
The last release on GNU ELPA was ~12 months ago. Please consider bumping the version to get recent changes to users.

Thanks!

**Comment by joaotavora** [comment]
ACK

**Comment by skangas** [comment]
Unless there are any objections, I plan to bump the version after #786 is merged. At a glance, the entry in `NEWS.md` looks fine to me, but please speak up if there is something that is missing.

**Comment by joaotavora** [comment]
Maybe I would add to the `NEWS.md` some entries about the recently merged PRs and commit that before releasing.  At the end of that file you'll find some bit of elisp code that you can evaluate with `C-x C-e`. It'll automatically update the missing Markdown links to issues.  Should be more or less self-explanatory, but let me know it it's not.

**Comment by skangas** [comment]
> Maybe I would add to the `NEWS.md` some entries about the recently merged PRs and commit that before releasing.

Thanks, I've made some updates. Unless there are some very obvious PRs coming in within the next day or two, I will make the release.

> At the end of that file you'll find some bit of elisp code that you can evaluate with `C-x C-e`. It'll automatically update the missing Markdown links to issues. Should be more or less self-explanatory, but let me know it it's not.

It was self-explanatory, thanks for pointing me to it.

**Comment by skangas** [comment]
Version 1.8 has now been released:

https://github.com/joaotavora/eglot/tree/1.8
