### ISSUE TITLE
eglot--lookup-mode returns no language-id

### ISSUE THREAD

**Issue by nemethf** [joaotavora/eglot#837]
If Eglot cannot guess the contact info for a server it asks the user to type the command that stats the server.  In this case Eglot sends nil as the language-id, which causes some servers (rust-analyzer or anything pygls based) to fail.  More precisely, `eglot--lookup-mode` returns nil in `eglot--guess-contact`, so the user is asked to "Enter program to execute ...", but language-id remains nil.

Obviously, this is not a problem for rust-analyzer as it is in `eglot-server-programs`.  But the bug may affect other servers that follow the specification and expect the language-id to be a string.

The patch bellow fixes the problem, although I'm not sure this is the right approach.
```diff --git a/eglot.el b/eglot.el
index e3f0654..6386710 100644
--- a/eglot.el
+++ b/eglot.el
@@ -854,7 +854,8 @@ LANGUAGE-ID is determined from MODE."
                               (string-remove-suffix "-mode" (symbol-name mode))))
                       contact))))
             (if (or (symbolp modes) (keywordp (cadr modes)))
-                (list modes) modes))))
+                (list modes) modes))
+   finally return `(,(string-remove-suffix "-mode" (symbol-name mode)) . nil)))
 
 (defun eglot--guess-contact (&optional interactive)
   "Helper for `eglot'.
```
  
* Server used:               rust-analyzer 
* Emacs version:           GNU Emacs 27.1
* Operating system:      Debian GNU/Linux 11 (bullseye)
* Eglot version:             1.8
* Eglot installation method:       git checkout 
* Using Doom:                No

#### LSP transcript - M-x eglot-events-buffer (mandatory unless Emacs inoperable)
this is the relevant part:
```lisp
(:jsonrpc "2.0" :method "textDocument/didOpen" :params
          (:textDocument
           (:uri "file:///home/nemethf/src/eglot/rust-hello-world/main.rs" :version 0 :languageId nil :text "....
```
    
#### Backtrace (mandatory, unless no error message seen or heard):
Instead of a backtrace, here is the end of the message buffer:     
```
[eglot] Connected! Server `rust-analyzer' now managing `rust-mode' buffers in project `rust-hello-world'.
[jsonrpc] Server exited with status 101
[eglot] (warning) Not auto-reconnecting, last one didn't last long.
```
   
#### Minimal configuration (mandatory)
     
 ```sh
 # Type this in a shell to start an Emacs with Eglot configured
 $ /path/to/a/certain/version/of/emacs -Q -f package-initialize -L /path/to/git-cloned/eglot -l eglot.el 
 ```
 
 
 ```lisp
 (setq  eglot-server-programs nil)
  ```

**Comment by joaotavora** [comment]
I did a decent-ish fix for this.  If the guess is not good enough, we could prompt the user directly for the language id, but at that point it's better to advise the user to build a `eglot-server-programs` entry.
