### ISSUE TITLE
Trying to get eglot to work with PHP

### ISSUE THREAD

**Issue by gayanhewa** [joaotavora/eglot#85]
I am trying to configure eglot with php language server. I am running the language server externally and wanted to configure it by `M-x eglot` and entering the `host:port` 

I have hit a wall with the jsonrpc error, so I cloned the repo and tried again on without any of my other configurations. I still seem to get the following error and everything freezes. I am on the master branch with this sha `e5b89af36236618b8b7a375d2dd4eb2929715a14`

<img width="768" alt="screen shot 2018-08-23 at 17 38 54" src="https://user-images.githubusercontent.com/1681406/44535910-7b463180-a6fb-11e8-92b0-23e7f6320e51.png">

**Comment by joaotavora** [comment]
@gayanhewa sorry to have let this fly under my radar. Please comment and I will reopen if the problem still persists.
