### ISSUE TITLE
textDocument/didChange has incorrect syncKind

### ISSUE THREAD

**Issue by zainab-ali** [joaotavora/eglot#86]
In `eglot--signal-textDocument/didChange`, the following line:
```
(sync-kind (eglot--server-capable :textDocumentSync))
```

should be
```
(sync-kind (eglot--server-capable :textDocumentSync :change))
```

Without this, we never handle the case of full sync and always send incremental updates.

**Comment by joaotavora** [comment]
Hi. Thanks for the report.

> Without this, we never handle the case of full sync and always send incremental updates.

No.  That only happens if the server is sending a `TextDocumentSyncOptions `structure in the value of `:textDocumentSync`. Most are sending just a number.  

The commit I pushed handles both cases.

**Comment by zainab-ali** [comment]
Thanks!
