### ISSUE TITLE
Hyperlinks from markdown hover text are unclickable

### ISSUE THREAD

**Issue by astoff** [joaotavora/eglot#865]
* Server used: Digestif
* Emacs version: 28
* Operating system: Linux
* Eglot version: 1.8            
* Eglot installation method: ELPA      
* Using Doom: No               

When an Eldoc buffer produced by Eglot contains hyperlinks (because the server sent the hover text in markdown format), the hyperlinks are formatted as such and contain the URL in the help-echo property, but clicking a link doesn't work.

This is because the markdown-mode command that opens the link relies on invisible text around the hyperlink to discover the URL. However, Eglot strips the invisible text in this line:

https://github.com/joaotavora/eglot/blob/d03235f39a39bdf2e74571d695163aa42f5b9506/eglot.el#L1439

In my opinion, the correct implementation of that function is as follows:

https://github.com/astoff/eglot/blob/b4a416f1c13ce0472944e385b867d79d9277c880/eglot.el#L1439-L1441

Now, the use of `filter-buffer-substring` originated from #482. The problem was that a specific server would send a hover string that started with "```\n", so when Eldoc would display the first line of the Eldoc buffer in the echo area, the results were poor.  Here are my observations:

- I can't reproduce the reported behavior with pylsp, perhaps the server changed its behavior.
- On the other hand, I don't know if any other server adds hyperlinks. Digestif does that because most TeX documentation is in PDF format, and pointing to a file for the user to look further is about the best I can do in most cases. (This also makes this issue rather low priority, I guess).
- Markdown mode is probably not at fault, as discussed here: https://github.com/jrblevin/markdown-mode/issues/693
- In the problem reported at #482, it's arguably Eldoc who's at fault. It should copy one visual line to the echo area and make sure it retains its essential display properties.

**Comment by joaotavora** [comment]
I like your reasoning Augusto. Let's fix Eglot and Eldoc. In that order
sounds good to me.

João

**Comment by astoff** [comment]
Okay, I made a pull request. But please take into account that this order of fixing things may break Eldoc for some users, for some time.

**Comment by astoff** [comment]
By the way, we should mention this to @muffinmad, who introduced the change that led to this.

**Comment by muffinmad** [comment]
Sadly, this breaks my setup. I'm using `anakin-language-server` wich sends hover info like
```
(:kind "markdown" :value "```python\nint(x: Union[str, bytes, SupportsInt, _SupportsIndex, _SupportsTrunc]=...)\n...
```
Setting the `eldoc-echo-area-use-multiline-p` variable to 1 leads to empty echo area instead of the first line of the hover info.

**Comment by joaotavora** [comment]
I don't understand this.  Both pre-and and post-change code seems to yield the same value when applied to your example @muffinmad:

```
(eglot--format-markup "```python\nint(x: Union[str, bytes, SupportsInt, _SupportsIndex, _SupportsTrunc]=...)\n")
```

returns:
```
#("```python\nint(x: Union[str, bytes, SupportsInt, _SupportsIndex, _SupportsTrunc]=...)\n```" 0 3
  (face
   (markdown-markup-face markdown-code-face)
   invisible markdown-markup markdown-gfm-block-begin
   (1 10 1 4 4 4 4 10 nil nil 10 10 #<killed buffer>))
  3 9
  (face
   (markdown-language-keyword-face markdown-code-face)
   invisible markdown-markup markdown-gfm-block-begin
   (1 10 1 4 4 4 4 10 nil nil 10 10 #<killed buffer>))
  9 10
  (invisible markdown-markup face
             (markdown-code-face)
             font-lock-multiline t)
  10 85
  (font-lock-multiline t face
                       (markdown-pre-face markdown-code-face)
                       markdown-gfm-code
                       (11 86))
  85 86
  (font-lock-multiline t face
                       (markdown-markup-face markdown-code-face)
                       invisible markdown-markup markdown-gfm-block-end
                       (86 89 86 89 89 89 #<killed buffer>))
  86 87
  (face
   (markdown-markup-face markdown-code-face)
   invisible markdown-markup markdown-gfm-block-end
   (86 89 86 89 89 89 #<killed buffer>))
  87 88
  (face
   (markdown-markup-face markdown-code-face)
   invisible markdown-markup font-lock-multiline t markdown-gfm-block-end
   (86 89 86 89 89 89 #<killed buffer>)))
```

in both cases.  What am I missing?

**Comment by astoff** [comment]
@muffinmad Of course Eglot should work with all sensible servers, but since you are the author of anakin-language-server, may I ask why you add that specific piece of markup? I suppose you want the server to work well on editors that can't format markdown, or slightly mangle it.

**Comment by joaotavora** [comment]
My two cents on the markdown vs non-markdown debate is that I think it's practically a standard now, there's no point in thinking too much about non-support (only a tiny bit ;-) )

My immediate interest here is to make both of you happy. It seems @astoff that all you were missing was hyperlinks right? Or more?  Does digestif emit markdown or not?

**Comment by astoff** [comment]
Of course, we should fix the issue @muffinmad reports. Emacs shouldn't be among the editors that slightly mangle markdown rendering. I was just saying that as a server developer I would play safe with the first line of the hover string specifically.

Now, the place we need to look is when Eldoc selects _n_ lines of the Eldoc buffer to display in the echo area. It should be _n_ visual lines, but currently it picks _n_ actual lines.

**Comment by muffinmad** [comment]
> @muffinmad Of course Eglot should work with all sensible servers, but since you are the author of anakin-language-server, may I ask why you add that specific piece of markup? I suppose you want the server to work well on editors that can't format markdown, or slightly mangle it.

In case the client is not reporting support for hover content in markdown mode, the server will respond with plain text:
```
(:jsonrpc "2.0" :id 12 :result
	  (:contents
	   (:kind "plaintext" :value "foo(bar: str, baz: int) -> bool\n\nSome docstring.\nUsage example:\n\n    if foo(\"\", 0):\n        return")))
```
<img width="595" src="https://user-images.githubusercontent.com/2702727/158027109-3aad7666-eef5-4c55-8c4a-62b24320c6d4.png">

The markdown format is sent only when the client reporting markdown support.

The first part of the hover info is usually the function signature, which is valid python code. So, to have syntax hightlight, it is wrapped in `python` code block.
The second part of the hover info is wrapped by plain code block in order to use fixed font and preserve indentation.

The whole hover info will look like this:
<img width="595" src="https://user-images.githubusercontent.com/2702727/158027128-5e44e876-0537-4597-b075-f522e89f4339.png">

**Comment by muffinmad** [comment]
Also, although the number of visible lines is the same, eldoc desides to truncate the hover info:
<img width="595" src="https://user-images.githubusercontent.com/2702727/158027529-6571bcb5-6385-4788-9426-2f5475c3f382.png">

The 7 lines of the hover info in plainttext format are fully displayed.

**Comment by muffinmad** [comment]
And here is screenshot of the previous behaviour:
<img width="595" src="https://user-images.githubusercontent.com/2702727/158027675-6c68e59e-73f8-4c85-9767-4a9d84043c14.png">

**Comment by astoff** [comment]
@muffinmad I understand the idea and the goal. I was just wondering why you want to do this, given that it will almost surely break some editor, even if we fix Eglot :-).

**Comment by nemethf** [comment]
This is a little bit orthogonal to this issue, but if I understand correctly, @muffinmad's underlying assumption is that "the first part of the hover info is usually the function signature".  If `eldoc-documentation-functions` is just `'(eglot-signature-eldoc-function)`, then eldoc will show just the signature.   And it seems anakin-language-server is a signatureHelpProvider.  So, what's wrong with this setup?

**Comment by muffinmad** [comment]
@astoff Some other editor is pretty fine with markdown format. Maybe because they do not try to get the first line of the docs :)
<img width="313" src="https://user-images.githubusercontent.com/2702727/159173490-ad26b019-e3ae-4acb-9b93-70544bd844e9.png">

**Comment by muffinmad** [comment]
@nemethf In case hover info will not contain signature in the first line, it still be wrapped in code block to preserve indentation

```
(:jsonrpc "2.0" :id 60 :result
          (:contents
           (:kind "markdown" :value "```\nConcrete date/time and related types.\n\nSee http://www.iana.org/time-zones/repository/tz-link.html for\ntime zone and DST data sources.\n```")))
```
<img width="448" src="https://user-images.githubusercontent.com/2702727/159173869-2c0a3b10-3628-4516-8a02-c028abc82a85.png">

**Comment by astoff** [comment]
> Some other editor is pretty fine with markdown format. Maybe because they do not try to get the first line of the docs :)

I'm sure _some other_ editor will handle that markup just fine. But I'm also sure _not every_ editor will.

> In case hover info will not contain signature in the first line, it still be wrapped in code block to preserve indentation

This is clearly a wrong use of a code block, since what's inside the code block is not code. According to the markdown documentation, you can insert a hard break by ending a line with at least two spaces.

Like   
I just did  
here.

**Comment by muffinmad** [comment]
> I'm sure _some other_ editor will handle that markup just fine. But I'm also sure _not every_ editor will.

If the editor enables markdown format support in hover info, then it is the editor task to handle it properly, right?

> This is clearly a wrong use of a code block, since what's inside the code block is not code. According to the markdown documentation, you can insert a hard break by ending a line with at least two spaces:

It's not about line breaks, but about docstring formattig using spaces. Here is the example from the docstring of `import` statement:
```
The "import" statement
**********************

   import_stmt     ::= "import" module ["as" identifier] ("," module ["as" identifier])*
                   | "from" relative_module "import" identifier ["as" identifier]
                   ("," identifier ["as" identifier])*
                   | "from" relative_module "import" "(" identifier ["as" identifier]
                   ("," identifier ["as" identifier])* [","] ")"
                   | "from" relative_module "import" "*"
   module          ::= (identifier ".")* identifier
   relative_module ::= "."* module | "."+
```

Can you imagine how it will looks like without `<pre>`? :)

According to https://daringfireball.net/projects/markdown/syntax#precode

> Pre-formatted code blocks are used for writing about programming or markup source code

I don't see it says "code blocks is only for code". Can we classify doscstrings as "writing about programming"? :)

**Comment by joaotavora** [comment]
@muffinmad regardless of your arguments, which are interesting (and on which I don't have a very clear position, due mainly to ignorance and lack of testing on these servers), have you tested @astoff 's patch to eldoc.el  in https://debbugs.gnu.org/cgi/bugreport.cgi?bug=54473 ?

Can you tell if it solves your problem completely/partially/not at all?

**Comment by muffinmad** [comment]
@joaotavora Not yet. But I will.

**Comment by joaotavora** [comment]
Cool. If possible, please reply to that thread.  I think your feedback is more useful there.
