### ISSUE TITLE
How to use more features of eglot with company-mode?

### ISSUE THREAD

**Issue by netjune** [joaotavora/eglot#89]
As far as I know, eglot supports capf and company-mode has a backend  company-capf.

Does company-capf support trigger keys of the lsp server? Does it support snippet in completion?

**Comment by joaotavora** [comment]
Snippets are now supported. Trigger keys are also supported (though `CompletionContext` and `CompletionTriggerKind.TriggerCharacter` is not yet supported, see #173 and https://github.com/MaskRay/ccls/issues/144)
