### ISSUE TITLE
Warn when server is unresponsive

### ISSUE THREAD

**Issue by mkcms** [joaotavora/eglot#91]
Sometimes when I use eglot, servers randomly become unresponsive after receiving a certain request (e.g. list all symbols in 30000-line file). I wonder if eglot could warn when, for example, the last 5 requests to the server timed out.

**Comment by joaotavora** [comment]
Don't know if you're still interested in this, but the mode-line indicates the number of outstanding requests that haven't received a reply yet.  It also displays red, I think, if a recent request has produced an error.  Is that not enough?

**Comment by mkcms** [comment]
I overlooked this feature. Originally, I had a more explicit warning in mind, but to be honest I'm fine with what eglot does currently.
