### ISSUE TITLE
Support custom cross references

### ISSUE THREAD

**Issue by MaskRay** [joaotavora/eglot#95]
There are several cross reference requests that are very similar in that they return `Location | Location[] | null`: `textDocument/definition` `textDocument/references` `textDocument/implementation` `textDocument/typeDefinition`. It will be good to have a *public* API backing them. Making it *public* is because they can be used to support implementation defined xref requests.  See https://github.com/MaskRay/ccls/wiki/Emacs#ccls-cross-reference-extension

You may find the predecessors helpful

* [lsp-find-custom](https://github.com/emacs-lsp/lsp-mode/pull/410)
* https://github.com/autozimu/LanguageClient-neovim/issues/454
* [lsp-ui-peek-find-custom](https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-peek.el#L610)

Also note that xref.el might be an inconvenient interface for users.

Long ago I sent a request to change the default of `xref-prompt-for-identifier` https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29619 , which unfortunately fell silent. You might revive it.

**Comment by mkcms** [comment]
Duplicate of #77?

**Comment by nemethf** [comment]
Now that Eglot has eglot-find-declaration, eglot-find-implementation, eglot-find-typeDefinition, all the standard xref methods are supported.  And as far as I know, João usually doesn't like to see non-standard features in Eglot.  So I think there's nothing more we can do with this issue.  @MaskRay, can we close it?

(Elgot-x supports the extended xref methods of ccls.)

**Comment by joaotavora** [comment]
Eglot-x is the way to go, yes. Heck even some Eglot-ccls, but I think Eglot-x is a better choice.

**Comment by nemethf** [comment]
I go ahead and close this, but comment here if you disagree.
