### ISSUE TITLE
display-local-help and eldoc-doc-buffer

### ISSUE THREAD

**Issue by Inkbottle007** [joaotavora/eglot#950]
Dear maintainer,
Initially it was a comment on https://github.com/joaotavora/eglot/issues/198, but since an issue cannot be reopened I copy the comments I've made here. Sorry about they are quite lengthy.

https://github.com/joaotavora/eglot/issues/198#issuecomment-1113402835

I've been experiencing the same inconvenience. This is the solution I came with:
```
(add-hook 'foo-mode-hook 'eglot-ensure)

(add-hook 'eglot--managed-mode-hook
          (lambda () (progn
                       (eldoc--format-doc-buffer nil)
                       (setq eldoc-echo-area-prefer-doc-buffer t)
                       (eldoc-doc-buffer))))

(setq display-buffer-alist
      `(("*eldoc*"
         (display-buffer-in-side-window)
         (side . bottom)
         (window-height . 0.16)
         (slot . 0))))
```
I don't know how well it works. `(eldoc--format-doc-buffer nil)` programmatically creates an `eldoc` buffer. Without it `(eldoc-doc-buffer)` fails.

https://github.com/joaotavora/eglot/issues/198#issuecomment-1125229364

The snippet above works really well to have the type of the function at point in a very well behaved side-window. It makes use of `eldoc-doc-buffer`. The action of `eldoc-doc-buffer` is exactly as described here: [There should be a cmd called eldoc-doc-buffer that pops up a new buffer showing the contents that would normally be in eldoc. You can scroll in this buffer as well.](https://www.reddit.com/r/emacs/comments/pipu20/comment/hbru60k/?utm_source=share&utm_medium=web2x&context=3)

There is another sort of help at point, which is about the errors at point, when there is wavy underline. I can get the related help two different ways: mouse-hovering or `M-x display-local-help`. Both are in the echo area. The first way is single line, which is not enough, and requires the mouse which I don't usually use. The second is also showing a flickering message saying that I could use `C-h .`, sharing the same echo area, which is very inconvenient.

Anyway, I haven't even started to describe the point that is troubling me.
I'm making use of both `eldoc-doc-buffer` and `display-local-help`. I need the action of `eldoc-doc-buffer` to keep behaving as described in the reddit post above. Both commands have totally different actions. They are linked to the same shortcut:
```emacs-lisp
(defvar eglot-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map [remap display-local-help] #'eldoc-doc-buffer)
    map))
```
btw. `C-h .` is not working on my emacs (29.0.50), I have to either `M-x display-local-help` or `M-x eldoc-doc-buffer` which anyway have totally different actions.

Long flickering messages in echo area are a distraction. Overlay windows like with `echo-box` are small, a distraction too, require a mouse, can't scroll them without a mouse wheel, which I do not have, heavy when compared to plain text buffer...

I have managed to very neatly tame the eldoc doc concerning types and function signatures. I was about to try to do the same with help messages concerning errors, when I stumbled on the snippet above which I do not understand at all. It identifies two actions seemingly totally different. (Also I don't understand, in eglot.el, how those two actions are implemented, where they take their content from, but that's a completely different story.)

Note: the code I actually use to tame "flicker doc on minibuffer when cursor changes..." is just the one in the previous post but wrapped into some `(advice-add 'select-window :after #'my/select-window-action)`, so the eldoc buffer in only showing when the main buffer is eglot managed. It's working really well, and I'd be happy if I can keep using it.

**Comment by joaotavora** [comment]
This is not what issues are for in the Eglot bug tracker.  I think I make this abundantly clear in the hard-to-miss issue-reporting template.

**Comment by joaotavora** [comment]
![image](https://user-images.githubusercontent.com/387011/168151405-76e061e9-066b-407f-9048-5216f217ac21.png)
So sorry but I closed the issue "just like that".
