### ISSUE TITLE
Eglot on Langserver.org

### ISSUE THREAD

**Issue by rchar01** [joaotavora/eglot#96]
Hello,
thanks for the great work on the eglot package.
Is there any particular reason why eglot is not on the [langserver.org](http://langserver.org/) ([git](https://github.com/langserver/langserver.github.io)) LSP list?

It took some time before I found the eglot package, a place on the list would make it easier.
It could attract new users. What do you think about this?

**Comment by muffinmad** [comment]
It's in `Work in progress` list already.
